//
//  File.swift
//
//
//  Created by MOBILE on 20/05/24.
//

import Foundation

class ArabicDataValues {
    func getDictionary() -> [String: String] {
        return [
            "RFID_Error_AlreadyDone" : "RFID: العملية المطلوبة تمت بالفعل",
            "RFID_Error_Busy" : "RFID: RFID مشغول",
            "RFID_Error_Failed" : "تتفاعل: فشل",
            "RFID_Error_FileIOError" : "ملف RFID: خطأ IO",
            "RFID_Error_InvalidDirectory" : "RFID: دليل غير صالح",
            "RFID_Error_InvalidParameter" : "RFID: تم العثور على معلمة غير صالحة في استدعاء ExecuteCommand()",
            "RFID_Error_NoChipDetected" : "RFID: لم يتم اكتشاف أي شريحة",
            "RFID_Error_NotAvailable" : "تتفاعل: غير متوفر",
            "RFID_Error_NotEnoughMemory" : "تتفاعل: نفاد الذاكرة",
            "RFID_Error_NotInitialized" : "RFID: الجهاز غير مهيأ",
            "RFID_Error_NotPerformed" : "RFID: لم يتم الأداء",
            "RFID_Error_OldFirmware" : "RFID: يجب تحديث البرنامج الثابت إلى إصدار أحدث",
            "RFID_Error_PCSC_CantConnectCard" : "PCSC: لا يمكن توصيل البطاقة",
            "RFID_Error_PCSC_CardIsBusy" : "PCSC: البطاقة مشغولة",
            "RFID_Error_PCSC_CardIsNotConnected" : "PCSC: البطاقة غير متصلة",
            "RFID_Error_PCSC_ExtLe_Failed" : "PCSC: فشل ExtLe",
            "RFID_Error_PCSC_Failed" : "PCSC: فشل",
            "RFID_Error_PCSC_FailedSCard" : "PCSC: فشل البطاقة الذكية",
            "RFID_Error_PCSC_OperationCancelled" : "PCSC: تم إلغاء العملية",
            "RFID_Error_PCSC_ReaderNotAvailable" : "PCSC: القارئ غير متاح",
            "RFID_Error_Session_AccessControl_AA_Failed" : "RFID: فشل AA",
            "RFID_Error_Session_AccessControl_CA_Failed" : "RFID: فشل CA",
            "RFID_Error_Session_AccessControl_IncorrectOptionCA" : "RFID: خيار CA غير صحيح",
            "RFID_Error_Session_AccessControl_RI_Failed" : "RFID: فشل RI",
            "RFID_Error_Session_AccessControl_RequiresCA" : "RFID: يتطلب CA",
            "RFID_Error_Session_AccessControl_RequiresCAKeys" : "RFID: يتطلب مفاتيح CA",
            "RFID_Error_Session_AccessControl_RequiresPACE" : "RFID: يتطلب PACE",
            "RFID_Error_Session_AccessControl_RequiresSM" : "RFID: يتطلب SM",
            "RFID_Error_Session_AccessControl_RequiresTA" : "RFID: يتطلب TA",
            "RFID_Error_Session_AccessControl_UnknownType" : "RFID: نوع التحكم في الوصول غير معروف",
                "RFID_Error_Session_AccessKey_IncorrectData" : "RFID: بيانات المفتاح غير صحيحة",
                "RFID_Error_Session_AccessKey_IncorrectSMType" : "RFID: نوع SM للمفتاح غير صحيح",
                "RFID_Error_Session_AccessKey_NotSet" : "RFID: المفتاح لم يتم تعيينه",
                "RFID_Error_Session_AccessKey_Restricted" : "RFID: المفتاح مقيد",
                "RFID_Error_Session_AccessKey_UnknownType" : "RFID: نوع المفتاح غير معروف",
                "RFID_Error_Session_AccessKey_UnsupportedSMType" : "RFID: نوع SM للمفتاح غير مدعوم",
                "RFID_Error_Session_File_AccessDenied" : "ملف RFID: تم رفض الوصول",
                "RFID_Error_Session_File_CantReadData" : "ملف RFID: لا يمكن قراءة البيانات",
                "RFID_Error_Session_File_CantUseData" : "ملف RFID: لا يمكن استخدام البيانات",
                "RFID_Error_Session_File_Contents_UnexpectedData" : "ملف RFID: محتويات البيانات غير المتوقعة",
                "RFID_Error_Session_File_IncorrectData" : "ملف RFID: البيانات غير صحيحة",
                "RFID_Error_Session_File_NotEnoughData" : "ملف RFID: البيانات غير كافية",
                "RFID_Error_Session_File_UnexpectedData" : "ملف RFID: البيانات غير متوقعة",
                "RFID_Error_Session_File_WrongTag" : "ملف RFID: العلامة خاطئة",
                "RFID_Error_Session_IncorrectData" : "RFID: البيانات غير صحيحة",
                "RFID_Error_Session_InvalidAuxData_CommunityID" : "RFID: معرف المجتمع المساعد غير صالح",
                "RFID_Error_Session_InvalidAuxData_DateOfBirth" : "RFID: تاريخ الميلاد المساعد غير صالح",
                "RFID_Error_Session_InvalidAuxData_DateOfExpiry" : "RFID: تاريخ انتهاء المساعد غير صالح",
                "RFID_Error_Session_IsClosed" : "RFID: الجلسة مغلقة",
                "RFID_Error_Session_PA_HashCheckFailed" : "RFID: فشل التحقق من الهاش",
                "RFID_Error_Session_PA_SignatureCheckFailed" : "RFID: فشل التحقق من التوقيع",
                "RFID_Error_Session_ProcedureType_NotSet" : "RFID: نوع الإجراء لم يتم تعيينه",
                "RFID_Error_Session_ProcedureType_Unknown" : "RFID: نوع الإجراء غير معروف",
                "RFID_Error_Session_ProcedureType_Unsupported" : "RFID: نوع الإجراء غير مدعوم",
                "RFID_Error_Session_PwdManagement_NotAuthorized" : "RFID: إدارة كلمة المرور غير مصرح بها",
                "RFID_Error_Session_TerminalType_BadCertificate" : "RFID: شهادة نوع المحطة سيئة",
                "RFID_Error_Session_TerminalType_NotSet" : "RFID: نوع المحطة لم يتم تعيينه",
                "RFID_Error_Session_TerminalType_Unknown" : "RFID: نوع المحطة غير معروف",
            "RFID_Error_Session_Terminal_UnsupportedOperation" : "RFID: عملية غير مدعومة من المحطة",
            "RFID_Error_Session_eSign_PIN_NotSet" : "RFID: لم يتم تعيين رقم التعريف الشخصي للتوقيع الإلكتروني",
            "RFID_Error_Session_eSign_PIN_NotVerified" : "RFID: رقم التعريف الشخصي للتوقيع الإلكتروني لم يتم التحقق منه",
            "RFID_Error_Session_eSign_RequiresAppSelection" : "RFID: يتطلب التوقيع الإلكتروني اختيار التطبيق",
            "RFID_Error_UnknownCommand" : "RFID: أمر غير معروف",
            "RFID_LAYER6_APP_SELECTION_FAILURE" : "LAYER6: ISO7816_A_03 \"فشل اختيار التطبيق\"",
            "RFID_LAYER6_EXT_AUTH_FAILURE" : "LAYER6: APDU_INS_EXTERNAL_AUTHENTICATE (فشل المصادقة الخارجية)",
            "RFID_LAYER6_FILE_EOF1" : "LAYER6: القراءة تتجاوز EOF / نهاية غير متوقعة للملف",
            "RFID_LAYER6_FILE_EOF2" : "LAYER6: القراءة تتجاوز EOF / نهاية غير متوقعة للملف",
            "RFID_LAYER6_FILE_NOT_FOUND" : "LAYER6: فشل اختيار الملف / الملف غير موجود",
            "RFID_LAYER6_GENERAL_AUTH_FAILURE" : "LAYER6: فشل المصادقة العامة",
            "RFID_LAYER6_GET_CHALLENGE_FAILURE" : "LAYER6: فشل الحصول على التحدي",
            "RFID_LAYER6_INCORRECT_PARAMS" : "LAYER6: معلمات غير صحيحة",
            "RFID_LAYER6_INT_AUTH_FAILURE" : "LAYER6: فشل APDU_INS_INTERNAL_AUTHENTICATE",
            "RFID_LAYER6_MSE_SET_AT_FAILURE" : "LAYER6: فشل MSE:Set AT",
            "RFID_LAYER6_MSE_SET_DST_FAILURE" : "LAYER6: فشل MSE:Set DST",
            "RFID_LAYER6_MSE_SET_KAT_FAILURE" : "LAYER6: فشل MSE:Set KAT",
            "RFID_LAYER6_MUTUAL_AUTH_ENC_FAIL" : "LAYER6: ISO7816_B_02 \"فشل تشفير المصادقة المتبادلة\"",
            "RFID_LAYER6_MUTUAL_AUTH_FAILURE" : "LAYER6: ISO7816_B_03 \"فشل المصادقة المتبادلة\"",
            "RFID_LAYER6_MUTUAL_AUTH_MAC_FAIL" : "LAYER6: ISO7816_B_01 \"فشل MAC المصادقة المتبادلة\"",
            "RFID_LAYER6_NON_TLV_RESPONSE_DATA" : "LAYER6: بيانات استجابة غير TLV",
            "RFID_LAYER6_NO_REFERENCE_DATA" : "LAYER6: لا توجد بيانات مرجعية",
            "RFID_LAYER6_PSO_CERTIFICATE_FAILURE" : "LAYER6: فشل شهادة PSO",
            "RFID_LAYER6_PWD_BLOCKED" : "LAYER6: كلمة المرور محظورة",
            "RFID_LAYER6_PWD_BLOCKED_2" : "LAYER6: كلمة المرور محظورة 2",
            "RFID_LAYER6_PWD_DEACTIVATED" : "LAYER6: كلمة المرور معطلة",
            "RFID_LAYER6_PWD_DEACTIVATED_2" : "LAYER6: كلمة المرور معطلة 2",
            "RFID_LAYER6_PWD_FAILED" : "LAYER6: فشل كلمة المرور",
            "RFID_LAYER6_PWD_SUSPENDED" : "LAYER6: كلمة المرور معلقة",
            "RFID_LAYER6_PWD_SUSPENDED_2" : "LAYER6: كلمة المرور معلقة 2",
            "RFID_LAYER6_SECURITY_MANAGER" : "LAYER6: لم يتم تفعيل المراسلة الآمنة",
            "RFID_LAYER6_SM_DO87_INCORRECT" : "LAYER6: فشل SM – تشفير غير صحيح",
            "RFID_LAYER6_SM_DO87_MISSING" : "LAYER6: فشل SM – التشفير مفقود",
            "RFID_LAYER6_SM_DO8E_MISSING" : "LAYER6: فشل SM – MAC مفقود",
            "RFID_LAYER6_SM_DO99_MISSING" : "LAYER6: فشل SM – رموز الحالة المؤمنة مفقودة",
            "RFID_LAYER6_SM_MAC_INCORRECT" : "LAYER6: فشل SM – MAC غير صحيح",
            "RFID_LAYER6_WRONG_RND_ICC_LENGTH" : "LAYER6: طول البيانات غير صحيح (APDU_INS_GET_CHALLENGE)",
            "RSDT_RFID_READING_FINISHED" : "اكتمل قراءة بيانات RFID",
            "TCT_Unknown" : "غير معروف",
            "chd_BackgroundComparisonError" : "اختلاف سطوع الصفحتين",
            "chd_BadAreaInAxial" : "فشل الحماية الارتجاعية",
            "chd_BarcodeDataFormatError" : "خطأ في تنسيق الباركود",
            "chd_BarcodeReadedWithErrors" : "تم قراءة الباركود بأخطاء",
            "chd_BarcodeSizeParamsError" : "خطأ في معلمات حجم الباركود",
            "chd_DocumentIsCancelling" : "تم إلغاء الوثيقة",
            "chd_ElementShouldBeColored" : "يجب أن يكون العنصر ملونًا",
            "chd_ElementShouldBeGrayscale" : "يجب أن يكون العنصر رماديًا",
            "chd_ExceptionInModule" : "تم اعتراض الاستثناء",
            "chd_FalseIPIParameters" : "معلمات IPI خاطئة",
            "chd_FalseLuminiscenceError" : "وجود أشياء لامعة زائدة",
            "chd_FalseLuminiscenceInBlank" : "توهج زائف في الأشعة فوق البنفسجية",
            "chd_FalseLuminiscenceInMRZ" : "توهج زائد في منطقة MRZ",
            "chd_FibersNotFound" : "الألياف غير موجودة",
            "chd_FieldPosCorrector_Highlight_IR" : "إضاءة زائدة في الأشعة تحت الحمراء",
            "chd_FieldsComparisonLogicError" : "خطأ منطقي عند مقارنة الحقول",
            "chd_FixedPatternError" : "عدم تطابق الكائن المحدد",
            "chd_HologramElementAbsent" : "الهولوجرام غير موجود",
            "chd_HologramElementPresent" : "الهولوجرام موجود",
            "chd_Hologram_Side_Top_Images_Absent" : "لا توجد صور جانبية أو علوية",
            "chd_IncorrectBackgroundLight" : "سطوع الخلفية غير صحيح",
            "chd_IncorrectTextColor" : "لون النص غير صحيح",
            "chd_InternalError" : "خطأ في معالجة البيانات الداخلية",
            "chd_InvalidChecksum" : "قيمة التحقق غير صالحة",
            "chd_InvalidFieldFormat" : "تنسيق الحقل لا يتطابق مع وصف الوثيقة",
            "chd_InvalidInputData" : "بيانات إدخال غير صالحة",
            "chd_InvisibleElementPresent" : "يجب أن يكون الكائن غير مرئي",
            "chd_LogicError" : "خطأ منطقي في البيانات",
            "chd_LowContrastInIRLight" : "تباين غير صحيح للكائن في الضوء تحت الحمراء",
            "chd_MobileImages_LowLightConditions" : "ظروف الإضاءة غير ملائمة لالتقاط الصور",
            "chd_MobileImages_WhileUVNoDifference" : "فرق منخفض بين الصور في أنظمة الإضاءة المختلفة",
            "chd_NecessaryImageNotFound" : "الصورة المطلوبة لهذا الفحص مفقودة",
            "chd_NotAllBarcodesRead" : "يجب أن يحتوي هذا المستند على المزيد من الباركود",
            "chd_OVI_BadColor_Front" : "عدم تطابق لون كائن OVI تحت الضوء الأبيض",
            "chd_OVI_BadColor_Percent" : "نسبة تطابق منخفضة بين عناصر OVI",
            "chd_OVI_BadColor_Side" : "عدم تطابق لون كائن OVI تحت الضوء المحوري",
            "chd_OVI_ColorInvariable" : "لون OVI غير متغير",
            "chd_OVI_IR_Invisible" : "عدم تطابق تباين كائن OVI",
            "chd_OVI_InsufficientArea" : "مساحة كائن OVI غير كافية",
            "chd_OVI_Wide_Color_Spread" : "عدم تطابق نطاق لون كائن OVI",
            "chd_Pass" : "لا توجد أخطاء",
            "chd_PhotoFalseLuminiscence": "الإضاءة الكاذبة في منطقة الصورة",
              "chd_PhotoPattern_DifferentColors": "ألوان النمط على الصورة وعلى الفراغ مختلفة",
              "chd_PhotoPattern_DifferentLinesThickness": "سماكة مختلفة لخطوط النمط",
              "chd_PhotoPattern_IR_Visible": "النمط الأمني مرئي في الأشعة تحت الحمراء",
              "chd_PhotoPattern_Interrupted": "النمط بين الصورة والفراغ يحتوي على كسر",
              "chd_PhotoPattern_InvalidColor": "لون النمط الأمني غير صالح",
              "chd_PhotoPattern_Not_Intersect": "حافة الصورة لا تتقاطع مع النمط",
              "chd_PhotoPattern_PatternNotFound": "النمط لم يتم العثور عليه في منطقة الصورة",
              "chd_PhotoPattern_Shifted": "النمط على الصورة منحرف بالنسبة للنمط على الفراغ",
              "chd_PhotoPattern_Shifted_Vert": "خطوط النمط منحرفة عمودياً بالنسبة لبعضها",
              "chd_PhotoSidesNotFound": "الحدود المطلوبة للصورة لم يتم العثور عليها",
              "chd_PhotoSize_Is_Wrong": "حجم الصورة غير صحيح",
              "chd_Photo_Corners_Is_Wrong": "زوايا الصورة لا تفي بالمتطلبات",
              "chd_Photo_IsNot_Rectangle": "شكل الصورة ليس مستطيلاً",
              "chd_PortraitComparison_NoLivePhoto": "لا توجد صورة حية",
              "chd_PortraitComparison_NoPortraitDetected": "لم يتم العثور على وجه في الصورة",
              "chd_PortraitComparison_NoServiceLicense": "لا يوجد ترخيص للخدمة",
              "chd_PortraitComparison_NoServiceReply": "الخدمة لا تستجيب",
              "chd_PortraitComparison_NotEnoughImages": "عدد الصور غير كافٍ",
              "chd_PortraitComparison_PortraitsDiffer": "الصور الشخصية لا تتطابق",
              "chd_PortraitComparison_ServiceError": "خطأ في الخدمة",
              "chd_SourcesComparisonError": "عدم تطابق البيانات من مصادر مختلفة",
              "chd_SpecksInUV": "الإضاءة الزائدة أو الوهج في الصورة تحت الأشعة فوق البنفسجية",
              "chd_SyntaxError": "خطأ في بناء الجملة",
              "chd_TextColorShouldBeBlue": "يجب أن يكون لون النص أزرق",
              "chd_TextColorShouldBeGreen": "يجب أن يكون لون النص أخضر",
              "chd_TextColorShouldBeRed": "يجب أن يكون لون النص أحمر",
              "chd_TextShouldBeBlack": "يجب أن يكون لون النص أسود",
              "chd_TooLowResolution": "دقة منخفضة جدًا للكشف عن الألياف",
              "chd_TooManyObjects": "عدد كبير جدًا من الأشياء",
              "chd_TooMuchShift": "قيمة الانحراف أكبر من القيمة المسموح بها",
              "chd_TrueLuminiscenceError": "عدم تطابق الكائنات المضيئة",
              "chd_UVDullPaperError": "خطأ في فحص الورق الباهت تحت الأشعة فوق البنفسجية",
              "chd_UVDullPaper_Blank": "فحص الورق الباهت تحت الأشعة فوق البنفسجية في منطقة الفراغ",
              "chd_UVDullPaper_MRZ": "فحص الورق الباهت تحت الأشعة فوق البنفسجية في منطقة MRZ",
              "chd_UVDullPaper_Photo": "فحص الورق الباهت تحت الأشعة فوق البنفسجية في منطقة الصورة",
              "chd_UncertainVerification": "لا يمكن اتخاذ قرار موثوق",
              "chd_Unknown": "رفض غير معروف",
              "chd_VisibleElementAbsent": "لا يوجد كائن مرئي تحت الأشعة تحت الحمراء",
              "strAGY": "AGY",
              "strAKADateofBirth": "تاريخ الميلاد المعروف أيضًا",
              "strAKAGivenNames": "الاسم الأول المعروف أيضًا",
              "strAKANamePrefix": "بادئة الاسم المعروف أيضًا",
              "strAKANameSuffix": "لاحقة الاسم المعروف أيضًا",
              "strAKASocialSecurityNumber": "رقم الضمان الاجتماعي المعروف أيضًا",
              "strAKASurname": "اللقب المعروف أيضًا",
              "strAKASurnameAndGivenNames": "الاسم الكامل المعروف أيضًا",
              "strALTCode": "رمز ALT",
              "strAcademicTitle": "اللقب الأكاديمي",
              "strAccessibilityCameraButton": "التقاط صورة وبدء المعالجة",
              "strAccessibilityCloseButton": "إغلاق",
              "strAccessibilityTorchButton": "مصباح يدوي",
              "strAccompaniedby": "برفقة",
              "strAddress": "عنوان",
              "strAddressArea": "منطقة",
              "strAddressBuilding": "وحدة",
              "strAddressCity": "مدينة",
              "strAddressCountry": "دولة",
              "strAddressFlat": "شقة",
              "strAddressHouse": "مبنى",
              "strAddressJurisdictionCode": "رمز الاختصاص القضائي",
              "strAddressLocation": "موقع",
              "strAddressMunicipality": "بلدية",
              "strAddressPostalCode": "الرمز البريدي",
              "strAddressState": "ولاية",
              "strAddressStreet": "شارع",
              "strAdministrativeNumber": "الرقم الإداري",
              "strAge": "عمر",
              "strAgeAtIssue": "العمر عند الإصدار",
              "strAirlineDesignatorofboardingpassissuer": "معرف شركة الطيران التي تصدر بطاقة الصعود",
              "strAirlineName": "اسم شركة الطيران",
              "strAirlineNameFrequentFlyer": "برنامج ولاء شركة الطيران للمسافرين الدائمين",
              "strAirlineNumericCode": "رمز شركة الطيران الرقمي",
              "strAirportFrom": "مطار المغادرة",
              "strAirportTo": "مطار الوصول",
              "strAllergies": "الحساسية",
              "strApplicationDoNotHavePermission": "التطبيق ليس لديه إذن لاستخدام الكاميرا، يرجى تغيير إعدادات الخصوصية",
              "strApplicationNumber": "رقم التطبيق",
              "strArtisticName": "اسم فني",
              "strAuditInformation": "رقم للتحقق",
              "strAuthentification": "التحقق من الأصالة",
              "strAuthority": "السلطة المصدرة",
              "strAuthorityCode": "رمز السلطة المصدرة",
              "strAuthorityRUS": "السلطة المصدرة (الوطنية)",
              "strAuthorizationNumber": "رقم الترخيص",
              "strAxialProtection": "الحماية العاكسة",
              "strBDBType": "نوع BDB",
              "strBankCardNumber": "رقم البطاقة البنكية",
              "strBankCardValidThru": "صلاحية البطاقة البنكية",
              "strBanknoteNumber": "رقم الورقة النقدية",
              "strBarcode": "الرمز الشريطي",
              "strBarcodeFormatCheck": "فحص تنسيق الرمز الشريطي",
              "strBenefitsNumber": "رقم الاستحقاقات",
              "strBinaryCode": "الرمز الثنائي",
              "strBiometricFormatOwner": "مالك تنسيق القياسات الحيوية",
              "strBiometricFormatType": "نوع تنسيق القياسات الحيوية",
              "strBiometricProductID": "معرف منتج القياسات الحيوية",
              "strBiometricSubtype": "نوع فرعي للقياسات الحيوية",
              "strBiometricType": "نوع القياسات الحيوية",
              "strBlankElement": "عنصر الفراغ",
            "strBloodGroup": "فصيلة الدم",
               "strBookletNumber": "رقم الكتيب",
               "strCCWUntil": "حتى CCW",
               "strCDLClass": "فئة CDL",
               "strCSCCode": "رمز CSC",
               "strCVV": "CVV/CVC",
               "strCaliber": "عيار",
               "strCameraUnavailable": "الكاميرا غير متوفرة",
               "strCardAccessNumber": "رقم البطاقة الوصول",
               "strCategory": "الفئة",
               "strCenturyDateOfBirth": "القرن من تاريخ الميلاد",
               "strChassisNumber": "رقم الهيكل",
               "strCheckInSequenceNumber": "رقم تسلسل الوصول",
               "strChildren": "الأطفال",
               "strCitizenshipOfFirstPerson": "جنسية الشخص الأول",
               "strCitizenshipOfSecondPerson": "جنسية الشخص الثاني",
               "strCivilStatus": "الحالة المدنية",
               "strColorDynamic": "ديناميكيات اللون",
               "strCommercialVehicleCodes": "رموز المركبات التجارية",
               "strCompanyName": "اسم الشركة",
               "strCompartmentCode": "رمز الحجرة",
               "strComplexion": "الملمس",
               "strComplianceType": "نوع الامتثال",
               "strConditions": "الشروط",
               "strConfiguration": "التكوين",
               "strControlNo": "رقم التحكم",
               "strCopy": "نسخة",
               "strCourtCode": "رمز المحكمة",
               "strCty": "مقاطعة",
               "strCurrentDate": "التاريخ الحالي",
               "strCustodyInfo": "معلومات الحضانة",
               "strDFTAppDirectory": "دليل التطبيق",
               "strDFTCertificate": "شهادة",
               "strDG1": "المنطقة القراءة الآلية (DG1)",
               "strDG10": "غير محدد (DG10)",
               "strDG11": "تفاصيل شخصية إضافية (DG11)",
               "strDG12": "تفاصيل وثيقة إضافية (DG12)",
               "strDG13": "تفاصيل اختيارية (DG13)",
               "strDG14": "معلومات EAC (DG14)",
               "strDG15": "معلومات المصادقة النشطة (DG15)",
               "strDG16": "الشخص (أشخاص) للإعلام (DG16)",
               "strDG17": "DG17",
               "strDG18": "DG18",
               "strDG19": "DG19",
               "strDG2": "بيانات الوجه (DG2)",
               "strDG20": "DG20",
               "strDG3": "بيانات بيومترية - بصمات الأصابع (DG3)",
               "strDG4": "بيانات بيومترية - بيانات القزحية (DG4)",
               "strDG5": "صور البورتريه (DG5)",
               "strDG6": "غير محدد (DG6)",
               "strDG7": "صورة التوقيع/العلامة العادية (DG7)",
               "strDG8": "غير محدد (DG8)",
               "strDG9": "غير محدد (DG9)",
               "strDLCDLRestrictionCode": "رمز قيود رخصة القيادة التجارية",
               "strDLClass": "فئة رخصة القيادة",
               "strDLClassCodeA1From": "فئة رخصة القيادة A1 صالحة من",
               "strDLClassCodeA1Notes": "رموز فئة رخصة القيادة A1",
               "strDLClassCodeA1To": "فئة رخصة القيادة A1 صالحة إلى",
               "strDLClassCodeA2From": "فئة رخصة القيادة A2 صالحة من",
               "strDLClassCodeA2Notes": "رموز فئة رخصة القيادة A2",
               "strDLClassCodeA2To": "فئة رخصة القيادة A2 صالحة إلى",
               "strDLClassCodeA3From": "فئة رخصة القيادة A3 صالحة من",
               "strDLClassCodeA3Notes": "رموز فئة رخصة القيادة A3",
               "strDLClassCodeA3To": "فئة رخصة القيادة A3 صالحة إلى",
               "strDLClassCodeAFrom": "فئة رخصة القيادة A صالحة من",
               "strDLClassCodeAMFrom": "فئة رخصة القيادة AM صالحة من",
               "strDLClassCodeAMNotes": "رموز فئة رخصة القيادة AM",
               "strDLClassCodeAMTo": "فئة رخصة القيادة AM صالحة إلى",
               "strDLClassCodeANotes": "رموز فئة رخصة القيادة A",
               "strDLClassCodeATo": "فئة رخصة القيادة A صالحة إلى",
               "strDLClassCodeB1From": "فئة رخصة القيادة B1 صالحة من",
               "strDLClassCodeB1Notes": "رموز ف",
            "strDLClassCodeB1To": "فئة رخصة القيادة B1 صالحة حتى",
              "strDLClassCodeB2EFrom": "فئة رخصة القيادة B2E صالحة من",
              "strDLClassCodeB2ENotes": "رموز فئة رخصة القيادة B2E",
              "strDLClassCodeB2ETo": "فئة رخصة القيادة B2E صالحة حتى",
              "strDLClassCodeB2From": "فئة رخصة القيادة B2 صالحة من",
              "strDLClassCodeB2Notes": "رموز فئة رخصة القيادة B2",
              "strDLClassCodeB2To": "فئة رخصة القيادة B2 صالحة حتى",
              "strDLClassCodeBEFrom": "فئة رخصة القيادة BE صالحة من",
              "strDLClassCodeBENotes": "رموز فئة رخصة القيادة BE",
              "strDLClassCodeBETo": "فئة رخصة القيادة BE صالحة حتى",
              "strDLClassCodeBFrom": "فئة رخصة القيادة B صالحة من",
              "strDLClassCodeBNotes": "رموز فئة رخصة القيادة B",
              "strDLClassCodeBTPFrom": "فئة رخصة القيادة BTP صالحة من",
              "strDLClassCodeBTPNotes": "رموز فئة رخصة القيادة BTP",
              "strDLClassCodeBTPTo": "فئة رخصة القيادة BTP صالحة حتى",
              "strDLClassCodeBTo": "فئة رخصة القيادة B صالحة حتى",
              "strDLClassCodeC1EFrom": "فئة رخصة القيادة C1E صالحة من",
              "strDLClassCodeC1ENotes": "رموز فئة رخصة القيادة C1E",
              "strDLClassCodeC1ETo": "فئة رخصة القيادة C1E صالحة حتى",
              "strDLClassCodeC1From": "فئة رخصة القيادة C1 صالحة من",
              "strDLClassCodeC1Notes": "رموز فئة رخصة القيادة C1",
              "strDLClassCodeC1To": "فئة رخصة القيادة C1 صالحة حتى",
              "strDLClassCodeC2From": "فئة رخصة القيادة C2 صالحة من",
              "strDLClassCodeC2Notes": "رموز فئة رخصة القيادة C2",
              "strDLClassCodeC2To": "فئة رخصة القيادة C2 صالحة حتى",
              "strDLClassCodeC3From": "فئة رخصة القيادة C3 صالحة من",
              "strDLClassCodeC3Notes": "رموز فئة رخصة القيادة C3",
              "strDLClassCodeC3To": "فئة رخصة القيادة C3 صالحة حتى",
              "strDLClassCodeCAFrom": "فئة رخصة القيادة CA صالحة من",
              "strDLClassCodeCANotes": "رموز فئة رخصة القيادة CA",
              "strDLClassCodeCATo": "فئة رخصة القيادة CA صالحة حتى",
              "strDLClassCodeCEFrom": "فئة رخصة القيادة CE صالحة من",
              "strDLClassCodeCENotes": "رموز فئة رخصة القيادة CE",
              "strDLClassCodeCETo": "فئة رخصة القيادة CE صالحة حتى",
              "strDLClassCodeCFrom": "فئة رخصة القيادة C صالحة من",
              "strDLClassCodeCNotes": "رموز فئة رخصة القيادة C",
              "strDLClassCodeCTo": "فئة رخصة القيادة C صالحة حتى",
              "strDLClassCodeD1EFrom": "فئة رخصة القيادة D1E صالحة من",
              "strDLClassCodeD1ENotes": "رموز فئة رخصة القيادة D1E",
              "strDLClassCodeD1ETo": "فئة رخصة القيادة D1E صالحة حتى",
              "strDLClassCodeD1From": "فئة رخصة القيادة D1 صالحة من",
              "strDLClassCodeD1Notes": "رموز فئة رخصة القيادة D1",
              "strDLClassCodeD1To": "فئة رخصة القيادة D1 صالحة حتى",
              "strDLClassCodeD2From": "فئة رخصة القيادة D2 صالحة من",
              "strDLClassCodeD2Notes": "رموز فئة رخصة القيادة D2",
              "strDLClassCodeD2To": "فئة رخصة القيادة D2 صالحة حتى",
              "strDLClassCodeDEFrom": "فئة رخصة القيادة DE صالحة من",
            "strDLClassCodeDENotes": "رموز فئة DL DE",
             "strDLClassCodeDETo": "صالح فئة DL DE حتى",
             "strDLClassCodeDFrom": "صالح فئة DL D من",
             "strDLClassCodeDNotes": "رموز فئة DL D",
             "strDLClassCodeDTo": "صالح فئة DL D حتى",
             "strDLClassCodeEFrom": "صالح فئة DL E من",
             "strDLClassCodeENotes": "رموز فئة DL E",
             "strDLClassCodeETo": "صالح فئة DL E حتى",
             "strDLClassCodeFA1From": "صالح فئة DL FA1 من",
             "strDLClassCodeFA1Notes": "رموز فئة DL FA1",
             "strDLClassCodeFA1To": "صالح فئة DL FA1 حتى",
             "strDLClassCodeFAFrom": "صالح فئة DL FA من",
             "strDLClassCodeFANotes": "رموز فئة DL FA",
             "strDLClassCodeFATo": "صالح فئة DL FA حتى",
             "strDLClassCodeFBFrom": "صالح فئة DL FB من",
             "strDLClassCodeFBNotes": "رموز فئة DL FB",
             "strDLClassCodeFBTo": "صالح فئة DL FB حتى",
             "strDLClassCodeFFrom": "صالح فئة DL F من",
             "strDLClassCodeFNotes": "رموز فئة DL F",
             "strDLClassCodeFTo": "صالح فئة DL F حتى",
             "strDLClassCodeG1From": "صالح فئة DL G1 من",
             "strDLClassCodeG1Notes": "رموز فئة DL G1",
             "strDLClassCodeG1To": "صالح فئة DL G1 حتى",
             "strDLClassCodeGFrom": "صالح فئة DL G من",
             "strDLClassCodeGNotes": "رموز فئة DL G",
             "strDLClassCodeGTo": "صالح فئة DL G حتى",
             "strDLClassCodeHCFrom": "صالح فئة DL HC من",
             "strDLClassCodeHCNotes": "رموز فئة DL HC",
             "strDLClassCodeHCTo": "صالح فئة DL HC حتى",
             "strDLClassCodeHFrom": "صالح فئة DL H من",
             "strDLClassCodeHNotes": "رموز فئة DL H",
             "strDLClassCodeHRFrom": "صالح فئة DL HR من",
             "strDLClassCodeHRNotes": "رموز فئة DL HR",
             "strDLClassCodeHRTo": "صالح فئة DL HR حتى",
             "strDLClassCodeHTo": "صالح فئة DL H حتى",
             "strDLClassCodeIFrom": "صالح فئة DL I من",
             "strDLClassCodeINotes": "رموز فئة DL I",
             "strDLClassCodeITo": "صالح فئة DL I حتى",
             "strDLClassCodeJFrom": "صالح فئة DL J من",
             "strDLClassCodeJNotes": "رموز فئة DL J",
             "strDLClassCodeJTo": "صالح فئة DL J حتى",
             "strDLClassCodeKFrom": "صالح فئة DL K من",
             "strDLClassCodeKNotes": "رموز فئة DL K",
             "strDLClassCodeKTo": "صالح فئة DL K حتى",
             "strDLClassCodeLCFrom": "صالح فئة DL LC من",
             "strDLClassCodeLCNotes": "رموز فئة DL LC",
             "strDLClassCodeLCTo": "صالح فئة DL LC حتى",
             "strDLClassCodeLFrom": "صالح فئة DL L من",
             "strDLClassCodeLKFrom": "صالح فئة DL LK من",
             "strDLClassCodeLKNotes": "رموز فئة DL LK",
             "strDLClassCodeLKTo": "صالح فئة DL LK حتى",
             "strDLClassCodeLNotes": "رموز فئة DL L",
             "strDLClassCodeLRFrom": "صالح فئة DL LR من",
             "strDLClassCodeLRNotes": "رموز فئة DL LR",
             "strDLClassCodeLRTo": "صالح فئة DL LR حتى",
             "strDLClassCodeLTo": "صالح فئة DL L حتى",
             "strDLClassCodeMCFrom": "صالح فئة DL MC من",
             "strDLClassCodeMCNotes": "رموز فئة DL MC",
             "strDLClassCodeMCTo": "صالح فئة DL MC حتى",
             "strDLClassCodeMFrom": "صالح فئة DL M من",
             "strDLClassCodeMNotes": "رموز فئة DL M",
             "strDLClassCodeMRFrom": "صالح فئة DL MR من",
             "strDLClassCodeMRNotes": "رموز فئة DL MR",
             "strDLClassCodeMRTo": "صالح فئة DL MR حتى",
             "strDLClassCodeMTo": "صالح فئة DL M حتى",
             "strDLClassCodeNFrom": "صالح فئة DL N من",
             "strDLClassCodeNNotes": "رموز فئة DL N",
             "strDLClassCodeNTo": "صالح فئة DL N حتى",
             "strDLClassCodeREFrom": "صالح فئة DL RE من",
             "strDLClassCodeRENotes": "رموز فئة DL RE",
             "strDLClassCodeRETo": "صالح فئة DL RE حتى",
             "strDLClassCodeRFrom": "صالح فئة DL R من",
             "strDLClassCodeRNotes": "رموز فئة DL R",
             "strDLClassCodeRTo": "صالح فئة DL R حتى",
             "strDLClassCodeSFrom": "صالح فئة DL S من",
             "strDLClassCodeSNotes": "رموز فئة DL S",
             "strDLClassCodeSTo": "صالح فئة DL S حتى",
             "strDLClassCodeTBFrom": "صالح فئة DL TB من",
             "strDLClassCodeTBNotes": "رموز فئة DL TB",
             "strDLClassCodeTBTo": "صالح فئة DL TB حتى",
             "strDLClassCodeTFrom": "صالح فئة DL T من",
             "strDLClassCodeTMFrom": "صالح فئة DL TM من",
             "strDLClassCodeTMNotes": "رموز فئة DL TM",
             "strDLClassCodeTMTo": "صالح فئة DL TM حتى",
             "strDLClassCodeTNotes": "رموز فئة DL T",
             "strDLClassCodeTRFrom": "صالح فئة DL TR من",
             "strDLClassCodeTRNotes": "رموز فئة DL TR",
             "strDLClassCodeTRTo": "صالح فئة DL TR حتى",
             "strDLClassCodeTTo": "صالح فئة DL T حتى",
             "strDLClassCodeTVFrom": "صالح فئة DL TV من",
             "strDLClassCodeTVNotes": "رموز فئة DL TV",
             "strDLClassCodeTVTo": "صالح فئة DL TV حتى",
             "strDLClassCodeVFrom": "صالح فئة DL V من",
             "strDLClassCodeVNotes": "رموز فئة DL V",
             "strDLClassCodeVTo": "صالح فئة DL V حتى",
             "strDLClassCodeWFrom": "صالح فئة DL W من",
             "strDLClassCodeWNotes": "رموز فئة DL W",
             "strDLClassCodeWTo": "صالح فئة DL W حتى",
             "strDLDuplicateDate": "تاريخ الإصدار المكرر",
             "strDLEndorsed": "رمز تأييد DL",
             "strDLIssType": "نوع البطاقة",
             "strDLRecordCreated": "تم إنشاء السجل",
             "strDLRestrictionCode": "رمز تقييد DL",
             "strDLUnder18Date": "تاريخ الميلاد الثامن عشر",
             "strDLUnder19Date": "تاريخ الميلاد التاسع عشر",
             "strDLUnder21Date": "تاريخ الميلاد الواحد والعشرين",
             "strDNINumber": "رقم DNI",
             "strDSCertificateIssuer": "جهة إصدار شهادة DS",
             "strDSCertificateSubject": "موضوع شهادة DS",
             "strDSCertificateValidFrom": "شهادة DS صالحة من",
             "strDSCertificateValidTo": "شهادة DS صالحة حتى",
             "strDUFNumber": "رقم DUF",
             "strDataDiscriminator": "مميز البيانات",
             "strDateFirstRenewal": "تاريخ التجديد الأول",
             "strDateOfBirthOfHusband": "تاريخ ميلاد الزوج",
             "strDateOfBirthOfWife": "تاريخ ميلاد الزوجة",
             "strDateOfInsuranceExpiry": "تاريخ انتهاء التأمين",
             "strDateSecondRenewal": "تاريخ التجديد الثاني",
             "strDateofBirth": "تاريخ الميلاد",
             "strDateofBirthCheckDigit": "الرقم التحققي لتاريخ الميلاد",
             "strDateofBirthChecksum": "مجموع التحقق لتاريخ الميلاد",
             "strDateofCreation": "تاريخ الإنشاء",
             "strDateofExpiry": "تاريخ الانتهاء",
             "strDateofExpiryCheckDigit": "الرقم التحققي لتاريخ الانتهاء",
             "strDateofExpiryChecksum": "مجموع التحقق لتاريخ الانتهاء",
             "strDateofFlight": "تاريخ الرحلة",
             "strDateofIssue": "تاريخ الإصدار",
             "strDateofIssueBoardingPass": "تاريخ إصدار بطاقة الصعود",
             "strDateofIssueCheckDigit": "الرقم التحققي لتاريخ الإصدار",
             "strDateofIssueChecksum": "مجموع التحقق لتاريخ الإصدار",
             "strDateofPersonalization": "تاريخ التخصيص",
            "strDateofRegistration": "تاريخ التسجيل",
              "strDay": "يوم",
              "strDepartment": "قسم",
              "strDeptNumber": "رقم القسم",
              "strDestination": "وجهة",
              "strDiscretionaryData": "بيانات تقديرية",
              "strDoDNumber": "رقم DoD",
              "strDocumentClassCode": "رمز فئة الوثيقة",
              "strDocumentClassName": "فئة الوثيقة",
              "strDocumentDiscriminator": "مميز الوثيقة",
              "strDocumentNumber": "رقم الوثيقة",
              "strDocumentNumberCheckDigit": "الرقم التحققي لرقم الوثيقة",
              "strDocumentNumberChecksum": "مجموع التحقق لرقم الوثيقة",
              "strDocumentSeries": "سلسلة الوثيقة",
              "strDocumentTooSmall": "ضع المستند في الإطار",
              "strDonor": "مانح",
              "strDossierNumber": "رقم الملف",
              "strDurationofStay": "مدة الإقامة",
              "strECEnvironmentalType": "نوع بيئة السيارة",
              "strEDLDG1": "عناصر البيانات النصية (DG1)",
              "strEDLDG10": "غير معرف (DG10)",
              "strEDLDG11": "بيانات محلية اختيارية (DG11)",
              "strEDLDG12": "تنبيه عدم المطابقة (DG12)",
              "strEDLDG13": "معلومات المصادقة النشطة (DG13)",
              "strEDLDG14": "معلومات EAC (DG14)",
              "strEDLDG2": "معلومات حامل الرخصة (DG2)",
              "strEDLDG3": "تفاصيل السلطة المصدرة (DG3)",
              "strEDLDG4": "صورة شخصية (DG4)",
              "strEDLDG5": "صورة التوقيع / العلامة المعتادة (DG5)",
              "strEDLDG6": "البيومترية - بيانات الوجه (DG6)",
              "strEDLDG7": "البيومترية - بصمة الإصبع (DG7)",
              "strEDLDG8": "البيومترية - بيانات القزحية (DG8)",
              "strEDLDG9": "البيومترية - أخرى (DG9)",
              "strEFCOM": "EF.COM",
              "strEFCVCA": "EF.CVCA",
              "strEFCardAccess": "EF.CardAccess",
              "strEFCardSecurity": "EF.CardSecurity",
              "strEFChipSecurity": "EF.ChipSecurity",
              "strEFSOD": "EF.SOD",
              "strEQVCode": "رمز EQV",
              "strElectronicTicketIndicator": "مؤشر التذكرة الإلكترونية",
              "strElement": "عنصر",
              "strEndorsementExpirationDate": "تاريخ انتهاء التأييد",
              "strEngineModel": "نموذج المحرك",
              "strEngineNumber": "رقم المحرك",
              "strEnginePower": "قوة المحرك",
              "strEngineVolume": "حجم المحرك",
              "strError": "خطأ",
              "strExamDate": "تاريخ الامتحان",
              "strExeptInTanks": "باستثناء في الخزانات",
              "strEye": "قزحية",
              "strEyesColor": "لون العينين",
              "strFaculty": "كلية",
              "strFalseLuminescence": "توهج زائد",
              "strFamilyName": "اسم العائلة/الاسم عند الولادة",
              "strFamilyNameTruncation": "اسم العائلة المبتور/الاسم عند الولادة",
              "strFastTrack": "خدمة المسار السريع",
              "strFatherCountryOfBirth": "بلد ميلاد الأب",
              "strFatherDateOfBirth": "تاريخ ميلاد الأب",
              "strFatherGivenName": "اسم الأب الأول",
              "strFatherPersonalNumber": "الرقم الشخصي للأب",
              "strFatherPlaceOfBirth": "مكان ميلاد الأب",
              "strFatherSurname": "لقب الأب",
              "strFathersName": "اسم الأب",
              "strFathersNameRUS": "اسم الأب (وطني)",
              "strFederalElections": "الانتخابات الفدرالية",
              "strFee": "رسوم",
              "strFieldFromMRZ": "حقل من MRZ",
              "strFieldTypeDocumentImage": "صورة الوثيقة",
              "strFillElement": "عنصر تعبئة",
              "strFinalCheckDigit": "الرقم التحققي النهائي",
              "strFinalChecksum": "مجموع التحقق النهائي",
              "strFingerprint": "بصمة الإصبع",
              "strFirstIssueDate": "تاريخ الإصدار الأول",
              "strFirstNameTruncation": "بتر الاسم الأول",
              "strFlightNumber": "رقم الرحلة",
              "strFolioNumber": "رقم الملف",
              "strFormOfEducation": "شكل التعليم",
              "strFreeBaggageAllowance": "بدل الأمتعة المجاني",
              "strFrequentFlyerAirlineDesignator": "رمز شركة الطيران للمسافر الدائم",
              "strFrequentFlyerNumber": "رقم المسافر الدائم",
              "strFromAirportCode": "رمز مطار المغادرة",
              "strFuelType": "نوع الوقود",
              "strGNIBNumber": "رقم GNIB",
              "strGhostPortrait": "صورة شبحية",
              "strGivenNames": "الاسم الأول",
              "strGivenNamesRUS": "الاسم الأول (وطني)",
              "strGlaresOnDocument": "تجنب الوهج على الوثيقة",
              "strGrandfatherName": "اسم الجد",
              "strHairColor": "لون الشعر",
              "strHealthNumber": "رقم التأمين الصحي",
              "strHeight": "الطول",
              "strHoldDocumentStraight": "أمسك الوثيقة بشكل مستقيم",
              "strHoloSimple": "توفر الهولوجرام",
              "strHoloVerifyDinamic": "التحقق من الهولوجرام الديناميكي",
              "strHoloVerifyMultiStatic": "التحقق من الهولوجرام المتعدد الساكن",
              "strHoloVerifyStatic": "التحقق من الهولوجرام الساكن",
              "strHolograms": "الهولوجرامات",
              "strIPI": "IPI (معلومات شخصية غير مرئية)",
              "strIRB900": "حبر IR B900",
              "strIRVis": "شفافية IR",
              "strISOIssuerIDNumber": "رقم معرف مصدر ISO",
              "strIdentifier": "معرف",
              "strIdentityCardNumber": "رقم بطاقة الهوية",
              "strIdentityCardNumberCheckDigit": "الرقم التحققي لرقم بطاقة الهوية",
              "strIdentityCardNumberChecksum": "مجموع التحقق لرقم بطاقة الهوية",
              "strImagePattern": "أنماط الصورة",
              "strInTanks": "في الخزانات",
              "strInventoryNumber": "رقم الجرد",
              "strInvitationNumber": "رقم الدعوة",
              "strInvitationNumberCheckDigit": "الرقم التحققي لرقم الدعوة",
              "strInvitationNumberChecksum": "مجموع التحقق لرقم الدعوة",
              "strInvitedBy": "مدعو من قبل",
              "strIssueTimestamp": "وقت الإصدار",
              "strIssuingStateCode": "رمز الدولة المصدرة",
              "strIssuingStateName": "الدولة المصدرة",
              "strJurisdictionEndorsementCode": "رمز تأييد السلطة القضائية",
              "strJurisdictionRestrictionCode": "رمز تقييد السلطة القضائية",
              "strJurisdictionVehicleClass": "فئة مركبة السلطة القضائية",
              "strKeepDeviceStill": "امسك الجهاز بثبات",
              "strLicenseNumber": "رقم الرخصة",
              "strLimitedDurationDocumentIndicator": "مؤشر مدة محدودة للوثيقة",
              "strLine1CheckDigit": "الرقم التحققي للسطر 1",
              "strLine1Checksum": "مجموع التحقق للسطر 1",
              "strLine1OptionalData": "بيانات اختيارية من السطر 1",
              "strLine2CheckDigit": "الرقم التحققي للسطر 2",
              "strLine2Checksum": "مجموع التحقق للسطر 2",
              "strLine2OptionalData": "بيانات اختيارية من السطر 2",
              "strLine3CheckDigit": "الرقم التحققي للسطر 3",
              "strLine3Checksum": "مجموع التحقق للسطر 3",
              "strLine3OptionalData": "بيانات اختيارية من السطر 3",
              "strLookingDocument": "جاري البحث عن وثيقة...",
              "strMCNoviceDate": "تاريخ انتهاء وضع المبتدئ للدراجات النارية",
              "strMRZ": "MRZ",
              "strMRZLinesICAORFID": "خطوط MRZ من ICAO RFID",
              "strMRZString1": "سطر MRZ 1",
              "strMRZString2": "سطر MRZ 2",
              "strMRZString3": "سطر MRZ 3",
              "strMRZStrings": "خطوط MRZ",
              "strMRZStringsWithCorrectCheckSums": "خطوط MRZ بمجموعات تحقق صحيحة",
              "strMRZType": "نوع MRZ",
              "strMailingAddressCity": "عنوان البريد - المدينة",
              "strMailingAddressJurisdictionCode": "عنوان البريد - رمز الولاية القضائية",
              "strMailingAddressPostalCode": "عنوان البريد - الرمز البريدي",
              "strMailingAddressStreet": "عنوان البريد - الشارع",
              "strMake": "الصانع",
              "strMaritalStatus": "الحالة الاجتماعية",
              "strMaxMassofTrailerBraked": "الحد الأقصى لوزن المقطورة (بمكابح)",
              "strMaxMassofTrailerUnbraked": "الحد الأقصى لوزن المقطورة (بدون مكابح)",
              "strMaxSpeed": "السرعة القصوى",
            "strMedicalIndicatorCodes": "الملاحظات / الرموز الطبية",
            "strMiddleName": "الاسم الأوسط",
            "strMiddleNameTruncation": "قص الاسم الأوسط",
            "strMifareData": "بيانات MIFARE",
            "strMifareValidity": "صلاحية MIFARE",
            "strMilitaryBookNumber": "رقم الهوية العسكرية",
            "strModel": "النموذج",
            "strMonth": "الشهر",
            "strMortgageBy": "رهن من قبل",
            "strMotherCountryOfBirth": "بلد ميلاد الأم",
            "strMotherDateOfBirth": "تاريخ ميلاد الأم",
            "strMotherGivenName": "اسم الأم الأول",
            "strMotherPersonalNumber": "رقم الأم الشخصي",
            "strMotherPlaceOfBirth": "مكان ميلاد الأم",
            "strMotherSurname": "لقب الأم",
            "strMothersName": "اسم الأم",
            "strNamePrefix": "بادئة الاسم",
            "strNameSuffix": "لاحقة الاسم",
            "strNationality": "الجنسية",
            "strNationalityCode": "رمز الجنسية",
            "strNonResidentIndicator": "مؤشر الغير مقيم",
            "strNone": "لا شيء",
            "strNotDefined": "غير معرف",
            "strNumberOfCardIssuance": "عدد إصدار البطاقة",
            "strNumberOfCardIssuanceCheckDigit": "الرقم السري لعدد إصدار البطاقة",
            "strNumberOfCardIssuanceChecksum": "المجموع الرقمي لعدد إصدار البطاقة",
            "strNumberOfCylinders": "عدد الأسطوانات",
            "strNumberofAxels": "عدد المحاور",
            "strNumberofDuplicates": "عدد النسخ المكررة",
            "strNumberofEntries": "عدد الإدخالات",
            "strNumberofSeats": "عدد المقاعد",
            "strNumberofStandingPlaces": "عدد أماكن الوقوف",
            "strOCRNumber": "رقم OCR",
            "strOK": "موافق",
            "strObservations": "ملاحظات",
            "strOldDateOfIssue": "تاريخ الإصدار القديم",
            "strOldDocumentNumber": "رقم الوثيقة القديم",
            "strOldPlaceOfIssue": "مكان الإصدار القديم",
            "strOptionalData": "بيانات اختيارية",
            "strOptionalDataCheckDigit": "الرقم السري للبيانات الاختيارية",
            "strOptionalDataChecksum": "المجموع الرقمي للبيانات الاختيارية",
            "strOptionalDetails": "تفاصيل اختيارية",
            "strOrganization": "المؤسسة",
            "strOther": "آخر",
            "strOtherName": "اسم آخر",
            "strOtherPersonName": "اسم شخص آخر",
            "strOtherValidID": "هويات صالحة أخرى",
            "strOwner": "المالك",
            "strPDF417Codec": "ترميز PDF417",
            "strPNRCode": "رمز PNR",
            "strParrentsGivenNames": "أسماء الوالدين",
            "strPassportNumber": "رقم جواز السفر",
            "strPassportNumberCheckDigit": "الرقم السري لرقم جواز السفر",
            "strPassportNumberChecksum": "المجموع الرقمي لرقم جواز السفر",
            "strPatronHeaderVersion": "إصدار رأس العميل",
            "strPatternDifferentLinesThickness": "مقارنة سمك خطوط النمط المختلفة",
            "strPatternIRInvisible": "نمط غير مرئي في الأشعة تحت الحمراء",
            "strPatternNotInterrupted": "لا انقطاعات",
            "strPatternNotShifted": "عناصر النمط غير متحركة",
            "strPatternSameColors": "ألوان نمط متماثلة",
            "strPayGrade": "رتبة الدفع",
            "strPayloadCapacity": "سعة الحمولة",
            "strPermissibleAxleLoad": "حمولة المحور المسموح بها",
            "strPermitDLClass": "فئة التصريح",
            "strPermitDateofExpiry": "تاريخ انتهاء التصريح",
            "strPermitDateofIssue": "تاريخ إصدار التصريح",
            "strPermitEndorsed": "رمز الإقرار بالتصريح",
            "strPermitIdentifier": "معرف التصريح",
            "strPermitRestrictionCode": "رمز قيود التصريح",
            "strPersonToNotifyAddress": "إخطار الشخص: العنوان",
            "strPersonToNotifyDateofRecord": "إخطار الشخص: تاريخ السجل",
            "strPersonToNotifyName": "إخطار الشخص: الاسم",
            "strPersonToNotifyPhone": "إخطار الشخص: الهاتف",
            "strPersonalNumber": "الرقم الشخصي",
            "strPersonalNumberCheckDigit": "الرقم السري للرقم الشخصي",
            "strPersonalNumberChecksum": "المجموع الرقمي للرقم الشخصي",
            "strPersonalSummary": "ملخص البيانات الشخصية",
            "strPersonalizationSN": "الرقم التسلسلي للتخصيص الشخصي",
            "strPhone": "الهاتف",
            "strPhotoArea": "منطقة الصورة",
            "strPhotoColor": "لون الصورة",
            "strPhotoCorners": "زوايا الصورة",
            "strPhotoElement": "عنصر الصورة",
            "strPhotoEmbedType": "نوع تضمين الصورة",
            "strPhotoProcessing": "معالجة الصورة...",
            "strPhotoShape": "شكل الصورة",
            "strPhotoSizeCheck": "فحص الحجم",
            "strPlaceDocumentInFrame": "ضع المستند في الإطار",
            "strPlaceOfBirthRUS": "مكان الميلاد (وطني)",
            "strPlaceOfBirthStateCode": "رمز الولاية لمكان الميلاد",
            "strPlaceOfExamination": "مكان الفحص",
            "strPlaceOfIssue": "مكان الإصدار",
            "strPlacePhoneOnDoc": "يرجى وضع الهاتف على المستند",
            "strPlaceofBirth": "مكان الميلاد",
            "strPlaceofBirthArea": "منطقة مكان الميلاد",
            "strPlaceofRegistration": "مكان التسجيل",
            "strPoliceDistrict": "منطقة الشرطة",
            "strPortrait": "صورة فوتوغرافية",
            "strPortraitComparison": "مقارنة الصور الفوتوغرافية",
            "strPortraitOfChild": "صورة الطفل",
            "strPortraitVSCamera": "صورة فوتوغرافية مقابل صورة من الكاميرا",
            "strPortraitVSGhost": "صورة فوتوغرافية مقابل صورة شبحية",
            "strPortraitVSRFID": "صورة فوتوغرافية مقابل صورة شريحة RFID",
            "strPowerWeightRatio": "نسبة القوة إلى الوزن",
            "strPrecinct": "حي",
            "strPrepareCamera": "جاري إعداد الكاميرا...",
            "strPresentNextPage": "يرجى تقديم الصفحة التالية",
            "strPreviousType": "نوع / رقم المستند السابق",
            "strProcessingDocument": "جاري معالجة المستند...",
            "strProfession": "المهنة",
            "strProfessionalIdNumber": "رقم الهوية المهنية",
            "strProofOfCitizenship": "إثبات الجنسية",
            "strPseudoCode": "شفرة زائفة",
            "strPurposeOfEntry": "غرض الدخول",
            "strRFIDVSCamera": "صورة شريحة RFID مقابل صورة من الكاميرا",
            "strRaceEthnicity": "العرق / الأصل العرقي",
            "strRank": "رتبة",
            "strReadingRFID": "قراءة بيانات شريحة RFID",
            "strReadingRFIDDGiOS": "قراءة %@ بيانات شريحة RFID",
            "strRecognizedDocumentType": "نوع المستند",
            "strReferenceNumber": "الرقم الفريد",
            "strReferenceNumberCheckDigit": "الرقم السري للرقم الفريد",
            "strReferenceNumberChecksum": "المجموع الرقمي للرقم الفريد",
            "strRegCertBodyNumber": "رقم الهيكل",
            "strRegCertBodyType": "نوع الهيكل",
            "strRegCertCarColor": "لون المركبة",
            "strRegCertCarMark": "ماركة المركبة",
            "strRegCertCarModel": "طراز المركبة",
            "strRegCertCarType": "نوع المركبة",
            "strRegCertMaxWeight": "الحد الأقصى للوزن المسموح به",
            "strRegCertRegNumber": "رقم التسجيل",
            "strRegCertRegNumberCheckDigit": "الرقم السري لرقم التسجيل",
            "strRegCertRegNumberChecksum": "المجموع الرقمي لرقم التسجيل",
            "strRegCertVIN": "رقم تعريف المركبة (VIN)",
            "strRegCertVINCheckDigit": "الرقم السري لـ VIN",
            "strRegCertVINChecksum": "المجموع الرقمي لـ VIN",
            "strRegCertVehicleITSCode": "رمز مركبة ITS",
            "strRegCertWeight": "الوزن الصافي",
            "strRelationship": "العلاقة",
            "strReligion": "الديانة",
            "strRemainderTerm": "الشهور حتى الانتهاء",
            "strResidentFrom": "مقيم من",
            "strResidentUntil": "مقيم حتى",
            "strRetirementNumber": "رقم التقاعد",
            "strRevisionDate": "تاريخ المراجعة",
            "strRoomNumber": "رقم الغرفة",
            "strSBHIntegrityOptions": "خيارات سلامة SBH",
            "strSBHSecurityOptions": "خيارات أمان SBH",
            "strSeatNumber": "رقم المقعد",
            "strSecondSurname": "اللقب الثاني",
            "strSection": "القسم",
            "strSecurityText": "نص الأمان",
            "strSelecteeIndicator": "مؤشر المختار",
            "strSequenceNumber": "رقم التسلسلي",
            "strSerialNumber": "الرقم التسلسلي",
            "strSettings": "الإعدادات",
            "strSex": "الجنس",
            "strSignature": "التوقيع",
            "strSkinColor": "لون البشرة",
            "strSocialSecurityNumber": "رقم الضمان الاجتماعي",
            "strSpCode": "الرمز الخاص",
            "strSpecialNotes": "ملاحظات خاصة",
            "strSponsor": "الكفيل",
            "strSponsorSSN": "رقم الضمان الاجتماعي للكفيل",
            "strSponsorService": "خدمة الكفيل",
            "strSponsorStatus": "حالة الكفيل",
            "strStamp": "الطابع",
            "strStampNumber": "رقم الطابع",
            "strStatusDateofExpiry": "تاريخ انتهاء الحالة",
            "strSurname": "اللقب",
            "strSurnameAndGivenNames": "اسم العائلة والأسماء الأولى",
              "strSurnameAndGivenNamesCheckDigit": "الرقم السري لاسم العائلة والأسماء الأولى",
              "strSurnameAndGivenNamesChecksum": "المجموع الرقمي لاسم العائلة والأسماء الأولى",
              "strSurnameAndGivenNamesRUS": "اسم العائلة والأسماء الأولى (وطني)",
              "strSurnameAtBirth": "اسم العائلة عند الولادة",
              "strSurnameOfHusbandAfterRegistration": "اسم العائلة للزوج بعد التسجيل",
              "strSurnameOfWifeAfterRegistration": "اسم العائلة للزوجة بعد التسجيل",
              "strSurnameofSpose": "اسم العائلة للزوج",
              "strTax": "ضريبة",
              "strTaxNumber": "رقم الضريبة",
              "strTelexCode": "كود التلكس",
              "strTerritorialValidity": "الصلاحية الإقليمية",
              "strTicketNumber": "رقم التذكرة",
              "strTitle": "اللقب",
              "strToAirportCode": "رمز مطار الوصول",
              "strTorchUnavailable": "المصباح غير متوفر",
              "strTrackingNumber": "رقم التتبع",
              "strTrailerHitch": "مشبك المقطورة",
              "strTransactionNumber": "رقم العملية",
              "strTransmissionType": "نوع النقل",
              "strTypeApprovalNumber": "نوع رقم الموافقة",
              "strURL": "رابط URL",
              "strUSCIS": "خدمات الهجرة والجنسية الأمريكية",
              "strUV": "أشعة فوق بنفسجية",
              "strUVFibers": "ألياف أمان فوق بنفسجية",
              "strUVLuminescence": "فحص الورق بأشعة فوق بنفسجية مملة",
              "strUnableCaptureMedia": "فشل تكوين الكاميرا",
              "strUniqueCustomerIdentifier": "معرف العميل الفريد",
              "strVRCDataObjectEntry": "بيانات المركبة من مجموعة البيانات DG1",
              "strValidityPeriod": "فترة الصلاحية",
              "strVehicleCategory": "فئة المركبة",
              "strVeteran": "قديم المحاربين",
              "strVisaClass": "فئة التأشيرة",
              "strVisaID": "هوية التأشيرة",
              "strVisaIDCheckDigit": "الرقم السري لهوية التأشيرة",
              "strVisaIDChecksum": "المجموع الرقمي لهوية التأشيرة",
              "strVisaIDRUS": "هوية التأشيرة (وطني)",
              "strVisaNumber": "رقم التأشيرة",
              "strVisaNumberCheckDigit": "الرقم السري لرقم التأشيرة",
              "strVisaNumberChecksum": "المجموع الرقمي لرقم التأشيرة",
              "strVisaSubClass": "فئة فرعية للتأشيرة",
              "strVisaType": "نوع التأشيرة",
              "strVisaValidFrom": "صالحة من تاريخ التأشيرة",
              "strVisaValidUntil": "صالحة حتى تاريخ التأشيرة",
              "strVisaValidUntilCheckDigit": "الرقم السري لتاريخ انتهاء صلاحية التأشيرة",
              "strVisaValidUntilChecksum": "المجموع الرقمي لتاريخ انتهاء صلاحية التأشيرة",
              "strVisibleLight": "ضوء مرئي",
              "strVoter": "ناخب",
              "strVoterKey": "مفتاح الناخب",
              "strVoucherNumber": "رقم الإيصال",
            "strWeight": "الوزن",
             "strWeightPound": "الوزن (جنيه)",
             "strYear": "السنة",
             "strYearsSinceIssue": "السنوات منذ الإصدار",
             "streIDPlaceOfBirthCity": "مكان الولادة: المدينة",
             "streIDPlaceOfBirthCountry": "مكان الولادة: البلد",
             "streIDPlaceOfBirthState": "مكان الولادة: الولاية",
             "streIDPlaceOfBirthStreet": "مكان الولادة: الشارع",
             "streIDPlaceOfBirthZipcode": "مكان الولادة: الرمز البريدي",
             "streIDResidencePermit1": "تصريح الإقامة 1",
             "streIDResidencePermit2": "تصريح الإقامة 2",
             "strfppLeftIndexFinger": "الإصبع السبابة الأيسر",
             "strfppLeftLittleFinger": "الإصبع الصغير الأيسر",
             "strfppLeftMiddleFinger": "الإصبع الأوسط الأيسر",
             "strfppLeftRingFinger": "الإصبع البيتي الأيسر",
             "strfppLeftThumb": "الإبهام الأيسر",
             "strfppRightIndexFinger": "الإصبع السبابة الأيمن",
             "strfppRightLittleFinger": "الإصبع الصغير الأيمن",
             "strfppRightMiddleFinger": "الإصبع الأوسط الأيمن",
             "strfppRightRingFinger": "الإصبع البيتي الأيمن",
             "strfppRightThumb": "الإبهام الأيمن"
        ]
    }
}
