//
//  File.swift
//  
//
//  Created by MOBILE on 26/07/24.
//

import Foundation
//
//  File.swift
//
//
//  Created by MOBILE on 20/05/24.
//

import Foundation

class CkbDataValues {
    func getDictionary() -> [String: String] {
        return [
            "RFID_Error_AlreadyDone" : "RFID: کارەکە پێشتر کراوە",
            "RFID_Error_Busy" : "RFID: RFID مشغوڵە",
            "RFID_Error_Failed" : "RFID: شکاوەت",
            "RFID_Error_FileIOError" : "پرۆبڵێمی RFID فایلی: IO",
            "RFID_Error_InvalidDirectory" : "RFID: ڕێنووسەکە هەڵەیە",
            "RFID_Error_InvalidParameter" : "RFID: پارامەتیری نەگونجاو لە بەرزەکردنەوەی ExecuteCommand() دۆزرایەوە",
            "RFID_Error_NoChipDetected" : "RFID: چیپ نەدۆزرایەوە",
            "RFID_Error_NotAvailable" : "RFID: نەماوە",
            "RFID_Error_NotEnoughMemory" : "RFID: بێ یادیارە",
            "RFID_Error_NotInitialized" : "RFID: ئامرازەکە دەستپێ نەکراوە",
            "RFID_Error_NotPerformed" : "RFID: نەکراوە",
            "RFID_Error_OldFirmware" : "RFID: فیرم وەری بە نوێیتر نوێ بکە",
            "RFID_Error_PCSC_CantConnectCard" : "PCSC: ناتوانێت کارتەکە پەیوەندیکات",
            "RFID_Error_PCSC_CardIsBusy" : "PCSC: کارتەکە مشغوڵە",
            "RFID_Error_PCSC_CardIsNotConnected" : "PCSC: کارتەکە پەیوەندی نەکراوە",
            "RFID_Error_PCSC_ExtLe_Failed" : "PCSC: ExtLe شکاوەت",
            "RFID_Error_PCSC_Failed" : "PCSC: شکاوەت",
            "RFID_Error_PCSC_FailedSCard" : "PCSC: کارتی زیرەک شکاوەت",
            "RFID_Error_PCSC_OperationCancelled" : "PCSC: کارەکە هەڵوەشێندرا",
            "RFID_Error_PCSC_ReaderNotAvailable" : "PCSC: خوێنەری نەماوە",
            "RFID_Error_Session_AccessControl_AA_Failed" : "RFID: AA شکاوەت",
            "RFID_Error_Session_AccessControl_CA_Failed" : "RFID: CA شکاوەت",
            "RFID_Error_Session_AccessControl_IncorrectOptionCA" : "RFID: هەڵەی CA لە هەڵبژاردنی",
            "RFID_Error_Session_AccessControl_RI_Failed" : "RFID: RI شکاوەت",
            "RFID_Error_Session_AccessControl_RequiresCA" : "RFID: CA پێویستە",
            "RFID_Error_Session_AccessControl_RequiresCAKeys" : "RFID: کلیلەکانی CA پێویستە",
            "RFID_Error_Session_AccessControl_RequiresPACE" : "RFID: PACE پێویستە",
            "RFID_Error_Session_AccessControl_RequiresSM" : "RFID: SM پێویستە",
            "RFID_Error_Session_AccessControl_RequiresTA" : "RFID: TA پێویستە",
            "RFID_Error_Session_AccessControl_TA_Failed" : "RFID: TA شکاوەت",
            "RFID_Error_Session_AccessControl_UnknownType" : "RFID: Access Control جۆری نەزانراو",
            "RFID_Error_Session_AccessKey_IncorrectData" : "RFID: Access Key داتای هەڵە",
            "RFID_Error_Session_AccessKey_IncorrectSMType" : "RFID: Access Key جۆری SM هەڵە",
            "RFID_Error_Session_AccessKey_NotSet" : "RFID: Access Key دانەنراوە",
            "RFID_Error_Session_AccessKey_Restricted" : "RFID: Access Key سنوردارکراو",
            "RFID_Error_Session_AccessKey_UnknownType" : "RFID: Access Key جۆری نەزانراو",
            "RFID_Error_Session_AccessKey_UnsupportedSMType" : "RFID: Access Key جۆری SM پشتگیری ناکات",
            "RFID_Error_Session_File_AccessDenied" : "پرۆبڵێمی RFID فایلی: ڕێگەپێنراو نییە",
            "RFID_Error_Session_File_CantReadData" : "پرۆبڵێمی RFID فایلی: ناتوانێت داتا بخوێنێت",
            "RFID_Error_Session_File_CantUseData" : "پرۆبڵێمی RFID فایلی: ناتوانێت داتا بەکاربەریت",
            "RFID_Error_Session_File_Contents_UnexpectedData" : "پرۆبڵێمی RFID فایلی: ناتوانێت داتای نەخوازراو",
            "RFID_Error_Session_File_IncorrectData" : "پرۆبڵێمی RFID فایلی: داتای هەڵە",
            "RFID_Error_Session_File_NotEnoughData" : "پرۆبڵێمی RFID فایلی: داتای پێویست ناکرێت",
            "RFID_Error_Session_File_UnexpectedData" : "پرۆبڵێمی RFID فایلی: داتای نەخوازراو",
            "RFID_Error_Session_File_WrongTag" : "پرۆبڵێمی RFID فایلی: تاگی هەڵە",
            "RFID_Error_Session_IncorrectData" : "RFID: داتای هەڵە",
            "RFID_Error_Session_InvalidAuxData_CommunityID" : "RFID: ناسنامەی ناحەقەی داتای هاوکاری",
            "RFID_Error_Session_InvalidAuxData_DateOfBirth" : "RFID: ڕوژەی لەدایکبوونی ناحەقەی داتای هاوکاری",
            "RFID_Error_Session_InvalidAuxData_DateOfExpiry" : "RFID: ڕوژەی بەسەرچوونی ناحەقەی داتای هاوکاری",
            "RFID_Error_Session_IsClosed" : "RFID: سێشەنەکە داخراوە",
            "RFID_Error_Session_PA_HashCheckFailed" : "RFID: تاقیکردنەوەی هاش شکاوەت",
            "RFID_Error_Session_PA_SignatureCheckFailed" : "RFID: تاقیکردنەوەی واژۆ شکاوەت",
            "RFID_Error_Session_ProcedureType_NotSet" : "RFID: جۆری پرۆسیجر دانەنراوە",
            "RFID_Error_Session_ProcedureType_Unknown" : "RFID: جۆری پرۆسیجر نەزانراوە",
            "RFID_Error_Session_ProcedureType_Unsupported" : "RFID: جۆری پرۆسیجر پشتگیری ناکرێت",
            "RFID_Error_Session_PwdManagement_NotAuthorized" : "RFID: بەڕێوەبردنی پاسۆرد دەسەڵات نەدراوە",
            "RFID_Error_Session_TerminalType_BadCertificate" : "RFID: جۆری تەرمیندا سەربەخەتی هەڵە",
            "RFID_Error_Session_TerminalType_NotSet" : "RFID: جۆری تەرمیندا دانەنراوە",
            "RFID_Error_Session_TerminalType_Unknown" : "RFID: جۆری تەرمیندا نەزانراوە",
            "RFID_Error_Session_Terminal_UnsupportedOperation" : "RFID: کارکردنی تەرمیندا پشتگیری ناکرێت",
            "RFID_Error_Session_eSign_PIN_NotSet" : "RFID: eSign PIN دانەنراوە",
            "RFID_Error_Session_eSign_PIN_NotVerified" : "RFID: eSign PIN پشتراوەنیە",
            "RFID_Error_Session_eSign_RequiresAppSelection" : "RFID: eSign هەڵبژاردنی بەرنامە پێویستە",
            "RFID_Error_UnknownCommand" : "RFID: فەرمانی نەزانراو",
            "RFID_LAYER6_APP_SELECTION_FAILURE" : "لایەری ۶: ISO7816_A_03 شکاوەتی هەڵبژاردنی بەرنامە",
            "RFID_LAYER6_EXT_AUTH_FAILURE" : "لایەری ۶: شکاوەتی ڕەسەنکردنی دەرەکی APDU_INS_EXTERNAL_AUTHENTICATE",
            "RFID_LAYER6_FILE_EOF1" : "لایەری ۶: خوێندنەوەی دەوری پەیوەندی خاتم",
            "RFID_LAYER6_FILE_EOF2" : "لایەری ۶: خوێندنەوەی دەوری پەیوەندی خاتم",
            "RFID_LAYER6_FILE_NOT_FOUND" : "لایەری ۶: فایلی نەدۆزرایەوە / شکاوەتی هەڵبژاردنی فایلی",
            "RFID_LAYER6_GENERAL_AUTH_FAILURE" : "لایەری ۶: شکاوەتی ڕەسەنکردنی گشتی",
            "RFID_LAYER6_GET_CHALLENGE_FAILURE" : "لایەری ۶: شکاوەتی GET CHALLENGE",
            "RFID_LAYER6_INCORRECT_PARAMS" : "لایەری ۶: پارامەتیری هەڵە",
            "RFID_LAYER6_INT_AUTH_FAILURE" : "لایەری ۶: شکاوەتی ڕەسەنکردنی نێوخۆی APDU_INS_INTERNAL_AUTHENTICATE",
            "RFID_LAYER6_MSE_SET_AT_FAILURE" : "لایەری ۶: شکاوەتی MSE:Set AT",
            "RFID_LAYER6_MSE_SET_DST_FAILURE" : "لایەری ۶: شکاوەتی MSE:Set DST",
            "RFID_LAYER6_MSE_SET_KAT_FAILURE" : "لایەری ۶: شکاوەتی MSE:Set KAT",
            "RFID_LAYER6_MUTUAL_AUTH_ENC_FAIL" : "لایەری ۶: ISO7816_B_02 شکاوەتی ڕەسەنکردنی هاوبەشی",
            "RFID_LAYER6_MUTUAL_AUTH_FAILURE" : "لایەری ۶: ISO7816_B_03 شکاوەتی ڕەسەنکردنی هاوبەشی",
            "RFID_LAYER6_MUTUAL_AUTH_MAC_FAIL" : "لایەری ۶: ISO7816_B_01 شکاوەتی ڕەسەنکردنی هاوبەشی MAC",
            "RFID_LAYER6_NON_TLV_RESPONSE_DATA" : "لایەری ۶: داتای وەڵامی TLV نیە",
            "RFID_LAYER6_NO_REFERENCE_DATA" : "لایەری ۶: هیچ داتای پەیوەندییەکی نیە",
            "RFID_LAYER6_PSO_CERTIFICATE_FAILURE" : "لایەری ۶: شکاوەتی پەسەندی PSO",
            "RFID_LAYER6_PWD_BLOCKED" : "لایەری ۶: پاسۆرد ڕابەسترا",
            "RFID_LAYER6_PWD_BLOCKED_2" : "لایەری ۶: پاسۆرد ڕابەسترا ٢",
            "RFID_LAYER6_PWD_DEACTIVATED" : "لایەری ۶: پاسۆرد ناچالاک کرا",
            "RFID_LAYER6_PWD_DEACTIVATED_2" : "لایەری ۶: پاسۆرد ناچالاک کرا ٢",
            "RFID_LAYER6_PWD_FAILED" : "لایەری ۶: پاسۆرد شکاوەت",
            "RFID_LAYER6_PWD_SUSPENDED" : "لایەری ۶: پاسۆرد ڕاوەستا",
            "RFID_LAYER6_PWD_SUSPENDED_2" : "لایەری ۶: پاسۆرد ڕاوەستا ٢",
            "RFID_LAYER6_SECURITY_MANAGER" : "لایەری ۶: پیامەکانی دژەهێنراوی چالاک نەکرا",
            "RFID_LAYER6_SM_DO87_INCORRECT" : "لایەری ۶: شکاوەتی SM – شێوازی هەڵەی کرپتوگرام",
            "RFID_LAYER6_SM_DO87_MISSING" : "لایەری ۶: شکاوەتی SM – کرپتوگرام بوونی نیە",
            "RFID_LAYER6_SM_DO8E_MISSING" : "لایەری ۶: شکاوەتی SM – MAC بوونی نیە",
            "RFID_LAYER6_SM_DO99_MISSING" : "لایەری ۶: شکاوەتی SM – دانەپێیەی تایبەتی چالاکی بوونی نیە",
            "RFID_LAYER6_SM_MAC_INCORRECT" : "لایەری ۶: شکاوەتی SM – MAC هەڵە",
            "RFID_LAYER6_WRONG_RND_ICC_LENGTH" : "لایەری ۶: درێژی داتای هەڵە (APDU_INS_GET_CHALLENGE)",
            "RSDT_RFID_READING_FINISHED" : "خوێندنەوەی داتای RFID تەواو بوو",
            "TCT_Unknown" : "نەزانراو",
            "chd_BackgroundComparisonError" : "رووناکی دوو پەڕەکان جیاوازە",
            "chd_BadAreaInAxial" : "شکاوەتی پەیوەندی ڕێکەوتکراو",
            "chd_BarcodeDataFormatError" : "شکاوەتی فۆڕمات بارکۆد",
            "chd_BarcodeReadedWithErrors" : "بارکۆد بە هەڵە خوێندرا",
            "chd_BarcodeSizeParamsError" : "شکاوەتی پارامەتەری قەبارەی بارکۆد",
            "chd_DocumentIsCancelling" : "بەڵگەکە پەسەند کراوە",
            "chd_ElementShouldBeColored" : "ئەلێمێنت دەبێت ڕەنگی هەبێت",
            "chd_ElementShouldBeGrayscale" : "ئەلێمێنت دەبێت ڕەنگی سۆری هەبێت",
            "chd_ExceptionInModule" : "دەرچووەکە بە ئاستمکار بوو",
            "chd_FalseIPIParameters" : "پارامەتەری نادروستی IPI",
            "chd_FalseLuminiscenceError" : "بوونی ئەشیاکانی نوری نەبەزار",
            "chd_FalseLuminiscenceInBlank" : "نوری نەبەزار لە شوێنە بەتالی UV",
            "chd_FalseLuminiscenceInMRZ" : "نوری نەبەزار لە شوێنەکانی MRZ",
            "chd_FibersNotFound" : "فایبەر نەدۆزرایەوە",
            "chd_FieldPosCorrector_Highlight_IR" : "نورە زیاتر لە IR",
            "chd_FieldsComparisonLogicError" : "شکاوەتی لۆژیکی لە کاتی بڕیاری خانەکان",
            "chd_FixedPatternError" : "شکاوەتی نەگۆڕینی شیئی تایبەتی",
            "chd_HologramElementAbsent" : "ھۆلۆگرام بوونی نیە",
            "chd_HologramElementPresent" : "ھۆلۆگرام دۆزرایەوە",
            "chd_Hologram_Side_Top_Images_Absent" : "وێنەی لاو یان لەوە بوونی نیە",
            "chd_IncorrectBackgroundLight" : "رووناکی پشتەی هەڵە",
            "chd_IncorrectTextColor" : "ڕەنگی دەق هەڵە",
            "chd_InternalError" : "شکاوەتی کارکردنی داتای ناوخۆ",
            "chd_InvalidChecksum" : "چیکەسەمی نادروست",
            "chd_InvalidFieldFormat" : "فۆڕماتی خانەی نەگونجاوە بەرەوەی پەسەندکراوی بەڵگە",
            "chd_InvalidInputData" : "داتای هاتوو نادروستە",
            "chd_InvisibleElementPresent" : "شیئی نادروست دەبێت بێت",
            "chd_LogicError" : "شکاوەتی داتای لۆژیکی",
            "chd_LowContrastInIRLight" : "کۆنترەستی نەگونجاوی شیئی لە نوری IR",
            "chd_MobileImages_LowLightConditions" : "مەزرۆی نوری نەگونجاو بۆ گراندنی وێنەکان",
            "chd_MobileImages_WhileUVNoDifference" : "جیاوازی نەگونجاو نێوان وێنەکان لە کاتی ڕووناوی UV",
            "chd_NecessaryImageNotFound" : "وێنەی پێویست بۆ ئەم تاقیکردنەوە نەبوو",
            "chd_NotAllBarcodesRead" : "ئەم بەڵگەیە دەبێت بارکۆدی زیاتر هەبێت",
            "chd_OVI_BadColor_Front" : "ڕەنگی شیئی OVI پێنەگونجاوی بە نوری سپی",
            "chd_OVI_BadColor_Percent" : "پێنەگونجینی سەدی شیئی OVI",
            "chd_OVI_BadColor_Side" : "ڕەنگی شیئی OVI پێنەگونجاوی بە نوری ڕاستەوخۆ",
            "chd_OVI_ColorInvariable" : "ڕەنگی OVI نەگونجاوە",
            "chd_OVI_IR_Invisible" : "کۆنترەستی شیئی OVI پێنەگونجاوە",
            "chd_OVI_InsufficientArea" : "شوێنی پێویستی شیئی OVI ناکرێت",
            "chd_OVI_Wide_Color_Spread" : "پێنەگونجینی ڕەنگی شیئی OVI",
            "chd_Pass" : "شکاوە نیە",
            "chd_PhotoFalseLuminiscence" : "نوری نەبەزار لە شوێنەکانی وێنە",
            "chd_PhotoPattern_DifferentColors" : "ڕەنگەکانی پەترنی لە وێنە وەک شوێنە بەتال جیاوازن",
            "chd_PhotoPattern_DifferentLinesThickness" : "درێژی جیاوازی شێوەکان",
            "chd_PhotoPattern_IR_Visible" : "پەترنی تایبەتی لە IR بینی",
            "chd_PhotoPattern_Interrupted" : "پەترنی نێوان وێنە وە شوێنە بەتال داخرا",
            "chd_PhotoPattern_InvalidColor" : "ڕەنگی پەترنی نادروست",
            "chd_PhotoPattern_Not_Intersect" : "لێکەوتەی لاوێنەی وێنە پەترن پێ نەگونجاوە",
            "chd_PhotoPattern_PatternNotFound" : "پەترن نەدۆزرایەوە لە شوێنەکانی وێنە",
            "chd_PhotoPattern_Shifted" : "پەترنی وێنە دایناوە بەرەو پەترنی شوێنە بەتال",
            "chd_PhotoPattern_Shifted_Vert" : "شێواکان بە بەراورد بەرەوی یەکێکتری تر جیاون",
            "chd_PhotoSidesNotFound" : "ئەنجامی لاوێنەی وێنە نەدۆزرایەوە",
            "chd_PhotoSize_Is_Wrong" : "قەبارەی وێنە هەڵەیە",
            "chd_Photo_Corners_Is_Wrong" : "گۆشەکانی وێنە پێ نەگونجاوە",
            "chd_Photo_IsNot_Rectangle" : "شێوەی وێنە قەدەخەی نیە",
            "chd_PortraitComparison_NoLivePhoto" : "وێنەی کەمارا نیە",
            "chd_PortraitComparison_NoPortraitDetected" : "وێنەی لە نێوان وێنەکان نەدۆزرایەوە",
            "chd_PortraitComparison_NoServiceLicense" : "مەجێنەی خزمەتی نیە",
            "chd_PortraitComparison_NoServiceReply" : "وەڵامی خزمەت نیە",
            "chd_PortraitComparison_NotEnoughImages" : "وێنەکان پێوەندین",
            "chd_PortraitComparison_PortraitsDiffer" : "وێنەکان پێ نەپەیوەندن",
            "chd_PortraitComparison_ServiceError" : "شکاوەتی خزمەت",
            "chd_SourcesComparisonError" : "شکاوەتی بەراوردی داتاکانی سەرچاوەکان",
            "chd_SpecksInUV" : "نوری زیاتر یان بڵاک لە وێنەی نوری UV",
            "chd_SyntaxError" : "شکاوەتی سێنەی تاکە",
            "chd_TextColorShouldBeBlue" : "ڕەنگی دەق دەبێت شین بێت",
            "chd_TextColorShouldBeGreen" : "ڕەنگی دەق دەبێت سەوز بێت",
            "chd_TextColorShouldBeRed" : "ڕەنگی دەق دەبێت سور بێت",
            "chd_TextShouldBeBlack" : "ڕەنگی دەق دەبێت ڕەش بێت",
            "chd_TooLowResolution" : "ڕزۆلێشنی زۆر کەم بۆ دۆزینەوەی فایبەرەکان",
            "chd_TooManyObjects" : "شییەکی زۆر",
            "chd_TooMuchShift" : "بەرامبەر نرخی ڕێپێدەران",
            "chd_TrueLuminiscenceError" : "نەگونجینی ئەنکاری نوری",
            "chd_UVDullPaperError" : "شکاوەتی پەیوەندی UV دڵکە",
            "chd_UVDullPaper_Blank" : "پەیوەندی UV لە شوێنە بەتالی دڵکە",
            "chd_UVDullPaper_MRZ" : "پەیوەندی UV لە شوێنەکانی MRZ دڵکە",
            "chd_UVDullPaper_Photo" : "پەیوەندی UV لە شوێنەکانی وێنە دڵکە",
            "chd_UncertainVerification" : "بەڵێنی پشتگیری بە باور نەکردنی بوو",
            "chd_Unknown" : "نەزانراو",
            "chd_VisibleElementAbsent" : "شیئی ڕەش بوونی نیە لە IR",
            "strAGY" : "AGY",
            "strAKADateofBirth" : "AKA داتای بە دایک بوون",
            "strAKAGivenNames" : "AKA ناوی پێشین",
            "strAKANamePrefix" : "AKA پێش زانیاری",
            "strAKANameSuffix" : "AKA پس زانیاری",
            "strAKASocialSecurityNumber" : "AKA ژمارەی پاراستنی کۆمەڵایەتی",
            "strAKASurname" : "AKA ناوی خانووە",
            "strAKASurnameAndGivenNames" : "AKA ناوی تەواو",
            "strALTCode" : "کۆدی ALT",
            "strAcademicTitle" : "سەردانی تەندروستی",
            "strAccessibilityCameraButton" : "وێنەیەک بگرە و دەست بە شیکردنەوە بکە",
            "strAccessibilityCloseButton" : "داخستن",
            "strAccessibilityTorchButton" : "پڕۆژە",
            "strAccompaniedby" : "پەیوەندیدار",
            "strAddress" : "ناونیشان",
            "strAddressArea" : "ناوچە",
            "strAddressBuilding" : "بەش",
            "strAddressCity" : "شار",
            "strAddressCountry" : "وڵات",
            "strAddressFlat" : "پارچە",
            "strAddressHouse" : "خانوو",
            "strAddressJurisdictionCode" : "کۆدی پەیوەندیداری",
            "strAddressLocation" : "شوێن",
            "strAddressMunicipality" : "پەیوەندیداری",
            "strAddressPostalCode" : "کۆدی پۆستی",
            "strAddressState" : "دۆڵەت",
            "strAddressStreet" : "شەقام",
            "strAdministrativeNumber" : "ژمارەی کارکردنی دەزگاکان",
            "strAge" : "تەمەن",
            "strAgeAtIssue" : "تەمەنی دەرچوو",
            "strAirlineDesignatorofboardingpassissuer" : "پەیوەندیداری ناوچەی نیشتجێ",
            "strAirlineName" : "ناوی فڕۆکە",
            "strAirlineNameFrequentFlyer" : "ناوی ئەنجامەکان بۆ فڕۆکەکان",
            "strAirlineNumericCode" : "کۆدی ژمارەی فڕۆکە",
            "strAirportFrom" : "بەرواری دیاری",
            "strAirportTo" : "بەرواری گەیشتن",
            "strAllergies" : "ئەوەدانەکانی نەبەزار",
            "strApplicationDoNotHavePermission" : "ئەپلیکەیشنی نییە بۆ بەکارهێنانی کامێرا، تکایە ڕوونی تایبەتی بگۆڕە",
            "strApplicationNumber" : "ژمارەی ئەپلیکەیشنی",
            "strArtisticName" : "ناوی هنەری",
            "strAuditInformation" : "ژمارەی پەیوەندیداری",
            "strAuthentification" : "پەیوەندیداری بۆ نەخێنی",
            "strAuthority" : "دەزگاکانی دەرچوو",
            "strAuthorityCode" : "کۆدی دەزگاکانی دەرچوو",
            "strAuthorityRUS" : "دەزگاکانی دەرچوو (نەشتیمانی)",
            "strAuthorizationNumber" : "ژمارەی پەیوەندیداری",
            "strAxialProtection" : "پەیوەندیداری ڕێکەوتکراوی",
            "strBDBType" : "جۆری BDB",
            "strBankCardNumber" : "ژمارەی کارتی بانک",
            "strBankCardValidThru" : "درێژەی کارتی بانک",
            "strBanknoteNumber" : "ژمارەی پارەی بانک",
            "strBarcode" : "بارکۆد",
            "strBarcodeFormatCheck" : "پشکنینی فۆرماتی بارکۆد",
            "strBenefitsNumber" : "ژمارەی دەرپەڕینا",
            "strBinaryCode" : "کۆدی دووگەر",
            "strBiometricFormatOwner" : "خاوەنی فۆرماتی بایۆمتریک",
            "strBiometricFormatType" : "جۆری فۆرماتی بایۆمتریک",
            "strBiometricProductID" : "ناسەی ئەوەدانە بایۆمتریک",
            "strBiometricSubtype" : "جۆری بایۆمتریک",
            "strBiometricType" : "جۆری بایۆمتریک",
            "strBlankElement" : "ئەندامە نەچالاک",
            "strBloodGroup" : "گروپی خوێن",
            "strBookletNumber" : "ژمارەی پەیوەندیدار",
            "strCCWUntil" : "CCW تاکوو",
            "strCDLClass" : "پۆلی CDL",
            "strCSCCode" : "کۆدی CSC",
            "strCVV" : "CVV/CVC",
            "strCaliber" : "بەراورد",
            "strCameraUnavailable" : "کامێرا بوونی نیە",
            "strCardAccessNumber" : "ژمارەی پەیوەندیداری کارت",
            "strCategory" : "پۆل",
            "strCenturyDateOfBirth" : "سەدەی بە دایک بوون",
            "strChassisNumber" : "ژمارەی شاسی",
            "strCheckInSequenceNumber" : "ژمارەی گۆڕینەوە",
            "strChildren" : "مندال",
            "strCitizenshipOfFirstPerson" : "پەیوەندیداری ئەوەندەیەکی یەکەم",
            "strCitizenshipOfSecondPerson" : "پەیوەندیداری ئەوەندەیەکی دووەم",
            "strCivilStatus" : "رەوەنداوی مەدەنی",
            "strColorDynamic" : "پێوەندیداری ڕەنگی چالاک",
            "strCommercialVehicleCodes" : "کۆدی ئوتومبێلی کەمیابی",
            "strCompanyName" : "ناوی کمپانیا",
            "strCompartmentCode" : "کۆدی بەشی پارچە",
            "strComplexion" : "کێش",
            "strComplianceType" : "جۆری گەیاندنی پەیوەندی",
            "strConditions" : "بارودۆخی گەیاندنی",
            "strConfiguration" : "چالاکی",
            "strControlNo" : "ژمارەی کارکردنی",
            "strCopy" : "کۆپی",
            "strCourtCode" : "کۆدی دادگا",
            "strCty" : "کانتی",
            "strCurrentDate" : "بەرواری هەنووکە",
            "strCustodyInfo" : "زانیاری پاراستن",
            "strDFTAppDirectory" : "ناوچەی ئەپلیکەیشنی",
            "strDFTCertificate" : "پەسەندکردنی دەزگاکان",
            "strDG1" : "زانیاری خوێندنەوەی ئوتۆماتیکی (DG1)",
            "strDG10" : "نەکارە DG10",
            "strDG11" : "زانیاری زیادەی شەخسی (DG11)",
            "strDG12" : "زانیاری زیادەی بەڵگە (DG12)",
            "strDG13" : "زانیاری تایبەتی (DG13)",
            "strDG14" : "زانیاری پەیوەندی چالاک (DG14)",
            "strDG15" : "پەیوەندی چالاک بۆ پەیوەندی (DG15)",
            "strDG16" : "کەسانی پەیوەندی دێندەکانی (DG16)",
            "strDG17" : "DG17",
            "strDG18" : "DG18",
            "strDG19" : "DG19",
            "strDG2" : "بایۆمتریک - زانیاری دەرووی (DG2)",
            "strDG20" : "DG20",
            "strDG3" : "بایۆمتریک - ئەنگوستەکان (DG3)",
            "strDG4" : "بایۆمتریک - زانیاری چاو (DG4)",
            "strDG5" : "وێنەکانی (DG5)",
            "strDG6" : "نەکارە DG6",
            "strDG7" : "وێنە یان کەمارا (DG7)",
            "strDG8" : "نەکارە DG8",
            "strDG9" : "نەکارە DG9",
            "strDLCDLRestrictionCode" : "کۆدی پەیوەندیداری CDL",
            "strDLClass" : "پۆلی DL",
            "strDLClassCodeA1From": "بەرواری جێبەجێبوونی پۆلی A1",
                "strDLClassCodeA1Notes": "کۆدی پۆلی A1",
                "strDLClassCodeA1To": "بەرواری بەسەرچوونی پۆلی A1",
                "strDLClassCodeA2From": "بەرواری جێبەجێبوونی پۆلی A2",
                "strDLClassCodeA2Notes": "کۆدی پۆلی A2",
                "strDLClassCodeA2To": "بەرواری بەسەرچوونی پۆلی A2",
                "strDLClassCodeA3From": "بەرواری جێبەجێبوونی پۆلی A3",
                "strDLClassCodeA3Notes": "کۆدی پۆلی A3",
                "strDLClassCodeA3To": "بەرواری بەسەرچوونی پۆلی A3",
                "strDLClassCodeAFrom": "بەرواری جێبەجێبوونی پۆلی A",
                "strDLClassCodeAMFrom": "بەرواری جێبەجێبوونی پۆلی AM",
                "strDLClassCodeAMNotes": "کۆدی پۆلی AM",
                "strDLClassCodeAMTo": "بەرواری بەسەرچوونی پۆلی AM",
                "strDLClassCodeANotes": "کۆدی پۆلی A",
                "strDLClassCodeATo": "بەرواری بەسەرچوونی پۆلی A",
                "strDLClassCodeB1From": "بەرواری جێبەجێبوونی پۆلی B1",
                "strDLClassCodeB1Notes": "کۆدی پۆلی B1",
                "strDLClassCodeB1To": "بەرواری بەسەرچوونی پۆلی B1",
                "strDLClassCodeB2EFrom": "بەرواری جێبەجێبوونی پۆلی B2E",
                "strDLClassCodeB2ENotes": "کۆدی پۆلی B2E",
                "strDLClassCodeB2ETo": "بەرواری بەسەرچوونی پۆلی B2E",
                "strDLClassCodeB2From": "بەرواری جێبەجێبوونی پۆلی B2",
                "strDLClassCodeB2Notes": "کۆدی پۆلی B2",
                "strDLClassCodeB2To": "بەرواری بەسەرچوونی پۆلی B2",
                "strDLClassCodeBEFrom": "بەرواری جێبەجێبوونی پۆلی BE",
                "strDLClassCodeBENotes": "کۆدی پۆلی BE",
                "strDLClassCodeBETo": "بەرواری بەسەرچوونی پۆلی BE",
                "strDLClassCodeBFrom": "بەرواری جێبەجێبوونی پۆلی B",
                "strDLClassCodeBNotes": "کۆدی پۆلی B",
                "strDLClassCodeBTPFrom": "بەرواری جێبەجێبوونی پۆلی BTP",
                "strDLClassCodeBTPNotes": "کۆدی پۆلی BTP",
                "strDLClassCodeBTPTo": "بەرواری بەسەرچوونی پۆلی BTP",
                "strDLClassCodeBTo": "بەرواری بەسەرچوونی پۆلی B",
                "strDLClassCodeC1EFrom": "بەرواری جێبەجێبوونی پۆلی C1E",
                "strDLClassCodeC1ENotes": "کۆدی پۆلی C1E",
                "strDLClassCodeC1ETo": "بەرواری بەسەرچوونی پۆلی C1E",
                "strDLClassCodeC1From": "بەرواری جێبەجێبوونی پۆلی C1",
                "strDLClassCodeC1Notes": "کۆدی پۆلی C1",
                "strDLClassCodeC1To": "بەرواری بەسەرچوونی پۆلی C1",
                "strDLClassCodeC2From": "بەرواری جێبەجێبوونی پۆلی C2",
                "strDLClassCodeC2Notes": "کۆدی پۆلی C2",
                "strDLClassCodeC2To": "بەرواری بەسەرچوونی پۆلی C2",
                "strDLClassCodeC3From": "بەرواری جێبەجێبوونی پۆلی C3",
                "strDLClassCodeC3Notes": "کۆدی پۆلی C3",
                "strDLClassCodeC3To": "بەرواری بەسەرچوونی پۆلی C3",
                "strDLClassCodeCAFrom": "بەرواری جێبەجێبوونی پۆلی CA",
                "strDLClassCodeCANotes": "کۆدی پۆلی CA",
                "strDLClassCodeCATo": "بەرواری بەسەرچوونی پۆلی CA",
                "strDLClassCodeCEFrom": "بەرواری جێبەجێبوونی پۆلی CE",
                "strDLClassCodeCENotes": "کۆدی پۆلی CE",
                "strDLClassCodeCETo": "بەرواری بەسەرچوونی پۆلی CE",
                "strDLClassCodeCFrom": "بەرواری جێبەجێبوونی پۆلی C",
                "strDLClassCodeCNotes": "کۆدی پۆلی C",
                "strDLClassCodeCTo": "بەرواری بەسەرچوونی پۆلی C",
                "strDLClassCodeD1EFrom": "بەرواری جێبەجێبوونی پۆلی D1E",
                "strDLClassCodeD1ENotes": "کۆدی پۆلی D1E",
                "strDLClassCodeD1ETo": "بەرواری بەسەرچوونی پۆلی D1E",
                "strDLClassCodeD1From": "بەرواری جێبەجێبوونی پۆلی D1",
                "strDLClassCodeD1Notes": "کۆدی پۆلی D1",
                "strDLClassCodeD1To": "بەرواری بەسەرچوونی پۆلی D1",
                "strDLClassCodeD2From": "بەرواری جێبەجێبوونی پۆلی D2",
                "strDLClassCodeD2Notes": "کۆدی پۆلی D2",
                "strDLClassCodeD2To": "بەرواری بەسەرچوونی پۆلی D2",
                "strDLClassCodeDEFrom": "بەرواری جێبەجێبوونی پۆلی DE",
                "strDLClassCodeDENotes": "کۆدی پۆلی DE",
                "strDLClassCodeDETo": "بەرواری بەسەرچوونی پۆلی DE",
                "strDLClassCodeDFrom": "بەرواری جێبەجێبوونی پۆلی D",
                "strDLClassCodeDNotes": "کۆدی پۆلی D",
                "strDLClassCodeDTo": "بەرواری بەسەرچوونی پۆلی D",
                "strDLClassCodeEFrom": "بەرواری جێبەجێبوونی پۆلی E",
                "strDLClassCodeENotes": "کۆدی پۆلی E",
                "strDLClassCodeETo": "بەرواری بەسەرچوونی پۆلی E",
                "strDLClassCodeFA1From": "بەرواری جێبەجێبوونی پۆلی FA1",
                "strDLClassCodeFA1Notes": "کۆدی پۆلی FA1",
                "strDLClassCodeFA1To": "بەرواری بەسەرچوونی پۆلی FA1",
                "strDLClassCodeFAFrom": "بەرواری جێبەجێبوونی پۆلی FA",
                "strDLClassCodeFANotes": "کۆدی پۆلی FA",
                "strDLClassCodeFATo": "بەرواری بەسەرچوونی پۆلی FA",
                "strDLClassCodeFBFrom": "بەرواری جێبەجێبوونی پۆلی FB",
                "strDLClassCodeFBNotes": "کۆدی پۆلی FB",
                "strDLClassCodeFBTo": "بەرواری بەسەرچوونی پۆلی FB",
                "strDLClassCodeFFrom": "بەرواری جێبەجێبوونی پۆلی F",
                "strDLClassCodeFNotes": "کۆدی پۆلی F",
                "strDLClassCodeFTo": "بەرواری بەسەرچوونی پۆلی F",
                "strDLClassCodeG1From": "بەرواری جێبەجێبوونی پۆلی G1",
                "strDLClassCodeG1Notes": "کۆدی پۆلی G1",
                "strDLClassCodeG1To": "بەرواری بەسەرچوونی پۆلی G1",
                "strDLClassCodeGFrom": "بەرواری جێبەجێبوونی پۆلی G",
                "strDLClassCodeGNotes": "کۆدی پۆلی G",
                "strDLClassCodeGTo": "بەرواری بەسەرچوونی پۆلی G",
                "strDLClassCodeHCFrom": "بەرواری جێبەجێبوونی پۆلی HC",
                "strDLClassCodeHCNotes": "کۆدی پۆلی HC",
                "strDLClassCodeHCTo": "بەرواری بەسەرچوونی پۆلی HC",
                "strDLClassCodeHFrom": "بەرواری جێبەجێبوونی پۆلی H",
                "strDLClassCodeHNotes": "کۆدی پۆلی H",
                "strDLClassCodeHRFrom": "بەرواری جێبەجێبوونی پۆلی HR",
                "strDLClassCodeHRNotes": "کۆدی پۆلی HR",
                "strDLClassCodeHRTo": "بەرواری بەسەرچوونی پۆلی HR",
                "strDLClassCodeHTo": "بەرواری بەسەرچوونی پۆلی H",
                "strDLClassCodeIFrom": "بەرواری جێبەجێبوونی پۆلی I",
                "strDLClassCodeINotes": "کۆدی پۆلی I",
                "strDLClassCodeITo": "بەرواری بەسەرچوونی پۆلی I",
                "strDLClassCodeJFrom": "بەرواری جێبەجێبوونی پۆلی J",
                "strDLClassCodeJNotes": "کۆدی پۆلی J",
                "strDLClassCodeJTo": "بەرواری بەسەرچوونی پۆلی J",
                "strDLClassCodeKFrom": "بەرواری جێبەجێبوونی پۆلی K",
                "strDLClassCodeKNotes": "کۆدی پۆلی K",
                "strDLClassCodeKTo": "بەرواری بەسەرچوونی پۆلی K",
                "strDLClassCodeLCFrom": "بەرواری جێبەجێبوونی پۆلی LC",
                "strDLClassCodeLCNotes": "کۆدی پۆلی LC",
                "strDLClassCodeLCTo": "بەرواری بەسەرچوونی پۆلی LC",
                "strDLClassCodeLFrom": "بەرواری جێبەجێبوونی پۆلی L",
                "strDLClassCodeLKFrom": "بەرواری جێبەجێبوونی پۆلی LK",
                "strDLClassCodeLKNotes": "کۆدی پۆلی LK",
                "strDLClassCodeLKTo": "بەرواری بەسەرچوونی پۆلی LK",
                "strDLClassCodeLNotes": "کۆدی پۆلی L",
                "strDLClassCodeLRFrom": "بەرواری جێبەجێبوونی پۆلی LR",
                "strDLClassCodeLRNotes": "کۆدی پۆلی LR",
                "strDLClassCodeLRTo": "بەرواری بەسەرچوونی پۆلی LR",
                "strDLClassCodeLTo": "بەرواری بەسەرچوونی پۆلی L",
                "strDLClassCodeMCFrom": "بەرواری جێبەجێبوونی پۆلی MC",
                "strDLClassCodeMCNotes": "کۆدی پۆلی MC",
                "strDLClassCodeMCTo": "بەرواری بەسەرچوونی پۆلی MC",
                "strDLClassCodeMFrom": "بەرواری جێبەجێبوونی پۆلی M",
                "strDLClassCodeMNotes": "کۆدی پۆلی M",
                "strDLClassCodeMRFrom": "بەرواری جێبەجێبوونی پۆلی MR",
                "strDLClassCodeMRNotes": "کۆدی پۆلی MR",
                "strDLClassCodeMRTo": "بەرواری بەسەرچوونی پۆلی MR",
                "strDLClassCodeMTo": "بەرواری بەسەرچوونی پۆلی M",
                "strDLClassCodeNFrom": "بەرواری جێبەجێبوونی پۆلی N",
                "strDLClassCodeNNotes": "کۆدی پۆلی N",
                "strDLClassCodeNTo": "بەرواری بەسەرچوونی پۆلی N",
                "strDLClassCodeREFrom": "بەرواری جێبەجێبوونی پۆلی RE",
                "strDLClassCodeRENotes": "کۆدی پۆلی RE",
                "strDLClassCodeRETo": "بەرواری بەسەرچوونی پۆلی RE",
                "strDLClassCodeRFrom": "بەرواری جێبەجێبوونی پۆلی R",
                "strDLClassCodeRNotes": "کۆدی پۆلی R",
                "strDLClassCodeRTo": "بەرواری بەسەرچوونی پۆلی R",
                "strDLClassCodeSFrom": "بەرواری جێبەجێبوونی پۆلی S",
                "strDLClassCodeSNotes": "کۆدی پۆلی S",
                "strDLClassCodeSTo": "بەرواری بەسەرچوونی پۆلی S",
                "strDLClassCodeTBFrom": "بەرواری جێبەجێبوونی پۆلی TB",
                "strDLClassCodeTBNotes": "کۆدی پۆلی TB",
                "strDLClassCodeTBTo": "بەرواری بەسەرچوونی پۆلی TB",
                "strDLClassCodeTFrom": "بەرواری جێبەجێبوونی پۆلی T",
                "strDLClassCodeTMFrom": "بەرواری جێبەجێبوونی پۆلی TM",
                "strDLClassCodeTMNotes": "کۆدی پۆلی TM",
                "strDLClassCodeTMTo": "بەرواری بەسەرچوونی پۆلی TM",
                "strDLClassCodeTNotes": "کۆدی پۆلی T",
                "strDLClassCodeTRFrom": "بەرواری جێبەجێبوونی پۆلی TR",
                "strDLClassCodeTRNotes": "کۆدی پۆلی TR",
                "strDLClassCodeTRTo": "بەرواری بەسەرچوونی پۆلی TR",
                "strDLClassCodeTTo": "بەرواری بەسەرچوونی پۆلی T",
                "strDLClassCodeTVFrom": "بەرواری جێبەجێبوونی پۆلی TV",
                "strDLClassCodeTVNotes": "کۆدی پۆلی TV",
                "strDLClassCodeTVTo": "بەرواری بەسەرچوونی پۆلی TV",
                "strDLClassCodeVFrom": "بەرواری جێبەجێبوونی پۆلی V",
                "strDLClassCodeVNotes": "کۆدی پۆلی V",
                "strDLClassCodeVTo": "بەرواری بەسەرچوونی پۆلی V",
                "strDLClassCodeWFrom": "بەرواری جێبەجێبوونی پۆلی W",
                "strDLClassCodeWNotes": "کۆدی پۆلی W",
                "strDLClassCodeWTo": "بەرواری بەسەرچوونی پۆلی W",
                "strDLDuplicateDate": "بەرواری دابەشکردنی دووبارە",
                "strDLEndorsed": "کۆدی پشتگری کردن",
                "strDLIssType": "جۆری کارت",
                "strDLRecordCreated": "تۆمار دروستکرا",
                "strDLRestrictionCode": "کۆدی سنوور",
                "strDLUnder18Date": "بەرواری 18 ساڵە",
                "strDLUnder19Date": "بەرواری 19 ساڵە",
                "strDLUnder21Date": "بەرواری 21 ساڵە",
                "strDNINumber": "ژمارەی DNI",
                "strDSCertificateIssuer": "ڕەزامەندی بلگی DS",
                "strDSCertificateSubject": "سەردێڕی بلگی DS",
                "strDSCertificateValidFrom": "بەرواری جێبەجێبوونی بلگی DS",
                "strDSCertificateValidTo": "بەرواری بەسەرچوونی بلگی DS",
                "strDUFNumber": "ژمارەی DUF",
                "strDataDiscriminator": "پۆشایە پاشان",
                "strDateFirstRenewal": "بەرواری نوێکردنەوەی یەکەم",
                "strDateOfBirthOfHusband": "بەرواری لەدایکبوونی مێرد",
                "strDateOfBirthOfWife": "بەرواری لەدایکبوونی ژن",
                "strDateOfInsuranceExpiry": "بەرواری بەسەرچوونی بیمە",
                "strDateSecondRenewal": "بەرواری نوێکردنەوەی دووەم",
                "strDateofBirth": "بەرواری لەدایکبوون",
                "strDateofBirthCheckDigit": "ژمارەی پشکنینی بەرواری لەدایکبوون",
                "strDateofBirthChecksum": "چێکسامی بەرواری لەدایکبوون",
                "strDateofCreation": "بەرواری دروستکردن",
                "strDateofExpiry": "بەرواری بەسەرچوون",
                "strDateofExpiryCheckDigit": "ژمارەی پشکنینی بەرواری بەسەرچوون",
                "strDateofExpiryChecksum": "چێکسامی بەرواری بەسەرچوون",
                "strDateofFlight": "بەرواری فڕین",
                "strDateofIssue": "بەرواری دابەشکردن",
                "strDateofIssueBoardingPass": "بەرواری دابەشکردنی پاسە بۆردینگ",
                "strDateofIssueCheckDigit": "ژمارەی پشکنینی بەرواری دابەشکردن",
                "strDateofIssueChecksum": "چێکسامی بەرواری دابەشکردن",
                "strDateofPersonalization": "بەرواری تاکەکەرە بەرکراوە",
                "strDateofRegistration": "بەرواری تۆمارکردن",
                "strDay": "ڕۆژ",
            "strDepartment": "بەش",
              "strDeptNumber": "ژمارەی بەش",
              "strDestination": "شوێن",
              "strDiscretionaryData": "زانیاری خەڵکی",
              "strDoDNumber": "ژمارەی DoD",
              "strDocumentClassCode": "کۆدی پۆلی بەڵگە",
              "strDocumentClassName": "پۆلی بەڵگە",
              "strDocumentDiscriminator": "جیاکرنەوەی بەڵگە",
              "strDocumentNumber": "ژمارەی بەڵگە",
              "strDocumentNumberCheckDigit": "ژمارەی پشتگری بۆ ژمارەی بەڵگە",
              "strDocumentNumberChecksum": "ژمارەی پشکنین بۆ ژمارەی بەڵگە",
              "strDocumentSeries": "سلسەی بەڵگە",
              "strDocumentTooSmall": "بەڵگەکە بچووکە، دەبێت لە ناو چوارچێوەکەدا بین",
              "strDonor": "دەربەخشی",
              "strDossierNumber": "ژمارەی دوسیە",
              "strDurationofStay": "ماوەی مانەوە",
              "strECEnvironmentalType": "جۆری جەستەی شەڕەکراو",
              "strEDLDG1": "بەشی زانیاری ئەلیمانتێکانی نووسراو (DG1)",
              "strEDLDG10": "ناشیاوە (DG10)",
              "strEDLDG11": "زانیاری ناوەندی خەڵک (DG11)",
              "strEDLDG12": "ئاگاداری بەرەنگاری (DG12)",
              "strEDLDG13": "زانیاری درێژکراوەی ژمارەی پشکنین (DG13)",
              "strEDLDG14": "زانیاری EAC (DG14)",
              "strEDLDG2": "زانیاری پارەدانەوەی کارد (DG2)",
              "strEDLDG3": "زانیاری دەسەڵاتی ڕووناکی (DG3)",
              "strEDLDG4": "وێنەی دەق (DG4)",
              "strEDLDG5": "وێنە/نیشانەی ڕێگەی نووسراو (DG5)",
              "strEDLDG6": "زانیاری ئێلەکترۆنیکی - ڕووپێکراوەی چاوی (DG6)",
              "strEDLDG7": "زانیاری ئێلەکترۆنیکی - ئانگوشتی ڕووپێکراوەکان (DG7)",
              "strEDLDG8": "زانیاری ئێلەکترۆنیکی - دانانی (DG8)",
              "strEDLDG9": "زانیاری ئێلەکترۆنیکی - هەر ئێک (DG9)",
              "strEFCOM": "EF.COM",
              "strEFCVCA": "EF.CVCA",
              "strEFCardAccess": "EF.CardAccess",
              "strEFCardSecurity": "EF.CardSecurity",
              "strEFChipSecurity": "EF.ChipSecurity",
              "strEFSOD": "EF.SOD",
              "strEQVCode": "کۆدی EQV",
              "strElectronicTicketIndicator": "ئاگاداری نووسینەوەی ئێلېکترۆنی",
              "strElement": "ئەڵێمانت",
              "strEndorsementExpirationDate": "بەرواری بەسەردانی پارەدانەوە",
              "strEngineModel": "مووەدێلی ماشی",
              "strEngineNumber": "ژمارەی ماشی",
              "strEnginePower": "هێزەی ماشی",
              "strEngineVolume": "پانی ماشی",
              "strError": "هەڵە",
              "strExamDate": "بەرواری تاقیکردنەوە",
              "strExeptInTanks": "چەندەکان تەنها لە تانکان",
              "strEye": "چاو",
              "strEyesColor": "ڕەنگی چاوی",
              "strFaculty": "باڵەخ",
              "strFalseLuminescence": "نورەڕاییی بەو چەندەکە زۆر",
              "strFamilyName": "ناوی خێزان/پیشین",
              "strFamilyNameTruncation": "ناوی خێزان/پیشین کراوە",
              "strFastTrack": "خزمەتگوزاری فاستیرا",
              "strFatherCountryOfBirth": "وڵاتی بەزانی باوەکان",
              "strFatherDateOfBirth": "بەرواری بەزانی باوەکان",
              "strFatherGivenName": "ناوی داوانی باوەکان",
              "strFatherPersonalNumber": "ژمارەی تایبەتی باوەکان",
              "strFatherPlaceOfBirth": "شوێنی بەزانی باوەکان",
              "strFatherSurname": "ناوی پاشەکەوتی باوەکان",
              "strFathersName": "ناوی باوەکان",
              "strFathersNameRUS": "ناوی باوەکان (نەتەوەیی)",
              "strFederalElections": "هەڵبژاردنە فیدرالیەکان",
              "strFee": "خەرجی",
              "strFieldFromMRZ": "بەشی لە MRZ",
              "strFieldTypeDocumentImage": "وێنەی بەڵگە",
              "strFillElement": "ئەڵێمانتی پڕکردنەوە",
              "strFinalCheckDigit": "ژمارەی پشکنینی کۆتایی",
              "strFinalChecksum": "ژمارەی پشکنینی کۆتایی",
              "strFingerprint": "ئانگوشتی پێچ",
              "strFirstIssueDate": "بەرواری بەرەوەبردنەوەی یەکەم",
              "strFirstNameTruncation": "یەکەم ناوی کراوە",
              "strFlightNumber": "ژمارەی فڕۆکە",
              "strFolioNumber": "ژمارەی فۆلیۆ",
              "strFormOfEducation": "شێوەی خوێندندەن",
              "strFreeBaggageAllowance": "ڕێگەپێدانەوەی بارە خۆدانەوە",
              "strFrequentFlyerAirlineDesignator": "دەیزانی فڕۆکەی خوێندانە",
              "strFrequentFlyerNumber": "ژمارەی فڕۆکەی خوێندانە",
              "strFromAirportCode": "کۆدی فرۆکەخانەی دەرچوو",
              "strFuelType": "جۆری مادەی سوخت",
              "strGNIBNumber": "ژمارەی GNIB",
              "strGhostPortrait": "وێنەی پیاوەرە",
              "strGivenNames": "ناوی داوانی",
              "strGivenNamesRUS": "ناوی داوانی (نەتەوەیی)",
              "strGlaresOnDocument": "ڕووناوی لە بەڵگەکەوە بەلایە",
              "strGrandfatherName": "ناوی باپیر",
              "strHairColor": "ڕەنگی موو",
              "strHealthNumber": "ژمارەی ناشتەوەی تەندروستی",
              "strHeight": "بەرزی",
              "strHoldDocumentStraight": "بەڵگەکە بەرەفراوە بکە",
              "strHoloSimple": "بەردەستەی هۆلۆگرام",
              "strHoloVerifyDinamic": "پشکنینی هۆلۆگرامەی دینامیک",
              "strHoloVerifyMultiStatic": "پشکنینی هۆلۆگرامەی چەندەیی ثابت",
              "strHoloVerifyStatic": "پشکنینی هۆلۆگرامەی ثابت",
              "strHolograms": "هۆلۆگرامەکان",
              "strIPI": "زانیاری کەمی تایبەتی نەشیاوە (IPI)",
              "strIRB900": "ماوی IR B900",
              "strIRVis": "ماوی IR ڕووناکی",
              "strISOIssuerIDNumber": "ژمارەی ناسنامەی ISO",
              "strIdentifier": "ناسنامە",
              "strIdentityCardNumber": "ژمارەی ناسنامەی پەیوەندیدار",
              "strIdentityCardNumberCheckDigit": "ژمارەی پشکنینی ژمارەی ناسنامەی پەیوەندیدار",
              "strIdentityCardNumberChecksum": "ژمارەی پشکنینی ژمارەی ناسنامەی پەیوەندیدار",
              "strImagePattern": "پەتەری وێنە",
              "strInTanks": "لە تانکان",
              "strInventoryNumber": "ژمارەی ئیمپۆرت",
              "strInvitationNumber": "ژمارەی بانگەوازی",
              "strInvitationNumberCheckDigit": "ژمارەی پشکنینی ژمارەی بانگەوازی",
              "strInvitationNumberChecksum": "ژمارەی پشکنینی ژمارەی بانگەوازی",
              "strInvitedBy": "بانگەوازی کراوە لە",
              "strIssueTimestamp": "کاتی بەرەوەبردنەوە",
              "strIssuingStateCode": "کۆدی وڵاتی بەرەوەبردنەوە",
              "strIssuingStateName": "ناوی وڵاتی بەرەوەبردنەوە",
              "strJurisdictionEndorsementCode": "کۆدی بەسەرکردنەوەی دەسەڵات",
              "strJurisdictionRestrictionCode": "کۆدی سنوردارکردنەوەی دەسەڵات",
              "strJurisdictionVehicleClass": "پۆلی دەسەڵاتی مووتەبیل",
              "strKeepDeviceStill": "ئامرازەکە بەرەبێستە",
              "strLicenseNumber": "ژمارەی مۆڵەت",
              "strLimitedDurationDocumentIndicator": "نیشانەی ماوەی سنووری بەڵگە",
              "strLine1CheckDigit": "ژمارەی پشکنینی هێڵ ١",
              "strLine1Checksum": "ژمارەی پشکنینی هێڵ ١",
              "strLine1OptionalData": "زانیاری هەڵبژارەیی لە هێڵ ١",
              "strLine2CheckDigit": "ژمارەی پشکنینی هێڵ ٢",
              "strLine2Checksum": "ژمارەی پشکنینی هێڵ ٢",
              "strLine2OptionalData": "زانیاری هەڵبژارەیی لە هێڵ ٢",
              "strLine3CheckDigit": "ژمارەی پشکنینی هێڵ ٣",
              "strLine3Checksum": "ژمارەی پشکنینی هێڵ ٣",
              "strLine3OptionalData": "زانیاری هەڵبژارەیی لە هێڵ ٣",
              "strLookingDocument": "ئەدۆزرێت بۆ بەڵگە...",
              "strMCNoviceDate": "بەرواری بەسەرکردنەوەی خاوەنی مووتۆسکلێتی نووسینەوە",
              "strMRZ": "MRZ",
            "strMRZLinesICAORFID": "ڕێچکەکانەی MRZ لە ICAO RFID",
                "strMRZString1": "تۆڕی MRZ ی یەکە",
                "strMRZString2": "تۆڕی MRZ ی دووە",
                "strMRZString3": "تۆڕی MRZ ی سێی",
                "strMRZStrings": "تۆڕەکانی MRZ",
                "strMRZStringsWithCorrectCheckSums": "تۆڕەکانی MRZ بە چەکسانە تایبەتیەکان",
                "strMRZType": "جۆری MRZ",
            "strMailingAddressCity": "ناونیشانی نیشتەجێ - شار",
               "strMailingAddressJurisdictionCode": "ناونیشانی نیشتەجێ - کۆدی ڕووکاری",
               "strMailingAddressPostalCode": "ناونیشانی نیشتەجێ - کۆدی پۆستە",
               "strMailingAddressStreet": "ناونیشانی نیشتەجێ - کوچە",
               "strMake": "ساز",
               "strMaritalStatus": "وضعیەتی زواجی",
               "strMaxMassofTrailerBraked": "بەرزترین کێشەی تەرەکی (بە لەنگر)",
               "strMaxMassofTrailerUnbraked": "بەرزترین کێشەی تەرەکی (بێ لەنگر)",
               "strMaxSpeed": "بەرزترین خێرا",
               "strMedicalIndicatorCodes": "پەیامە پزیشکیەکان/کۆدەکان",
               "strMiddleName": "ناوی ناوەڕاست",
               "strMiddleNameTruncation": "کورتکردنەوەی ناوی ناوەڕاست",
               "strMifareData": "داتاى MIFARE",
               "strMifareValidity": "بەرزبوونی MIFARE",
               "strMilitaryBookNumber": "ژمارەی ناسنامەی ئۆفیسری",
               "strModel": "مو델",
               "strMonth": "مانگ",
               "strMortgageBy": "ڕێگەی ئیش",
               "strMotherCountryOfBirth": "کشوری لەدایک بوونی دایکم",
               "strMotherDateOfBirth": "بەرواری لەدایک بوونی دایکم",
               "strMotherGivenName": "ناوی پێشینی دایکم",
               "strMotherPersonalNumber": "ژمارەی تایبەتی دایکم",
               "strMotherPlaceOfBirth": "شوێنی لەدایک بوونی دایکم",
               "strMotherSurname": "ناوی خانوادەی دایکم",
               "strMothersName": "ناوی دایکم",
               "strNamePrefix": "پیشەنی ناو",
               "strNameSuffix": "پاشەکەوتی ناو",
               "strNationality": "ناساندنی نیشتیمانی",
               "strNationalityCode": "کۆدی نیشتیمانی",
               "strNonResidentIndicator": "نیشانی نەسەردانی",
               "strNone": "هیچ",
               "strNotDefined": "نەوەڵامی",
               "strNumberOfCardIssuance": "ژمارەی فەرمی پەیوەندیدا",
               "strNumberOfCardIssuanceCheckDigit": "چەک دیژیت بۆ ژمارەی فەرمی پەیوەندیدا",
               "strNumberOfCardIssuanceChecksum": "چیکسەم بۆ ژمارەی فەرمی پەیوەندیدا",
               "strNumberOfCylinders": "ژمارەی سیلندرەکان",
               "strNumberofAxels": "ژمارەی ئاکسەلەکان",
               "strNumberofDuplicates": "ژمارەی کۆپیەکان",
               "strNumberofEntries": "ژمارەی ناوچەکان",
               "strNumberofSeats": "ژمارەی کۆرسیەکان",
               "strNumberofStandingPlaces": "ژمارەی شوێنە سەوزەکان",
            "strOCRNumber": "ژمارەی OCR",
             "strOK": "باشە",
             "strObservations": "پێداویستیەکان",
             "strOldDateOfIssue": "بەرواری کەهنەی ئیشکراو",
             "strOldDocumentNumber": "ژمارەی بەرگی کەهنە",
             "strOldPlaceOfIssue": "شوێنی کەهنەی ئیشکراو",
             "strOptionalData": "داتاى پەسەندە",
             "strOptionalDataCheckDigit": "چەک دیژیت بۆ داتاى پەسەندە",
             "strOptionalDataChecksum": "چیکسەم بۆ داتاى پەسەندە",
             "strOptionalDetails": "تەپەڕەکانى پەسەندە",
             "strOrganization": "رەشنوسی",
             "strOther": "ئیشتی",
             "strOtherName": "ناوی ئیشتی",
             "strOtherPersonName": "ناوی کەسە ئیشتیەکان",
             "strOtherValidID": "ناسنامەی تایبەتی تری تایبەتی",
             "strOwner": "خاوەن",
             "strPDF417Codec": "کۆدێکی PDF417",
             "strPNRCode": "کۆدی PNR",
             "strParrentsGivenNames": "ناوە پێشینی مەدەوەکان",
             "strPassportNumber": "ژمارەی پاسپۆرت",
             "strPassportNumberCheckDigit": "چەک دیژیت بۆ ژمارەی پاسپۆرت",
             "strPassportNumberChecksum": "چیکسەم بۆ ژمارەی پاسپۆرت",
             "strPatronHeaderVersion": "کۆدەی سەرەکی پەیوەندیدا",
             "strPatternDifferentLinesThickness": "پەیمانەی تاقیەکانى هەڵسەنگاندنەوە",
             "strPatternIRInvisible": "پەیامە نادیدارەکان لە IR",
             "strPatternNotInterrupted": "بێ بریک",
             "strPatternNotShifted": "ئەندامەکانى پەیامە بەرز نەکردووە",
             "strPatternSameColors": "هەمان رنگەکانى پەیامە",
             "strPayGrade": "پێشەوەی پەی",
             "strPayloadCapacity": "توانای بەرزە",
             "strPermissibleAxleLoad": "بەرزەی ئاکسەلەکان",
             "strPermitDLClass": "پەسەندەی بەرز",
             "strPermitDateofExpiry": "بەرواری کۆتایی پەسەندە",
             "strPermitDateofIssue": "بەرواری ئیشکراوی پەسەندە",
             "strPermitEndorsed": "کۆدی پەسەندەی تایبەتی",
             "strPermitIdentifier": "ناسنامەی پەسەندە",
             "strPermitRestrictionCode": "کۆدی پەسەندەی بەرز",
             "strPersonToNotifyAddress": "پەیوەندیدە: ناونیشان",
             "strPersonToNotifyDateofRecord": "پەیوەندیدە: بەرواری تۆمار",
             "strPersonToNotifyName": "پەیوەندیدە: ناو",
             "strPersonToNotifyPhone": "پەیوەندیدە: تلەفۆن",
             "strPersonalNumber": "ژمارەی تایبەتی",
             "strPersonalNumberCheckDigit": "چەک دیژیت بۆ ژمارەی تایبەتی",
             "strPersonalNumberChecksum": "چیکسەم بۆ ژمارەی تایبەتی",
             "strPersonalSummary": "خەلاصەی زانیاری تایبەتی",
             "strPersonalizationSN": "ژمارەی تایبەتی پەیوەندیدا",
             "strPhone": "تلەفۆن",
             "strPhotoArea": "ناوچەی وێنە",
             "strPhotoColor": "رەنگى وێنە",
             "strPhotoCorners": "کۆناکانى وێنە",
             "strPhotoElement": "ئەندامى وێنە",
             "strPhotoEmbedType": "جۆرەکی پەیوەندیدانی وێنە",
             "strPhotoProcessing": "پڕۆسەی وێنە...",
            "strPhotoShape": "شکلەی وێنە",
                "strPhotoSizeCheck": "پشکنینی قەبارە",
                "strPlaceDocumentInFrame": "بەرگەکە لە فریمەکەدا دانێ",
                "strPlaceOfBirthRUS": "شوێنی لەدایکبوون (ئەندامەی نیشتمانی)",
                "strPlaceOfBirthStateCode": "کۆدی پارەی شوێنی لەدایکبوون",
                "strPlaceOfExamination": "شوێنی تاقیکردنەوە",
                "strPlaceOfIssue": "شوێنی ئیشکراو",
                "strPlacePhoneOnDoc": "تەلەفۆن لە بەرگەکەدا دانێ تکایە",
                "strPlaceofBirth": "شوێنی لەدایکبوون",
                "strPlaceofBirthArea": "ناوچەی شوێنی لەدایکبوون",
                "strPlaceofRegistration": "شوێنی تۆمارکردن",
                "strPoliceDistrict": "ناوچەی پۆلیس",
                "strPortrait": "پەرتڕەیت",
                "strPortraitComparison": "پەیمانەی پەرتڕەیتەکان",
                "strPortraitOfChild": "پەرتڕەیتى منداڵ",
                "strPortraitVSCamera": "پەرتڕەیت لە پەرتڕەیتە کەمێرەکان",
                "strPortraitVSGhost": "پەرتڕەیت لە وێنەی تێر",
                "strPortraitVSRFID": "پەرتڕەیت لە وێنەی RFID",
                "strPowerWeightRatio": "نسبەی هەواڵ بەرز",
                "strPrecinct": "ناوچە",
                "strPrepareCamera": "هەموارکردنی کەمێرە...",
                "strPresentNextPage": "تکایە پەیجی پاشکەوتەکان پێشکەش بکە",
                "strPreviousType": "جۆر/ژمارەی بەرگەی پێشوو",
                "strProcessingDocument": "پڕۆسەی بەرگە...",
                "strProfession": "پیشە",
                "strProfessionalIdNumber": "ژمارەی ناسنامەی پەیوەندیدا",
                "strProofOfCitizenship": "پەسەندەی نیشتمانی",
                "strPseudoCode": "کۆدی پەسەندە",
                "strPurposeOfEntry": "مقەصەدی ناچوون",
                "strRFIDVSCamera": "وێنەی RFID لە وێنەی کەمێرە",
                "strRaceEthnicity": "ژنان/ناوچە",
                "strRank": "پەیوەندیدانی بەرز",
                "strReadingRFID": "خوێندنی داتای RFID",
                "strReadingRFIDDGiOS": "خوێندنی داتای RFID %@",
                "strRecognizedDocumentType": "جۆری بەرگە",
                "strReferenceNumber": "ژمارەی تایبەتی",
                "strReferenceNumberCheckDigit": "چەک دیژیت بۆ ژمارەی تایبەتی",
                "strReferenceNumberChecksum": "چیکسەم بۆ ژمارەی تایبەتی",
                "strRegCertBodyNumber": "ژمارەی بەرگە",
                "strRegCertBodyType": "جۆری بەرگە",
                "strRegCertCarColor": "رەنگى ئۆتۆمبیل",
                "strRegCertCarMark": "مارکەى ئۆتۆمبیل",
                "strRegCertCarModel": "جۆری ئۆتۆمبیل",
                "strRegCertCarType": "جۆری ئۆتۆمبیل",
            "strRegCertMaxWeight": "زیاترین بارەی پەسەندە",
               "strRegCertRegNumber": "ژمارەی تۆمارکردن",
               "strRegCertRegNumberCheckDigit": "چەک دیژیت بۆ ژمارەی تۆمارکردن",
               "strRegCertRegNumberChecksum": "چیکسەم بۆ ژمارەی تۆمارکردن",
               "strRegCertVIN": "ژمارەی ناسنامەی ئۆتۆمبیل",
               "strRegCertVINCheckDigit": "چەک دیژیت بۆ VIN",
               "strRegCertVINChecksum": "چیکسەم بۆ VIN",
               "strRegCertVehicleITSCode": "کۆدی ITS بۆ ئۆتۆمبیل",
               "strRegCertWeight": "قەبارەی بەرز",
               "strRelationship": "پەیوەندیدان",
               "strReligion": "ئەیند",
               "strRemainderTerm": "مانگەکان بۆ کۆتایی",
               "strResidentFrom": "نیشتەجێ بوو لە",
               "strResidentUntil": "نیشتەجێ بوو تا",
               "strRetirementNumber": "ژمارەی پارەدان",
               "strRevisionDate": "بەروارەی گۆڕین",
               "strRoomNumber": "ژمارەی بەرگە",
               "strSBHIntegrityOptions": "ئامەڕەکان بۆ تایبەتمەندی SBH",
               "strSBHSecurityOptions": "ئامەڕەکان بۆ پاراستن SBH",
               "strSeatNumber": "ژمارەی کەرسی",
               "strSecondSurname": "ناوی دووەم",
               "strSection": "بەش",
               "strSecurityText": "متنە پاراستن",
               "strSelecteeIndicator": "شاخصی هەڵبژاردن",
               "strSequenceNumber": "ژمارەی پەیوەندیدان",
               "strSerialNumber": "ژمارەی تایبەتی",
               "strSettings": "پەیامەکان",
               "strSex": "جنس",
               "strSignature": "تۆمار",
               "strSkinColor": "رەنگی پەستە",
               "strSocialSecurityNumber": "ژمارەی تێکەڵاتی کۆمەڵایەتی",
               "strSpCode": "کۆدی تایبەتی",
               "strSpecialNotes": "تێبینی تایبەتی",
               "strSponsor": "پشتیوان",
               "strSponsorSSN": "ژمارەی تێکەڵاتی پشتیوان",
               "strSponsorService": "خزمەتی پشتیوان",
               "strSponsorStatus": "پاراستنی پشتیوان",
               "strStamp": "تەوەڵە",
               "strStampNumber": "ژمارەی تەوەڵە",
               "strStatusDateofExpiry": "بەرواری کۆتایی ئیشکراو",
               "strSurname": "ناو",
               "strSurnameAndGivenNames": "ناو و ناوەکان",
               "strSurnameAndGivenNamesCheckDigit": "چەک دیژیت بۆ ناو و ناوەکان",
               "strSurnameAndGivenNamesChecksum": "چیکسەم بۆ ناو و ناوەکان",
               "strSurnameAndGivenNamesRUS": "ناو و ناوەکان (ئەندامەی نیشتمانی)",
               "strSurnameAtBirth": "ناوی لەدایکبوون",
               "strSurnameOfHusbandAfterRegistration": "ناوی شوێنەوەی پەسەندکراو",
               "strSurnameOfWifeAfterRegistration": "ناوی ژنەوەی پەسەندکراو",
            "strSurnameofSpose": "ناوی هاوڕێ",
               "strTax": "بەرهەمی پارە",
               "strTaxNumber": "ژمارەی بەرهەمی پارە",
               "strTelexCode": "کۆدی تێلەگراف",
               "strTerritorialValidity": "دەستپێکردنی مەناچی نیشتیمانی",
               "strTicketNumber": "ژمارەی تیکەت",
               "strTitle": "پۆزەیەتی",
               "strToAirportCode": "کۆدی فڕۆکەخانەی هەبوو",
               "strTorchUnavailable": "پەیدا نەکراو",
               "strTrackingNumber": "ژمارەی هەڵگرتن",
               "strTrailerHitch": "پەیوەندیدانی تریلەر",
               "strTransactionNumber": "ژمارەی بەرەسەکە",
               "strTransmissionType": "جۆری نیشانە",
               "strTypeApprovalNumber": "ژمارەی تایبەتی پەسەندکردن",
               "strURL": "URL",
               "strUSCIS": "USCIS",
               "strUV": "UV",
               "strUVFibers": "فایبەرە تایبەتی UV",
               "strUVLuminescence": "پیشاندانی کاغەذەی بە شەف",
               "strUnableCaptureMedia": "پێشاندانی کەمەرە ناکرێت",
               "strUniqueCustomerIdentifier": "ناسنامەی تایبەتی کڕیار",
               "strVRCDataObjectEntry": "زانیاری ئۆتۆمبیل لە کۆمەڵگەی زانیاری DG1",
               "strValidityPeriod": "کاتەکانی دەستپێکردن",
               "strVehicleCategory": "کۆمەڵەی ئۆتۆمبیل",
               "strVeteran": "پێشەنگ",
               "strVisaClass": "کۆمەڵەی ڤیزا",
               "strVisaID": "ID-ی ڤیزا",
               "strVisaIDCheckDigit": "چەک دیژیت بۆ ID-ی ڤیزا",
               "strVisaIDChecksum": "چیکسەم بۆ ID-ی ڤیزا",
               "strVisaIDRUS": "ID-ی ڤیزا (ناشتیمانی)",
               "strVisaNumber": "ژمارەی ڤیزا",
               "strVisaNumberCheckDigit": "چەک دیژیت بۆ ژمارەی ڤیزا",
               "strVisaNumberChecksum": "چیکسەم بۆ ژمارەی ڤیزا",
               "strVisaSubClass": "کۆمەڵەی فرعی ڤیزا",
               "strVisaType": "جۆری ڤیزا",
               "strVisaValidFrom": "دەستپێکردنی ڤیزا لە",
               "strVisaValidUntil": "پەسەندکردنی ڤیزا تا",
               "strVisaValidUntilCheckDigit": "چەک دیژیت بۆ بەرواری کۆتایی ڤیزا",
               "strVisaValidUntilChecksum": "چیکسەم بۆ بەرواری کۆتایی ڤیزا",
               "strVisibleLight": "ڕوونی دیاری",
               "strVoter": "دەنگدان",
               "strVoterKey": "کلیلەی دەنگدان",
               "strVoucherNumber": "ژمارەی ڤاچەر",
               "strWeight": "قەبارە",
               "strWeightPound": "قەبارە (پەوند)",
               "strYear": "ساڵ",
               "strYearsSinceIssue": "ساڵەکان لە کاتێکدا تۆمارکراوە",
               "streIDPlaceOfBirthCity": "شوێنی لەدایکبوون: شاری",
               "streIDPlaceOfBirthCountry": "شوێنی لەدایکبوون: وڵات",
               "streIDPlaceOfBirthState": "شوێنی لەدایکبوون: پارێزگا",
               "streIDPlaceOfBirthStreet": "شوێنی لەدایکبوون: خیابان",
               "streIDPlaceOfBirthZipcode": "شوێنی لەدایکبوون: کۆدی پۆستە",
               "streIDResidencePermit1": "پەسەندنامەی نیشتیمانی 1",
               "streIDResidencePermit2": "پەسەندنامەی نیشتیمانی 2",
               "strfppLeftIndexFinger": "ئەصابعەی تۆشە چەپ",
               "strfppLeftLittleFinger": "ئەصابعەی بچووکە چەپ",
               "strfppLeftMiddleFinger": "ئەصابعەی نێوانی چەپ",
               "strfppLeftRingFinger": "ئەصابعەی پەروپەڕە چەپ",
               "strfppLeftThumb": "پەستە چەپ",
               "strfppRightIndexFinger": "ئەصابعەی تۆشە راست",
               "strfppRightLittleFinger": "ئەصابعەی بچووکە راست",
               "strfppRightMiddleFinger": "ئەصابعەی نێوانی راست",
               "strfppRightRingFinger": "ئەصابعەی پەروپەڕە راست",
               "strfppRightThumb": "پەستە راست"
        ]
    }
}
