//
//  File.swift
//
//
//  Created by MOBILE on 20/05/24.
//

import Foundation

class GermanDataValues {
    func getDictionary() -> [String: String] {
        return [
            "RFID_Error_AlreadyDone" : "RFID: Anforderung bereits ausgeführt",
            "RFID_Error_Busy" : "RFID: RFID ist beschäftigt",
            "RFID_Error_Failed" : "RFID: Fehler",
            "RFID_Error_FileIOError" : "RFID-Datei: E/A-Fehler",
            "RFID_Error_InvalidDirectory" : "RFID: Ungültiges Verzeichnis",
            "RFID_Error_InvalidParameter" : "RFID: Ungültiger Parameter im ExecuteCommand() Aufruf gefunden",
            "RFID_Error_NoChipDetected" : "RFID: Kein Chip erkannt",
            "RFID_Error_NotAvailable" : "RFID: Nicht verfügbar",
            "RFID_Error_NotEnoughMemory" : "RFID: Nicht genügend Speicher",
            "RFID_Error_NotInitialized" : "RFID: Gerät nicht initialisiert",
            "RFID_Error_NotPerformed" : "RFID: Nicht durchgeführt",
            "RFID_Error_OldFirmware" : "RFID: Firmware muss auf eine neuere Version aktualisiert werden",
            "RFID_Error_PCSC_CantConnectCard" : "PCSC: Karte kann nicht verbunden werden",
            "RFID_Error_PCSC_CardIsBusy" : "PCSC: Karte ist beschäftigt",
            "RFID_Error_PCSC_CardIsNotConnected" : "PCSC: Karte ist nicht verbunden",
            "RFID_Error_PCSC_ExtLe_Failed" : "PCSC: ExtLe fehlgeschlagen",
            "RFID_Error_PCSC_Failed" : "PCSC: Fehler",
            "RFID_Error_PCSC_FailedSCard" : "PCSC: Fehler bei der Smartcard",
            "RFID_Error_PCSC_OperationCancelled" : "PCSC: Vorgang abgebrochen",
            "RFID_Error_PCSC_ReaderNotAvailable" : "PCSC: Leser nicht verfügbar",
            "RFID_Error_Session_AccessControl_AA_Failed" : "RFID: AA fehlgeschlagen",
            "RFID_Error_Session_AccessControl_CA_Failed" : "RFID: CA fehlgeschlagen",
            "RFID_Error_Session_AccessControl_IncorrectOptionCA" : "RFID: Falsche Option CA",
            "RFID_Error_Session_AccessControl_RI_Failed" : "RFID: RI fehlgeschlagen",
            "RFID_Error_Session_AccessControl_RequiresCA" : "RFID: CA erforderlich",
            "RFID_Error_Session_AccessControl_RequiresCAKeys" : "RFID: CA-Schlüssel erforderlich",
            "RFID_Error_Session_AccessControl_RequiresPACE" : "RFID: PACE erforderlich",
            "RFID_Error_Session_AccessControl_RequiresSM" : "RFID: SM erforderlich",
            "RFID_Error_Session_AccessControl_RequiresTA" : "RFID: TA erforderlich",
            "RFID_Error_Session_AccessControl_TA_Failed" : "RFID: TA fehlgeschlagen",
            "RFID_Error_Session_AccessControl_UnknownType" : "RFID: Zugangskontrolle Unbekannter Typ",
            "RFID_Error_Session_AccessKey_IncorrectData" : "RFID: Zugriffsschlüssel Falsche Daten",
            "RFID_Error_Session_AccessKey_IncorrectSMType" : "RFID: Zugriffsschlüssel Falscher SM-Typ",
            "RFID_Error_Session_AccessKey_NotSet" : "RFID: Zugriffsschlüssel Nicht gesetzt",
            "RFID_Error_Session_AccessKey_Restricted" : "RFID: Zugriffsschlüssel Beschränkt",
            "RFID_Error_Session_AccessKey_UnknownType" : "RFID: Zugriffsschlüssel Unbekannter Typ",
            "RFID_Error_Session_AccessKey_UnsupportedSMType" : "RFID: Zugriffsschlüssel Nicht unterstützter SM-Typ",
            "RFID_Error_Session_File_AccessDenied" : "RFID-Datei: Zugriff verweigert",
            "RFID_Error_Session_File_CantReadData" : "RFID-Datei: Daten können nicht gelesen werden",
            "RFID_Error_Session_File_CantUseData" : "RFID-Datei: Daten können nicht verwendet werden",
            "RFID_Error_Session_File_Contents_UnexpectedData" : "RFID-Datei: Unerwartete Daten im Inhalt",
            "RFID_Error_Session_File_IncorrectData" : "RFID-Datei: Falsche Daten",
            "RFID_Error_Session_File_NotEnoughData" : "RFID-Datei: Nicht genügend Daten",
            "RFID_Error_Session_File_UnexpectedData" : "RFID-Datei: Unerwartete Daten",
            "RFID_Error_Session_File_WrongTag" : "RFID-Datei: Falscher Tag",
            "RFID_Error_Session_IncorrectData" : "RFID: Falsche Daten",
            "RFID_Error_Session_InvalidAuxData_CommunityID" : "RFID: Ungültige Hilfsdaten Community ID",
            "RFID_Error_Session_InvalidAuxData_DateOfBirth" : "RFID: Ungültige Hilfsdaten Geburtsdatum",
            "RFID_Error_Session_InvalidAuxData_DateOfExpiry" : "RFID: Ungültige Hilfsdaten Ablaufdatum",
            "RFID_Error_Session_IsClosed" : "RFID: Sitzung ist geschlossen",
            "RFID_Error_Session_PA_HashCheckFailed" : "RFID: Hash-Prüfung fehlgeschlagen",
            "RFID_Error_Session_PA_SignatureCheckFailed" : "RFID: SO-Signaturprüfung fehlgeschlagen",
            "RFID_Error_Session_ProcedureType_NotSet" : "RFID: Verfahrensart nicht festgelegt",
            "RFID_Error_Session_ProcedureType_Unknown" : "RFID: Verfahrensart unbekannt",
            "RFID_Error_Session_ProcedureType_Unsupported" : "RFID: Verfahrensart nicht unterstützt",
            "RFID_Error_Session_PwdManagement_NotAuthorized" : "RFID: Passwortverwaltung nicht autorisiert",
            "RFID_Error_Session_TerminalType_BadCertificate" : "RFID: Terminaltyp schlechtes Zertifikat",
            "RFID_Error_Session_TerminalType_NotSet" : "RFID: Terminaltyp nicht festgelegt",
            "RFID_Error_Session_TerminalType_Unknown" : "RFID: Terminaltyp unbekannt",
            "RFID_Error_Session_Terminal_UnsupportedOperation" : "RFID: Terminal nicht unterstützte Operation",
            "RFID_Error_Session_eSign_PIN_NotSet" : "RFID: eSign-PIN nicht festgelegt",
            "RFID_Error_Session_eSign_PIN_NotVerified" : "RFID: eSign-PIN nicht verifiziert",
            "RFID_Error_Session_eSign_RequiresAppSelection" : "RFID: eSign erfordert App-Auswahl",
            "RFID_Error_UnknownCommand" : "RFID: Unbekannter Befehl",
            "RFID_LAYER6_APP_SELECTION_FAILURE" : "LAYER6: ISO7816_A_03 \"Anwendungsauswahl fehlgeschlagen\"",
            "RFID_LAYER6_EXT_AUTH_FAILURE" : "LAYER6: APDU_INS_EXTERNAL_AUTHENTICATE (Externe Authentifizierung) fehlgeschlagen",
            "RFID_LAYER6_FILE_EOF1" : "LAYER6: Lesen über das EOF hinaus / Unerwartetes EOF",
            "RFID_LAYER6_FILE_EOF2" : "LAYER6: Lesen über das EOF hinaus / Unerwartetes EOF",
            "RFID_LAYER6_FILE_NOT_FOUND" : "LAYER6: Dateiauswahl fehlgeschlagen / Datei nicht gefunden",
            "RFID_LAYER6_GENERAL_AUTH_FAILURE" : "LAYER6: Allgemeiner Authentifizierungsfehler",
            "RFID_LAYER6_GET_CHALLENGE_FAILURE" : "LAYER6: GET CHALLENGE fehlgeschlagen",
            "RFID_LAYER6_INCORRECT_PARAMS" : "LAYER6: Falsche Parameter",
            "RFID_LAYER6_INT_AUTH_FAILURE" : "LAYER6: APDU_INS_INTERNAL_AUTHENTICATE fehlgeschlagen",
            "RFID_LAYER6_MSE_SET_AT_FAILURE" : "LAYER6: MSE:Set AT fehlgeschlagen",
            "RFID_LAYER6_MSE_SET_DST_FAILURE" : "LAYER6: MSE:Set DST fehlgeschlagen",
            "RFID_LAYER6_MSE_SET_KAT_FAILURE" : "LAYER6: MSE:Set KAT fehlgeschlagen",
            "RFID_LAYER6_MUTUAL_AUTH_ENC_FAIL" : "LAYER6: ISO7816_B_02 \"Fehler bei der gegenseitigen Authentifizierung - Verschlüsselung fehlgeschlagen\"",
            "RFID_LAYER6_MUTUAL_AUTH_FAILURE" : "LAYER6: ISO7816_B_03 \"Fehler bei der gegenseitigen Authentifizierung\"",
            "RFID_LAYER6_MUTUAL_AUTH_MAC_FAIL" : "LAYER6: ISO7816_B_01 \"Fehler bei der gegenseitigen Authentifizierung - MAC fehlgeschlagen\"",
            "RFID_LAYER6_NON_TLV_RESPONSE_DATA" : "LAYER6: Keine TLV-Antwortdaten",
            "RFID_LAYER6_NO_REFERENCE_DATA" :
            "LAYER6: Keine Referenzdaten",
            "RFID_LAYER6_PSO_CERTIFICATE_FAILURE" :
            "LAYER6: PSO-Zertifikatfehler",
            "RFID_LAYER6_PWD_BLOCKED" :
            "LAYER6: Passwort gesperrt",
            "RFID_LAYER6_PWD_BLOCKED_2" :
            "LAYER6: Passwort gesperrt 2",
            "RFID_LAYER6_PWD_DEACTIVATED" :
            "LAYER6: Passwort deaktiviert",
            "RFID_LAYER6_PWD_DEACTIVATED_2" :
            "LAYER6: Passwort deaktiviert 2",
            "RFID_LAYER6_PWD_FAILED" :
            "LAYER6: Passwort fehlgeschlagen",
            "RFID_LAYER6_PWD_SUSPENDED" :
            "LAYER6: Passwort ausgesetzt",
            "RFID_LAYER6_PWD_SUSPENDED_2" :
            "LAYER6: Passwort ausgesetzt 2",
            "RFID_LAYER6_SECURITY_MANAGER" :
            "LAYER6: Sichere Nachrichtenübertragung wurde nicht aktiviert",
            "RFID_LAYER6_SM_DO87_INCORRECT" :
            "LAYER6: SM-Fehler – falsches Kryptogramm",
            "RFID_LAYER6_SM_DO87_MISSING" :
            "LAYER6: SM-Fehler – Kryptogramm fehlt",
            "RFID_LAYER6_SM_DO8E_MISSING" :
            "LAYER6: SM-Fehler – MAC fehlt",
            "RFID_LAYER6_SM_DO99_MISSING" :
            "LAYER6: SM-Fehler – gesicherte Statusbytes fehlen",
            "RFID_LAYER6_SM_MAC_INCORRECT" :
            "LAYER6: SM-Fehler – falsches MAC",
            "RFID_LAYER6_WRONG_RND_ICC_LENGTH" : "LAYER6: Falsche Datenlänge (APDU_INS_GET_CHALLENGE)",
            "RSDT_RFID_READING_FINISHED" :
            "RFID-Datenlesung abgeschlossen",
            "TCT_Unknown" : "Unbekannt",
            "chd_BackgroundComparisonError" :
            "Helligkeit der beiden Seiten ist unterschiedlich",
            "chd_BadAreaInAxial" :
            "Fehler bei der retroreflektiven Schutzprüfung",
            "chd_BarcodeDataFormatError" :
            "Barcode-Formatfehler",
            "chd_BarcodeReadedWithErrors" :
            "Barcode wurde mit Fehlern gelesen",
            "chd_BarcodeSizeParamsError" :
            "Barcode-Parameterfehler",
            "chd_DocumentIsCancelling" :
            "Dokument wird storniert",
            "chd_ElementShouldBeColored" :
            "Element sollte farbig sein",
            "chd_ElementShouldBeGrayscale" :
            "Element sollte graustufig sein",
            "chd_ExceptionInModule" :
            "Abgefangene Ausnahme",
            "chd_FalseIPIParameters" : "Falsche IPI-Parameter",
            "chd_FalseLuminiscenceError" :
            "Vorhandensein von übermäßigen lumineszierenden Objekten",
            "chd_FalseLuminiscenceInBlank" :
            "Falsche Lumineszenz im UV",
            "chd_FalseLuminiscenceInMRZ" :
            "Übermäßige Lumineszenz in der MRZ",
            "chd_FibersNotFound" : "Fasern nicht gefunden",
            "chd_FieldPosCorrector_Highlight_IR" :
            "Übermäßige Helligkeit im IR",
            "chd_FieldsComparisonLogicError" :
            "Logikfehler beim Vergleich von Feldern",
            "chd_FixedPatternError" :
            "Nichtübereinstimmung des angegebenen Objekts",
            "chd_HologramElementAbsent" :
            "Hologramm fehlt",
            "chd_HologramElementPresent" :
            "Hologramm gefunden",
            "chd_Hologram_Side_Top_Images_Absent" :
            "Keine Seiten- oder Oberbilder",
            "chd_IncorrectBackgroundLight" :
            "Falsche Hintergrundhelligkeit",
            "chd_IncorrectTextColor" :
            "Falsche Textfarbe",
            "chd_InternalError" :
            "Fehler bei der internen Datenverarbeitung",
            "chd_InvalidChecksum" :
            "Ungültige Prüfsumme",
            "chd_InvalidFieldFormat" :
            "Das Format des Feldes stimmt nicht mit der Beschreibung des Dokuments überein",
            "chd_InvalidInputData" :
            "Ungültige Eingabedaten",
            "chd_InvisibleElementPresent" :
            "Objekt muss unsichtbar sein",
            "chd_LogicError" :
            "Logikfehler bei den Daten",
            "chd_LowContrastInIRLight" :
            "Falscher Objektkontrast im IR-Licht",
            "chd_MobileImages_LowLightConditions" :
            "Ungeeignete Lichtverhältnisse für die Bildaufnahme",
            "chd_MobileImages_WhileUVNoDifference" :
            "Geringer Unterschied zwischen Bildern bei unterschiedlichen Beleuchtungsschemata",
            "chd_NecessaryImageNotFound" :
            "Das für diese Prüfung erforderliche Bild fehlt",
            "chd_NotAllBarcodesRead" :
            "Dieses Dokument sollte mehr Barcodes enthalten",
            "chd_OVI_BadColor_Front" :
            "Farbabweichung des OVI-Objekts bei weißem Licht",
            "chd_OVI_BadColor_Percent" :
            "Geringsprozentsatzige Übereinstimmung der OVI-Elemente",
            "chd_OVI_BadColor_Side" :
            "Farbabweichung des OVI-Objekts bei axialem Licht",
            "chd_OVI_ColorInvariable" :
            "OVI-Farbe unveränderlich",
            "chd_OVI_IR_Invisible" :
            "OVI-Objekt-Kontrast-Abweichung",
            "chd_OVI_InsufficientArea" :
            "Unzureichende Fläche des OVI-Objekts",
            "chd_OVI_Wide_Color_Spread" :
            "Farbabweichung des OVI-Objekts",
            "chd_Pass" :
            "Keine Fehler",
            "chd_PhotoFalseLuminiscence" :
            "Falsche Lumineszenz im Fotobereich",
            "chd_PhotoPattern_DifferentColors" :
            "Farben des Musters auf dem Foto und dem Dokument sind unterschiedlich",
            "chd_PhotoPattern_DifferentLinesThickness" :
            "Unterschiedliche Dicke der Musternlinien",
            "chd_PhotoPattern_IR_Visible" :
            "Sicherheitsmuster im IR sichtbar",
            "chd_PhotoPattern_Interrupted" :
            "Das Muster zwischen dem Foto und dem Dokument hat eine Unterbrechung",
            "chd_PhotoPattern_InvalidColor" :
            "Ungültige Farbe des Sicherheitsmusters",
            "chd_PhotoPattern_Not_Intersect" :
            "Der Rand des Fotos überschneidet sich nicht mit dem Muster",
            "chd_PhotoPattern_PatternNotFound" :
            "Muster im Fotobereich nicht gefunden",
            "chd_PhotoPattern_Shifted" :
            "Das Muster auf dem Foto ist im Verhältnis zum Muster auf dem Dokument verschoben",
            "chd_PhotoPattern_Shifted_Vert" :
            "Musternlinien sind vertikal zueinander verschoben",
            "chd_PhotoSidesNotFound" :
            "Die erforderliche Fotokante wurde nicht gefunden",
            "chd_PhotoSize_Is_Wrong" :
            "Fotogröße ist falsch",
            "chd_Photo_Corners_Is_Wrong" :
            "Die Ecken des Fotos entsprechen nicht den Anforderungen",
            "chd_Photo_IsNot_Rectangle" :
            "Die Form des Fotos ist nicht rechteckig",
            "chd_PortraitComparison_NoLivePhoto" :
            "Es gibt kein Kamerabild",
            "chd_PortraitComparison_NoPortraitDetected" :
            "Kein Gesicht im Bild gefunden",
            "chd_PortraitComparison_NoServiceLicense" :
            "Keine Lizenz für den Dienst vorhanden",
            "chd_PortraitComparison_NoServiceReply" :
            "Der Dienst antwortet nicht",
            "chd_PortraitComparison_NotEnoughImages" :
            "Nicht genügend Bilder",
            "chd_PortraitComparison_PortraitsDiffer" :
            "Die Porträts stimmen nicht überein",
            "chd_PortraitComparison_ServiceError" :
            "Dienstfehler",
            "chd_SourcesComparisonError" :
            "Nichtübereinstimmung der Daten aus verschiedenen Quellen",
            "chd_SpecksInUV" :
            "Überbelichtung oder Blendeffekte im Bild unter UV-Licht",
            "chd_SyntaxError" :
            "Datensyntaxfehler",
            "chd_TextColorShouldBeBlue" :
            "Textfarbe sollte blau sein",
            "chd_TextColorShouldBeGreen" :
            "Textfarbe sollte grün sein",
            "chd_TextColorShouldBeRed" :
            "Textfarbe sollte rot sein",
            "chd_TextShouldBeBlack" :
            "Textfarbe sollte schwarz sein",
            "chd_TooLowResolution" :
            "Zu niedrige Auflösung, um Fasern zu erkennen",
            "chd_TooManyObjects" :
            "Zu viele Objekte",
            "chd_TooMuchShift" :
            "Der Verschiebungswert ist größer als der erlaubte Wert",
            "chd_TrueLuminiscenceError" :
            "Nichtübereinstimmung lumineszierender Objekte",
            "chd_UVDullPaperError" : "Fehler bei der Prüfung auf UV-mattes Papier",
            "chd_UVDullPaper_Blank" : "Prüfung auf UV-mattes Papier im Bereich des Dokuments",
            "chd_UVDullPaper_MRZ" : "Prüfung auf UV-mattes Papier im MRZ-Bereich",
            "chd_UVDullPaper_Photo" : "Prüfung auf UV-mattes Papier im Fotobereich",
            "chd_UncertainVerification" : "Zuverlässige Entscheidung nicht möglich",
            "chd_Unknown" : "Unbekannte Ablehnung",
            "chd_VisibleElementAbsent" : "Kein sichtbares Objekt unter IR",
            "strAGY" : "AGY",
            "strAKADateofBirth" : "Geburtsdatum (alias)",
            "strAKAGivenNames" : "Vorname (alias)",
            "strAKANamePrefix" : "Namenspräfix (alias)",
            "strAKANameSuffix" : "Namenssuffix (alias)",
            "strAKASocialSecurityNumber" : "Sozialversicherungsnummer (alias)",
            "strAKASurname" : "Nachname (alias)",
            "strAKASurnameAndGivenNames" : "Vollständiger Name (alias)",
            "strALTCode" : "ALT-Code",
            "strAcademicTitle" : "Akademischer Titel",
            "strAccessibilityCameraButton" : "Ein Bild aufnehmen und mit der Verarbeitung beginnen",
            "strAccessibilityCloseButton" : "Schließen",
            "strAccessibilityTorchButton" : "Taschenlampe",
            "strAccompaniedby" : "Begleitet von",
            "strAddress" : "Adresse",
            "strAddressArea" : "Bereich",
            "strAddressBuilding" : "Einheit",
            "strAddressCity" : "Stadt",
            "strAddressCountry" : "Land",
            "strAddressFlat" : "Wohnung",
            "strAddressHouse" : "Gebäude",
            "strAddressJurisdictionCode" : "Gerichtsbarkeitscode",
            "strAddressLocation" : "Ort",
            "strAddressMunicipality" : "Gemeinde",
            "strAddressPostalCode" : "Postleitzahl",
            "strAddressState" : "Bundesland",
            "strAddressStreet" : "Straße",
            "strAdministrativeNumber" : "Verwaltungsnummer",
            "strAge" : "Alter",
            "strAgeAtIssue" : "Alter bei Ausstellung",
            "strAirlineDesignatorofboardingpassissuer" : "Airline-Code des Bordkarten-Ausstellers",
            "strAirlineName" : "Airline-Name",
            "strAirlineNameFrequentFlyer" : "Vielfliegerprogramm der Airline",
            "strAirlineNumericCode" : "Airline-Nummercode",
            "strAirportFrom" : "Abflughafen",
            "strAirportTo" : "Ankunftsflughafen",
            "strAllergies" : "Allergien",
            "strApplicationDoNotHavePermission" : "Die Anwendung hat keine Berechtigung, die Kamera zu verwenden, bitte ändern Sie die Datenschutzeinstellungen",
            "strApplicationNumber" : "Antragsnummer",
            "strArtisticName" : "Pseudonym",
            "strAuditInformation" : "Validierungsnummer",
            "strAuthentification" : "Echtheitsüberprüfung",
            "strAuthority" : "Ausstellende Behörde",
            "strAuthorityCode" : "Behördencode",
            "strAuthorityRUS" : "Ausstellende Behörde (National)",
            "strAuthorizationNumber" : "Autorisierungsnummer",
            "strAxialProtection" : "Retroreflektierende Schutz",
            "strBDBType" : "BDB-Typ",
            "strBankCardNumber" : "Bankkartennummer",
            "strBankCardValidThru" : "Gültigkeit der Bankkarte",
            "strBanknoteNumber" : "Banknotennummer",
            "strBarcode" : "Barcode",
            "strBarcodeFormatCheck" : "Barcode-Formatprüfung",
            "strBenefitsNumber" : "Leistungsnummer",
            "strBinaryCode" : "Binärcode",
            "strBiometricFormatOwner" : "Eigentümer des biometrischen Formats",
            "strBiometricFormatType" : "Biometrischer Formattyp",
            "strBiometricProductID" : "Biometrische Produkt-ID",
            "strBiometricSubtype" : "Biometrischer Subtyp",
            "strBiometricType" : "Biometrischer Typ",
            "strBlankElement" : "Leeres Element",
            "strBloodGroup" : "Blutgruppe",
            "strBookletNumber" : "Heftnummer",
            "strCCWUntil" : "CCW bis",
            "strCDLClass" : "CDL-Klasse",
            "strCSCCode" : "CSC-Code",
            "strCVV" : "CVV/CVC",
            "strCaliber" : "Kaliber",
            "strCameraUnavailable" : "Kamera nicht verfügbar",
            "strCardAccessNumber" : "Kartenzugangsnummer",
            "strCategory" : "Kategorie",
            "strCenturyDateOfBirth" : "Jahrhundert der Geburt",
            "strChassisNumber" : "Fahrgestellnummer",
            "strCheckInSequenceNumber" : "Check-in-Sequenznummer",
            "strChildren" : "Kinder",
            "strCitizenshipOfFirstPerson" : "Staatsangehörigkeit der ersten Person",
            "strCitizenshipOfSecondPerson" : "Staatsangehörigkeit der zweiten Person",
            "strCivilStatus" : "Familienstand",
            "strColorDynamic" : "Farbdynamik",
            "strCommercialVehicleCodes" : "Code für Nutzfahrzeuge",
            "strCompanyName" : "Firmenname",
            "strCompartmentCode": "Abteilcode",
            "strComplexion": "Teint",
            "strComplianceType": "Einhaltungstyp",
            "strConditions": "Bedingungen",
            "strConfiguration": "Konfiguration",
            "strControlNo": "Kontrollnummer",
            "strCopy": "Kopie",
            "strCourtCode": "Gerichtscode",
            "strCty": "Kreis",
            "strCurrentDate": "Aktuelles Datum",
            "strCustodyInfo": "Haftinformation",
            "strDFTAppDirectory": "App-Verzeichnis",
            "strDFTCertificate": "Zertifikat",
            "strDG1": "Maschinenlesbare Zone (DG1)",
            "strDG10": "nicht definiert (DG10)",
            "strDG11": "Zusätzliche persönliche Details (DG11)",
            "strDG12": "Zusätzliche Dokumentdetails (DG12)",
            "strDG13": "Optionale Details (DG13)",
            "strDG14": "EAC-Informationen (DG14)",
            "strDG15": "Aktive Authentifizierungsinfo (DG15)",
            "strDG16": "Zu benachrichtigende Personen (DG16)",
            "strDG17": "DG17",
            "strDG18": "DG18",
            "strDG19": "DG19",
            "strDG2": "Biometrie - Gesichtsdaten (DG2)",
            "strDG20": "DG20",
            "strDG3": "Biometrie - Fingerabdrücke (DG3)",
            "strDG4": "Biometrie - Irisdaten (DG4)",
            "strDG5": "Porträts (DG5)",
            "strDG6": "nicht definiert (DG6)",
            "strDG7": "Unterschrift / übliche Markierung (DG7)",
            "strDG8": "nicht definiert (DG8)",
            "strDG9": "nicht definiert (DG9)",
            "strDLCDLRestrictionCode": "CDL-Einschränkungscode",
            "strDLClass": "Führerscheinkategorie",
            "strDLClassCodeA1From": "Führerscheinkategorie A1 gültig ab",
            "strDLClassCodeA1Notes": "Führerscheinkategorie A1 Codes",
            "strDLClassCodeA1To": "Führerscheinkategorie A1 gültig bis",
            "strDLClassCodeA2From": "Führerscheinkategorie A2 gültig ab",
            "strDLClassCodeA2Notes": "Führerscheinkategorie A2 Codes",
            "strDLClassCodeA2To": "Führerscheinkategorie A2 gültig bis",
            "strDLClassCodeA3From": "Führerscheinkategorie A3 gültig ab",
            "strDLClassCodeA3Notes": "Führerscheinkategorie A3 Codes",
            "strDLClassCodeA3To": "Führerscheinkategorie A3 gültig bis",
            "strDLClassCodeAFrom": "Führerscheinkategorie A gültig ab",
            "strDLClassCodeAMFrom": "Führerscheinkategorie AM gültig ab",
            "strDLClassCodeAMNotes": "Führerscheinkategorie AM Codes",
            "strDLClassCodeAMTo": "Führerscheinkategorie AM gültig bis",
            "strDLClassCodeANotes": "Führerscheinkategorie A Codes",
            "strDLClassCodeATo": "Führerscheinkategorie A gültig bis",
            "strDLClassCodeB1From": "Führerscheinkategorie B1 gültig ab",
            "strDLClassCodeB1Notes": "Führerscheinkategorie B1 Codes",
            "strDLClassCodeB1To": "Führerscheinkategorie B1 gültig bis",
            "strDLClassCodeB2EFrom": "Führerscheinkategorie B2E gültig ab",
            "strDLClassCodeB2ENotes": "Führerscheinkategorie B2E Codes",
            "strDLClassCodeB2ETo": "Führerscheinkategorie B2E gültig bis",
            "strDLClassCodeB2From": "Führerscheinkategorie B2 gültig ab",
            "strDLClassCodeB2Notes": "Führerscheinkategorie B2 Codes",
            "strDLClassCodeB2To": "Führerscheinkategorie B2 gültig bis",
            "strDLClassCodeBEFrom": "Führerscheinkategorie BE gültig ab",
            "strDLClassCodeBENotes": "Führerscheinkategorie BE Codes",
            "strDLClassCodeBETo": "Führerscheinkategorie BE gültig bis",
            "strDLClassCodeBFrom": "Führerscheinkategorie B gültig ab",
            "strDLClassCodeBNotes": "Führerscheinkategorie B Codes",
            "strDLClassCodeBTPFrom": "Führerscheinkategorie BTP gültig ab",
            "strDLClassCodeBTPNotes": "Führerscheinkategorie BTP Codes",
            "strDLClassCodeBTPTo": "Führerscheinkategorie BTP gültig bis",
            "strDLClassCodeBTo": "Führerscheinkategorie B gültig bis",
            "strDLClassCodeC1EFrom": "Führerscheinkategorie C1E gültig ab",
            "strDLClassCodeC1ENotes": "Führerscheinkategorie C1E Codes",
            "strDLClassCodeC1ETo": "Führerscheinkategorie C1E gültig bis",
            "strDLClassCodeC1From": "Führerscheinkategorie C1 gültig ab",
            "strDLClassCodeC1Notes": "Führerscheinkategorie C1 Codes",
            "strDLClassCodeC1To": "Führerscheinkategorie C1 gültig bis",
            "strDLClassCodeC2From": "Führerscheinkategorie C2 gültig ab",
            "strDLClassCodeC2Notes": "Führerscheinkategorie C2 Codes",
            "strDLClassCodeC2To": "Führerscheinkategorie C2 gültig bis",
            "strDLClassCodeC3From": "Führerscheinkategorie C3 gültig ab",
            "strDLClassCodeC3Notes": "Führerscheinkategorie C3 Codes",
            "strDLClassCodeC3To": "Führerscheinkategorie C3 gültig bis",
            "strDLClassCodeCAFrom": "Führerscheinkategorie CA gültig ab",
            "strDLClassCodeCANotes": "Führerscheinkategorie CA Codes",
            "strDLClassCodeCATo": "Führerscheinkategorie CA gültig bis",
            "strDLClassCodeCEFrom": "Führerscheinkategorie CE gültig ab",
            "strDLClassCodeCENotes": "Führerscheinkategorie CE Codes",
            "strDLClassCodeCETo": "Führerscheinkategorie CE gültig bis",
            "strDLClassCodeCFrom": "Führerscheinkategorie C gültig ab",
            "strDLClassCodeCNotes": "Führerscheinkategorie C Codes",
            "strDLClassCodeCTo": "Führerscheinkategorie C gültig bis",
            "strDLClassCodeD1EFrom": "Führerscheinkategorie D1E gültig ab",
            "strDLClassCodeD1ENotes": "Führerscheinkategorie D1E Codes",
            "strDLClassCodeD1ETo": "Führerscheinkategorie D1E gültig bis",
            "strDLClassCodeD1From": "Führerscheinkategorie D1 gültig ab",
            "strDLClassCodeD1Notes": "Führerscheinkategorie D1 Codes",
            "strDLClassCodeD1To": "Führerscheinkategorie D1 gültig bis",
            "strDLClassCodeD2From": "Führerscheinkategorie D2 gültig ab",
            "strDLClassCodeD2Notes": "Führerscheinkategorie D2 Codes",
            "strDLClassCodeD2To": "Führerscheinkategorie D2 gültig bis",
            "strDLClassCodeDEFrom": "Führerscheinkategorie DE gültig ab",
            "strDLClassCodeDENotes": "Führerscheinkategorie DE Codes",
            "strDLClassCodeDETo": "Führerscheinkategorie DE gültig bis",
            "strDLClassCodeDFrom": "Führerscheinkategorie D gültig ab",
            "strDLClassCodeDNotes": "Führerscheinkategorie D Codes",
            "strDLClassCodeDTo": "Führerscheinkategorie D gültig bis",
            "strDLClassCodeEFrom": "Führerscheinkategorie E gültig ab",
            "strDLClassCodeENotes": "Führerscheinkategorie E Codes",
            "strDLClassCodeETo": "Führerscheinkategorie E gültig bis",
            "strDLClassCodeFA1From": "Führerscheinkategorie FA1 gültig ab",
            "strDLClassCodeFA1Notes": "Führerscheinkategorie FA1 Codes",
            "strDLClassCodeFA1To": "Führerscheinkategorie FA1 gültig bis",
            "strDLClassCodeFAFrom": "Führerscheinkategorie FA gültig ab",
            "strDLClassCodeFANotes": "Führerscheinkategorie FA Codes",
            "strDLClassCodeFATo": "Führerscheinkategorie FA gültig bis",
            "strDLClassCodeFBFrom": "Führerscheinkategorie FB gültig ab",
            "strDLClassCodeFBNotes": "Führerscheinkategorie FB Codes",
            "strDLClassCodeFBTo": "Führerscheinkategorie FB gültig bis",
            "strDLClassCodeFFrom": "Führerscheinkategorie F gültig ab",
            "strDLClassCodeFNotes": "Führerscheinkategorie F Codes",
            "strDLClassCodeFTo": "Führerscheinkategorie F gültig bis",
            "strDLClassCodeG1From": "Führerscheinkategorie G1 gültig ab",
            "strDLClassCodeG1Notes": "Führerscheinkategorie G1 Codes",
            "strDLClassCodeG1To": "Führerscheinkategorie G1 gültig bis",
            "strDLClassCodeGFrom": "Führerscheinkategorie G gültig ab",
            "strDLClassCodeGNotes": "Führerscheinkategorie G Codes",
            "strDLClassCodeGTo": "Führerscheinkategorie G gültig bis",
            "strDLClassCodeHCFrom": "Führerscheinkategorie HC gültig ab",
            "strDLClassCodeHCNotes": "Führerscheinkategorie HC Codes",
            "strDLClassCodeHCTo": "Führerscheinkategorie HC gültig bis",
            "strDLClassCodeHFrom": "Führerscheinkategorie H gültig ab",
            "strDLClassCodeHNotes": "Führerscheinkategorie H Codes",
            "strDLClassCodeHRFrom": "Führerscheinkategorie HR gültig ab",
            "strDLClassCodeHRNotes": "Führerscheinkategorie HR Codes",
            "strDLClassCodeHRTo": "Führerscheinkategorie HR gültig bis",
            "strDLClassCodeHTo": "Führerscheinkategorie H gültig bis",
            "strDLClassCodeIFrom": "Führerscheinkategorie I gültig ab",
            "strDLClassCodeINotes": "Führerscheinkategorie I Codes",
            "strDLClassCodeITo": "Führerscheinkategorie I gültig bis",
            "strDLClassCodeJFrom": "Führerscheinkategorie J gültig ab",
            "strDLClassCodeJNotes": "Führerscheinkategorie J Codes",
            "strDLClassCodeJTo": "Führerscheinkategorie J gültig bis",
            "strDLClassCodeKFrom": "Führerscheinkategorie K gültig ab",
            "strDLClassCodeKNotes": "Führerscheinkategorie K Codes",
            "strDLClassCodeKTo": "Führerscheinkategorie K gültig bis",
            "strDLClassCodeLCFrom": "Führerscheinkategorie LC gültig ab",
            "strDLClassCodeLCNotes": "Führerscheinkategorie LC Codes",
            "strDLClassCodeLCTo": "Führerscheinkategorie LC gültig bis",
            "strDLClassCodeLFrom": "Führerscheinkategorie L gültig ab",
            "strDLClassCodeLKFrom": "Führerscheinkategorie LK gültig ab",
            "strDLClassCodeLKNotes": "Führerscheinkategorie LK Codes",
            "strDLClassCodeLKTo": "Führerscheinkategorie LK gültig bis",
            "strDLClassCodeLNotes": "Führerscheinkategorie L Codes",
            "strDLClassCodeLRFrom": "Führerscheinkategorie LR gültig ab",
            "strDLClassCodeLRNotes": "Führerscheinkategorie LR Codes",
            "strDLClassCodeLRTo": "Führerscheinkategorie LR gültig bis",
            "strDLClassCodeLTo": "Führerscheinkategorie L gültig bis",
            "strDLClassCodeMCFrom": "Führerscheinkategorie MC gültig ab",
            "strDLClassCodeMCNotes": "Führerscheinkategorie MC Codes",
            "strDLClassCodeMCTo": "Führerscheinkategorie MC gültig bis",
            "strDLClassCodeMFrom": "Führerscheinkategorie M gültig ab",
            "strDLClassCodeMNotes": "Führerscheinkategorie M Codes",
            "strDLClassCodeMRFrom": "Führerscheinkategorie MR gültig ab",
            "strDLClassCodeMRNotes": "Führerscheinkategorie MR Codes",
            "strDLClassCodeMRTo": "Führerscheinkategorie MR gültig bis",
            "strDLClassCodeMTo": "Führerscheinkategorie M gültig bis",
            "strDLClassCodeNFrom": "Führerscheinkategorie N gültig ab",
            "strDLClassCodeNNotes": "Führerscheinkategorie N Codes",
            "strDLClassCodeNTo": "Führerscheinkategorie N gültig bis",
            "strDLClassCodeREFrom": "Führerscheinkategorie RE gültig ab",
            "strDLClassCodeRENotes": "Führerscheinkategorie RE Codes",
            "strDLClassCodeRETo": "Führerscheinkategorie RE gültig bis",
            "strDLClassCodeRFrom": "Führerscheinkategorie R gültig ab",
            "strDLClassCodeRNotes": "Führerscheinkategorie R Codes",
            "strDLClassCodeRTo": "Führerscheinkategorie R gültig bis",
            "strDLClassCodeSFrom": "Führerscheinkategorie S gültig ab",
            "strDLClassCodeSNotes": "Führerscheinkategorie S Codes",
            "strDLClassCodeSTo": "Führerscheinkategorie S gültig bis",
            "strDLClassCodeTBFrom": "Führerscheinkategorie TB gültig ab",
            "strDLClassCodeTBNotes": "Führerscheinkategorie TB Codes",
            "strDLClassCodeTBTo": "Führerscheinkategorie TB gültig bis",
            "strDLClassCodeTFrom": "Führerscheinkategorie T gültig ab",
            "strDLClassCodeTMFrom": "Führerscheinkategorie TM gültig ab",
            "strDLClassCodeTMNotes": "Führerscheinkategorie TM Codes",
            "strDLClassCodeTMTo": "Führerscheinkategorie TM gültig bis",
            "strDLClassCodeTNotes": "Führerscheinkategorie T Codes",
            "strDLClassCodeTRFrom": "Führerscheinkategorie TR gültig ab",
            "strDLClassCodeTRNotes": "Führerscheinkategorie TR Codes",
            "strDLClassCodeTRTo": "Führerscheinkategorie TR gültig bis",
            "strDLClassCodeTTo": "Führerscheinkategorie T gültig bis",
            "strDLClassCodeTVFrom": "Führerscheinkategorie TV gültig ab",
            "strDLClassCodeTVNotes": "Führerscheinkategorie TV Codes",
            "strDLClassCodeTVTo": "Führerscheinkategorie TV gültig bis",
            "strDLClassCodeVFrom": "Führerscheinkategorie V gültig ab",
            "strDLClassCodeVNotes": "Führerscheinkategorie V Codes",
            "strDLClassCodeVTo": "Führerscheinkategorie V gültig bis",
            "strDLClassCodeWFrom": "Führerscheinkategorie W gültig ab",
            "strDLClassCodeWNotes": "Führerscheinkategorie W Codes",
            "strDLClassCodeWTo": "Führerscheinkategorie W gültig bis",
            "strDLDuplicateDate": "Datum der Ausstellung des Duplikats",
            "strDLEndorsed": "DL-Bescheinigungscodes",
            "strDLIssType": "Kartentyp",
            "strDLRecordCreated": "Datensatz erstellt am",
            "strDLRestrictionCode": "DL-Beschränkungscode",
            "strDLUnder18Date": "Datum des 18. Geburtstags",
            "strDLUnder19Date": "Datum des 19. Geburtstags",
            "strDLUnder21Date": "Datum des 21. Geburtstags",
            "strDNINumber": "DNI-Nummer",
            "strDSCertificateIssuer": "DS-Zertifikatsaussteller",
            "strDSCertificateSubject": "DS-Zertifikatsgegenstand",
            "strDSCertificateValidFrom": "DS-Zertifikat gültig von",
            "strDSCertificateValidTo": "DS-Zertifikat gültig bis",
            "strDUFNumber": "DUF-Nummer",
            "strDataDiscriminator": "Datenunterscheider",
            "strDateFirstRenewal": "Datum der ersten Verlängerung",
            "strDateOfBirthOfHusband": "Geburtsdatum des Ehemanns",
            "strDateOfBirthOfWife": "Geburtsdatum der Ehefrau",
            "strDateOfInsuranceExpiry": "Ablaufdatum der Versicherung",
            "strDateSecondRenewal": "Datum der zweiten Verlängerung",
            "strDateofBirth": "Geburtsdatum",
            "strDateofBirthCheckDigit": "Prüfziffer für das Geburtsdatum",
            "strDateofBirthChecksum": "Prüfsumme für das Geburtsdatum",
            "strDateofCreation": "Erstellungsdatum",
            "strDateofExpiry": "Ablaufdatum",
            "strDateofExpiryCheckDigit": "Prüfziffer für das Ablaufdatum",
            "strDateofExpiryChecksum": "Prüfsumme für das Ablaufdatum",
            "strDateofFlight": "Flugdatum",
            "strDateofIssue": "Ausgabedatum",
            "strDateofIssueBoardingPass": "Ausgabedatum der Bordkarte",
            "strDateofIssueCheckDigit": "Prüfziffer für das Ausgabedatum",
            "strDateofIssueChecksum": "Prüfsumme für das Ausgabedatum",
            "strDateofPersonalization": "Personalisierungsdatum",
            "strDateofRegistration": "Registrierungsdatum",
            "strDay": "Tag",
            "strDepartment": "Abteilung",
            "strDeptNumber": "Abteilungsnummer",
            "strDestination": "Zielort",
            "strDiscretionaryData": "Freiwählbare Daten",
            "strDoDNumber": "DoD-Nummer",
            "strDocumentClassCode": "Dokumentenklassencode",
            "strDocumentClassName": "Dokumentenklasse",
            "strDocumentDiscriminator": "Dokumentunterscheider",
            "strDocumentNumber": "Dokumentennummer",
            "strDocumentNumberCheckDigit": "Prüfziffer für die Dokumentennummer",
            "strDocumentNumberChecksum": "Prüfsumme für die Dokumentennummer",
            "strDocumentSeries": "Dokumentenserie",
            "strDocumentTooSmall": "Dokument in den Rahmen einlegen",
            "strDonor": "Spender",
            "strDossierNumber": "Dossiernummer",
            "strDurationofStay": "Aufenthaltsdauer",
            "strECEnvironmentalType": "Fahrzeugumwelttyp",
            "strEDLDG1": "Textdatenelemente (DG1)",
            "strEDLDG10": "Nicht definiert (DG10)",
            "strEDLDG11": "Optionale Inlandsdaten (DG11)",
            "strEDLDG12": "Nicht-Übereinstimmungsalarm (DG12)",
            "strEDLDG13": "Aktive Authentifizierungsinformationen (DG13)",
            "strEDLDG14": "EAC-Informationen (DG14)",
            "strEDLDG2": "Informationen zum Lizenzinhaber (DG2)",
            "strEDLDG3": "Angaben zur ausstellenden Behörde (DG3)",
            "strEDLDG4": "Porträtbild (DG4)",
            "strEDLDG5": "Unterschriften-/übliches Markierungsbild (DG5)",
            "strEDLDG6": "Biometrie - Gesichtsdaten (DG6)",
            "strEDLDG7": "Biometrie - Fingerabdrücke (DG7)",
            "strEDLDG8": "Biometrie - Irisdaten (DG8)",
            "strEDLDG9": "Biometrie - Sonstige (DG9)",
            "strEFCOM": "EF.COM",
            "strEFCVCA": "EF.CVCA",
            "strEFCardAccess": "EF.Kartenzugriff",
            "strEFCardSecurity": "EF.Kartensicherheit",
            "strEFChipSecurity": "EF.Chip-Sicherheit",
            "strEFSOD": "EF.SOD",
            "strEQVCode": "EQV-Code",
            "strElectronicTicketIndicator": "Elektronischer Ticket-Indikator",
            "strElement": "Element",
            "strEndorsementExpirationDate": "Ablaufdatum der Bescheinigung",
            "strEngineModel": "Motormodell",
            "strEngineNumber": "Motornummer",
            "strEnginePower": "Motorleistung",
            "strEngineVolume": "Hubraum",
            "strError": "Fehler",
            "strExamDate": "Prüfungsdatum",
            "strExeptInTanks": "Ausgenommen in Tanks",
            "strEye": "Iris",
            "strEyesColor": "Augenfarbe",
            "strFaculty": "Fakultät",
            "strFalseLuminescence": "Übermäßige Lumineszenz",
            "strFamilyName": "Nachname/Vorname bei der Geburt",
            "strFamilyNameTruncation": "Gekürzter Nachname/Vorname bei der Geburt",
            "strFastTrack": "Schnellverfahren",
            "strFatherCountryOfBirth": "Land des Geburtsorts des Vaters",
            "strFatherDateOfBirth": "Geburtsdatum des Vaters",
            "strFatherGivenName": "Vorname des Vaters",
            "strFatherPersonalNumber": "Persönliche Nummer des Vaters",
            "strFatherPlaceOfBirth": "Geburtsort des Vaters",
            "strFatherSurname": "Nachname des Vaters",
            "strFathersName": "Name des Vaters",
            "strFathersNameRUS": "Name des Vaters (national)",
            "strFederalElections": "Bundeswahlen",
            "strFee": "Gebühr",
            "strFieldFromMRZ": "Feld aus MRZ",
            "strFieldTypeDocumentImage": "Dokumentbildtyp",
            "strFillElement": "Füllelement",
            "strFinalCheckDigit": "Endprüfziffer",
            "strFinalChecksum": "Endprüfsumme",
            "strFingerprint": "Fingerabdruck",
            "strFirstIssueDate": "Erstausgabedatum",
            "strFirstNameTruncation": "Trunkierung des Vornamens",
            "strFlightNumber": "Flugnummer",
            "strFolioNumber": "Foliennnummer",
            "strFormOfEducation": "Bildungsform",
            "strFreeBaggageAllowance": "Freigepäckgrenze",
            "strFrequentFlyerAirlineDesignator": "Kennzeichnung der Vielfliegerfluggesellschaft",
            "strFrequentFlyerNumber": "Vielfliegernummer",
            "strFromAirportCode": "Code des Abflughafens",
            "strFuelType": "Kraftstofftyp",
            "strGNIBNumber": "GNIB-Nummer",
            "strGhostPortrait": "Geisterporträt",
            "strGivenNames": "Vorname",
            "strGivenNamesRUS": "Vorname (national)",
            "strGlaresOnDocument": "Vermeiden Sie Reflexionen auf dem Dokument",
            "strGrandfatherName": "Name des Großvaters",
            "strHairColor": "Haarfarbe",
            "strHealthNumber": "Krankenversicherungsnummer",
            "strHeight": "Größe",
            "strHoldDocumentStraight": "Halten Sie das Dokument gerade",
            "strHoloSimple": "Verfügbarkeit von Hologrammen",
            "strHoloVerifyDinamic": "Dynamisches Hologramm überprüfen",
            "strHoloVerifyMultiStatic": "Mehrere statische Hologramme überprüfen",
            "strHoloVerifyStatic": "Statisches Hologramm überprüfen",
            "strHolograms": "Hologramme",
            "strIPI": "IPI (unsichtbare persönliche Informationen)",
            "strIRB900": "IR B900-Tinte",
            "strIRVis": "IR-Transparenz",
            "strISOIssuerIDNumber": "ID-Nummer des ISO-Herausgebers",
            "strIdentifier": "Kennung",
            "strIdentityCardNumber": "Personalausweisnummer",
            "strIdentityCardNumberCheckDigit": "Prüfziffer für Personalausweisnummer",
            "strIdentityCardNumberChecksum": "Prüfsumme für Personalausweisnummer",
            "strImagePattern": "Bildmuster",
            "strInTanks": "In Tanks",
            "strInventoryNumber": "Inventarnummer",
            "strInvitationNumber": "Einladungsnummer",
            "strInvitationNumberCheckDigit": "Prüfziffer für Einladungsnummer",
            "strInvitationNumberChecksum": "Prüfsumme für Einladungsnummer",
            "strInvitedBy": "Eingeladen von",
            "strIssueTimestamp": "Ausstellungszeitpunkt",
            "strIssuingStateCode": "Ausstellender Staatencode",
            "strIssuingStateName": "Ausstellender Staat",
            "strJurisdictionEndorsementCode": "Gerichtszustimmungscode",
            "strJurisdictionRestrictionCode": "Gerichtsbeschränkungscode",
            "strJurisdictionVehicleClass": "Gerichtsfahrzeugklasse",
            "strKeepDeviceStill": "Halten Sie das Gerät still",
            "strLicenseNumber": "Führerscheinnummer",
            "strLimitedDurationDocumentIndicator": "Indikator für dokumentierte begrenzte Dauer",
            "strLine1CheckDigit": "Prüfziffer für Zeile 1",
            "strLine1Checksum": "Prüfsumme für Zeile 1",
            "strLine1OptionalData": "Optionale Daten aus Zeile 1",
            "strLine2CheckDigit": "Prüfziffer für Zeile 2",
            "strLine2Checksum": "Prüfsumme für Zeile 2",
            "strLine2OptionalData": "Optionale Daten aus Zeile 2",
            "strLine3CheckDigit": "Prüfziffer für Zeile 3",
            "strLine3Checksum": "Prüfsumme für Zeile 3",
            "strLine3OptionalData": "Optionale Daten aus Zeile 3",
            "strLookingDocument": "Suche nach einem Dokument...",
            "strMCNoviceDate": "Ablaufdatum des Anfängerstatus für Motorräder",
            "strMRZ": "MRZ",
            "strMRZLinesICAORFID": "MRZ-Zeilen von ICAO RFID",
            "strMRZString1": "MRZ-Zeile 1",
            "strMRZString2": "MRZ-Zeile 2",
            "strMRZString3": "MRZ-Zeile 3",
            "strMRZStrings": "MRZ-Zeilen",
            "strMRZStringsWithCorrectCheckSums": "MRZ-Zeilen mit korrekten Prüfsummen",
            "strMRZType": "MRZ-Typ",
            "strMailingAddressCity": "Postanschrift - Stadt",
            "strMailingAddressJurisdictionCode": "Postanschrift - Zuständigkeitscode",
            "strMailingAddressPostalCode": "Postanschrift - Postleitzahl",
            "strMailingAddressStreet": "Postanschrift - Straße",
            "strMake": "Hersteller",
            "strMaritalStatus": "Familienstand",
            "strMaxMassofTrailerBraked": "Maximales Gewicht des Anhängers (gebremst)",
            "strMaxMassofTrailerUnbraked": "Maximales Gewicht des Anhängers (ungebremst)",
            "strMaxSpeed": "Höchstgeschwindigkeit",
            "strMedicalIndicatorCodes": "Medizinische Hinweise/Codes",
            "strMiddleName": "Zweiter Vorname",
            "strMiddleNameTruncation": "Zweiter Vorname abgekürzt",
            "strMifareData": "MIFARE-Daten",
            "strMifareValidity": "MIFARE-Gültigkeit",
            "strMilitaryBookNumber": "Militärische Ausweisnummer",
            "strModel": "Modell",
            "strMonth": "Monat",
            "strMortgageBy": "Hypothek von",
            "strMotherCountryOfBirth": "Land der Geburt der Mutter",
            "strMotherDateOfBirth": "Geburtsdatum der Mutter",
            "strMotherGivenName": "Vorname der Mutter",
            "strMotherPersonalNumber": "Personalausweisnummer der Mutter",
            "strMotherPlaceOfBirth": "Geburtsort der Mutter",
            "strMotherSurname": "Nachname der Mutter",
            "strMothersName": "Name der Mutter",
            "strNamePrefix": "Namenspräfix",
            "strNameSuffix": "Namenssuffix",
            "strNationality": "Nationalität",
            "strNationalityCode": "Nationalitätscode",
            "strNonResidentIndicator": "Indikator für Nichtansässige",
            "strNone": "Keine",
            "strNotDefined": "Nicht definiert",
            "strNumberOfCardIssuance": "Anzahl der Kartenherausgaben",
            "strNumberOfCardIssuanceCheckDigit": "Prüfziffer für Anzahl der Kartenausstellungen",
            "strNumberOfCardIssuanceChecksum": "Prüfsumme für Anzahl der Kartenausstellungen",
            "strNumberOfCylinders": "Anzahl der Zylinder",
            "strNumberofAxels": "Anzahl der Achsen",
            "strNumberofDuplicates": "Anzahl der Duplikate",
            "strNumberofEntries": "Anzahl der Einträge",
            "strNumberofSeats": "Anzahl der Sitze",
            "strNumberofStandingPlaces": "Anzahl der Stehplätze",
            "strOCRNumber": "OCR-Nummer",
            "strOK": "OK",
            "strObservations": "Beobachtungen",
            "strOldDateOfIssue": "Altes Ausgabedatum",
            "strOldDocumentNumber": "Alte Dokumentnummer",
            "strOldPlaceOfIssue": "Alter Ausstellungsort",
            "strOptionalData": "Optionale Daten",
            "strOptionalDataCheckDigit": "Prüfziffer für optionale Daten",
            "strOptionalDataChecksum": "Prüfsumme für optionale Daten",
            "strOptionalDetails": "Optionale Details",
            "strOrganization": "Organisation",
            "strOther": "Andere",
            "strOtherName": "Anderer Name",
            "strOtherPersonName": "Andere Person, Name",
            "strOtherValidID": "Andere gültige IDs",
            "strOwner": "Eigentümer",
            "strPDF417Codec": "PDF417-Codec",
            "strPNRCode": "PNR-Code",
            "strParrentsGivenNames": "Vornamen der Eltern",
            "strPassportNumber": "Reisepassnummer",
            "strPassportNumberCheckDigit": "Prüfziffer für Reisepassnummer",
            "strPassportNumberChecksum": "Prüfsumme für Reisepassnummer",
            "strPatronHeaderVersion": "Version des Patronenkopfes",
            "strPatternDifferentLinesThickness": "Vergleich der Dicke der Musterlinien",
            "strPatternIRInvisible": "Unsichtbares Muster in IR",
            "strPatternNotInterrupted": "Keine Unterbrechungen",
            "strPatternNotShifted": "Musterlemente sind nicht verschoben",
            "strPatternSameColors": "Gleiche Farben des Musters",
            "strPayGrade": "Bezahlungsstufe",
            "strPayloadCapacity": "Ladekapazität",
            "strPermissibleAxleLoad": "Zulässige Achslast",
            "strPermitDLClass": "Genehmigungsklasse",
            "strPermitDateofExpiry": "Ablaufdatum der Genehmigung",
            "strPermitDateofIssue": "Ausgabedatum der Genehmigung",
            "strPermitEndorsed": "Genehmigung Endorsement-Code",
            "strPermitIdentifier": "Genehmigungsidentifikator",
            "strPermitRestrictionCode": "Genehmigungsbeschränkungscode",
            "strPersonToNotifyAddress": "Person benachrichtigen: Adresse",
            "strPersonToNotifyDateofRecord": "Person benachrichtigen: Datum des Datensatzes",
            "strPersonToNotifyName": "Person benachrichtigen: Name",
            "strPersonToNotifyPhone": "Person benachrichtigen: Telefon",
            "strPersonalNumber": "Persönliche Nummer",
            "strPersonalNumberCheckDigit": "Prüfziffer für persönliche Nummer",
            "strPersonalNumberChecksum": "Prüfsumme für persönliche Nummer",
            "strPersonalSummary": "Zusammenfassung der persönlichen Daten",
            "strPersonalizationSN": "Seriennummer der Personalisierung",
            "strPhone": "Telefon",
            "strPhotoArea": "Foto-Bereich",
            "strPhotoColor": "Farbe des Fotos",
            "strPhotoCorners": "Ecken des Fotos",
            "strPhotoElement": "Fotoelement",
            "strPhotoEmbedType": "Typ der Fotoeinbettung",
            "strPhotoProcessing": "Fotoverarbeitung...",
            "strPhotoShape": "Form des Fotos",
            "strPhotoSizeCheck": "Größenüberprüfung des Fotos",
            "strPlaceDocumentInFrame": "Dokument in den Rahmen legen",
            "strPlaceOfBirthRUS": "Geburtsort (National)",
            "strPlaceOfBirthStateCode": "Bundeslandcode des Geburtsortes",
            "strPlaceOfExamination": "Ort der Untersuchung",
            "strPlaceOfIssue": "Ausstellungsort",
            "strPlacePhoneOnDoc": "Legen Sie das Telefon bitte auf das Dokument",
            "strPlaceofBirth": "Geburtsort",
            "strPlaceofBirthArea": "Geburtsortbereich",
            "strPlaceofRegistration": "Registrierungsort",
            "strPoliceDistrict": "Polizeibezirk",
            "strPortrait": "Porträt",
            "strPortraitComparison": "Vergleich der Porträts",
            "strPortraitOfChild": "Porträt des Kindes",
            "strPortraitVSCamera": "Porträt vs Kameraaufnahme",
            "strPortraitVSGhost": "Porträt vs Geisterfoto",
            "strPortraitVSRFID": "Porträt vs RFID-Chip-Porträt",
            "strPowerWeightRatio": "Leistungsgewichtsverhältnis",
            "strPrecinct": "Wahlbezirk",
            "strPrepareCamera": "Vorbereitung der Kamera...",
            "strPresentNextPage": "Bitte die nächste Seite vorlegen",
            "strPreviousType": "Typ/Nummer des vorherigen Dokuments",
            "strProcessingDocument": "Verarbeitung von Dokumenten...",
            "strProfession": "Beruf",
            "strProfessionalIdNumber": "Berufliche ID-Nummer",
            "strProofOfCitizenship": "Nachweis der Staatsbürgerschaft",
            "strPseudoCode": "Pseudocode",
            "strPurposeOfEntry": "Zweck der Einreise",
            "strRFIDVSCamera": "RFID-Chip-Porträt vs Kameraaufnahme",
            "strRaceEthnicity": "Rasse/Ethnizität",
            "strRank": "Rang",
            "strReadingRFID": "RFID-Chip-Daten werden gelesen",
            "strReadingRFIDDGiOS": "RFID %@-Daten werden gelesen",
            "strRecognizedDocumentType": "Dokumenttyp",
            "strReferenceNumber": "Eindeutige Nummer",
            "strReferenceNumberCheckDigit": "Prüfziffer für eindeutige Nummer",
            "strReferenceNumberChecksum": "Prüfsumme für eindeutige Nummer",
            "strRegCertBodyNumber": "Karosserienummer",
            "strRegCertBodyType": "Karosserietyp",
            "strRegCertCarColor": "Fahrzeugfarbe",
            "strRegCertCarMark": "Fahrzeugmarke",
            "strRegCertCarModel": "Fahrzeugmodell",
            "strRegCertCarType": "Fahrzeugtyp",
            "strRegCertMaxWeight": "Maximales zulässiges Gewicht",
            "strRegCertRegNumber": "Kennzeichen",
            "strRegCertRegNumberCheckDigit": "Prüfziffer für Kennzeichen",
            "strRegCertRegNumberChecksum": "Prüfsumme für Kennzeichen",
            "strRegCertVIN": "Fahrzeugidentifikationsnummer (VIN)",
            "strRegCertVINCheckDigit": "Prüfziffer für VIN",
            "strRegCertVINChecksum": "Prüfsumme für VIN",
            "strRegCertVehicleITSCode": "Fahrzeug-ITS-Code",
            "strRegCertWeight": "Leergewicht",
            "strRelationship": "Beziehung",
            "strReligion": "Religion",
            "strRemainderTerm": "Monate bis zum Ablauf",
            "strResidentFrom": "Einwohner seit",
            "strResidentUntil": "Einwohner bis",
            "strRetirementNumber": "Rentennummer",
            "strRevisionDate": "Revisionsdatum",
            "strRoomNumber": "Zimmernummer",
            "strSBHIntegrityOptions": "SBH-Integritätsoptionen",
            "strSBHSecurityOptions": "SBH-Sicherheitsoptionen",
            "strSeatNumber": "Sitznummer",
            "strSecondSurname": "Zweiter Nachname",
            "strSection": "Abschnitt",
            "strSecurityText": "Sicherheitstext",
            "strSelecteeIndicator": "Auswahlindikator",
            "strSequenceNumber": "Sequenznummer",
            "strSerialNumber": "Seriennummer",
            "strSettings": "Einstellungen",
            "strSex": "Geschlecht",
            "strSignature": "Unterschrift",
            "strSkinColor": "Hautfarbe",
            "strSocialSecurityNumber": "Sozialversicherungsnummer",
            "strSpCode": "Sondercode",
            "strSpecialNotes": "Besondere Hinweise",
            "strSponsor": "Sponsor",
            "strSponsorSSN": "Sponsor SSN",
            "strSponsorService": "Sponsor-Service",
            "strSponsorStatus": "Sponsorstatus",
            "strStamp": "Stempel",
            "strStampNumber": "Stempelnummer",
            "strStatusDateofExpiry": "Ablaufdatum des Status",
            "strSurname": "Nachname",
            "strSurnameAndGivenNames": "Nachname und Vornamen",
            "strSurnameAndGivenNamesCheckDigit": "Prüfziffer für Nachnamen und Vornamen",
            "strSurnameAndGivenNamesChecksum": "Prüfsumme für Nachnamen und Vornamen",
            "strSurnameAndGivenNamesRUS": "Nachname und Vornamen (National)",
            "strSurnameAtBirth": "Nachname bei der Geburt",
            "strSurnameOfHusbandAfterRegistration": "Nachname des Ehemanns nach der Registrierung",
            "strSurnameOfWifeAfterRegistration": "Nachname der Ehefrau nach der Registrierung",
            "strSurnameofSpose": "Nachname des Ehepartners",
            "strTax": "Steuer",
            "strTaxNumber": "Steuernummer",
            "strTelexCode": "Telex-Code",
            "strTerritorialValidity": "Territoriale Gültigkeit",
            "strTicketNumber": "Ticketnummer",
            "strTitle": "Position",
            "strToAirportCode": "Code des Ankunftsflughafens",
            "strTorchUnavailable": "Taschenlampe nicht verfügbar",
            "strTrackingNumber": "Sendungsnummer",
            "strTrailerHitch": "Anhängerkupplung",
            "strTransactionNumber": "Transaktionsnummer",
            "strTransmissionType": "Getriebetyp",
            "strTypeApprovalNumber": "Typgenehmigungsnummer",
            "strURL": "URL",
            "strUSCIS": "USCIS",
            "strUV": "UV",
            "strUVFibers": "UV-Sicherheitsfasern",
            "strUVLuminescence": "UV-Mattkontrolle",
            "strUnableCaptureMedia": "Kamerakonfiguration fehlgeschlagen",
            "strUniqueCustomerIdentifier": "Eindeutiger Kundenidentifikator",
            "strVRCDataObjectEntry": "Fahrzeugdaten aus der DG1-Datengruppe",
            "strValidityPeriod": "Gültigkeitsdauer",
            "strVehicleCategory": "Fahrzeugkategorie",
            "strVeteran": "Veteran",
            "strVisaClass": "Visumklasse",
            "strVisaID": "Visum-ID",
            "strVisaIDCheckDigit": "Prüfziffer für Visum-ID",
            "strVisaIDChecksum": "Prüfsumme für Visum-ID",
            "strVisaIDRUS": "Visum-ID (national)",
            "strVisaNumber": "Visumsnummer",
            "strVisaNumberCheckDigit": "Prüfziffer für Visumsnummer",
            "strVisaNumberChecksum": "Prüfsumme für Visumsnummer",
            "strVisaSubClass": "Visumunterklasse",
            "strVisaType": "Visumtyp",
            "strVisaValidFrom": "Gültig ab",
            "strVisaValidUntil": "Gültig bis",
            "strVisaValidUntilCheckDigit": "Prüfziffer für Ablaufdatum des Visums",
            "strVisaValidUntilChecksum": "Prüfsumme für Ablaufdatum des Visums",
            "strVisibleLight": "Sichtbares Licht",
            "strVoter": "Wähler",
            "strVoterKey": "Wählerschlüssel",
            "strVoucherNumber": "Gutscheinnummer",
            "strWeight": "Gewicht",
            "strWeightPound": "Gewicht (Pfund)",
            "strYear": "Jahr",
            "strYearsSinceIssue": "Jahre seit Ausstellung",
            "streIDPlaceOfBirthCity": "Geburtsort: Stadt",
            "streIDPlaceOfBirthCountry": "Geburtsort: Land",
            "streIDPlaceOfBirthState": "Geburtsort: Bundesland",
            "streIDPlaceOfBirthStreet": "Geburtsort: Straße",
            "streIDPlaceOfBirthZipcode": "Geburtsort: Postleitzahl",
            "streIDResidencePermit1": "Aufenthaltserlaubnis 1",
            "streIDResidencePermit2": "Aufenthaltserlaubnis 2",
            "strfppLeftIndexFinger": "Linker Zeigefinger",
            "strfppLeftLittleFinger": "Linker kleiner Finger",
            "strfppLeftMiddleFinger": "Linker Mittelfinger",
            "strfppLeftRingFinger": "Linker Ringfinger",
            "strfppLeftThumb": "Linker Daumen",
            "strfppRightIndexFinger": "Rechter Zeigefinger",
            "strfppRightLittleFinger": "Rechter kleiner Finger",
            "strfppRightMiddleFinger": "Rechter Mittelfinger",
            "strfppRightRingFinger": "Rechter Ringfinger",
            "strfppRightThumb": "Rechter Daumen"
        ]
    }
}
