//
//  File.swift
//  
//
//  Created by MOBILE on 20/05/24.
//

import Foundation

class EnglishDataValues {
    func getDictionary() -> [String: String] {
        return [
            "RFID_Error_AlreadyDone" : "RFID: Requested operation is already done",
            "RFID_Error_Busy" : "RFID: RFID is Busy",
            "RFID_Error_Failed" : "RFID: Failed",
            "RFID_Error_FileIOError" : "RFID File: IO Error",
            "RFID_Error_InvalidDirectory" : "RFID: Invalid directory",
            "RFID_Error_InvalidParameter" : "RFID: Invalid parameter in ExecuteCommand() call found",
            "RFID_Error_NoChipDetected" : "RFID: No chip is detected",
            "RFID_Error_NotAvailable" : "RFID: Unavailable",
            "RFID_Error_NotEnoughMemory" : "RFID: Out of memory",
            "RFID_Error_NotInitialized" : "RFID: Device is uninitialized",
            "RFID_Error_NotPerformed" : "RFID: Not Performed",
            "RFID_Error_OldFirmware" : "RFID: Firmware need to be updated with newer version",
            "RFID_Error_PCSC_CantConnectCard" : "PCSC: Card cannot be connected",
            "RFID_Error_PCSC_CardIsBusy" : "PCSC: Card Is Busy",
            "RFID_Error_PCSC_CardIsNotConnected" : "PCSC: Card is not connected",
            "RFID_Error_PCSC_ExtLe_Failed" : "PCSC: ExtLe Failed",
            "RFID_Error_PCSC_Failed" : "PCSC: Failed",
            "RFID_Error_PCSC_FailedSCard" : "PCSC: Failed Smart Card",
            "RFID_Error_PCSC_OperationCancelled" : "PCSC: Operation is cancelled",
            "RFID_Error_PCSC_ReaderNotAvailable" : "PCSC: Reader is unavailable",
            "RFID_Error_Session_AccessControl_AA_Failed" : "RFID: AA Failed",
            "RFID_Error_Session_AccessControl_CA_Failed" : "RFID: CA Failed",
            "RFID_Error_Session_AccessControl_IncorrectOptionCA" : "RFID: Incorrect Option CA",
            "RFID_Error_Session_AccessControl_RI_Failed" : "RFID: RI Failed",
            "RFID_Error_Session_AccessControl_RequiresCA" : "RFID: Requires CA",
            "RFID_Error_Session_AccessControl_RequiresCAKeys" : "RFID: Requires CA Keys",
            "RFID_Error_Session_AccessControl_RequiresPACE" : "RFID: Requires PACE",
            "RFID_Error_Session_AccessControl_RequiresSM" : "RFID: Requires SM",
            "RFID_Error_Session_AccessControl_RequiresTA" : "RFID: Requires TA",
            "RFID_Error_Session_AccessControl_TA_Failed" : "RFID: TA Failed",
            "RFID_Error_Session_AccessControl_UnknownType" : "RFID: Access Control UnknownType",
            "RFID_Error_Session_AccessKey_IncorrectData" : "RFID: Access Key Incorrect Data",
            "RFID_Error_Session_AccessKey_IncorrectSMType" : "RFID: Access Key Incorrect SM Type",
            "RFID_Error_Session_AccessKey_NotSet" : "RFID: Access Key Not Set",
            "RFID_Error_Session_AccessKey_Restricted" : "RFID: Access Key Restricted",
            "RFID_Error_Session_AccessKey_UnknownType" : "RFID: Access Key Unknown Type",
            "RFID_Error_Session_AccessKey_UnsupportedSMType" : "RFID: Access Key Unsupported SM Type",
            "RFID_Error_Session_File_AccessDenied" : "RFID File: Access Denied",
            "RFID_Error_Session_File_CantReadData" : "RFID File: Cannot Read Data",
            "RFID_Error_Session_File_CantUseData" : "RFID File: Cannot Use Data",
            "RFID_Error_Session_File_Contents_UnexpectedData" : "RFID File: Contents Unexpected Data",
            "RFID_Error_Session_File_IncorrectData" : "RFID File: Incorrect Data",
            "RFID_Error_Session_File_NotEnoughData" : "RFID File: Not Enough Data",
            "RFID_Error_Session_File_UnexpectedData" : "RFID File: Unexpected Data",
            "RFID_Error_Session_File_WrongTag" : "RFID File: Wrong Tag",
            "RFID_Error_Session_IncorrectData" : "RFID: Incorrect data",
            "RFID_Error_Session_InvalidAuxData_CommunityID" : "RFID: Invalid Aux Data Community ID",
            "RFID_Error_Session_InvalidAuxData_DateOfBirth" : "RFID: Invalid Aux Data Date Of Birth",
            "RFID_Error_Session_InvalidAuxData_DateOfExpiry" : "RFID: Invalid Aux Data Date Of Expiry",
            "RFID_Error_Session_IsClosed" : "RFID: Session Is Closed",
            "RFID_Error_Session_PA_HashCheckFailed" : "RFID: Hash Check Failed",
            "RFID_Error_Session_PA_SignatureCheckFailed" : "RFID: SO Signature Check Failed",
            "RFID_Error_Session_ProcedureType_NotSet" : "RFID: Procedure Type Not Set",
            "RFID_Error_Session_ProcedureType_Unknown" : "RFID: Procedure Type Unknown",
            "RFID_Error_Session_ProcedureType_Unsupported" : "RFID: Procedure Type Unsupported",
            "RFID_Error_Session_PwdManagement_NotAuthorized" : "RFID: Pwd Management Not Authorized",
            "RFID_Error_Session_TerminalType_BadCertificate" : "RFID: Terminal Type Bad Certificate",
            "RFID_Error_Session_TerminalType_NotSet" : "RFID: Terminal Type Not Set",
            "RFID_Error_Session_TerminalType_Unknown" : "RFID: Terminal Type Unknown",
            "RFID_Error_Session_Terminal_UnsupportedOperation" : "RFID: Terminal Unsupported Operation",
            "RFID_Error_Session_eSign_PIN_NotSet" : "RFID: eSign PIN Not Set",
            "RFID_Error_Session_eSign_PIN_NotVerified" : "RFID: eSign PIN Not Verified",
            "RFID_Error_Session_eSign_RequiresAppSelection" : "RFID: eSign Requires App Selection",
            "RFID_Error_UnknownCommand" : "RFID: Unknown command",
            "RFID_LAYER6_APP_SELECTION_FAILURE" : "LAYER6: ISO7816_A_03 \"Application selection failure\"",
            "RFID_LAYER6_EXT_AUTH_FAILURE" : "LAYER6: APDU_INS_EXTERNAL_AUTHENTICATE (External Authentication) failure",
            "RFID_LAYER6_FILE_EOF1" : "LAYER6: Reading beyond EOF / Unexpected EOF",
            "RFID_LAYER6_FILE_EOF2" : "LAYER6: Reading beyond EOF / Unexpected EOF",
            "RFID_LAYER6_FILE_NOT_FOUND" : "LAYER6: File selection failure / file not found",
            "RFID_LAYER6_GENERAL_AUTH_FAILURE" : "LAYER6: General Authenticity Failure",
            "RFID_LAYER6_GET_CHALLENGE_FAILURE" : "LAYER6: GET CHALLENGE failure",
            "RFID_LAYER6_INCORRECT_PARAMS" : "LAYER6: Incorrect Params",
            "RFID_LAYER6_INT_AUTH_FAILURE" : "LAYER6: APDU_INS_INTERNAL_AUTHENTICATE failure",
            "RFID_LAYER6_MSE_SET_AT_FAILURE" : "LAYER6: MSE:Set AT failure",
            "RFID_LAYER6_MSE_SET_DST_FAILURE" : "LAYER6: MSE:Set DST failure",
            "RFID_LAYER6_MSE_SET_KAT_FAILURE" : "LAYER6: MSE:Set KAT failure",
            "RFID_LAYER6_MUTUAL_AUTH_ENC_FAIL" : "LAYER6: ISO7816_B_02 \"Mutual authentication encryption failure\"",
            "RFID_LAYER6_MUTUAL_AUTH_FAILURE" : "LAYER6: ISO7816_B_03 \"Mutual authentication failure\"",
            "RFID_LAYER6_MUTUAL_AUTH_MAC_FAIL" : "LAYER6: ISO7816_B_01 \"Mutual authentication MAC failure\"",
            "RFID_LAYER6_NON_TLV_RESPONSE_DATA" : "LAYER6: Not TLV response data",
            "RFID_LAYER6_NO_REFERENCE_DATA" : "LAYER6: No Reference Data",
            "RFID_LAYER6_PSO_CERTIFICATE_FAILURE" : "LAYER6: PSO CERTIFICATE failure",
            "RFID_LAYER6_PWD_BLOCKED" : "LAYER6: PWD Blocked",
            "RFID_LAYER6_PWD_BLOCKED_2" : "LAYER6: PWD Blocked 2",
            "RFID_LAYER6_PWD_DEACTIVATED" : "LAYER6: PWD Deactivatted",
            "RFID_LAYER6_PWD_DEACTIVATED_2" : "LAYER6: PWD Deactivated 2",
            "RFID_LAYER6_PWD_FAILED" : "LAYER6: PWD Failed",
            "RFID_LAYER6_PWD_SUSPENDED" : "LAYER6: PWD Suspended",
            "RFID_LAYER6_PWD_SUSPENDED_2" : "LAYER6: PWD Suspended 2",
            "RFID_LAYER6_SECURITY_MANAGER" : "LAYER6: Secure Messaging was not activated",
            "RFID_LAYER6_SM_DO87_INCORRECT" : "LAYER6: SM failure – incorrect cryptogram",
            "RFID_LAYER6_SM_DO87_MISSING" : "LAYER6: SM failure – cryptogram missing",
            "RFID_LAYER6_SM_DO8E_MISSING" : "LAYER6: SM failure – MAC missing",
            "RFID_LAYER6_SM_DO99_MISSING" : "LAYER6: SM failure – secured status bytes missing",
            "RFID_LAYER6_SM_MAC_INCORRECT" : "LAYER6: SM failure – incorrect MAC",
            "RFID_LAYER6_WRONG_RND_ICC_LENGTH" : "LAYER6: Wrong data length (APDU_INS_GET_CHALLENGE)",
            "RSDT_RFID_READING_FINISHED" : "RFID data reading is finished",
            "TCT_Unknown" : "Unknown",
            "chd_BackgroundComparisonError" : "Brightness of the two pages is different",
            "chd_BadAreaInAxial" : "Retroreflective protection failure",
            "chd_BarcodeDataFormatError" : "Barcode format error",
            "chd_BarcodeReadedWithErrors" : "Barcode has been read with errors",
            "chd_BarcodeSizeParamsError" : "Barcode parameters error",
            "chd_DocumentIsCancelling" : "Document is cancelled",
            "chd_ElementShouldBeColored" : "Element should be colored",
            "chd_ElementShouldBeGrayscale" : "Element should be grayscale",
            "chd_ExceptionInModule" : "Intercepted exception",
            "chd_FalseIPIParameters" : "False IPI parameters",
            "chd_FalseLuminiscenceError" : "Presence of excess luminescent objects",
            "chd_FalseLuminiscenceInBlank" : "Fake luminescence in UV",
            "chd_FalseLuminiscenceInMRZ" : "Excessive luminescence in MRZ",
            "chd_FibersNotFound" : "Fibers are not found",
            "chd_FieldPosCorrector_Highlight_IR" : "Excessive light in IR",
            "chd_FieldsComparisonLogicError" : "Logical error when comparing fields",
            "chd_FixedPatternError" : "Specified object noncoincidence",
            "chd_HologramElementAbsent" : "Hologram is absent",
            "chd_HologramElementPresent" : "Hologram found",
            "chd_Hologram_Side_Top_Images_Absent" : "No side or top images",
            "chd_IncorrectBackgroundLight" : "Incorrect background brightness",
            "chd_IncorrectTextColor" : "Incorrect text color",
            "chd_InternalError" : "Error of internal data processing",
            "chd_InvalidChecksum" : "Invalid checksum",
            "chd_InvalidFieldFormat" : "The format of the field does not match the description of the document",
            "chd_InvalidInputData" : "Invalid input data",
            "chd_InvisibleElementPresent" : "Object must be invisible",
            "chd_LogicError" : "Logical data error",
            "chd_LowContrastInIRLight" : "Incorrect object contrast in IR light",
            "chd_MobileImages_LowLightConditions" : "Inappropriate light conditions for capturing images",
            "chd_MobileImages_WhileUVNoDifference" : "Low difference between images in different illumination schemes",
            "chd_NecessaryImageNotFound" : "The image required for this check is missing",
            "chd_NotAllBarcodesRead" : "This document should contain more barcodes",
            "chd_OVI_BadColor_Front" : "OVI object color mismatch under white light",
            "chd_OVI_BadColor_Percent" : "Low percentage of coincidence between the OVI elements",
            "chd_OVI_BadColor_Side" : "OVI object color mismatch under axial light",
            "chd_OVI_ColorInvariable" : "OVI color invariable",
            "chd_OVI_IR_Invisible" : "OVI object contrast mismatch",
            "chd_OVI_InsufficientArea" : "Insufficient area of OVI object",
            "chd_OVI_Wide_Color_Spread" : "OVI object color range mismatch",
            "chd_Pass" : "No errors",
            "chd_PhotoFalseLuminiscence" : "False luminescence in the photo area",
            "chd_PhotoPattern_DifferentColors" : "Colors of the pattern on the photo and on the blank are different",
            "chd_PhotoPattern_DifferentLinesThickness" : "Different thickness of the pattern lines",
            "chd_PhotoPattern_IR_Visible" : "Security pattern visible in IR",
            "chd_PhotoPattern_Interrupted" : "The pattern between the photo and the blank has a break",
            "chd_PhotoPattern_InvalidColor" : "Invalid color of the security pattern",
            "chd_PhotoPattern_Not_Intersect" : "The edge of the photo does not intersect with the pattern",
            "chd_PhotoPattern_PatternNotFound" : "Pattern was not found in the photo area",
            "chd_PhotoPattern_Shifted" : "The pattern on the photo is shifted relative to the pattern on the blank",
            "chd_PhotoPattern_Shifted_Vert" : "Pattern lines are vertically shifted relative to each other",
            "chd_PhotoSidesNotFound" : "The required photo border was not found",
            "chd_PhotoSize_Is_Wrong" : "Photo size is incorrect",
            "chd_Photo_Corners_Is_Wrong" : "The corners of the photo do not meet the requirements",
            "chd_Photo_IsNot_Rectangle" : "The shape of the photo is not rectangular",
            "chd_PortraitComparison_NoLivePhoto" : "There is no camera image",
            "chd_PortraitComparison_NoPortraitDetected" : "No face found in the image",
            "chd_PortraitComparison_NoServiceLicense" : "There is no license for the service",
            "chd_PortraitComparison_NoServiceReply" : "The service does not respond",
            "chd_PortraitComparison_NotEnoughImages" : "Not enough images",
            "chd_PortraitComparison_PortraitsDiffer" : "The portraits do not match",
            "chd_PortraitComparison_ServiceError" : "Service error",
            "chd_SourcesComparisonError" : "Noncoincidence of data from different sources",
            "chd_SpecksInUV" : "Overexposure or glares in the image under UV light",
            "chd_SyntaxError" : "Data syntax error",
            "chd_TextColorShouldBeBlue" : "Text color should be blue",
            "chd_TextColorShouldBeGreen" : "Text color should be green",
            "chd_TextColorShouldBeRed" : "Text color should be red",
            "chd_TextShouldBeBlack" : "Text color should be black",
            "chd_TooLowResolution" : "Too low resolution to detect fibers",
            "chd_TooManyObjects" : "Too many objects",
            "chd_TooMuchShift" : "The shift value is greater than the allowed value",
            "chd_TrueLuminiscenceError" : "Noncoincidence of luminescent objects",
            "chd_UVDullPaperError" : "UV dull paper check error",
            "chd_UVDullPaper_Blank" : "UV dull paper check in the area of the blank",
            "chd_UVDullPaper_MRZ" : "UV dull paper check in the MRZ area",
            "chd_UVDullPaper_Photo" : "UV dull paper check in the photo area",
            "chd_UncertainVerification" : "Reliable decision cannot be made",
            "chd_Unknown" : "Unknown denial",
            "chd_VisibleElementAbsent" : "No visible object under IR",
            "strAGY" : "AGY",
            "strAKADateofBirth" : "AKA Date of birth",
            "strAKAGivenNames" : "AKA Given name",
            "strAKANamePrefix" : "AKA Name prefix",
            "strAKANameSuffix" : "AKA Name suffix",
            "strAKASocialSecurityNumber" : "AKA Social Insurance Number",
            "strAKASurname" : "AKA Surname",
            "strAKASurnameAndGivenNames" : "AKA Full name",
            "strALTCode" : "ALT code",
            "strAcademicTitle" : "Academic title",
            "strAccessibilityCameraButton" : "Capture an image and start processing",
            "strAccessibilityCloseButton" : "Close",
            "strAccessibilityTorchButton" : "Torch",
            "strAccompaniedby" : "Accompanied by",
            "strAddress" : "Address",
            "strAddressArea" : "Area",
            "strAddressBuilding" : "Unit",
            "strAddressCity" : "City",
            "strAddressCountry" : "Country",
            "strAddressFlat" : "Apartment",
            "strAddressHouse" : "Building",
            "strAddressJurisdictionCode" : "Jurisdiction code",
            "strAddressLocation" : "Location",
            "strAddressMunicipality" : "Municipality",
            "strAddressPostalCode" : "Postal code",
            "strAddressState" : "State",
            "strAddressStreet" : "Street",
            "strAdministrativeNumber" : "Administrative number",
            "strAge" : "Age",
            "strAgeAtIssue" : "Age at issue",
            "strAirlineDesignatorofboardingpassissuer" : "Airline designator of boarding pass issuer",
            "strAirlineName" : "Airline name",
            "strAirlineNameFrequentFlyer" : "Airline loyalty program for frequent flyers",
            "strAirlineNumericCode" : "Airline numeric code",
            "strAirportFrom" : "Airport of departure",
            "strAirportTo" : "Airport of arrival",
            "strAllergies" : "Allergies",
            "strApplicationDoNotHavePermission" : "The application doesn't have permission to use the camera, please change the privacy settings",
            "strApplicationNumber" : "Application number",
            "strArtisticName" : "Pseudonym",
            "strAuditInformation" : "Number for validation",
            "strAuthentification" : "Authenticity verification",
            "strAuthority" : "Issuing authority",
            "strAuthorityCode" : "Issuing authority code",
            "strAuthorityRUS" : "Issuing authority (National)",
            "strAuthorizationNumber" : "Authorization number",
            "strAxialProtection" : "Retroreflective protection",
            "strBDBType" : "BDB type",
            "strBankCardNumber" : "Bank card number",
            "strBankCardValidThru" : "Bank card validity",
            "strBanknoteNumber" : "Banknote number",
            "strBarcode" : "Barcode",
            "strBarcodeFormatCheck" : "Barcode format check",
            "strBenefitsNumber" : "Benefits number",
            "strBinaryCode" : "Binary code",
            "strBiometricFormatOwner" : "Biometric format owner",
            "strBiometricFormatType" : "Biometric format type",
            "strBiometricProductID" : "Biometric product ID",
            "strBiometricSubtype" : "Biometric subtype",
            "strBiometricType" : "Biometric type",
            "strBlankElement" : "Blank element",
            "strBloodGroup" : "Blood group",
            "strBookletNumber" : "Booklet number",
            "strCCWUntil" : "CCW until",
            "strCDLClass" : "CDL Class",
            "strCSCCode" : "CSC Code",
            "strCVV" : "CVV/CVC",
            "strCaliber" : "Caliber",
            "strCameraUnavailable" : "Camera unavailable",
            "strCardAccessNumber" : "Card access number",
            "strCategory" : "Category",
            "strCenturyDateOfBirth" : "Century of birth",
            "strChassisNumber" : "Chassis number",
            "strCheckInSequenceNumber" : "Check-in sequence number",
            "strChildren" : "Children",
            "strCitizenshipOfFirstPerson" : "Citizenship of the first person",
            "strCitizenshipOfSecondPerson" : "Citizenship of the second person",
            "strCivilStatus" : "Civil status",
            "strColorDynamic" : "Color dynamics",
            "strCommercialVehicleCodes" : "Commercial vehicle code",
            "strCompanyName" : "Company name",
            "strCompartmentCode" : "Compartment code",
            "strComplexion" : "Complexion",
            "strComplianceType" : "Compliance type",
            "strConditions" : "Conditions",
            "strConfiguration" : "Configuration",
            "strControlNo" : "Control number",
            "strCopy" : "Copy",
            "strCourtCode" : "Court code",
            "strCty" : "County",
            "strCurrentDate" : "Current date",
            "strCustodyInfo" : "Custody info",
            "strDFTAppDirectory" : "App directory",
            "strDFTCertificate" : "Certificate",
            "strDG1" : "Machine Readable Zone (DG1)",
            "strDG10" : "not defined (DG10)",
            "strDG11" : "Additional personal detail(s) (DG11)",
            "strDG12" : "Additional document details (DG12)",
            "strDG13" : "Optional detail(s) (DG13)",
            "strDG14" : "EAC info (DG14)",
            "strDG15" : "Active Authentication info (DG15)",
            "strDG16" : "Person(s) to notify (DG16)",
            "strDG17" : "DG17",
            "strDG18" : "DG18",
            "strDG19" : "DG19",
            "strDG2" : "Biometry - Facial data (DG2)",
            "strDG20" : "DG20",
            "strDG3" : "Biometry - Fingerprint(s) (DG3)",
            "strDG4" : "Biometry - Iris Data (DG4)",
            "strDG5" : "Portrait(s) (DG5)",
            "strDG6" : "not defined (DG6)",
            "strDG7" : "Signature / usual mark image (DG7)",
            "strDG8" : "not defined (DG8)",
            "strDG9" : "not defined (DG9)",
            "strDLCDLRestrictionCode" : "CDL Restriction Code",
            "strDLClass" : "DL category",
            "strDLClassCodeA1From" : "DL category A1 valid from",
            "strDLClassCodeA1Notes" : "DL category A1 codes",
            "strDLClassCodeA1To" : "DL category A1 valid to",
            "strDLClassCodeA2From" : "DL category A2 valid from",
            "strDLClassCodeA2Notes" : "DL category A2 codes",
            "strDLClassCodeA2To" : "DL category A2 valid to",
            "strDLClassCodeA3From" : "DL category A3 valid from",
            "strDLClassCodeA3Notes" : "DL category A3 codes",
            "strDLClassCodeA3To" : "DL category A3 valid to",
            "strDLClassCodeAFrom" : "DL category A valid from",
            "strDLClassCodeAMFrom" : "DL category AM valid from",
            "strDLClassCodeAMNotes" : "DL category AM codes",
            "strDLClassCodeAMTo" : "DL category AM valid to",
            "strDLClassCodeANotes" : "DL category A codes",
            "strDLClassCodeATo" : "DL category A valid to",
            "strDLClassCodeB1From" : "DL category B1 valid from",
            "strDLClassCodeB1Notes" : "DL category B1 codes",
            "strDLClassCodeB1To" : "DL category B1 valid to",
            "strDLClassCodeB2EFrom" : "DL category B2E valid from",
            "strDLClassCodeB2ENotes" : "DL category B2E codes",
            "strDLClassCodeB2ETo" : "DL category B2E valid to",
            "strDLClassCodeB2From" : "DL category B2 valid from",
            "strDLClassCodeB2Notes" : "DL category B2 codes",
            "strDLClassCodeB2To" : "DL category B2 valid to",
            "strDLClassCodeBEFrom" : "DL category BE valid from",
            "strDLClassCodeBENotes" : "DL category BE codes",
            "strDLClassCodeBETo" : "DL category BE valid to",
            "strDLClassCodeBFrom" : "DL category B valid from",
            "strDLClassCodeBNotes" : "DL category B codes",
            "strDLClassCodeBTPFrom" : "DL category BTP valid from",
            "strDLClassCodeBTPNotes" : "DL category BTP codes",
            "strDLClassCodeBTPTo" : "DL category BTP valid to",
            "strDLClassCodeBTo" : "DL category B valid to",
            "strDLClassCodeC1EFrom" : "DL category C1E valid from",
            "strDLClassCodeC1ENotes" : "DL category C1E codes",
            "strDLClassCodeC1ETo" : "DL category C1E valid to",
            "strDLClassCodeC1From" : "DL category C1 valid from",
            "strDLClassCodeC1Notes" : "DL category C1 codes",
            "strDLClassCodeC1To" : "DL category C1 valid to",
            "strDLClassCodeC2From" : "DL category C2 valid from",
            "strDLClassCodeC2Notes" : "DL category C2 codes",
            "strDLClassCodeC2To" : "DL category C2 valid to",
            "strDLClassCodeC3From" : "DL category C3 valid from",
            "strDLClassCodeC3Notes" : "DL category C3 codes",
            "strDLClassCodeC3To" : "DL category C3 valid to",
            "strDLClassCodeCAFrom" : "DL category CA valid from",
            "strDLClassCodeCANotes" : "DL category CA codes",
            "strDLClassCodeCATo" : "DL category CA valid to",
            "strDLClassCodeCEFrom" : "DL category CE valid from",
            "strDLClassCodeCENotes" : "DL category CE codes",
            "strDLClassCodeCETo" : "DL category CE valid to",
            "strDLClassCodeCFrom" : "DL category C valid from",
            "strDLClassCodeCNotes" : "DL category C codes",
            "strDLClassCodeCTo" : "DL category C valid to",
            "strDLClassCodeD1EFrom" : "DL category D1E valid from",
            "strDLClassCodeD1ENotes" : "DL category D1E codes",
            "strDLClassCodeD1ETo" : "DL category D1E valid to",
            "strDLClassCodeD1From" : "DL category D1 valid from",
            "strDLClassCodeD1Notes" : "DL category D1 codes",
            "strDLClassCodeD1To" : "DL category D1 valid to",
            "strDLClassCodeD2From" : "DL category D2 valid from",
            "strDLClassCodeD2Notes" : "DL category D2 codes",
            "strDLClassCodeD2To" : "DL category D2 valid to",
            "strDLClassCodeDEFrom" : "DL category DE valid from",
            "strDLClassCodeDENotes" : "DL category DE codes",
            "strDLClassCodeDETo" : "DL category DE valid to",
            "strDLClassCodeDFrom" : "DL category D valid from",
            "strDLClassCodeDNotes" : "DL category D codes",
            "strDLClassCodeDTo" : "DL category D valid to",
            "strDLClassCodeEFrom" : "DL category E valid from",
            "strDLClassCodeENotes" : "DL category E codes",
            "strDLClassCodeETo" : "DL category E valid to",
            "strDLClassCodeFA1From" : "DL category FA1 valid from",
            "strDLClassCodeFA1Notes" : "DL category FA1 codes",
            "strDLClassCodeFA1To" : "DL category FA1 valid to",
            "strDLClassCodeFAFrom" : "DL category FA valid from",
            "strDLClassCodeFANotes" : "DL category FA codes",
            "strDLClassCodeFATo" : "DL category FA valid to",
            "strDLClassCodeFBFrom" : "DL category FB valid from",
            "strDLClassCodeFBNotes" : "DL category FB codes",
            "strDLClassCodeFBTo" : "DL category FB valid to",
            "strDLClassCodeFFrom" : "DL category F valid from",
            "strDLClassCodeFNotes" : "DL category F codes",
            "strDLClassCodeFTo" : "DL category F valid to",
            "strDLClassCodeG1From" : "DL category G1 valid from",
            "strDLClassCodeG1Notes" : "DL category G1 codes",
            "strDLClassCodeG1To" : "DL category G1 valid to",
            "strDLClassCodeGFrom" : "DL category G valid from",
            "strDLClassCodeGNotes" : "DL category G codes",
            "strDLClassCodeGTo" : "DL category G valid to",
            "strDLClassCodeHCFrom" : "DL category HC valid from",
            "strDLClassCodeHCNotes" : "DL category HC codes",
            "strDLClassCodeHCTo" : "DL category HC valid to",
            "strDLClassCodeHFrom" : "DL category H valid from",
            "strDLClassCodeHNotes" : "DL category H codes",
            "strDLClassCodeHRFrom" : "DL category HR valid from",
            "strDLClassCodeHRNotes" : "DL category HR codes",
            "strDLClassCodeHRTo" : "DL category HR valid to",
            "strDLClassCodeHTo" : "DL category H valid to",
            "strDLClassCodeIFrom" : "DL category I valid from",
            "strDLClassCodeINotes" : "DL category I codes",
            "strDLClassCodeITo" : "DL category I valid to",
            "strDLClassCodeJFrom" : "DL category J valid from",
            "strDLClassCodeJNotes" : "DL category J codes",
            "strDLClassCodeJTo" : "DL category J valid to",
            "strDLClassCodeKFrom" : "DL category K valid from",
            "strDLClassCodeKNotes" : "DL category K codes",
            "strDLClassCodeKTo" : "DL category K valid to",
            "strDLClassCodeLCFrom" : "DL category LC valid from",
            "strDLClassCodeLCNotes" : "DL category LC codes",
            "strDLClassCodeLCTo" : "DL category LC valid to",
            "strDLClassCodeLFrom" : "DL category L valid from",
            "strDLClassCodeLKFrom" : "DL category LK valid from",
            "strDLClassCodeLKNotes" : "DL category LK codes",
            "strDLClassCodeLKTo" : "DL category LK valid to",
            "strDLClassCodeLNotes" : "DL category L codes",
            "strDLClassCodeLRFrom" : "DL category LR valid from",
            "strDLClassCodeLRNotes" : "DL category LR codes",
            "strDLClassCodeLRTo" : "DL category LR valid to",
            "strDLClassCodeLTo" : "DL category L valid to",
            "strDLClassCodeMCFrom" : "DL category MC valid from",
            "strDLClassCodeMCNotes" : "DL category MC codes",
            "strDLClassCodeMCTo" : "DL category MC valid to",
            "strDLClassCodeMFrom" : "DL category M valid from",
            "strDLClassCodeMNotes" : "DL category M codes",
            "strDLClassCodeMRFrom" : "DL category MR valid from",
            "strDLClassCodeMRNotes" : "DL category MR codes",
            "strDLClassCodeMRTo" : "DL category MR valid to",
            "strDLClassCodeMTo" : "DL category M valid to",
            "strDLClassCodeNFrom" : "DL category N valid from",
            "strDLClassCodeNNotes" : "DL category N codes",
            "strDLClassCodeNTo" : "DL category N valid to",
            "strDLClassCodeREFrom" : "DL category RE valid from",
            "strDLClassCodeRENotes" : "DL category RE codes",
            "strDLClassCodeRETo" : "DL category RE valid to",
            "strDLClassCodeRFrom" : "DL category R valid from",
            "strDLClassCodeRNotes" : "DL category R codes",
            "strDLClassCodeRTo" : "DL category R valid to",
            "strDLClassCodeSFrom" : "DL category S valid from",
            "strDLClassCodeSNotes" : "DL category S codes",
            "strDLClassCodeSTo" : "DL category S valid to",
            "strDLClassCodeTBFrom" : "DL category TB valid from",
            "strDLClassCodeTBNotes" : "DL category TB codes",
            "strDLClassCodeTBTo" : "DL category TB valid to",
            "strDLClassCodeTFrom" : "DL category T valid from",
            "strDLClassCodeTMFrom" : "DL category TM valid from",
            "strDLClassCodeTMNotes" : "DL category TM codes",
            "strDLClassCodeTMTo" : "DL category TM valid to",
            "strDLClassCodeTNotes" : "DL category T codes",
            "strDLClassCodeTRFrom" : "DL category TR valid from",
            "strDLClassCodeTRNotes" : "DL category TR codes",
            "strDLClassCodeTRTo" : "DL category TR valid to",
            "strDLClassCodeTTo" : "DL category T valid to",
            "strDLClassCodeTVFrom" : "DL category TV valid from",
            "strDLClassCodeTVNotes" : "DL category TV codes",
            "strDLClassCodeTVTo" : "DL category TV valid to",
            "strDLClassCodeVFrom" : "DL category V valid from",
            "strDLClassCodeVNotes" : "DL category V codes",
            "strDLClassCodeVTo" : "DL category V valid to",
            "strDLClassCodeWFrom" : "DL category W valid from",
            "strDLClassCodeWNotes" : "DL category W codes",
            "strDLClassCodeWTo" : "DL category W valid to",
            "strDLDuplicateDate" : "Date of duplicate issue",
            "strDLEndorsed" : "DL endorsement code",
            "strDLIssType" : "Card type",
            "strDLRecordCreated" : "Record created",
            "strDLRestrictionCode" : "DL Restriction Code",
            "strDLUnder18Date" : "Date of 18th birthday",
            "strDLUnder19Date" : "Date of 19th birthday",
            "strDLUnder21Date" : "Date of 21st birthday",
            "strDNINumber" : "DNI number",
            "strDSCertificateIssuer" : "DS certificate issuer",
            "strDSCertificateSubject" : "DS certificate subject",
            "strDSCertificateValidFrom" : "DS certificate valid from",
            "strDSCertificateValidTo" : "DS certificate valid to",
            "strDUFNumber" : "DUF number",
            "strDataDiscriminator" : "Data discriminator",
            "strDateFirstRenewal" : "Date of first renewal",
            "strDateOfBirthOfHusband" : "Date of birth of husband",
            "strDateOfBirthOfWife" : "Date of birth of wife",
            "strDateOfInsuranceExpiry" : "Expiry date of insurance",
            "strDateSecondRenewal" : "Date of second renewal",
            "strDateofBirth" : "Date of birth",
            "strDateofBirthCheckDigit" : "Check digit for date of birth",
            "strDateofBirthChecksum" : "Checksum for date of birth",
            "strDateofCreation" : "Creation date",
            "strDateofExpiry" : "Date of expiry",
            "strDateofExpiryCheckDigit" : "Check digit for date of expiry",
            "strDateofExpiryChecksum" : "Checksum for date of expiry",
            "strDateofFlight" : "Date of flight",
            "strDateofIssue" : "Date of issue",
            "strDateofIssueBoardingPass" : "Date of boarding pass issue",
            "strDateofIssueCheckDigit" : "Check digit for date of issue",
            "strDateofIssueChecksum" : "Checksum for date of issue",
            "strDateofPersonalization" : "Personalization date",
            "strDateofRegistration" : "Date of registration",
            "strDay" : "Day",
            "strDepartment" : "Department",
            "strDeptNumber" : "Department number",
            "strDestination" : "Destination",
            "strDiscretionaryData" : "Discretionary data",
            "strDoDNumber" : "DoD number",
            "strDocumentClassCode" : "Document class code",
            "strDocumentClassName" : "Document class",
            "strDocumentDiscriminator" : "Document discriminator",
            "strDocumentNumber" : "Document number",
            "strDocumentNumberCheckDigit" : "Check digit for document number",
            "strDocumentNumberChecksum" : "Checksum for document number",
            "strDocumentSeries" : "Document series",
            "strDocumentTooSmall" : "Fit the document into the frame",
            "strDonor" : "Donor",
            "strDossierNumber" : "Dossier number",
            "strDurationofStay" : "Duration of stay",
            "strECEnvironmentalType" : "Vehicle environmental type",
            "strEDLDG1" : "Text data elements (DG1)",
            "strEDLDG10" : "not defined (DG10)",
            "strEDLDG11" : "Optional domestic data (DG11)",
            "strEDLDG12" : "Non-match alert (DG12)",
            "strEDLDG13" : "Active Authentication info (DG13)",
            "strEDLDG14" : "EAC info (DG14)",
            "strEDLDG2" : "License holder information (DG2)",
            "strEDLDG3" : "Issuing authority details (DG3)",
            "strEDLDG4" : "Portrait image (DG4)",
            "strEDLDG5" : "Signature / usual mark image (DG5)",
            "strEDLDG6" : "Biometry - Facial data (DG6)",
            "strEDLDG7" : "Biometry - Fingerprint(s) (DG7)",
            "strEDLDG8" : "Biometry - Iris Data (DG8)",
            "strEDLDG9" : "Biometry - Other (DG9)",
            "strEFCOM" : "EF.COM",
            "strEFCVCA" : "EF.CVCA",
            "strEFCardAccess" : "EF.CardAccess",
            "strEFCardSecurity" : "EF.CardSecurity",
            "strEFChipSecurity" : "EF.ChipSecurity",
            "strEFSOD" : "EF.SOD",
            "strEQVCode" : "EQV code",
            "strElectronicTicketIndicator" : "Electronic ticket indicator",
            "strElement" : "Element",
            "strEndorsementExpirationDate" : "Endorsement expiration date",
            "strEngineModel" : "Engine model",
            "strEngineNumber" : "Engine number",
            "strEnginePower" : "Engine power",
            "strEngineVolume" : "Engine volume",
            "strError" : "Error",
            "strExamDate" : "Exam date",
            "strExeptInTanks" : "Except in tanks",
            "strEye" : "Iris",
            "strEyesColor" : "Eye color",
            "strFaculty" : "Faculty",
            "strFalseLuminescence" : "Excessive luminescence",
            "strFamilyName" : "Surname/given name at birth",
            "strFamilyNameTruncation" : "Truncated surname/given name at birth",
            "strFastTrack" : "Fast Track service",
            "strFatherCountryOfBirth" : "Father's country of birth",
            "strFatherDateOfBirth" : "Father's date of birth",
            "strFatherGivenName" : "Father's given name",
            "strFatherPersonalNumber" : "Father's personal number",
            "strFatherPlaceOfBirth" : "Father's place of birth",
            "strFatherSurname" : "Father's surname",
            "strFathersName" : "Father's name",
            "strFathersNameRUS" : "Father's name (National)",
            "strFederalElections" : "Federal elections",
            "strFee" : "Fee",
            "strFieldFromMRZ" : "Field from MRZ",
            "strFieldTypeDocumentImage" : "Document image",
            "strFillElement" : "Filling element",
            "strFinalCheckDigit" : "Final check digit",
            "strFinalChecksum" : "Final checksum",
            "strFingerprint" : "Fingerprint",
            "strFirstIssueDate" : "First issue date",
            "strFirstNameTruncation" : "First name truncation",
            "strFlightNumber" : "Flight number",
            "strFolioNumber" : "Folio number",
            "strFormOfEducation" : "Form of education",
            "strFreeBaggageAllowance" : "Free baggage allowance",
            "strFrequentFlyerAirlineDesignator" : "Frequent flyer airline designator",
            "strFrequentFlyerNumber" : "Frequent flyer number",
            "strFromAirportCode" : "Code of the airport of departure",
            "strFuelType" : "Fuel type",
            "strGNIBNumber" : "GNIB number",
            "strGhostPortrait" : "Ghost portrait",
            "strGivenNames" : "Given name",
            "strGivenNamesRUS" : "Given name (National)",
            "strGlaresOnDocument" : "Avoid glare on the document",
            "strGrandfatherName" : "Grandfather's name",
            "strHairColor" : "Hair color",
            "strHealthNumber" : "Health insurance number",
            "strHeight" : "Height",
            "strHoldDocumentStraight" : "Hold the document straight",
            "strHoloSimple" : "Hologram availability",
            "strHoloVerifyDinamic" : "Verify dynamic hologram",
            "strHoloVerifyMultiStatic" : "Verify Multi Static Hologram",
            "strHoloVerifyStatic" : "Verify Static Hologram",
            "strHolograms" : "Holograms",
            "strIPI" : "IPI (invisible personal information)",
            "strIRB900" : "IR B900 ink",
            "strIRVis" : "IR transparency",
            "strISOIssuerIDNumber" : "ID number of ISO issuer",
            "strIdentifier" : "Identifier",
            "strIdentityCardNumber" : "Identity card number",
            "strIdentityCardNumberCheckDigit" : "Check digit for identity card number",
            "strIdentityCardNumberChecksum" : "Checksum for identity card number",
            "strImagePattern" : "Image patterns",
            "strInTanks" : "In tanks",
            "strInventoryNumber" : "Inventory number",
            "strInvitationNumber" : "Invitation number",
            "strInvitationNumberCheckDigit" : "Check digit for invitation number",
            "strInvitationNumberChecksum" : "Checksum for invitation number",
            "strInvitedBy" : "Invited by",
            "strIssueTimestamp" : "Issue time",
            "strIssuingStateCode" : "Issuing state code",
            "strIssuingStateName" : "Issuing state",
            "strJurisdictionEndorsementCode" : "Jurisdiction endorsement code",
            "strJurisdictionRestrictionCode" : "Jurisdiction restriction code",
            "strJurisdictionVehicleClass" : "Jurisdiction vehicle class",
            "strKeepDeviceStill" : "Hold the device still",
            "strLicenseNumber" : "License number",
            "strLimitedDurationDocumentIndicator" : "Indicator of document limited duration",
            "strLine1CheckDigit" : "Check digit for line 1",
            "strLine1Checksum" : "Checksum for line 1",
            "strLine1OptionalData" : "Optional data from line 1",
            "strLine2CheckDigit" : "Check digit for line 2",
            "strLine2Checksum" : "Checksum for line 2",
            "strLine2OptionalData" : "Optional data from line 2",
            "strLine3CheckDigit" : "Check digit for line 3",
            "strLine3Checksum" : "Checksum for line 3",
            "strLine3OptionalData" : "Optional data from line 3",
            "strLookingDocument" : "Searching for a document...",
            "strMCNoviceDate" : "Expiry date of Motorcycle Novice status",
            "strMRZ" : "MRZ",
            "strMRZLinesICAORFID" : "MRZ lines from ICAO RFID",
            "strMRZString1" : "MRZ line 1",
            "strMRZString2" : "MRZ line 2",
            "strMRZString3" : "MRZ line 3",
            "strMRZStrings" : "MRZ lines",
            "strMRZStringsWithCorrectCheckSums" : "MRZ lines with correct checksums",
            "strMRZType" : "MRZ Type",
            "strMailingAddressCity" : "Mailing address - city",
            "strMailingAddressJurisdictionCode" : "Mailing address - jurisdiction code",
            "strMailingAddressPostalCode" : "Mailing address - postal code",
            "strMailingAddressStreet" : "Mailing address - street",
            "strMake" : "Make",
            "strMaritalStatus" : "Marital status",
            "strMaxMassofTrailerBraked" : "Max mass of trailer (braked)",
            "strMaxMassofTrailerUnbraked" : "Max mass of trailer (unbraked)",
            "strMaxSpeed" : "Max speed",
            "strMedicalIndicatorCodes" : "Medical notes/codes",
            "strMiddleName" : "Middle name",
            "strMiddleNameTruncation" : "Middle name truncation",
            "strMifareData" : "MIFARE data",
            "strMifareValidity" : "MIFARE validity",
            "strMilitaryBookNumber" : "Military ID number",
            "strModel" : "Model",
            "strMonth" : "Month",
            "strMortgageBy" : "Mortgage by",
            "strMotherCountryOfBirth" : "Mother's country of birth",
            "strMotherDateOfBirth" : "Mother's date of birth",
            "strMotherGivenName" : "Mother's given name",
            "strMotherPersonalNumber" : "Mother's personal number",
            "strMotherPlaceOfBirth" : "Mother's place of birth",
            "strMotherSurname" : "Mother's surname",
            "strMothersName" : "Mother's name",
            "strNamePrefix" : "Name prefix",
            "strNameSuffix" : "Name suffix",
            "strNationality" : "Nationality",
            "strNationalityCode" : "Nationality code",
            "strNonResidentIndicator" : "Non-resident indicator",
            "strNone" : "None",
            "strNotDefined" : "Undefined",
            "strNumberOfCardIssuance" : "Number of card issuances",
            "strNumberOfCardIssuanceCheckDigit" : "Check digit for number of card issuances",
            "strNumberOfCardIssuanceChecksum" : "Checksum for number of card issuances",
            "strNumberOfCylinders" : "Number of cylinders",
            "strNumberofAxels" : "Number of axles",
            "strNumberofDuplicates" : "Number of duplicates",
            "strNumberofEntries" : "Number of entries",
            "strNumberofSeats" : "Number of seats",
            "strNumberofStandingPlaces" : "Number of standing places",
            "strOCRNumber" : "OCR number",
            "strOK" : "OK",
            "strObservations" : "Observations",
            "strOldDateOfIssue" : "Old date of issue",
            "strOldDocumentNumber" : "Old document number",
            "strOldPlaceOfIssue" : "Old place of issue",
            "strOptionalData" : "Optional data",
            "strOptionalDataCheckDigit" : "Check digit for optional data",
            "strOptionalDataChecksum" : "Checksum for optional data",
            "strOptionalDetails" : "Optional details",
            "strOrganization" : "Organization",
            "strOther" : "Other",
            "strOtherName" : "Other name",
            "strOtherPersonName" : "Other person, name",
            "strOtherValidID" : "Other valid IDs",
            "strOwner" : "Owner",
            "strPDF417Codec" : "PDF417 codec",
            "strPNRCode" : "PNR code",
            "strParrentsGivenNames" : "Parents' given names",
            "strPassportNumber" : "Passport number",
            "strPassportNumberCheckDigit" : "Check digit for passport number",
            "strPassportNumberChecksum" : "Checksum for passport number",
            "strPatronHeaderVersion" : "Patron header version",
            "strPatternDifferentLinesThickness" : "Comparison of the thickness of the pattern lines",
            "strPatternIRInvisible" : "Invisible pattern in IR",
            "strPatternNotInterrupted" : "No breaks",
            "strPatternNotShifted" : "Pattern elements are not shifted",
            "strPatternSameColors" : "Same colors of the pattern",
            "strPayGrade" : "Pay grade",
            "strPayloadCapacity" : "Payload capacity",
            "strPermissibleAxleLoad" : "Permissible axle load",
            "strPermitDLClass" : "Permit class",
            "strPermitDateofExpiry" : "Permit expiry date",
            "strPermitDateofIssue" : "Permit issue date",
            "strPermitEndorsed" : "Permit endorsement code",
            "strPermitIdentifier" : "Permit identifier",
            "strPermitRestrictionCode" : "Permit restriction code",
            "strPersonToNotifyAddress" : "Notify person: Address",
            "strPersonToNotifyDateofRecord" : "Notify person: Date of record",
            "strPersonToNotifyName" : "Notify person: Name",
            "strPersonToNotifyPhone" : "Notify person: Phone",
            "strPersonalNumber" : "Personal number",
            "strPersonalNumberCheckDigit" : "Check digit for personal number",
            "strPersonalNumberChecksum" : "Checksum for personal number",
            "strPersonalSummary" : "Personal data summary",
            "strPersonalizationSN" : "Serial number of personalization",
            "strPhone" : "Phone",
            "strPhotoArea" : "Photo area",
            "strPhotoColor" : "Color of the photo",
            "strPhotoCorners" : "Corners of the photo",
            "strPhotoElement" : "Photo element",
            "strPhotoEmbedType" : "Photo embedding type",
            "strPhotoProcessing" : "Photo processing...",
            "strPhotoShape" : "Shape of the photo",
            "strPhotoSizeCheck" : "Size check",
            "strPlaceDocumentInFrame" : "Fit the document into the frame",
            "strPlaceOfBirthRUS" : "Place of birth (National)",
            "strPlaceOfBirthStateCode" : "State code of birthplace",
            "strPlaceOfExamination" : "Place of examination",
            "strPlaceOfIssue" : "Place of issue",
            "strPlacePhoneOnDoc" : "Place the phone on the document please",
            "strPlaceofBirth" : "Place of birth",
            "strPlaceofBirthArea" : "Area of birthplace",
            "strPlaceofRegistration" : "Place of registration",
            "strPoliceDistrict" : "Police district",
            "strPortrait" : "Portrait",
            "strPortraitComparison" : "Comparison of the portraits",
            "strPortraitOfChild" : "Portrait of child",
            "strPortraitVSCamera" : "Portrait vs Camera image",
            "strPortraitVSGhost" : "Portrait vs Ghost photo",
            "strPortraitVSRFID" : "Portrait vs RFID chip portrait",
            "strPowerWeightRatio" : "Power-to-weight ratio",
            "strPrecinct" : "Precinct",
            "strPrepareCamera" : "Preparing the camera...",
            "strPresentNextPage" : "Please provide the next page",
            "strPreviousType" : "Type/number of the previous document",
            "strProcessingDocument" : "Document processing...",
            "strProfession" : "Profession",
            "strProfessionalIdNumber" : "Professional ID number",
            "strProofOfCitizenship" : "Proof of citizenship",
            "strPseudoCode" : "Pseudocode",
            "strPurposeOfEntry" : "Purpose of entry",
            "strRFIDVSCamera" : "RFID chip portrait vs Camera image",
            "strRaceEthnicity" : "Race/ethnicity",
            "strRank" : "Rank",
            "strReadingRFID" : "Reading RFID chip data",
            "strReadingRFIDDGiOS" : "Reading RFID %@ data",
            "strRecognizedDocumentType" : "Document type",
            "strReferenceNumber" : "Unique number",
            "strReferenceNumberCheckDigit" : "Unique number check digit",
            "strReferenceNumberChecksum" : "Unique number checksum",
            "strRegCertBodyNumber" : "Body number",
            "strRegCertBodyType" : "Body type",
            "strRegCertCarColor" : "Vehicle color",
            "strRegCertCarMark" : "Vehicle make",
            "strRegCertCarModel" : "Vehicle model",
            "strRegCertCarType" : "Vehicle type",
            "strRegCertMaxWeight" : "Max permissible weight",
            "strRegCertRegNumber" : "Registration number",
            "strRegCertRegNumberCheckDigit" : "Check digit for registration number",
            "strRegCertRegNumberChecksum" : "Checksum for registration number",
            "strRegCertVIN" : "Vehicle identification number",
            "strRegCertVINCheckDigit" : "Check digit for VIN",
            "strRegCertVINChecksum" : "Checksum for VIN",
            "strRegCertVehicleITSCode" : "Vehicle ITS code",
            "strRegCertWeight" : "Unladen mass",
            "strRelationship" : "Relationship",
            "strReligion" : "Religion",
            "strRemainderTerm" : "Months to expire",
            "strResidentFrom" : "Resident from",
            "strResidentUntil" : "Resident until",
            "strRetirementNumber" : "Retirement number",
            "strRevisionDate" : "Revision date",
            "strRoomNumber" : "Room number",
            "strSBHIntegrityOptions" : "SBH integrity options",
            "strSBHSecurityOptions" : "SBH security options",
            "strSeatNumber" : "Seat number",
            "strSecondSurname" : "Second surname",
            "strSection" : "Section",
            "strSecurityText" : "Security text",
            "strSelecteeIndicator" : "Selectee indicator",
            "strSequenceNumber" : "Sequence number",
            "strSerialNumber" : "Serial number",
            "strSettings" : "Settings",
            "strSex" : "Sex",
            "strSignature" : "Signature",
            "strSkinColor" : "Skin color",
            "strSocialSecurityNumber" : "Social insurance number",
            "strSpCode" : "Special code",
            "strSpecialNotes" : "Special notes",
            "strSponsor" : "Sponsor",
            "strSponsorSSN" : "Sponsor SSN",
            "strSponsorService" : "Sponsor service",
            "strSponsorStatus" : "Sponsor status",
            "strStamp" : "Stamp",
            "strStampNumber" : "Stamp number",
            "strStatusDateofExpiry" : "Status Expiry Date",
            "strSurname" : "Surname",
            "strSurnameAndGivenNames" : "Surname and given names",
            "strSurnameAndGivenNamesCheckDigit" : "Check digit for surname and given names",
            "strSurnameAndGivenNamesChecksum" : "Checksum for surname and given names",
            "strSurnameAndGivenNamesRUS" : "Surname and given names (National)",
            "strSurnameAtBirth" : "Surname at birth",
            "strSurnameOfHusbandAfterRegistration" : "Surname of husband after registration",
            "strSurnameOfWifeAfterRegistration" : "Surname of wife after registration",
            "strSurnameofSpose" : "Spouse's surname",
            "strTax" : "Tax",
            "strTaxNumber" : "Tax number",
            "strTelexCode" : "Telegraph code",
            "strTerritorialValidity" : "Territorial validity",
            "strTicketNumber" : "Ticket number",
            "strTitle" : "Position",
            "strToAirportCode" : "Code of the airport of arrival",
            "strTorchUnavailable" : "Torch unavailable",
            "strTrackingNumber" : "Tracking number",
            "strTrailerHitch" : "Trailer hitch",
            "strTransactionNumber" : "Transaction number",
            "strTransmissionType" : "Transmission type",
            "strTypeApprovalNumber" : "Type of approval number",
            "strURL" : "URL",
            "strUSCIS" : "USCIS",
            "strUV" : "UV",
            "strUVFibers" : "UV security fibers",
            "strUVLuminescence" : "UV dull paper check",
            "strUnableCaptureMedia" : "Camera configuration failed",
            "strUniqueCustomerIdentifier" : "Unique customer identifier",
            "strVRCDataObjectEntry" : "Vehicle data from the DG1 data group",
            "strValidityPeriod" : "Validity period",
            "strVehicleCategory" : "Vehicle category",
            "strVeteran" : "Veteran",
            "strVisaClass" : "Visa Class",
            "strVisaID" : "Visa ID",
            "strVisaIDCheckDigit" : "Check digit for visa ID",
            "strVisaIDChecksum" : "Checksum for visa ID",
            "strVisaIDRUS" : "Visa ID (National)",
            "strVisaNumber" : "Visa Number",
            "strVisaNumberCheckDigit" : "Check digit for visa number",
            "strVisaNumberChecksum" : "Checksum for visa number",
            "strVisaSubClass" : "Visa subclass",
            "strVisaType" : "Visa type",
            "strVisaValidFrom" : "Visa valid from",
            "strVisaValidUntil" : "Visa valid until",
            "strVisaValidUntilCheckDigit" : "Check digit for visa expiry date",
            "strVisaValidUntilChecksum" : "Checksum for visa expiry date",
            "strVisibleLight" : "Visible light",
            "strVoter" : "Voter",
            "strVoterKey" : "Voter Key",
            "strVoucherNumber" : "Voucher number",
            "strWeight" : "Weight",
            "strWeightPound" : "Weight (pound)",
            "strYear" : "Year",
            "strYearsSinceIssue" : "Years since issue",
            "streIDPlaceOfBirthCity" : "Place of Birth: City",
            "streIDPlaceOfBirthCountry" : "Place of Birth: Country",
            "streIDPlaceOfBirthState" : "Place of Birth: State",
            "streIDPlaceOfBirthStreet" : "Place of Birth: Street",
            "streIDPlaceOfBirthZipcode" : "Place of Birth: Postal code",
            "streIDResidencePermit1" : "Residence permit 1",
            "streIDResidencePermit2" : "Residence permit 2",
            "strfppLeftIndexFinger" : "Left index finger",
            "strfppLeftLittleFinger" : "Left little finger",
            "strfppLeftMiddleFinger" : "Left middle finger",
            "strfppLeftRingFinger" : "Left ring finger",
            "strfppLeftThumb" : "Left thumb",
            "strfppRightIndexFinger" : "Right index finger",
            "strfppRightLittleFinger" : "Right little finger",
            "strfppRightMiddleFinger" : "Right middle finger",
            "strfppRightRingFinger" : "Right ring finger",
            "strfppRightThumb" : "Right thumb",
        ]
    }
}
