
//
// File.swift
//
//
// Created by MOBILE on 20/05/24.
//
import Foundation
class FrenchDataValues {
func getDictionary() -> [String: String] {
return [



"RFID_Error_Session_AccessControl_RequiresPACE" : "RFID: Requires PACE",
"RFID_Error_Session_AccessControl_RequiresSM"
: "RFID: Requires SM",
"RFID_Error_Session_AccessControl_RequiresTA"
: "RFID: Requires TA",
"RFID_Error_Session_AccessControl_TA_Failed" :
"RFID: TA Failed",
"RFID_Error_Session_AccessControl_UnknownType"
: "RFID: Access Control UnknownType",
"RFID_Error_Session_AccessKey_IncorrectData" :
"RFID: Access Key Incorrect Data",
"RFID_Error_Session_AccessKey_IncorrectSMType"
: "RFID: Access Key Incorrect SM Type",
"RFID_Error_Session_AccessKey_NotSet" : "RFID:Access Key Not Set",
"RFID_Error_Session_AccessKey_Restricted" :
"RFID: Access Key Restricted",
"RFID_Error_Session_AccessKey_UnknownType" :
"RFID: Access Key Unknown Type",
"RFID_Error_Session_AccessKey_UnsupportedSMType" : "RFID: Access Key Unsupported SM Type",
"RFID_Error_Session_File_AccessDenied" : "RFID File: Access Denied",
"RFID_Error_Session_File_CantReadData" : "RFID File: Cannot Read Data",
"RFID_Error_Session_File_CantUseData" : "RFID File: Cannot Use Data",
"RFID_Error_Session_File_Contents_UnexpectedData" : "RFID File: Contents Unexpected Data",
"RFID_Error_Session_File_IncorrectData" :
"RFID File: Incorrect Data",
"RFID_Error_Session_File_NotEnoughData" :
"RFID File: Not Enough Data",
"RFID_Error_Session_File_UnexpectedData" :
"RFID File: Unexpected Data",
"RFID_Error_Session_File_WrongTag" : "RFID File: Wrong Tag",
"RFID_Error_Session_IncorrectData" : "RFID: Incorrect data",
"RFID_Error_Session_InvalidAuxData_CommunityID" : "RFID: Invalid Aux Data Community ID",
"RFID_Error_Session_InvalidAuxData_DateOfBirth" : "RFID: Invalid Aux Data Date Of Birth",
"RFID_Error_Session_InvalidAuxData_DateOfExpiry" : "RFID: Invalid Aux Data Date Of Expiry",
"RFID_Error_Session_IsClosed" :
"RFID: Session Is Closed",
"RFID_Error_Session_PA_HashCheckFailed" :
"RFID: Hash Check Failed" ,
"RFID_Error_AlreadyDone" : "RFID : L'opération demandée est déjà effectuée",
"RFID_Error_Busy" : "RFID : RFID est occupé",
"RFID_Error_Failed" : "RFID : Échec",
"RFID_Error_FileIOError" : "RFID Fichier : Erreur d'E/S",
"RFID_Error_InvalidDirectory" : "RFID : Répertoire invalide",
"RFID_Error_InvalidParameter" : "RFID : Paramètre invalide trouvé dans l'appel ExecuteCommand()",
"RFID_Error_NoChipDetected" : "RFID : Aucune puce détectée",
"RFID_Error_NotAvailable" : "RFID : Non disponible",
"RFID_Error_NotEnoughMemory" : "RFID : Mémoire insuffisante",
"RFID_Error_NotInitialized" : "RFID : Le périphérique n'est pas initialisé",
"RFID_Error_NotPerformed" : "RFID : Non effectué",
"RFID_Error_OldFirmware" : "RFID : Le firmware doit être mis à jour avec une version plus récente",
"RFID_Error_PCSC_CantConnectCard" : "PCSC : La carte ne peut pas être connectée",
"RFID_Error_PCSC_CardIsBusy" : "PCSC : La carte est occupée",
"RFID_Error_PCSC_CardIsNotConnected" : "PCSC : La carte n'est pas connectée",
"RFID_Error_PCSC_ExtLe_Failed" : "PCSC : ExtLe a échoué",
"RFID_Error_PCSC_Failed" : "PCSC : Échec",
"RFID_Error_PCSC_FailedSCard" : "PCSC : Échec de la carte intelligente",
"RFID_Error_PCSC_OperationCancelled" : "PCSC : L'opération est annulée",
"RFID_Error_PCSC_ReaderNotAvailable" : "PCSC : Le lecteur n'est pas disponible",
"RFID_Error_Session_AccessControl_AA_Failed" : "RFID : AA a échoué",
"RFID_Error_Session_AccessControl_CA_Failed" : "RFID : CA a échoué",
"RFID_Error_Session_AccessControl_IncorrectOptionCA" : "RFID : Option CA incorrecte",
"RFID_Error_Session_AccessControl_RI_Failed" : "RFID : RI a échoué",
"RFID_Error_Session_AccessControl_RequiresCA" : "RFID : Nécessite CA",
"RFID_Error_Session_AccessControl_RequiresCAKeys" : "RFID : Nécessite des clés CA",
"RFID_Error_Session_PA_SignatureCheckFailed" : "RFID : Vérification de la signature SO échouée",
"RFID_Error_Session_ProcedureType_NotSet" : "RFID : Type de procédure non défini",
"RFID_Error_Session_ProcedureType_Unknown" : "RFID : Type de procédure inconnu",
"RFID_Error_Session_ProcedureType_Unsupported" : "RFID : Type de procédure non pris en charge",
"RFID_Error_Session_PwdManagement_NotAuthorized" : "RFID : Gestion des mots de passe non autorisée",
"RFID_Error_Session_TerminalType_BadCertificate" : "RFID : Type de terminal Certificat incorrect",
"RFID_Error_Session_TerminalType_NotSet" : "RFID : Type de terminal non défini",
"RFID_Error_Session_TerminalType_Unknown" : "RFID : Type de terminal inconnu",
"RFID_Error_Session_Terminal_UnsupportedOperation" : "RFID : Opération de terminal non prise en charge",
"RFID_Error_Session_eSign_PIN_NotSet" : "RFID : PIN eSign non défini",
"RFID_Error_Session_eSign_PIN_NotVerified" : "RFID : PIN eSign non vérifié",
"RFID_Error_Session_eSign_RequiresAppSelection" : "RFID : eSign nécessite une sélection d'application",
"RFID_Error_UnknownCommand" : "RFID : Commande inconnue",
"RFID_LAYER6_APP_SELECTION_FAILURE" : "LAYER6 : ISO7816_A_03 \"Échec de la sélection de l'application\"",
"RFID_LAYER6_EXT_AUTH_FAILURE" : "LAYER6 : APDU_INS_EXTERNAL_AUTHENTICATE (Authentification externe) échec",
"RFID_LAYER6_FILE_EOF1" : "LAYER6 : Lecture au-delà de la fin du fichier / Fin de fichier inattendue",
"RFID_LAYER6_FILE_EOF2" : "LAYER6 : Lecture au-delà de la fin du fichier / Fin de fichier inattendue",
"RFID_LAYER6_FILE_NOT_FOUND" : "LAYER6 : Échec de la sélection du fichier / fichier non trouvé",
"RFID_LAYER6_GENERAL_AUTH_FAILURE" : "LAYER6 : Échec général de l'authenticité",
"RFID_LAYER6_GET_CHALLENGE_FAILURE" : "LAYER6 : Échec GET CHALLENGE",
"RFID_LAYER6_INCORRECT_PARAMS" : "LAYER6 : Paramètres incorrects",
"RFID_LAYER6_INT_AUTH_FAILURE" : "LAYER6 : APDU_INS_INTERNAL_AUTHENTICATE échec",
"RFID_LAYER6_MSE_SET_AT_FAILURE" : "LAYER6 : MSE: Définition AT échouée",
"RFID_LAYER6_MSE_SET_DST_FAILURE" : "LAYER6 : MSE: Définition DST échouée",
"RFID_LAYER6_MSE_SET_KAT_FAILURE" : "LAYER6 : MSE: Définition KAT échouée",
"RFID_LAYER6_MUTUAL_AUTH_ENC_FAIL" : "LAYER6 : ISO7816_B_02\"Échec de l'authentification mutuelle par chiffrement\"",
"RFID_LAYER6_MUTUAL_AUTH_FAILURE" : "LAYER6 : Échec de l'authentification mutuelle",
"RFID_LAYER6_MUTUAL_AUTH_MAC_FAIL" : "LAYER6 : Échec de l'authentification mutuelle par MAC",
"RFID_LAYER6_NON_TLV_RESPONSE_DATA" : "LAYER6 : Données de réponse non TLV",
"RFID_LAYER6_NO_REFERENCE_DATA" : "LAYER6 : Pas de données de référence",
"RFID_LAYER6_PSO_CERTIFICATE_FAILURE" : "LAYER6 : Échec de certificat PSO",
"RFID_LAYER6_PWD_BLOCKED" : "LAYER6 : Mot de passe bloqué",
"RFID_LAYER6_PWD_BLOCKED_2" : "LAYER6 : Mot de passe bloqué 2",
"RFID_LAYER6_PWD_DEACTIVATED" : "LAYER6 : Mot de passe désactivé",
"RFID_LAYER6_PWD_DEACTIVATED_2" : "LAYER6 : Mot de passe désactivé 2",
"RFID_LAYER6_PWD_FAILED" : "LAYER6 : Mot de passe incorrect",
"RFID_LAYER6_PWD_SUSPENDED" : "LAYER6 : Mot de passe suspendu",
"RFID_LAYER6_PWD_SUSPENDED_2" : "LAYER6 : Mot de passe suspendu 2",
"RFID_LAYER6_SECURITY_MANAGER" : "LAYER6 : La messagerie sécurisée n'a pas été activée",
"RFID_LAYER6_SM_DO87_INCORRECT" : "LAYER6 : Échec SM - cryptogramme incorrect",
"RFID_LAYER6_SM_DO87_MISSING" : "LAYER6 : Échec SM - cryptogramme manquant",
"RFID_LAYER6_SM_DO8E_MISSING" : "LAYER6 : Échec SM - MAC manquant",
"RFID_LAYER6_SM_DO99_MISSING" : "LAYER6 : Échec SM - octets d'état sécurisés manquants",
"RFID_LAYER6_SM_MAC_INCORRECT" : "LAYER6 : Échec SM - MAC incorrect",
"RFID_LAYER6_WRONG_RND_ICC_LENGTH" : "LAYER6 : Longueur de données incorrecte (APDU_INS_GET_CHALLENGE)",
"RSDT_RFID_READING_FINISHED" : "La lecture des données RFID est terminée",
"TCT_Unknown" : "Inconnu",
"chd_BackgroundComparisonError" : "La luminosité des deux pages est différente",
"chd_BadAreaInAxial" : "Échec de la protection rétro-réfléchissante",
"chd_BarcodeDataFormatError" : "Erreur de format de code-barres",
"chd_BarcodeReadedWithErrors" : "Le code-barres a été lu avec des erreurs",
"chd_BarcodeSizeParamsError" : "Erreur de paramètres de taille de code- barres",
"chd_DocumentIsCancelling" : "Le document est annulé",
"chd_ElementShouldBeColored" : "L'élément doit être coloré",
"chd_ElementShouldBeGrayscale" : "L'élément doit être en niveaux de gris",
"chd_ExceptionInModule" : "Exception interceptée",
"chd_FalseIPIParameters" : "Faux paramètres IPI",
"chd_FalseLuminiscenceError" : "Présence d'objets luminescents en excès",
"chd_FalseLuminiscenceInBlank" : "Luminescence artificielle en UV",
"chd_FalseLuminiscenceInMRZ" : "Luminescence excessive dans la zone MRZ",
"chd_FibersNotFound" : "Les fibres ne sont pas trouvées",
"chd_FieldPosCorrector_Highlight_IR" : "Lumière excessive en infrarouge",
"chd_FieldsComparisonLogicError" : "Erreur logique lors de la comparaison des champs",
"chd_FixedPatternError" : "Non-coïncidence de l'objet spécifié",
"chd_HologramElementAbsent" : "Hologramme absent",
"chd_HologramElementPresent" : "Hologramme trouvé",
"chd_Hologram_Side_Top_Images_Absent" : "Pas d'images latérales ou supérieures",
"chd_IncorrectBackgroundLight" : "Luminosité de fond incorrecte",
"chd_IncorrectTextColor" : "Couleur de texte incorrecte",
"chd_InternalError" : "Erreur de traitement des données internes",
"chd_InvalidChecksum" : "Checksum invalide",
"chd_InvalidFieldFormat" : "Le format du champ ne correspond pas à la description du document",
"chd_InvalidInputData" : "Données d'entrée invalides",
"chd_InvisibleElementPresent" : "L'objet doit être invisible",
"chd_LogicError" : "Erreur logique des données",
"chd_LowContrastInIRLight" : "Contraste incorrect de l'objet en lumière infrarouge",
"chd_MobileImages_LowLightConditions" : "Conditions lumineuses inappropriées pour la capture d'images",
"chd_MobileImages_WhileUVNoDifference" : "Faible différence entre les images dans différents schémas d'éclairage",
"chd_NecessaryImageNotFound" : "L'image requise pour cette vérification est manquante",
"chd_NotAllBarcodesRead" : "Ce document devrait contenir plus de codes- barres",
"chd_OVI_BadColor_Front" : "Incompatibilité de couleur d'objet OVI sous lumière blanche",
"chd_OVI_BadColor_Percent" : "Faible pourcentage de coïncidence entre les éléments OVI",
"chd_OVI_BadColor_Side" : "Incompatibilité de couleur d'objet OVI sous lumière axiale",
"chd_OVI_ColorInvariable" : "Couleur OVI invariable",
"chd_OVI_IR_Invisible" : "Incompatibilité de contraste d'objet OVI",
"chd_OVI_InsufficientArea" : "Surface insuffisante de l'objet OVI",
"chd_OVI_Wide_Color_Spread" : "Plage de couleur d'objet OVI incompatible",
"chd_Pass" : "Aucune erreur",
"chd_PhotoFalseLuminiscence" : "Fausse luminescence dans la zone de la photo",
"chd_PhotoPattern_DifferentColors" : "Couleurs du motif sur la photo et sur le document différents",
"chd_PhotoPattern_DifferentLinesThickness" : "Épaisseur différente des lignes du motif",
"chd_PhotoPattern_IR_Visible" : "Motif de sécurité visible en infrarouge",
"chd_PhotoPattern_Interrupted" : "Le motif entre la photo et le document présente une interruption",
"chd_PhotoPattern_InvalidColor" : "Couleur invalide du motif de sécurité",
"chd_PhotoPattern_Not_Intersect" : "Le bord de la photo ne croise pas le motif",
"chd_PhotoPattern_PatternNotFound" : "Le motif n'a pas été trouvé dans la zone de la photo",
"chd_PhotoPattern_Shifted" : "Le motif sur la photo est décalé par rapport au motif sur le document",
"chd_PhotoPattern_Shifted_Vert" : "Les lignes du motif sont décalées verticalement les unes par rapport aux autres",
"chd_PhotoSidesNotFound" : "La bordure de la photo requise n'a pas été trouvée",
"chd_PhotoSize_Is_Wrong" : "La taille de la photo est incorrecte",
"chd_Photo_Corners_Is_Wrong" : "Les coins de la photo ne répondent pas aux exigences",
"chd_Photo_IsNot_Rectangle" : "La forme de la photo n'est pas rectangulaire",
"chd_PortraitComparison_NoLivePhoto" : "Il n'y a pas d'image de caméra",
"chd_PortraitComparison_NoPortraitDetected" : "Aucun visage trouvé dans l'image",
"chd_PortraitComparison_NoServiceLicense" : "Il n'y a pas de licence pour le service",
"chd_PortraitComparison_NoServiceReply" : "Le service ne répond pas",
"chd_PortraitComparison_NotEnoughImages" : "Pas assez d'images",
"chd_PortraitComparison_PortraitsDiffer" : "Les portraits ne correspondent pas",
"chd_PortraitComparison_ServiceError" : "Erreur de service",
"chd_SourcesComparisonError" : "Non-coïncidence des données provenant de différentes sources",
"chd_SpecksInUV" : "Surimpression ou reflets dans l'image sous lumière UV",
"chd_SyntaxError" : "Erreur de syntaxe des données",
"chd_TextColorShouldBeBlue" : "La couleur du texte devrait être bleue",
"chd_TextColorShouldBeGreen" : "La couleur du texte devrait être verte",
"chd_TextColorShouldBeRed" : "La couleur du texte devrait être rouge",
"chd_TextShouldBeBlack" : "La couleur du texte devrait être noire",
"chd_TooLowResolution" : "Résolution trop basse pour détecter les fibres",
"chd_TooManyObjects" : "Trop d'objets",
"chd_TooMuchShift" : "La valeur de décalage est supérieure à la valeur autorisée",
"chd_TrueLuminiscenceError" : "Erreur de luminiscence réelle",
"Noncoincidence of luminescent objects" : "Non-coïncidence des objets luminescents",
"chd_UVDullPaperError" : "Erreur de vérification du papier UV terne",
"chd_UVDullPaper_Blank" : "Vérification du papier UV terne dans la zone du document",
"chd_UVDullPaper_MRZ" : "Vérification du papier UV terne dans la zone MRZ",
"chd_UVDullPaper_Photo" : "Vérification du papier UV terne dans la zone de la photo",
"chd_UncertainVerification" : "Décision fiable ne pouvant être prise",
"chd_Unknown" : "Refus inconnu",
"chd_VisibleElementAbsent" : "Aucun objet visible sous IR",
"strAGY" : "AGY",
"strAKADateofBirth" : "Date de naissance AKA",
"strAKAGivenNames" : "Prénoms AKA",
"strAKANamePrefix" : "Préfixe de nom AKA",
"strAKANameSuffix" : "Suffixe de nom AKA",
"strAKASocialSecurityNumber" : "Numéro d'assurance sociale AKA",
"strAKASurname" : "Nom de famille AKA",
"strAKASurnameAndGivenNames" : "Nom complet AKA",
"strALTCode" : "Code ALT",
"strAcademicTitle" : "Titre académique",
"strAccessibilityCameraButton" : "Capturer une image et commencer le traitement",
"strAccessibilityCloseButton" : "Fermer",
"strAccessibilityTorchButton" : "Lampe de poche",
"strAccompaniedby" : "Accompagné par",
"strAddress" : "Adresse",
"strAddressArea" : "Zone",
"strAddressBuilding" : "Unité",
"strAddressCity" : "Ville",
"strAddressCountry" : "Pays",
"strAddressFlat" : "Appartement",
"strAddressHouse" : "Bâtiment",
"strAddressJurisdictionCode" : "Code de juridiction",
"strAddressLocation" : "Emplacement",
"strAddressMunicipality" : "Municipalité",
"strAddressPostalCode" : "Code postal",
"strAddressState" : "État",
"strAddressStreet" : "Rue",
"strAdministrativeNumber" : "Numéro administratif",
"strAge" : "Âge",
"strAgeAtIssue" : "Âge au moment de la délivrance",
"strAirlineDesignatorofboardingpassissuer" : "Désignateur de compagnie aérienne de l'émetteur du billet",
"strAirlineName" : "Nom de la compagnie aérienne",
"strAirlineNameFrequentFlyer" : "Programme de fidélité de la compagnie aérienne pour les voyageurs fréquents",
"strAirlineNumericCode" : "Code numérique de la compagnie aérienne",
"strAirportFrom" : "Aéroport de départ",
"strAirportTo" : "Aéroport d'arrivée",
"strAllergies" : "Allergies",
"strApplicationDoNotHavePermission" : "L'application n'a pas l'autorisation d'utiliser l'appareil photo, veuillez modifier les paramètres de confidentialité",
"strApplicationNumber" : "Numéro de l'application",
"strArtisticName" : "Pseudonyme",
"strAuditInformation" : "Numéro de validation",
"strAuthentification" : "Vérification de l'authenticité",
"strAuthority" : "Autorité émettrice",
"strAuthorityCode" : "Code de l'autorité émettrice",
"strAuthorityRUS" : "Autorité émettrice (National)",
"strAuthorizationNumber" : "Numéro d'autorisation",
"strAxialProtection" : "Protection rétro réfléchissante",
"strBDBType" : "Type de BDB",
"strBankCardNumber" : "Numéro de carte bancaire",
"strBankCardValidThru" : "Validité de la carte bancaire",
"strBanknoteNumber" : "Numéro de billet de banque",
"strBarcode" : "Code-barres",
"strBarcodeFormatCheck" : "Vérification du format du code-barres",
"strBenefitsNumber" : "Numéro d'avantages",
"strBinaryCode" : "Code binaire",
"strBiometricFormatOwner" : "Propriétaire du format biométrique",
"strBiometricFormatType" : "Type de format biométrique",
"strBiometricProductID" : "Identifiant du produit biométrique",
"strBiometricSubtype" : "Sous-type biométrique",
"strBiometricType" : "Type biométrique",
"strBlankElement" : "Élément vierge",
"strBloodGroup" : "Groupe sanguin",
"strBookletNumber" : "Numéro du livret",
"strCCWUntil" : "Dans le sens antihoraire jusqu'à",
"strCDLClass" : "Classe de CDL",
"strCSCCode" : "Code CSC",
"strCVV" : "CVV/CVC",
"strCaliber" : "Calibre",
"strCameraUnavailable" : "Caméra non disponible",
"strCardAccessNumber" : "Numéro d'accès à la carte",
"strCategory" : "Catégorie",
"strCenturyDateOfBirth" : "Siècle de naissance",
"strChassisNumber" : "Numéro de châssis",
"strCheckInSequenceNumber" : "Numéro de séquence d'enregistrement",
"strChildren" : "Enfants",
"strCitizenshipOfFirstPerson" : "Citoyenneté du premier individu",
"strCitizenshipOfSecondPerson" : "Citoyenneté du deuxième individu",
"strCivilStatus" : "État civil",
"strColorDynamic" : "Dynamique de couleur",
"strCommercialVehicleCodes" : "Codes de véhicules commerciaux",
"strCompanyName" : "Nom de l'entreprise",
"strCompartmentCode" : "Code du compartiment",
"strComplexion" : "Teint",
"strComplianceType" : "Type de conformité",
"strConditions" : "Conditions",
"strConfiguration" : "Configuration",
"strControlNo" : "Numéro de contrôle",
"strCopy" : "Copie",
"strCourtCode" : "Code du tribunal",
"strCty" : "Comté",
"strCurrentDate" : "Date actuelle",
"strCustodyInfo" : "Informations de garde",
"strDFTAppDirectory" : "Répertoire de l'application",
"strDFTCertificate" : "Certificat",
"strDG1" : "Zone lisible par machine (DG1)",
"strDG10" : "non défini (DG10)",
"strDG11" : "Détail(s) personnel(s) supplémentaire(s) (DG11)",
"strDG12" : "Détails supplémentaires du document (DG12)",
"strDG13" : "Détail(s) facultatif(s) (DG13)",
"strDG14" : "Infos EAC (DG14)",
"strDG15" : "Infos d'authentification active (DG15)",
"strDG16" : "Personne(s) à notifier (DG16)",
"strDG17" : "DG17",
"strDG18" : "DG18",
"strDG19" : "DG19",
"strDG2" : "Biométrie - Données faciales (DG2)",
"strDG20" : "DG20",
"strDG3" : "Biométrie - Empreinte(s) digitale(s) (DG3)",
"strDG4" : "Biométrie - Données de l'iris (DG4)" ,
"strDG5" : "Portraits (DG5)",
"strDG6" : "non défini (DG6)",
"strDG7" : "Signature / image de marque habituelle (DG7)",
"strDG8" : "non défini (DG8)",
"strDG9" : "non défini (DG9)",
"strDLCDLRestrictionCode" : "Code de restriction de la CDL",
"strDLClass" : "Catégorie de permis de conduire",
"strDLClassCodeA1From" : "Catégorie A1 du permis de conduire valide à partir de",
"strDLClassCodeA1Notes" : "Codes de catégorie A1 du permis de conduire",
"strDLClassCodeA1To" : "Catégorie A1 du permis de conduire valide jusqu'à",
"strDLClassCodeA2From" : "Catégorie A2 du permis de conduire valide à partir de",
"strDLClassCodeA2Notes" : "Codes de catégorie A2 du permis de conduire",
"strDLClassCodeA2To" : "Catégorie A2 du permis de conduire valide jusqu'à",
"strDLClassCodeA3From" : "Catégorie A3 du permis de conduire valide à partir de",
"strDLClassCodeA3Notes" : "Codes de catégorie A3 du permis de conduire",
"strDLClassCodeA3To" : "Catégorie A3 du permis de conduire valide jusqu'à",
"strDLClassCodeAFrom" : "Catégorie A du permis de conduire valide à partir de",
"strDLClassCodeAMFrom" : "Catégorie AM du permis de conduire valide à partir de",
"strDLClassCodeAMNotes" : "Codes de catégorie AM du permis de conduire",
"strDLClassCodeAMTo" : "Catégorie AM du permis de conduire valide jusqu'à",
"strDLClassCodeANotes" : "Codes de catégorie A du permis de conduire",
"strDLClassCodeATo" : "Catégorie A du permis de conduire valide jusqu'à",
"strDLClassCodeB1From": "Permis B1 valide à partir de",
"strDLClassCodeB1Notes": "Codes de catégorie B1",
"strDLClassCodeB1To": "Permis B1 valide jusqu'à",
"strDLClassCodeB2EFrom": "Permis B2E valide à partir de",
"strDLClassCodeB2ENotes": "Codes de catégorie B2E",
"strDLClassCodeB2ETo": "Permis B2E valide jusqu'à",
"strDLClassCodeB2From": "Permis B2 valide à partir de",
"strDLClassCodeB2Notes": "Codes de catégorie B2",
"strDLClassCodeB2To": "Permis B2 valide jusqu'à",
"strDLClassCodeBEFrom": "Permis BE valide à partir de",
"strDLClassCodeBENotes": "Codes de catégorie BE",
"strDLClassCodeBETo": "Permis BE valide jusqu'à",
"strDLClassCodeBFrom": "Permis B valide à partir de",
"strDLClassCodeBNotes": "Codes de catégorie B",
"strDLClassCodeBTPFrom": "Permis BTP valide à partir de",
"strDLClassCodeBTPNotes": "Codes de catégorie BTP",
"strDLClassCodeBTPTo": "Permis BTP valide jusqu'à",
"strDLClassCodeBTo": "Permis B valide jusqu'à",
"strDLClassCodeC1EFrom": "Permis C1E valide à partir de",
"strDLClassCodeC1ENotes": "Codes de catégorie C1E",
"strDLClassCodeC1ETo": "Permis C1E valide jusqu'à",
"strDLClassCodeC1From": "Permis C1 valide à partir de",
"strDLClassCodeC1Notes": "Codes de catégorie C1",
"strDLClassCodeC1To": "Permis C1 valide jusqu'à",
"strDLClassCodeC2From": "Permis C2 valide à partir de",
"strDLClassCodeC2Notes": "Codes de catégorie C2",
"strDLClassCodeC2To": "Permis C2 valide jusqu'à",
"strDLClassCodeC3From": "Permis C3 valide à partir de",
"strDLClassCodeC3Notes": "Codes de catégorie C3",
"strDLClassCodeC3To": "Permis C3 valide jusqu'à",
"strDLClassCodeCAFrom": "Permis CA valide à partir de",
"strDLClassCodeCANotes": "Codes de catégorie CA",
"strDLClassCodeCATo": "Permis CA valide jusqu'à",
"strDLClassCodeCEFrom": "Permis CE valide à partir de",
"strDLClassCodeCENotes": "Codes de catégorie CE",
"strDLClassCodeCETo": "Permis CE valide jusqu'à",
"strDLClassCodeCFrom": "Permis C valide à partir de",
"strDLClassCodeCNotes": "Codes de catégorie C",
"strDLClassCodeCTo": "Permis C valide jusqu'à",
"strDLClassCodeD1EFrom": "Permis D1E valide à partir de",
"strDLClassCodeD1ENotes": "Codes de catégorie D1E",
"strDLClassCodeD1ETo": "Permis D1E valide jusqu'à",
"strDLClassCodeD1From": "Permis D1 valide à partir de",
"strDLClassCodeD1Notes": "Codes de catégorie D1",
"strDLClassCodeD1To": "Permis D1 valide jusqu'à",
"strDLClassCodeD2From": "Permis D2 valide à partir de",
"strDLClassCodeD2Notes": "Codes de catégorie D2",
"strDLClassCodeD2To": "Permis D2 valide jusqu'à",
"strDLClassCodeDEFrom": "Permis DE valide à partir de",
"strDLClassCodeDENotes": "Codes de catégorie DE",
"strDLClassCodeDETo": "Permis DE valide jusqu'à",
"strDLClassCodeDFrom": "Permis D valide à partir de",
"strDLClassCodeDNotes": "Codes de catégorie D",
"strDLClassCodeDTo": "Permis D valide jusqu'à",
"strDLClassCodeEFrom": "Permis E valide à partir de",
"strDLClassCodeENotes": "Codes de catégorie E",
"strDLClassCodeETo": "Permis E valide jusqu'à",
"strDLClassCodeFA1From": "Permis FA1 valide à partir de",
"strDLClassCodeFA1Notes": "Codes de catégorie FA1",
"strDLClassCodeFA1To": "Permis FA1 valide jusqu'à",
"strDLClassCodeFAFrom": "Permis FA valide à partir de",
"strDLClassCodeFANotes": "Codes de catégorie FA",
"strDLClassCodeFATo": "Permis FA valide jusqu'à",
"strDLClassCodeFBFrom": "Permis FB valide à partir de",
"strDLClassCodeFBNotes": "Codes de catégorie FB",
"strDLClassCodeFBTo": "Permis FB valide jusqu'à",
"strDLClassCodeFFrom": "Permis F valide à partir de",
"strDLClassCodeFNotes": "Codes de catégorie F",
"strDLClassCodeFTo": "Permis F valide jusqu'à",
"strDLClassCodeG1From": "Permis G1 valide à partir de",
"strDLClassCodeG1Notes": "Codes de catégorie G1",
"strDLClassCodeG1To": "Permis G1 valide jusqu'à",
"strDLClassCodeGFrom": "Permis G valide à partir de",
"strDLClassCodeGNotes": "Codes de catégorie G",
"strDLClassCodeGTo": "Permis G valide jusqu'à",
"strDLClassCodeHCFrom": "Permis HC valide à partir de",
"strDLClassCodeHCNotes": "Codes de catégorie HC",
"strDLClassCodeHCTo": "Permis HC valide jusqu'à",
"strDLClassCodeHFrom": "Permis H valide à partir de",
"strDLClassCodeHNotes": "Codes de catégorie H",
"strDLClassCodeHRFrom": "Permis HR valide à partir de",
"strDLClassCodeHRNotes": "Codes de catégorie HR",
"strDLClassCodeHRTo": "Permis HR valide jusqu'à",
"strDLClassCodeHTo": "Permis H valide jusqu'à",
"strDLClassCodeIFrom": "Permis I valide à partir de",
"strDLClassCodeINotes": "Codes de catégorie I",
"strDLClassCodeITo": "Permis I valide jusqu'à",
"strDLClassCodeJFrom": "Permis J valide à partir de",
"strDLClassCodeJNotes": "Codes de catégorie J",
"strDLClassCodeJTo": "Permis J valide jusqu'à",
"strDLClassCodeKFrom": "Permis K valide à partir de",
"strDLClassCodeKNotes": "Codes de catégorie K",
"strDLClassCodeKTo": "Permis K valide jusqu'à",
"strDLClassCodeLCFrom": "Permis LC valide à partir de",
"strDLClassCodeLCNotes": "Codes de catégorie LC",
"strDLClassCodeLCTo": "Permis LC valide jusqu'à",
"strDLClassCodeLFrom": "Permis L valide à partir de",
"strDLClassCodeLKFrom": "Permis LK valide à partir de",
"strDLClassCodeLKNotes": "Codes de catégorie LK",
"strDLClassCodeLKTo": "Permis LK valide jusqu'à",
"strDLClassCodeLNotes": "Codes de catégorie L",
"strDLClassCodeLRFrom": "Permis LR valide à partir de",
"strDLClassCodeLRNotes": "Codes de catégorie LR",
"strDLClassCodeLRTo": "Permis LR valide jusqu'à",
"strDLClassCodeLTo": "Permis L valide jusqu'à",
"strDLClassCodeMCFrom": "Permis MC valide à partir de",
"strDLClassCodeMCNotes": "Codes de catégorie MC",
"strDLClassCodeMCTo": "Permis MC valide jusqu'à",
"strDLClassCodeMFrom": "Permis M valide à partir de",
"strDLClassCodeMNotes": "Codes de catégorie M",
"strDLClassCodeMRFrom": "Permis MR valide à partir de",
"strDLClassCodeMRNotes": "Codes de catégorie MR",
"strDLClassCodeMRTo": "Permis MR valide jusqu'à",
"strDLClassCodeMTo": "Permis M valide jusqu'à",
"strDLClassCodeNFrom": "Permis N valide à partir de",
"strDLClassCodeNNotes": "Codes de catégorie N",
"strDLClassCodeNTo": "Permis N valide jusqu'à",
"strDLClassCodeREFrom": "Permis RE valide à partir de",
"strDLClassCodeRENotes": "Codes de catégorie RE",
"strDLClassCodeRETo": "Permis RE valide jusqu'à",
"strDLClassCodeRFrom": "Permis R valide à partir de",
"strDLClassCodeRNotes": "Codes de catégorie R",
"strDLClassCodeRTo": "Permis R valide jusqu'à",
"strDLClassCodeSFrom": "Permis S valide à partir de",
"strDLClassCodeSNotes": "Codes de catégorie S",
"strDLClassCodeSTo": "Permis S valide jusqu'à",
"strDLClassCodeTBFrom": "Permis TB valide à partir de",
"strDLClassCodeTBNotes": "Codes de catégorie TB",
"strDLClassCodeTBTo": "Permis TB valide jusqu'à",
"strDLClassCodeTFrom": "Permis T valide à partir de",
"strDLClassCodeTMFrom": "Permis TM valide à partir de",
"strDLClassCodeTMNotes": "Codes de catégorie TM",
"strDLClassCodeTMTo": "Permis TM valide jusqu'à",
"strDLClassCodeTNotes": "Codes de catégorie T",
"strDLClassCodeTRFrom": "Permis TR valide à partir de",
"strDLClassCodeTRNotes": "Codes de catégorie TR",
"strDLClassCodeTRTo": "Permis TR valide jusqu'à",
"strDLClassCodeTTo": "Permis T valide jusqu'à",
"strDLClassCodeTVFrom": "Permis TV valide à partir de",
"strDLClassCodeTVNotes": "Codes de catégorie TV",
"strDLClassCodeTVTo": "Permis TV valide jusqu'à",
"strDLClassCodeVFrom": "Permis V valide à partir de",
"strDLClassCodeVNotes": "Codes de catégorie V",
"strDLClassCodeVTo": "Permis V valide jusqu'à",
"strDLClassCodeWFrom": "Permis W valide à partir de",
"strDLClassCodeWNotes": "Codes de catégorie W",
"strDLClassCodeWTo": "Permis W valide jusqu'à",
"strDLDuplicateDate": "Date de délivrance du duplicata",
"strDLEndorsed": "Code de mention du permis de conduire",
"strDLIssType": "Type de carte",
"strDLRecordCreated": "Enregistrement créé",
"strDLRestrictionCode": "Code de restriction du permis de conduire",
"strDLUnder18Date": "Date du 18ème anniversaire",
"strDLUnder19Date": "Date du 19ème anniversaire",
"strDLUnder21Date": "Date du 21ème anniversaire",
"strDNINumber": "Numéro de DNI",
"strDSCertificateIssuer": "Émetteur du certificat DS",
"strDSCertificateSubject": "Sujet du certificat DS",
"strDSCertificateValidFrom": "Certificat DS valide à partir de",
"strDSCertificateValidTo": "Certificat DS valide jusqu'à",
"strDUFNumber": "Numéro DUF",
"strDataDiscriminator": "Discriminateur de données",
"strDateFirstRenewal": "Date du premier renouvellement",
"strDateOfBirthOfHusband": "Date de naissance du mari",
"strDateOfBirthOfWife": "Date de naissance de la femme",
"strDateOfInsuranceExpiry": "Date d'expiration de l'assurance",
"strDateSecondRenewal": "Date du deuxième renouvellement",
"strDateofBirth": "Date de naissance",
"strDateofBirthCheckDigit": "Chiffre de contrôle pour la date de naissance",
"strDateofBirthChecksum": "Somme de contrôle pour la date de naissance",
"strDateofCreation": "Date de création",
"strDateofExpiry": "Date d'expiration",
"strDateofExpiryCheckDigit": "Chiffre de contrôle pour la date d'expiration",
"strDateofExpiryChecksum": "Somme de contrôle pour la date d'expiration",
"strDateofFlight": "Date du vol",
"strDateofIssue": "Date de délivrance",
"strDateofIssueBoardingPass": "Date de délivrance de la carte d'embarquement",
"strDateofIssueCheckDigit": "Chiffre de contrôle pour la date de délivrance",
"strDateofIssueChecksum": "Somme de contrôle pour la date de délivrance",
"strDateofPersonalization": "Date de personnalisation",
"strDateofRegistration": "Date d'enregistrement",
"strDay": "Jour",
"strDepartment": "Département",
"strDeptNumber": "Numéro de département",
"strDestination": "Destination",
"strDiscretionaryData": "Données discrétionnaires",
"strDoDNumber": "Numéro DoD",
"strDocumentClassCode": "Code de classe de document",
"strDocumentClassName": "Classe de document",
"strDocumentDiscriminator": "Discriminateur de document",
"strDocumentNumber": "Numéro de document",
"strDocumentNumberCheckDigit": "Chiffre de contrôle pour le numéro de document",
"strDocumentNumberChecksum": "Somme de contrôle pour le numéro de document",
"strDocumentSeries": "Série de documents",
"strDocumentTooSmall": "Document trop petit",
"strDonor": "Donneur",
"strDossierNumber": "Numéro de dossier",
"strDurationofStay": "Durée du séjour",
"strECEnvironmentalType": "Type environnemental du véhicule",
"strEDLDG1": "Éléments de données textuelles (DG1)",
"strEDLDG10": "non défini (DG10)",
"strEDLDG11": "Données domestiques facultatives (DG11)",
"strEDLDG12": "Alerte de non-correspondance (DG12)",
"strEDLDG13": "Informations d'authentification active (DG13)",
"strEDLDG14": "Infos EAC (DG14)",
"strEDLDG2": "Informations du titulaire du permis (DG2)",
"strEDLDG3": "Détails de l'autorité de délivrance (DG3)",
"strEDLDG4": "Image du portrait (DG4)",
"strEDLDG5": "Image de la signature / marque habituelle (DG5)",
"strEDLDG6": "Biométrie - Données faciales (DG6)",
"strEDLDG7": "Biométrie - Empreinte(s) digitale(s) (DG7)",
"strEDLDG8": "Biométrie - Données de l'iris (DG8)",
"strEDLDG9": "Biométrie - Autres (DG9)",
"strEFCOM": "EF.COM",
"strEFCVCA": "EF.CVCA",
"strEFCardAccess": "EF.CardAccess",
"strEFCardSecurity": "EF.CardSecurity",
"strEFChipSecurity": "EF.ChipSecurity",
"strEFSOD": "EF.SOD",
"strEQVCode": "Code EQV",
"strElectronicTicketIndicator": "Indicateur de billet électronique",
"strElement": "Élément",
"strEndorsementExpirationDate": "Date d'expiration de la mention",
"strEngineModel": "Modèle de moteur",
"strEngineNumber": "Numéro de moteur",
"strEnginePower": "Puissance du moteur",
"strEngineVolume": "Volume du moteur",
"strError": "Erreur",
"strExamDate": "Date de l'examen",
"strExeptInTanks": "Sauf dans les réservoirs",
"strEye" : "Iris",
"strEyesColor" : "Couleur des yeux",
"strFaculty" : "Faculté",
"strFalseLuminescence" : "Luminescence excessive",
"strFamilyName" : "Nom de famille / nom donné à la naissance",
"strFamilyNameTruncation" : "Nom de famille/troncature du nom donné à la naissance",
"strFastTrack" : "Service Fast Track",
"strFatherCountryOfBirth" : "Pays de naissance du père",
"strFatherDateOfBirth" : "Date de naissance du père",
"strFatherGivenName" : "Prénom du père",
"strFatherPersonalNumber" : "Numéro personnel du père",
"strFatherPlaceOfBirth" : "Lieu de naissance du père",
"strFatherSurname" : "Nom de famille du père",
"strFathersName" : "Nom du père",
"strFathersNameRUS" : "Nom du père (National)",
"strFederalElections" : "Élections fédérales",
"strFee" : "Frais",
"strFieldFromMRZ" : "Champ de la zone de lecture optique (MRZ)",
"strFieldTypeDocumentImage" : "Image du document",
"strFillElement" : "Élément de remplissage",
"strFinalCheckDigit" : "Chiffre de contrôle final",
"strFinalChecksum" : "Somme de contrôle finale",
"strFingerprint" : "Empreinte digitale",
"strFirstIssueDate" : "Date de première délivrance",
"strFirstNameTruncation" : "Troncature du prénom",
"strFlightNumber" : "Numéro de vol",
"strFolioNumber" : "Numéro de folio",
"strFormOfEducation" : "Forme d'éducation",
"strFreeBaggageAllowance" : "Allocation de bagages gratuite",
"strFrequentFlyerAirlineDesignator" : "Indicateur de compagnie aérienne pour voyageur fréquent",
"strFrequentFlyerNumber" : "Numéro de voyageur fréquent",
"strFromAirportCode" : "Code de l'aéroport de départ",
"strFuelType" : "Type de carburant",
"strGNIBNumber" : "Numéro GNIB",
"strGhostPortrait" : "Portrait fantôme",
"strGivenNames" : "Prénoms",
"strGivenNamesRUS" : "Prénoms (National)",
"strGlaresOnDocument" : "Reflets sur le document",
"strGrandfatherName" : "Nom du grand-père",
"strHairColor" : "Couleur des cheveux",
"strHealthNumber" : "Numéro d'assurance maladie",
"strHeight" : "Taille",
"strHoldDocumentStraight" : "Tenir le document droit",
"strHoloSimple" : "Disponibilité de l'hologramme simple",
"strHoloVerifyDinamic" : "Vérifier l'hologramme dynamique",
"strHoloVerifyMultiStatic" : "Vérifier l'hologramme multi-statique",
"strHoloVerifyStatic" : "Vérifier l'hologramme statique",
"strHolograms" : "Hologrammes",
"strIPI" : "IPI (information personnelle invisible)",
"strIRB900" : "Encre IR B900",
"strIRVis" : "Transparence infrarouge",
"strISOIssuerIDNumber" : "Numéro d'identification de l'émetteur ISO",
"strIdentifier" : "Identifiant",
"strIdentityCardNumber" : "Numéro de carte d'identité",
"strIdentityCardNumberCheckDigit" : "Chiffre de contrôle pour le numéro de carte d'identité",
"strIdentityCardNumberChecksum" : "Somme de contrôle pour le numéro de carte d'identité",
"strImagePattern" : "Motifs d'image",
"strInTanks" : "Dans les réservoirs",
"strInventoryNumber" : "Numéro d'inventaire",
"strInvitationNumber" : "Numéro d'invitation",
"strInvitationNumberCheckDigit" : "Chiffre de contrôle pour le numéro d'invitation",
"strInvitationNumberChecksum" : "Somme de contrôle pour le numéro d'invitation",
"strInvitedBy" : "Invité par",
"strIssueTimestamp" : "Heure de délivrance",
"strIssuingStateCode" : "Code de l'état délivrant",
"strIssuingStateName" : "État de délivrance",
"strJurisdictionEndorsementCode" : "Code d'approbation de la juridiction",
"strJurisdictionRestrictionCode" : "Code de restriction de la juridiction",
"strJurisdictionVehicleClass" : "Classe de véhicule de la juridiction",
"strKeepDeviceStill" : "Maintenez l'appareil immobile",
"strLicenseNumber" : "Numéro de licence",
"strLimitedDurationDocumentIndicator" : "Indicateur de durée limitée du document",
"strLine1CheckDigit" : "Chiffre de contrôle pour la ligne 1",
"strLine1Checksum" : "Somme de contrôle pour la ligne 1",
"strLine1OptionalData" : "Données optionnelles de la ligne 1",
"strLine2CheckDigit" : "Chiffre de contrôle pour la ligne 2",
"strLine2Checksum" : "Somme de contrôle pour la ligne 2",
"strLine2OptionalData" : "Données optionnelles de la ligne 2",
"strLine3CheckDigit" : "Chiffre de contrôle pour la ligne 3",
"strLine3Checksum" : "Somme de contrôle pour la ligne 3",
"strLine3OptionalData" : "Données optionnelles de la ligne 3",
"strLookingDocument" : "Recherche d'un document...",
"strMCNoviceDate" : "Date d'expiration du statut de novice en moto",
"strMRZ" : "MRZ",
"strMRZLinesICAORFID" : "Lignes MRZ de l'ICAO RFID",
"strMRZString1" : "Ligne MRZ 1",
"strMRZString2" : "Ligne MRZ 2",
"strMRZString3" : "Ligne MRZ 3",
"strMRZStrings" : "Lignes MRZ",
"strMRZStringsWithCorrectCheckSums" : "Lignes MRZ avec les sommes de contrôle correctes",
"strMRZType" : "Type MRZ",
"strMailingAddressCity" : "Ville de l'adresse postale",
"strMailingAddressJurisdictionCode" : "Code de juridiction de l'adresse postale",
"strMailingAddressPostalCode" : "Code postal de l'adresse postale",
"strMailingAddressStreet" : "Rue de l'adresse postale",
"strMake" : "Marque",
"strMaritalStatus" : "État civil",
"strMaxMassofTrailerBraked" : "Masse maximale de la remorque (freinée)",
"strMaxMassofTrailerUnbraked" : "Masse maximale de la remorque (non freinée)",
"strMaxSpeed" : "Vitesse maximale",
"strMedicalIndicatorCodes" : "Notes/codes médicaux",
"strMiddleName" : "Deuxième prénom",
"strMiddleNameTruncation" : "Troncature du deuxième prénom",
"strMifareData" : "Données MIFARE",
"strMifareValidity" : "Validité MIFARE",
"strMilitaryBookNumber" : "Numéro de carte militaire",
"strModel" : "Modèle",
"strMonth" : "Mois",
"strMortgageBy" : "Hypothéqué par",
"strMotherCountryOfBirth" : "Pays de naissance de la mère",
"strMotherDateOfBirth" : "Date de naissance de la mère",
"strMotherGivenName" : "Prénom de la mère",
"strMotherPersonalNumber" : "Numéro personnel de la mère",
"strMotherPlaceOfBirth" : "Lieu de naissance de la mère",
"strMotherSurname" : "Nom de famille de la mère",
"strMothersName" : "Nom de la mère",
"strNamePrefix" : "Préfixe de nom",
"strNameSuffix" : "Suffixe de nom",
"strNationality" : "Nationalité",
"strNationalityCode" : "Code de nationalité",
"strNonResidentIndicator" : "Indicateur de non-résident",
"strNone" : "Aucun",
"strNotDefined" : "Non défini",
"strNumberOfCardIssuance" : "Nombre de délivrances de carte",
"strNumberOfCardIssuanceCheckDigit" : "Chiffre de contrôle pour le nombre de délivrances de carte",
"strNumberOfCardIssuanceChecksum" : "Checksum pour le nombre de délivrances de carte",
"strNumberOfCylinders" : "Nombre de cylindres",
"strNumberofAxels" : "Nombre d'essieux",
"strNumberofDuplicates" : "Nombre de doublons",
"strNumberofEntries" : "Nombre d'entrées",
"strNumberofSeats" : "Nombre de sièges",
"strNumberofStandingPlaces" : "Nombre de places debout",
"strOCRNumber" : "Numéro OCR",
"strOK" : "OK",
"strObservations" : "Observations",
"strOldDateOfIssue" : "Ancienne date de délivrance",
"strOldDocumentNumber" : "Ancien numéro de document",
"strOldPlaceOfIssue" : "Ancien lieu de délivrance",
"strOptionalData" : "Données facultatives",
"strOptionalDataCheckDigit" : "Chiffre de contrôle pour les données facultatives",
"strOptionalDataChecksum" : "Checksum pour les données facultatives",
"strOptionalDetails" : "Détails facultatifs",
"strOrganization" : "Organisation",
"strOther" : "Autre",
"strOtherName" : "Autre nom",
"strOtherPersonName" : "Autre personne, nom",
"strOtherValidID" : "Autres pièces d'identité valides",
"strOwner" : "Propriétaire",
"strPDF417Codec" : "Codec PDF417",
"strPNRCode" : "Code PNR",
"strParrentsGivenNames" : "Prénoms des parents",
"strPassportNumber" : "Numéro de passeport",
"strPassportNumberCheckDigit" : "Chiffre de contrôle pour le numéro de passeport",
"strPassportNumberChecksum" : "Checksum pour le numéro de passeport",
"strPatronHeaderVersion" : "Version de l'en-tête du client",
"strPatternDifferentLinesThickness" : "Comparaison de l'épaisseur des lignes du motif",
"strPatternIRInvisible" : "Motif invisible en IR",
"strPatternNotInterrupted" : "Pas d'interruption",
"strPatternNotShifted" : "Les éléments du motif ne sont pas décalés",
"strPatternSameColors" : "Mêmes couleurs du motif",
"strPayGrade" : "Échelon de rémunération",
"strPayloadCapacity" : "Capacité de charge",
"strPermissibleAxleLoad" : "Charge d'essieu autorisée",
"strPermitDLClass" : "Classe de permis",
"strPermitDateofExpiry" : "Date d'expiration du permis",
"strPermitDateofIssue" : "Date de délivrance du permis",
"strPermitEndorsed" : "Code de l'endossement du permis",
"strPermitIdentifier" : "Identifiant du permis",
"strPermitRestrictionCode" : "Code de restriction du permis",
"strPersonToNotifyAddress" : "Personne à notifier : Adresse",
"strPersonToNotifyDateofRecord" : "Personne à notifier : Date d'enregistrement",
"strPersonToNotifyName" : "Personne à notifier : Nom",
"strPersonToNotifyPhone" : "Personne à notifier : Téléphone",
"strPersonalNumber" : "Numéro personnel",
"strPersonalNumberCheckDigit" : "Chiffre de contrôle pour le numéro personnel",
"strPersonalNumberChecksum" : "Checksum pour le numéro personnel",
"strPersonalSummary" : "Résumé des données personnelles",
"strPersonalizationSN" : "Numéro de série de la personnalisation",
"strPhone" : "Téléphone",
"strPhotoArea" : "Zone de la photo",
"strPhotoColor" : "Couleur de la photo",
"strPhotoCorners" : "Coins de la photo",
"strPhotoElement" : "Élément de la photo",
"strPhotoEmbedType" : "Type d'incorporation de la photo",
"strPhotoProcessing" : "Traitement de la photo...",
"strPhotoShape" : "Forme de la photo",
"strPhotoSizeCheck" : "Vérification de la taille de la photo",
"strPlaceDocumentInFrame" : "Insérer le document dans le cadre",
"strPlaceOfBirthRUS" : "Lieu de naissance (National)",
"strPlaceOfBirthStateCode" : "Code d'état du lieu de naissance",
"strPlaceOfExamination" : "Lieu de l'examen",
"strPlaceOfIssue" : "Lieu de délivrance",
"strPlacePhoneOnDoc" : "Placez le téléphone sur le document s'il vous plaît",
"strPlaceofBirth" : "Lieu de naissance",
"strPlaceofBirthArea" : "Zone de lieu de naissance",
"strPlaceofRegistration" : "Lieu d'enregistrement",
"strPoliceDistrict" : "District de police",
"strPortrait" : "Portrait",
"strPortraitComparison" : "Comparaison des portraits",
"strPortraitOfChild" : "Portrait de l'enfant",
"strPortraitVSCamera" : "Portrait vs Image de la caméra",
"strPortraitVSGhost" : "Portrait vs Photo fantôme",
"strPortraitVSRFID" : "Portrait vs Portrait de puce RFID",
"strPowerWeightRatio" : "Ratio puissance/poids",
"strPrecinct" : "Arrondissement",
"strPrepareCamera" : "Préparation de l'appareil photo...",
"strPresentNextPage" : "Veuillez fournir la page suivante",
"strPreviousType" : "Type/numéro du document précédent",
"strProcessingDocument" : "Traitement des documents...",
"strProfession" : "Profession",
"strProfessionalIdNumber" : "Numéro d'identification professionnelle",
"strProofOfCitizenship" : "Preuve de citoyenneté",
"strPseudoCode" : "Pseudo-code",
"strPurposeOfEntry" : "But de l'entrée",
"strRFIDVSCamera" : "Portrait de la puce RFID vs Image de la caméra",
"strRaceEthnicity" : "Race/ethnie",
"strRank" : "Rang",
"strReadingRFID" : "Lecture des données de la puce RFID",
"strReadingRFIDDGiOS" : "Lecture des données RFID %@",
"strRecognizedDocumentType" : "Type de document reconnu",
"strReferenceNumber" : "Numéro unique",
"strReferenceNumberCheckDigit" : "Chiffre de contrôle du numéro unique",
"strReferenceNumberChecksum" : "Checksum du numéro unique",
"strRegCertBodyNumber" : "Numéro de carrosserie",
"strRegCertBodyType" : "Type de carrosserie",
"strRegCertCarColor" : "Couleur du véhicule",
"strRegCertCarMark" : "Marque du véhicule",
"strRegCertCarModel" : "Modèle du véhicule",
"strRegCertCarType" : "Type de véhicule",
"strRegCertMaxWeight" : "Poids maximal autorisé",
"strRegCertRegNumber" : "Numéro d'immatriculation",
"strRegCertRegNumberCheckDigit" : "Chiffre de contrôle du numéro d'immatriculation",
"strRegCertRegNumberChecksum" : "Checksum pour le numéro d'immatriculation",
"strRegCertVIN" : "Numéro d'identification du véhicule",
"strRegCertVINCheckDigit" : "Chiffre de contrôle pour VIN",
"strRegCertVINChecksum" : "Checksum pour VIN",
"strRegCertVehicleITSCode" : "Code ITS du véhicule",
"strRegCertWeight" : "Masse à vide",
"strRelationship" : "Relation",
"strReligion" : "Religion",
"strRemainderTerm" : "Mois avant expiration",
"strResidentFrom" : "Résident depuis",
"strResidentUntil" : "Résident jusqu'à",
"strRetirementNumber" : "Numéro de retraite",
"strRevisionDate" : "Date de révision",
"strRoomNumber" : "Numéro de chambre",
"strSBHIntegrityOptions" : "Options d'intégrité SBH",
"strSBHSecurityOptions" : "Options de sécurité SBH",
"strSeatNumber" : "Numéro de siège",
"strSecondSurname" : "Deuxième nom de famille",
"strSection" : "Section",
"strSecurityText" : "Texte de sécurité",
"strSelecteeIndicator" : "Indicateur de sélection",
"strSequenceNumber" : "Numéro de séquence",
"strSerialNumber" : "Numéro de série",
"strSettings" : "Paramètres",
"strSex" : "Sexe",
"strSignature" : "Signature",
"strSkinColor" : "Couleur de peau",
"strSocialSecurityNumber" : "Numéro d'assurance sociale",
"strSpCode" : "Code spécial",
"strSpecialNotes" : "Remarques spéciales",
"strSponsor" : "Parrain",
"strSponsorSSN" : "SSN du parrain",
"strSponsorService" : "Service de parrainage",
"strSponsorStatus" : "Statut du parrain",
"strStamp" : "Timbre",
"strStampNumber" : "Numéro de timbre",
"strStatusDateofExpiry" : "Date d'expiration du statut",
"strSurname" : "Nom de famille",
"strSurnameAndGivenNames" : "Nom de famille et prénoms",
"strSurnameAndGivenNamesCheckDigit" : "Chiffre de contrôle pour le nom de famille et les prénoms",
"strSurnameAndGivenNamesChecksum" : "Checksum pour le nom de famille et les prénoms",
"strSurnameAndGivenNamesRUS" : "Nom de famille et prénoms (National)",
"strSurnameAtBirth" : "Nom de famille à la naissance",
"strSurnameOfHusbandAfterRegistration" : "Nom de famille du mari après l'enregistrement",
"strSurnameOfWifeAfterRegistration" : "Nom de famille de la femme après l'enregistrement",
"strSurnameofSpose" : "Nom de famille du conjoint",
"strTax" : "Impôt",
"strTaxNumber" : "Numéro de taxation",
"strTelexCode" : "Code télégraphique",
"strTerritorialValidity" : "Validité territoriale",
"strTicketNumber" : "Numéro de billet",
"strTitle" : "Titre",
"strToAirportCode" : "Code de l'aéroport d'arrivée",
"strTorchUnavailable" : "Torche indisponible",
"strTrackingNumber" : "Numéro de suivi",
"strTrailerHitch" : "Attelage de remorque",
"strTransactionNumber" : "Numéro de transaction",
"strTransmissionType" : "Type de transmission",
"strTypeApprovalNumber" : "Numéro d'approbation de type",
"strURL" : "URL",
"strUSCIS" : "USCIS",
"strUV" : "UV",
"strUVFibers" : "Fibres de sécurité UV",
"strUVLuminescence" : "Vérification du papier UV terne",
"strUnableCaptureMedia" : "Échec de la configuration de la caméra",
"strUniqueCustomerIdentifier" : "Identifiant client unique",
"strVRCDataObjectEntry" : "Données du véhicule du groupe de données DG1",
"strValidityPeriod" : "Période de validité",
"strVehicleCategory" : "Catégorie de véhicule",
"strVeteran" : "Ancien combattant",
"strVisaClass" : "Classe de visa",
"strVisaID" : "ID de visa",
"strVisaIDCheckDigit" : "Chiffre de contrôle pour l'ID de visa",
"strVisaIDChecksum" : "Checksum pour l'ID de visa",
"strVisaIDRUS" : "ID de visa (National)",
"strVisaNumber" : "Numéro de visa",
"strVisaNumberCheckDigit" : "Chiffre de contrôle pour le numéro de visa",
"strVisaNumberChecksum" : "Checksum pour le numéro de visa",
"strVisaSubClass" : "Sous-classe de visa",
"strVisaType" : "Type de visa",
"strVisaValidFrom" : "Valide à partir de",
"strVisaValidUntil" : "Valide jusqu'à",
"strVisaValidUntilCheckDigit" : "Chiffre de contrôle pour la date d'expiration du visa",
"strVisaValidUntilChecksum" : "Checksum pour la date d'expiration du visa",
"strVisibleLight" : "Lumière visible",
"strVoter" : "Électeur",
"strVoterKey" : "Clé d'électeur",
"strVoucherNumber" : "Numéro de bon",
"strWeight" : "Poids",
"strWeightPound" : "Poids (livre)",
"strYear" : "Année",
"strYearsSinceIssue" : "Années depuis l'émission",
"streIDPlaceOfBirthCity" : "Lieu de naissance : Ville",
"streIDPlaceOfBirthCountry" : "Lieu de naissance : Pays",
"streIDPlaceOfBirthState" : "Lieu de naissance : État",
"streIDPlaceOfBirthStreet" : "Lieu de naissance : Rue",
"streIDPlaceOfBirthZipcode" : "Lieu de naissance : Code postal",
"streIDResidencePermit1" : "Permis de résidence 1",
"streIDResidencePermit2" : "Permis de résidence 2",
"strfppLeftIndexFinger" : "Index gauche",
"strfppLeftLittleFinger" : "Petit doigt gauche",
"strfppLeftMiddleFinger" : "Majeur gauche",
"strfppLeftRingFinger" : "Annulaire gauche",
"strfppLeftThumb" : "Pouce gauche",
"strfppRightIndexFinger" : "Index droit",
"strfppRightLittleFinger" : "Petit doigt droit",
"strfppRightMiddleFinger" : "Majeur droit",
"strfppRightRingFinger" : "Annulaire droit",
"strfppRightThumb" : "Pouce droit"
]
}
}
