//
//  File.swift
//
//
//  Created by MOBILE on 20/05/24.
//

import Foundation

class KurdishDataValues {
    func getDictionary() -> [String: String] {
        return [
            "RFID_Error_AlreadyDone" : "RFID: Operasyona daxwazkirî jixwe hatiye kirin",
            "RFID_Error_Busy" : "RFID: RFID mijûl e",
            "RFID_Error_Failed" : "RFID: Bi ser neket",
            "RFID_Error_FileIOError": "Xêrata RFID: Xêrata IO",
               "RFID_Error_InvalidDirectory": "Xêrata RFID: Direktoriya neyênîn",
               "RFID_Error_InvalidParameter": "Xêrata RFID: Parametra neyênîn li gorî ExecuteCommand() hatiye dîtin",
               "RFID_Error_NoChipDetected": "Xêrata RFID: Têgihê nehatiye dîtin",
               "RFID_Error_NotAvailable": "Xêrata RFID: Nehatiye zêwandin",
               "RFID_Error_NotEnoughMemory": "Xêrata RFID: Ji bo xêrata memûriyê",
               "RFID_Error_NotInitialized": "Xêrata RFID: Têvlişe nehatiye kirin",
               "RFID_Error_NotPerformed": "Xêrata RFID: Nehatiye kirin",
               "RFID_Error_OldFirmware": "Xêrata RFID: Fîrmweyriya piçûk ji berî hatiye dîtin",
               "RFID_Error_PCSC_CantConnectCard": "PCSC: Kartê nehatiye zêwandin",
               "RFID_Error_PCSC_CardIsBusy": "PCSC: Kartê di karkeriya",
            "RFID_Error_PCSC_CardIsNotConnected": "PCSC: Kartê nehatiye zêwandin",
                "RFID_Error_PCSC_ExtLe_Failed": "PCSC: ExtLe Failed",
                "RFID_Error_PCSC_Failed": "PCSC: Failed",
                "RFID_Error_PCSC_FailedSCard": "PCSC: Kartê smartê nehatiye zêwandin",
                "RFID_Error_PCSC_OperationCancelled": "PCSC: Operasyona hatiye îstopkirin",
                "RFID_Error_PCSC_ReaderNotAvailable": "PCSC: Lêserê nehatiye zêwandin",
                "RFID_Error_Session_AccessControl_AA_Failed": "RFID: AA Failed",
                "RFID_Error_Session_AccessControl_CA_Failed": "RFID: CA Failed",
                "RFID_Error_Session_AccessControl_IncorrectOptionCA": "RFID: Opça CA neyênîn",
                "RFID_Error_Session_AccessControl_RI_Failed": "RFID: RI Failed",
                "RFID_Error_Session_AccessControl_RequiresCA": "RFID: CA hêstiye",
                "RFID_Error_Session_AccessControl_RequiresCAKeys": "RFID: Nîşanên CA hêstiye",
                "RFID_Error_Session_AccessControl_RequiresPACE": "RFID: PACE hêstiye",
                "RFID_Error_Session_AccessControl_RequiresSM": "RFID: SM hêstiye",
                "RFID_Error_Session_AccessControl_RequiresTA": "RFID: TA hêstiye",
                "RFID_Error_Session_AccessControl_TA_Failed": "RFID: TA Failed",
                "RFID_Error_Session_AccessControl_UnknownType": "RFID: Tipa Nezanîn",
                "RFID_Error_Session_AccessKey_IncorrectData": "RFID: Nîşana Dijwarî Neyênîn",
                "RFID_Error_Session_AccessKey_IncorrectSMType": "RFID: Nîşana Dijwarî Tipê SM Neyênîn",
                "RFID_Error_Session_AccessKey_NotSet": "RFID: Nîşana Dijwarî Nehatîye Hatîye",
                "RFID_Error_Session_AccessKey_Restricted": "RFID: Nîşana Dijwarî Peydewariye",
                "RFID_Error_Session_AccessKey_UnknownType": "RFID: Tipa Nîşana Dijwarî Nezanîn",
                "RFID_Error_Session_AccessKey_UnsupportedSMType": "RFID: Tipê SMê Nîşana Dijwarî Nehêstiye",
                "RFID_Error_Session_File_AccessDenied": "RFID File: Hêstiye",
                "RFID_Error_Session_File_CantReadData": "RFID File: Nêzîkiya Datayê",
                "RFID_Error_Session_File_CantUseData": "RFID File: Nêzîkiya Datayê",
                "RFID_Error_Session_File_Contents_UnexpectedData": "RFID File: Datayê Neqederî",
                "RFID_Error_Session_File_IncorrectData": "RFID File: Datayê Neyênîn",
                "RFID_Error_Session_File_NotEnoughData": "RFID File: Datayê Neyênîn",
                "RFID_Error_Session_File_UnexpectedData": "RFID File: Datayê Neqederî",
                "RFID_Error_Session_File_WrongTag": "RFID File: Etiketa Neyênîn",
                "RFID_Error_Session_IncorrectData": "RFID: Datayê Neyênîn",
                "RFID_Error_Session_InvalidAuxData_CommunityID": "RFID: IDê Komunîtyê Neyênîn",
                "RFID_Error_Session_InvalidAuxData_DateOfBirth": "RFID: Roja Jidayê Neyênîn",
            "RFID_Error_Session_InvalidAuxData_DateOfExpiry": "RFID: Roja Jidayê Neyênîn",
                "RFID_Error_Session_IsClosed": "RFID: Sesiona Hatîye Îstopkirin",
                "RFID_Error_Session_PA_HashCheckFailed": "RFID: Kontrola Hashê Neyênîn",
                "RFID_Error_Session_PA_SignatureCheckFailed": "RFID: Kontrola Oznayê Neyênîn",
                "RFID_Error_Session_ProcedureType_NotSet": "RFID: Tipa Operasyonê Nehatîye Hatîye",
                "RFID_Error_Session_ProcedureType_Unknown": "RFID: Tipa Operasyonê Nezanîn",
                "RFID_Error_Session_ProcedureType_Unsupported": "RFID: Tipa Operasyonê Nehêstiye",
                "RFID_Error_Session_PwdManagement_NotAuthorized": "RFID: Bûyerên Pwd Nehêstiye",
                "RFID_Error_Session_TerminalType_BadCertificate": "RFID: Tipe Terminalê Sertîfîka Piçûk",
                "RFID_Error_Session_TerminalType_NotSet": "RFID: Tipe Terminalê Nehatîye Hatîye",
                "RFID_Error_Session_TerminalType_Unknown": "RFID: Tipe Terminalê Nezanîn",
                "RFID_Error_Session_Terminal_UnsupportedOperation": "RFID: Operasyona Têvlişe Nehêstiye",
                "RFID_Error_Session_eSign_PIN_NotSet": "RFID: PINê eSign Nehatîye Hatîye",
                "RFID_Error_Session_eSign_PIN_NotVerified": "RFID: PINê eSign Nehêstiye Têgih",
                "RFID_Error_Session_eSign_RequiresAppSelection": "RFID: eSign Hêstiye Têgih",
                "RFID_Error_UnknownCommand": "RFID: Komanda Nezanîn",
                "RFID_LAYER6_APP_SELECTION_FAILURE": "LAYER6: ISO7816_A_03 \"Têgihê Aplicasyonê Neyênîn\"",
                "RFID_LAYER6_EXT_AUTH_FAILURE": "LAYER6: APDU_INS_EXTERNAL_AUTHENTICATE (Autentîkasyona Dîrokar) Neyênîn",
                "RFID_LAYER6_FILE_EOF1": "LAYER6: Lîsteya Datayê Piştî EOF / EOFê Neqederî",
                "RFID_LAYER6_FILE_EOF2": "LAYER6: Lîsteya Datayê Piştî EOF / EOFê Neqederî",
                "RFID_LAYER6_FILE_NOT_FOUND": "LAYER6: Têgihê Lîsteyê Neyênîn / lîsteye nehatiye dîtin",
                "RFID_LAYER6_GENERAL_AUTH_FAILURE": "LAYER6: Neyênîna Autentîkasyona Yekem",
                "RFID_LAYER6_GET_CHALLENGE_FAILURE": "LAYER6: GET CHALLENGE Neyênîn",
                "RFID_LAYER6_INCORRECT_PARAMS": "LAYER6: Paramêtên Neyênîn",
                "RFID_LAYER6_INT_AUTH_FAILURE": "LAYER6: APDU_INS_INTERNAL_AUTHENTICATE Neyênîn",
                "RFID_LAYER6_MSE_SET_AT_FAILURE": "LAYER6: MSE:Set AT Neyênîn",
                "RFID_LAYER6_MSE_SET_DST_FAILURE": "LAYER6: MSE:Set DST Neyênîn",
                "RFID_LAYER6_MSE_SET_KAT_FAILURE": "LAYER6: MSE:Set KAT Neyênîn",
                "RFID_LAYER6_MUTUAL_AUTH_ENC_FAIL": "LAYER6: ISO7816_B_02 \"Neyênîna Autentîkasyona Dîrokî\"",
                "RFID_LAYER6_MUTUAL_AUTH_FAILURE": "LAYER6: ISO7816_B_03 \"Neyênîna Autentîkasyona Dîrokî\"",
                "RFID_LAYER6_MUTUAL_AUTH_MAC_FAIL": "LAYER6: ISO7816_B_01 \"Neyênîna MACê Autentîkasyona Dîrokî\"",
                "RFID_LAYER6_NON_TLV_RESPONSE_DATA": "LAYER6: Data ya Responseê NeTLV",
                "RFID_LAYER6_NO_REFERENCE_DATA": "LAYER6: Data ya Referansê Neyênîn",
                "RFID_LAYER6_PSO_CERTIFICATE_FAILURE": "LAYER6: Sertîfîka PSO Neyênîn",
                "RFID_LAYER6_PWD_BLOCKED": "LAYER6: PWD Nehêstiye",
                "RFID_LAYER6_PWD_BLOCKED_2": "LAYER6: PWD Nehêstiye 2",
                "RFID_LAYER6_PWD_DEACTIVATED": "LAYER6: PWD Deaktivatt",
                "RFID_LAYER6_PWD_DEACTIVATED_2": "LAYER6: PWD Deaktivatt 2",
                "RFID_LAYER6_PWD_FAILED": "LAYER6: PWD Neyênîn",
                "RFID_LAYER6_PWD_SUSPENDED": "LAYER6: PWD Nehêstiye",
            "RFID_LAYER6_PWD_SUSPENDED_2": "LAYER6: PWD Nehêstiye 2",
               "RFID_LAYER6_SECURITY_MANAGER": "LAYER6: Mesajên Girîngîn Nehêstiye Hatîye",
               "RFID_LAYER6_SM_DO87_INCORRECT": "LAYER6: SM Neyênîn – Cryptogramê Neyênîn",
               "RFID_LAYER6_SM_DO87_MISSING": "LAYER6: SM Neyênîn – Cryptogramê Nehatîye Hatîye",
               "RFID_LAYER6_SM_DO8E_MISSING": "LAYER6: SM Neyênîn – MACê Nehatîye Hatîye",
               "RFID_LAYER6_SM_DO99_MISSING": "LAYER6: SM Neyênîn – Baytên Statûsê Girîngîn Nehatîye Hatîye",
               "RFID_LAYER6_SM_MAC_INCORRECT": "LAYER6: SM Neyênîn – MACê Neyênîn",
               "RFID_LAYER6_WRONG_RND_ICC_LENGTH": "LAYER6: Dirêjiya Datayê Gêrîn (APDU_INS_GET_CHALLENGE)",
               "RSDT_RFID_READING_FINISHED": "Lêkolina Datayê RFID Hatîye Îstopkirin",
               "TCT_Unknown": "Nezanîn",
               "chd_BackgroundComparisonError": "Dirêjiya Brîghtnesê Du Rûpelan Eynî Neyênîn",
               "chd_BadAreaInAxial": "Neyênîna Parêzgeriya Retroreflective",
               "chd_BarcodeDataFormatError": "Neyênîna Formata Barcodê",
               "chd_BarcodeReadedWithErrors": "Barcodê Bi Dijwarî Hatîye Dîtin",
               "chd_BarcodeSizeParamsError": "Neyênîna Paramêtên Barcodê",
               "chd_DocumentIsCancelling": "Dokumentê Hatîye Îstopkirin",
               "chd_ElementShouldBeColored": "Elemenê Hêla Girîngîn Bûye",
               "chd_ElementShouldBeGrayscale": "Elemenê Hêla Grayscale Bûye",
               "chd_ExceptionInModule": "Kesayetiya Întercepted",
               "chd_FalseIPIParameters": "Paramêtên False IPI",
               "chd_FalseLuminiscenceError": "Hêsankirina Ekserciyê Li Ser Objektên Ekserciyê",
               "chd_FalseLuminiscenceInBlank": "Hêsankirina Ekserciyê Li Ser Blankê",
               "chd_FalseLuminiscenceInMRZ": "Hêsankirina Ekserciyê Li Ser MRZê",
               "chd_FibersNotFound": "Drûşên Nehatîye Hatîye Dîtin",
               "chd_FieldPosCorrector_Highlight_IR": "Hêsarkirina Ekserciyê Li Ser IRê",
               "chd_FieldsComparisonLogicError": "Neyênîna Logicê Di Bindestiyê Çavkanînê",
               "chd_FixedPatternError": "Neyênîna Objetên Specifiye",
               "chd_HologramElementAbsent": "Holograma Nehatîye Hatîye Dîtin",
               "chd_HologramElementPresent": "Holograma Hatîye Dîtin",
               "chd_Hologram_Side_Top_Images_Absent": "Neyênîna Taybetên Lateral û Enverûn",
               "chd_IncorrectBackgroundLight": "Brîghtnesê Arka Neyênîn",
               "chd_IncorrectTextColor": "Renê Teksta Neyênîn",
               "chd_InternalError": "Neyênîna Procêseringê Datayê Navîn",
               "chd_InvalidChecksum": "Neyênîna Checksumê",
               "chd_InvalidFieldFormat": "Formata Çavkanînê Neyênîn",
               "chd_InvalidInputData": "Datayê Daxistî Neyênîn",
               "chd_InvisibleElementPresent": "Objektê Gehilbatî Nehêstiye",
               "chd_LogicError": "Neyênîna Logicê",
               "chd_LowContrastInIRLight": "Kontrasta Objetê Li Ser Lightê IR Neyênîn",
               "chd_MobileImages_LowLightConditions": "Şertên Lightê Nehêstiye Li Ser Capturê Imajê",
               "chd_MobileImages_WhileUVNoDifference": "Neyênîna Farka Zêde Li Ser Imajên Di Bindestiyê Illuminationê",
               "chd_NecessaryImageNotFound": "Imaja Hêstiye Li Ser Checkê Nehatîye Hatîye Dîtin",
               "chd_NotAllBarcodesRead": "Dokumentê Hêstiye Barcodên Zêde",
               "chd_OVI_BadColor_Front": "Renê Objetê OVI Neyênîn Li Ser Lightê Ab",
               "chd_OVI_BadColor_Percent": "Neyênîna Farka Zêde Li Ser Elemenetên OVI",
               "chd_OVI_BadColor_Side": "Renê Objetê OVI Neyênîn Li Ser Lightê Axial",
               "chd_OVI_ColorInvariable": "Renê OVI Nehêstiye Gewre",
               "chd_OVI_IR_Invisible": "Kontrasta Objetê OVI Neyênîn",
               "chd_OVI_InsufficientArea": "Çavkanîna Zêde Li Ser Objetê OVI",
               "chd_OVI_Wide_Color_Spread": "Farka Renê Objetê OVI Neyênîn",
            
            
            
            
            "chd_Pass": "Neyênîn Nîn",
              "chd_PhotoFalseLuminiscence": "Hêsankirina Ekserciyê Li Ser Cîhana Fotografî",
              "chd_PhotoPattern_DifferentColors": "Renên Môtakalên Li Ser Fotografî û Blankê Eynî Neyênîn",
              "chd_PhotoPattern_DifferentLinesThickness": "Dirêjiya Çavkanînên Môtakalê Neyênîn",
              "chd_PhotoPattern_IR_Visible": "Môtaka Girîngîn Li Ser Lightê IR Peyîn",
              "chd_PhotoPattern_Interrupted": "Môtaka Li Ser Fotografî û Blankê Peyîn",
              "chd_PhotoPattern_InvalidColor": "Renê Môtakayê Girîngîn Neyênîn",
              "chd_PhotoPattern_Not_Intersect": "Çavkanîna Arka Fotografî û Môtakayê Neyênîn",
              "chd_PhotoPattern_PatternNotFound": "Môtaka Nehatîye Hatîye Dîtin",
              "chd_PhotoPattern_Shifted": "Môtaka Li Ser Fotografî Peyîn Li Gor Môtakayê Blankê",
              "chd_PhotoPattern_Shifted_Vert": "Çavkanînên Môtakayê Peyîn Li Gor Hevbehiya Vertikal",
              "chd_PhotoSidesNotFound": "Arka Fotografî Nehatîye Hatîye Dîtin",
              "chd_PhotoSize_Is_Wrong": "Dirêjiya Fotografî Neyênîn",
              "chd_Photo_Corners_Is_Wrong": "Gola Çavkanînên Fotografî Neyênîn",
              "chd_Photo_IsNot_Rectangle": "Gola Fotografî Nehêstiye Rectangular",
              "chd_PortraitComparison_NoLivePhoto": "Neyênîna Camera Image",
              "chd_PortraitComparison_NoPortraitDetected": "Neyênîna Gozê Dîn Li Ser Image",
              "chd_PortraitComparison_NoServiceLicense": "Neyênîna Licensa Servisê",
              "chd_PortraitComparison_NoServiceReply": "Servis Nehêstiye Pêşbînkirin",
              "chd_PortraitComparison_NotEnoughImages": "Neyênîna Zarava Image",
              "chd_PortraitComparison_PortraitsDiffer": "Portreyên Dîn Nehêstiye Eynî",
              "chd_PortraitComparison_ServiceError": "Neyênîna Servisê",
              "chd_SourcesComparisonError": "Neyênîna Noncoincidence Li Ser Datayê Ji Berfiretiya Çavkanînê",
              "chd_SpecksInUV": "Hêsarkirina Ekserciyê Li Ser Image Li Ser Lightê UV",
              "chd_SyntaxError": "Neyênîna Syntaxê Datayê",
              "chd_TextColorShouldBeBlue": "Renê Teksta Hêla Girîngîn Peyîn",
              "chd_TextColorShouldBeGreen": "Renê Teksta Hêla Girîngîn Peyîn",
              "chd_TextColorShouldBeRed": "Renê Teksta Hêla Girîngîn Peyîn",
              "chd_TextShouldBeBlack": "Teksta Hêla Girîngîn Peyîn",
              "chd_TooLowResolution": "Dirêjiya Resolutionê Zêde Nehêstiye Drûşên Hatîye Dîtin",
              "chd_TooManyObjects": "Zarava Objetên Zêde",
              "chd_TooMuchShift": "Qeydkirina Zêde Li Gor Qeydkirina Hêviya Hêstiye",
              "chd_TrueLuminiscenceError": "Neyênîna Noncoincidence Li Ser Objetên Hêsarkirî",
              "chd_UVDullPaperError": "Neyênîna Checkê Papira Dull UV",
              "chd_UVDullPaper_Blank": "Checkê Papira Dull UV Li Ser Area Ya Blankê",
              "chd_UVDullPaper_MRZ": "Checkê Papira Dull UV Li Ser Area Ya MRZê",
              "chd_UVDullPaper_Photo": "Checkê Papira Dull UV Li Ser Area Ya Fotografî",
              "chd_UncertainVerification": "Neyênîna Decisionê Reliable",
              "chd_Unknown": "Neyênîna Denyê Nezanîn",
              "chd_VisibleElementAbsent": "Neyênîna Objetê Peyîn Li Ser Lightê IR",
            "strAGY": "Nîşanê AGY",
             "strAKADateofBirth": "Roja Jidayê",
             "strAKAGivenNames": "Navên Navdar",
             "strAKANamePrefix": "Prefiksê Navê",
             "strAKANameSuffix": "Sufeksê Navê",
             "strAKASocialSecurityNumber": "Nûmra ya Befirahiyê Sosîal",
             "strAKASurname": "Navê Dêr",
             "strAKASurnameAndGivenNames": "Navê Tewr û Navên Navdar",
             "strALTCode": "Kodê ALT",
             "strAcademicTitle": "Derejeya Akadêmik",
             "strAccessibilityCameraButton": "Girtina Îmage û Dibistinêna",
             "strAccessibilityCloseButton": "Îwaz",
             "strAccessibilityTorchButton": "Lîstika",
             "strAccompaniedby": "Hilbijê",
             "strAddress": "Cihata",
             "strAddressArea": "Navçeyê",
             "strAddressBuilding": "Binkeyekê",
             "strAddressCity": "Şehrê",
             "strAddressCountry": "Welatê",
             "strAddressFlat": "Apartmanê",
             "strAddressHouse": "Malê",
             "strAddressJurisdictionCode": "Koda Qanûnmandiya",
             "strAddressLocation": "Cihata",
             "strAddressMunicipality": "Qezaxaneyê",
             "strAddressPostalCode": "Koda Postayê",
             "strAddressState": "Parêzgeha",
             "strAddressStreet": "Çawreya",
             "strAdministrativeNumber": "Nûmra ya Fermî",
             "strAge": "Salbûn",
             "strAgeAtIssue": "Salbûna li Zimanê",
             "strAirlineDesignatorofboardingpassissuer": "Nîşana Rêveberê Hewayê ya Li Ser Destpêka Xweyê",
             "strAirlineName": "Navê Hewayê",
             "strAirlineNameFrequentFlyer": "Programa Loyaltyê ya Hewayê ya Li Gor Destpêka Xweyê",
             "strAirlineNumericCode": "Koda Nûmericê ya Hewayê",
             "strAirportFrom": "Derxistina Gerdûna Hewayê",
             "strAirportTo": "Destpêkê Gerdûna Hewayê",
             "strAllergies": "Alêrgî",
             "strApplicationDoNotHavePermission": "Aplicasyona Neqabliye Kamera Vekiyan Di",
             "strApplicationNumber": "Nûmra ya Aplicasyona",
             "strArtisticName": "Navê Edebi",
             "strAuditInformation": "Informasyonên Revîsê",
             "strAuthentification": "Revîsiya Lêkolînê",
             "strAuthority": "Rêveberê",
             "strAuthorityCode": "Koda Rêveberê",
             "strAuthorityRUS": "Rêveberê (Neteweyî)",
             "strAuthorizationNumber": "Nûmra ya Leşkerî",
             "strAxialProtection": "Pirsgiriya Axial",
             "strBDBType": "Tîpa BDB",
             "strBankCardNumber": "Nûmra ya Kartê Bankê",
             "strBankCardValidThru": "Dirêjiya Gelavê Kartê Bankê",
             "strBanknoteNumber": "Nûmra ya Banknotê",
             "strBarcode": "Barcod",
             "strBarcodeFormatCheck": "Revîsiya Formata Barcodê",
             "strBenefitsNumber": "Nûmra ya Benefîtên",
             "strBinaryCode": "Koda Binêri",
             "strBiometricFormatOwner": "Sedema Biometrik",
            "strBiometricFormatType": "Tîpa Formata Biometrik",
             "strBiometricProductID": "ID ya Produktê Biometrik",
             "strBiometricSubtype": "Tîpa Zimanê Biometrik",
             "strBiometricType": "Tîpa Biometrik",
             "strBlankElement": "Elemenê Goşt",
             "strBloodGroup": "Grupê Xweyê",
             "strBookletNumber": "Nûmra ya Bookletê",
             "strCCWUntil": "CCWê Heta",
             "strCDLClass": "Klasê CDL",
             "strCSCCode": "Koda CSC",
             "strCVV": "CVV/CVC",
             "strCaliber": "Kalîber",
             "strCameraUnavailable": "Kamerya Neqabliye",
             "strCardAccessNumber": "Nûmra ya Eksluziviyê ya Kartê",
             "strCategory": "Kategorî",
             "strCenturyDateOfBirth": "Salê ji dayîna",
               "strChassisNumber": "Nûmera şasiyê",
               "strCheckInSequenceNumber": "Nûmera li ser çekandinê",
               "strChildren": "Kurên",
               "strCitizenshipOfFirstPerson": "Habûbendiya yekemîn",
               "strCitizenshipOfSecondPerson": "Habûbendiya duyemîn",
               "strCivilStatus": "Hewlê jiyanê",
               "strColorDynamic": "Reng dinamik",
               "strCommercialVehicleCodes": "Kodên veyîna tijarêt",
               "strCompanyName": "Navê kompaniyê",
               "strCompartmentCode": "Koda kompartiman",
               "strComplexion": "Soraya xwe",
               "strComplianceType": "Ji bo pêdeken",
               "strConditions": "Parçebûn",
               "strConfiguration": "Konfigürasyon",
               "strControlNo": "Nûmera kontrolê",
               "strCopy": "Nesxan",
               "strCourtCode": "Koda dergahiye",
               "strCty": "Şaredariya",
               "strCurrentDate": "Roja niha",
               "strCustodyInfo": "Informasyona bawername",
               "strDFTAppDirectory": "Derbarê aplikasyonê de",
               "strDFTCertificate": "Serlêkê",
               "strDG1": "Zonê Qereqola Qeyskirinê (DG1)",
               "strDG10": "ne definiye (DG10)",
               "strDG11": "Detayên kişiyê (DG11)",
               "strDG12": "Detayên dokumenê (DG12)",
               "strDG13": "Detayên opsyonal (DG13)",
               "strDG14": "Informasyona EAC (DG14)",
               "strDG15": "Informasyona Authentikasyonê Aktif (DG15)",
               "strDG16": "Li hemberiya xelkê (DG16)",
               "strDG17": "DG17",
               "strDG18": "DG18",
               "strDG19": "DG19",
               "strDG2": "Biometri - Rûyê (DG2)",
               "strDG20": "DG20",
               "strDG3": "Biometri - Nivîsên parmakê (DG3)",
               "strDG4": "Biometri - Dîtina Çavkanê (DG4)",
               "strDG5": "Portreto (DG5)",
               "strDG6": "ne definiye (DG6)",
               "strDG7": "Ozna / nîşana navîn (DG7)",
               "strDG8": "ne definiye (DG8)",
               "strDG9": "ne definiye (DG9)",
               "strDLCDLRestrictionCode": "Koda Încirbozkirinê CDL",
               "strDLClass": "Klasa DL",
               "strDLClassCodeA1From": "Klasa DL A1 ji rojê",
               "strDLClassCodeA1Notes": "Kodên klase DL A1",
               "strDLClassCodeA1To": "Klasa DL A1 ji rojê",
               "strDLClassCodeA2From": "Klasa DL A2 ji rojê",
               "strDLClassCodeA2Notes": "Kodên klase DL A2",
               "strDLClassCodeA2To": "Klasa DL A2 ji rojê",
               "strDLClassCodeA3From": "Klasa DL A3 ji rojê",
               "strDLClassCodeA3Notes": "Kodên klase DL A3",
               "strDLClassCodeA3To": "Klasa DL A3 ji rojê",
               "strDLClassCodeAFrom": "Klasa DL A ji rojê",
               "strDLClassCodeAMFrom": "Klasa DL AM ji rojê",
               "strDLClassCodeAMNotes": "Kodên klase DL AM",
               "strDLClassCodeAMTo": "Klasa DL AM ji rojê",
               "strDLClassCodeANotes": "Kodên klase DL A",
               "strDLClassCodeATo": "Klasa DL A ji rojê",
               "strDLClassCodeB1From": "Klasa DL B1 ji rojê",
               "strDLClassCodeB1Notes": "Kodên klase DL B1",
               "strDLClassCodeB1To": "Klasa DL B1 ji rojê",
               "strDLClassCodeB2EFrom": "Klasa DL B2E ji rojê",
               "strDLClassCodeB2ENotes": "Kodên klase DL B2E",
               "strDLClassCodeB2ETo": "Klasa DL B2E ji rojê",
               "strDLClassCodeB2From": "Klasa DL B2 ji rojê",
               "strDLClassCodeB2Notes": "Kodên klase DL B2",
               "strDLClassCodeB2To": "Klasa DL B2 ji rojê",
               "strDLClassCodeBEFrom": "Klasa DL BE ji rojê",
               "strDLClassCodeBENotes": "Kodên klase DL BE",
               "strDLClassCodeBETo": "Klasa DL BE ji rojê",
               "strDLClassCodeBFrom": "Klasa DL B ji rojê",
               "strDLClassCodeBNotes": "Kodên klase DL B",
               "strDLClassCodeBTPFrom": "Klasa DL BTP ji rojê",
               "strDLClassCodeBTPNotes": "Kodên klase DL BTP",
               "strDLClassCodeBTPTo": "Klasa DL BTP ji rojê",
               "strDLClassCodeBTo": "Klasa DL B ji rojê",
               "strDLClassCodeC1EFrom": "Klasa DL C1E ji rojê",
               "strDLClassCodeC1ENotes": "Kodên klase DL C1E",
               "strDLClassCodeC1ETo": "Klasa DL C1E ji rojê",
               "strDLClassCodeC1From": "Klasa DL C1 ji rojê",
               "strDLClassCodeC1Notes": "Kodên klase DL C1",
               "strDLClassCodeC1To": "Klasa DL C1 ji rojê",
               "strDLClassCodeC2From": "Klasa DL C2 ji rojê",
               "strDLClassCodeC2Notes": "Kodên klase DL C2",
               "strDLClassCodeC2To": "Klasa DL C2 ji rojê",
               "strDLClassCodeC3From": "Klasa DL C3 ji rojê",
               "strDLClassCodeC3Notes": "Kodên klase DL C3",
            
            
            "strDLClassCodeC3To": "Kategorîya DL C3 têbé",
             "strDLClassCodeCAFrom": "Kategorîya DL CA têbé",
             "strDLClassCodeCANotes": "Kodên kategorîya DL CA",
             "strDLClassCodeCATo": "Kategorîya DL CA têbé",
             "strDLClassCodeCEFrom": "Kategorîya DL CE têbé",
             "strDLClassCodeCENotes": "Kodên kategorîya DL CE",
             "strDLClassCodeCETo": "Kategorîya DL CE têbé",
             "strDLClassCodeCFrom": "Kategorîya DL C têbé",
             "strDLClassCodeCNotes": "Kodên kategorîya DL C",
             "strDLClassCodeCTo": "Kategorîya DL C têbé",
             "strDLClassCodeD1EFrom": "Kategorîya DL D1E têbé",
             "strDLClassCodeD1ENotes": "Kodên kategorîya DL D1E",
             "strDLClassCodeD1ETo": "Kategorîya DL D1E têbé",
             "strDLClassCodeD1From": "Kategorîya DL D1 têbé",
             "strDLClassCodeD1Notes": "Kodên kategorîya DL D1",
             "strDLClassCodeD1To": "Kategorîya DL D1 têbé",
             "strDLClassCodeD2From": "Kategorîya DL D2 têbé",
             "strDLClassCodeD2Notes": "Kodên kategorîya DL D2",
             "strDLClassCodeD2To": "Kategorîya DL D2 têbé",
             "strDLClassCodeDEFrom": "Kategorîya DL DE têbé",
             "strDLClassCodeDENotes": "Kodên kategorîya DL DE",
             "strDLClassCodeDETo": "Kategorîya DL DE têbé",
             "strDLClassCodeDFrom": "Kategorîya DL D têbé",
             "strDLClassCodeDNotes": "Kodên kategorîya DL D",
             "strDLClassCodeDTo": "Kategorîya DL D têbé",
             "strDLClassCodeEFrom": "Kategorîya DL E têbé",
             "strDLClassCodeENotes": "Kodên kategorîya DL E",
             "strDLClassCodeETo": "Kategorîya DL E têbé",
             "strDLClassCodeFA1From": "Kategorîya DL FA1 têbé",
             "strDLClassCodeFA1Notes": "Kodên kategorîya DL FA1",
             "strDLClassCodeFA1To": "Kategorîya DL FA1 têbé",
             "strDLClassCodeFAFrom": "Kategorîya DL FA têbé",
             "strDLClassCodeFANotes": "Kodên kategorîya DL FA",
             "strDLClassCodeFATo": "Kategorîya DL FA têbé",
             "strDLClassCodeFBFrom": "Kategorîya DL FB têbé",
             "strDLClassCodeFBNotes": "Kodên kategorîya DL FB",
             "strDLClassCodeFBTo": "Kategorîya DL FB têbé",
             "strDLClassCodeFFrom": "Kategorîya DL F têbé",
             "strDLClassCodeFNotes": "Kodên kategorîya DL F",
             "strDLClassCodeFTo": "Kategorîya DL F têbé",
             "strDLClassCodeG1From": "Kategorîya DL G1 têbé",
             "strDLClassCodeG1Notes": "Kodên kategorîya DL G1",
             "strDLClassCodeG1To": "Kategorîya DL G1 têbé",
             "strDLClassCodeGFrom": "Kategorîya DL G têbé",
             "strDLClassCodeGNotes": "Kodên kategorîya DL G",
             "strDLClassCodeGTo": "Kategorîya DL G têbé",
             "strDLClassCodeHCFrom": "Kategorîya DL HC têbé",
             "strDLClassCodeHCNotes": "Kodên kategorîya DL HC",
             "strDLClassCodeHCTo": "Kategorîya DL HC têbé",
             "strDLClassCodeHFrom": "Kategorîya DL H têbé",
             "strDLClassCodeHNotes": "Kodên kategorîya DL H",
             "strDLClassCodeHRFrom": "Kategorîya DL HR têbé",
             "strDLClassCodeHRNotes": "Kodên kategorîya DL HR",
             "strDLClassCodeHRTo": "Kategorîya DL HR têbé",
             "strDLClassCodeHTo": "Kategorîya DL H têbé",
             "strDLClassCodeIFrom": "Kategorîya DL I têbé",
             "strDLClassCodeINotes": "Kodên kategorîya DL I",
             "strDLClassCodeITo": "Kategorîya DL I têbé",
             "strDLClassCodeJFrom": "Kategorîya DL J têbé",
             "strDLClassCodeJNotes": "Kodên kategorîya DL J",
             "strDLClassCodeJTo": "Kategorîya DL J têbé",
             "strDLClassCodeKFrom": "Kategorîya DL K têbé",
             "strDLClassCodeKNotes": "Kodên kategorîya DL K",
             "strDLClassCodeKTo": "Kategorîya DL K têbé",
             "strDLClassCodeLCFrom": "Kategorîya DL LC têbé",
             "strDLClassCodeLCNotes": "Kodên kategorîya DL LC",
             "strDLClassCodeLCTo": "Kategorîya DL LC têbé",
             "strDLClassCodeLFrom": "Kategorîya DL L têbé",
             "strDLClassCodeLKFrom": "Kategorîya DL LK têbé",
             "strDLClassCodeLKNotes": "Kodên kategorîya DL LK",
             "strDLClassCodeLKTo": "Kategorîya DL LK têbé",
             "strDLClassCodeLNotes": "Kodên kategorîya DL L",
             "strDLClassCodeLRFrom": "Kategorîya DL LR têbé",
             "strDLClassCodeLRNotes": "Kodên kategorîya DL LR",
             "strDLClassCodeLRTo": "Kategorîya DL LR têbé",
             "strDLClassCodeLTo": "Kategorîya DL L têbé",
             "strDLClassCodeMCFrom": "Kategorîya DL MC têbé",
             "strDLClassCodeMCNotes": "Kodên kategorîya DL MC",
             "strDLClassCodeMCTo": "Kategorîya DL MC têbé",
             "strDLClassCodeMFrom": "Kategorîya DL M têbé",
             "strDLClassCodeMNotes": "Kodên kategorîya DL M",
             "strDLClassCodeMRFrom": "Kategorîya DL MR têbé",
             "strDLClassCodeMRNotes": "Kodên kategorîya DL MR",
             "strDLClassCodeMRTo": "Kategorîya DL MR têbé",
             "strDLClassCodeMTo": "Kategorîya DL M têbé",
             "strDLClassCodeNFrom": "Kategorîya DL N têbé",
             "strDLClassCodeNNotes": "Kodên kategorîya DL N",
             "strDLClassCodeNTo": "Kategorîya DL N têbé",
             "strDLClassCodeREFrom": "Kategorîya DL RE têbé",
             "strDLClassCodeRENotes": "Kodên kategorîya DL RE",
             "strDLClassCodeRETo": "Kategorîya DL RE têbé",
             "strDLClassCodeRFrom": "Kategorîya DL R têbé",
             "strDLClassCodeRNotes": "Kodên kategorîya DL R",
             "strDLClassCodeRTo": "Kategorîya DL R têbé",
            "strDLClassCodeSFrom": "Klasa DL S ji rojê",
                "strDLClassCodeSNotes": "Kodên klase DL S",
                "strDLClassCodeSTo": "Klasa DL S ji rojê",
                "strDLClassCodeTBFrom": "Klasa DL TB ji rojê",
                "strDLClassCodeTBNotes": "Kodên klase DL TB",
                "strDLClassCodeTBTo": "Klasa DL TB ji rojê",
                "strDLClassCodeTFrom": "Klasa DL T ji rojê",
                "strDLClassCodeTMFrom": "Klasa DL TM ji rojê",
                "strDLClassCodeTMNotes": "Kodên klase DL TM",
                "strDLClassCodeTMTo": "Klasa DL TM ji rojê",
                "strDLClassCodeTNotes": "Kodên klase DL T",
                "strDLClassCodeTRFrom": "Klasa DL TR ji rojê",
                "strDLClassCodeTRNotes": "Kodên klase DL TR",
                "strDLClassCodeTRTo": "Klasa DL TR ji rojê",
                "strDLClassCodeTTo": "Klasa DL T ji rojê",
                "strDLClassCodeTVFrom": "Klasa DL TV ji rojê",
                "strDLClassCodeTVNotes": "Kodên klase DL TV",
                "strDLClassCodeTVTo": "Klasa DL TV ji rojê",
                "strDLClassCodeVFrom": "Klasa DL V ji rojê",
                "strDLClassCodeVNotes": "Kodên klase DL V",
                "strDLClassCodeVTo": "Klasa DL V ji rojê",
                "strDLClassCodeWFrom": "Klasa DL W ji rojê",
                "strDLClassCodeWNotes": "Kodên klase DL W",
                "strDLClassCodeWTo": "Klasa DL W ji rojê",
                "strDLDuplicateDate": "Roja ji derbasdarî",
                "strDLEndorsed": "Koda destegihî",
                "strDLIssType": "Têrêza kartê",
                "strDLRecordCreated": "Nivîsa hatiye çêkirin",
                "strDLRestrictionCode": "Koda încirbozkirinê DL",
                "strDLUnder18Date": "Roja 18ê ji dayîna",
                "strDLUnder19Date": "Roja 19ê ji dayîna",
                "strDLUnder21Date": "Roja 21ê ji dayîna",
                "strDNINumber": "Nûmra DNI",
                "strDSCertificateIssuer": "Serlêkê DS",
                "strDSCertificateSubject": "Mamoste DS",
                "strDSCertificateValidFrom": "Serlêka DS ji rojê",
                "strDSCertificateValidTo": "Serlêka DS ji rojê",
                "strDUFNumber": "Nûmra DUF",
                "strDataDiscriminator": "Diskriminantê datayê",
                "strDateFirstRenewal": "Roja yekemîn a renou",
                "strDateOfBirthOfHusband": "Roja dayîna zêrê",
                "strDateOfBirthOfWife": "Roja dayîna jinê",
                "strDateOfInsuranceExpiry": "Roja berdanê ya bîrkçûnê",
                "strDateSecondRenewal": "Roja duyemîn a renou",
                "strDateofBirth": "Roja dayîna",
                "strDateofBirthCheckDigit": "Nûmra kontrolê ya roja dayîna",
                "strDateofBirthChecksum": "Checksum ya roja dayîna",
                "strDateofCreation": "Roja çêkirinê",
                "strDateofExpiry": "Roja berdanê",
                "strDateofExpiryCheckDigit": "Nûmra kontrolê ya roja berdanê",
                "strDateofExpiryChecksum": "Checksum ya roja berdanê",
                "strDateofFlight": "Roja flîta",
                "strDateofIssue": "Roja çêkirinê",
                "strDateofIssueBoardingPass": "Roja çêkirinê ya paspirtê",
                "strDateofIssueCheckDigit": "Nûmra kontrolê ya roja çêkirinê",
                "strDateofIssueChecksum": "Checksum ya roja çêkirinê",
                "strDateofPersonalization": "Roja personalizasyonê",
                "strDateofRegistration": "Roja nûmêranî",
                "strDay": "Roj",
                "strDepartment": "Departman",
                "strDeptNumber": "Nûmra departmanê",
                "strDestination": "Destinasyon",
                "strDiscretionaryData": "Datayê dewlemend",
                "strDoDNumber": "Nûmra DoD",
                "strDocumentClassCode": "Koda klase belgeyê",
                "strDocumentClassName": "Navê klase belgeyê",
                "strDocumentDiscriminator": "Diskriminantê belgeyê",
                "strDocumentNumber": "Nûmra belgeyê",
                "strDocumentNumberCheckDigit": "Nûmra kontrolê ya nûmreyê belgeyê",
                "strDocumentNumberChecksum": "Checksum ya nûmreyê belgeyê",
                "strDocumentSeries": "Serî belgeyê",
                "strDocumentTooSmall": "Belgeyê di çarçoveyê de bicîh bikin",
                "strDonor": "Donor",
                "strDossierNumber": "Nûmra dosyê",
                "strDurationofStay": "Mevtiya manzilê",
                "strECEnvironmentalType": "Tipa environtala veyîna",
                "strEDLDG1": "Elemenên textê (DG1)",
                "strEDLDG10": "ne definiye (DG10)",
                "strEDLDG11": "Data domêtîk (DG11)",
                "strEDLDG12": "Alerta neharî (DG12)",
                "strEDLDG13": "Informasyona Authentikasyonê Aktif (DG13)",
                "strEDLDG14": "Informasyona EAC (DG14)",
                "strEDLDG2": "Informasyona malbatê (DG2)",
                "strEDLDG3": "Detayên hêlkerê (DG3)",
                "strEDLDG4": "Îmageya portreta (DG4)",
                "strEDLDG5": "Ozna / nîşana navîn (DG5)",
                "strEDLDG6": "Biometri - Rûyê (DG6)",
                "strEDLDG7": "Biometri - Nivîsên parmakê (DG7)",
                "strEDLDG8": "Biometri - Dîtina Çavkanê (DG8)",
                "strEDLDG9": "Biometri - Yekemîn (DG9)",
                "strEFCOM": "EF.COM",
                "strEFCVCA": "EF.CVCA",
                "strEFCardAccess": "EF.CardAccess",
                "strEFCardSecurity": "EF.CardSecurity",
                "strEFChipSecurity": "EF.ChipSecurity",
                "strEFSOD": "EF.SOD",
                "strEQVCode": "Koda EQV",
                "strElectronicTicketIndicator": "Indikatora biletelektronîkê",
                "strElement": "Element",
                "strEndorsementExpirationDate": "Roja berdanê ya destegihî",
                "strEngineModel": "Modela motorê",
                "strEngineNumber": "Nûmra motorê",
                "strEnginePower": "Qutyara motorê",
                "strEngineVolume": "Gelê motorê",
                "strError": "Xet",
                "strExamDate": "Roja examê",
                "strExeptInTanks": "Pîvane di tankên de nehatine",
                "strEye": "Çav",
                "strEyesColor": "Renga çavê",
                "strFaculty": "Facultê",
                "strFalseLuminescence": "Luminansê berz",
                "strFamilyName": "Navê zarokê",
                "strFamilyNameTruncation": "Navê zarokê bicîh",
                "strFastTrack": "Servîsa Fast Track",
                "strFatherCountryOfBirth": "Welatê dayika zêrê",
                "strFatherDateOfBirth": "Roja dayîna zêrê",
                "strFatherGivenName": "Navê zêrê",
                "strFatherPersonalNumber": "Nûmra zêrê",
                "strFatherPlaceOfBirth": "Plaka dayika zêrê",
                "strFatherSurname": "Navê zêrê",
                "strFathersName": "Navê zêrê",
                "strFathersNameRUS": "Navê zêrê (Netwaveland)",
                "strFederalElections": "Heleba federal",
                "strFee": "Taxa",
                "strFieldFromMRZ": "Mezra ji MRZ",
                "strFieldTypeDocumentImage": "Îmageya belgeyê",
                "strFillElement": "Elemenda biharê",
                "strFinalCheckDigit": "Nûmra kontrolê ya final",
                "strFinalChecksum": "Checksum ya final",
                "strFingerprint": "Nivîsên parmakê",
                "strFirstIssueDate": "Roja yekemîn a çêkirinê",
                "strFirstNameTruncation": "Navê yekemîn bicîh",
                "strFlightNumber": "Nûmra flîta",
                "strFolioNumber": "Nûmra folio",
                "strFormOfEducation": "Forma edukasyonê",
                "strFreeBaggageAllowance": "Hewayê bagajê",
                "strFrequentFlyerAirlineDesignator": "Desîgnatora veyîna pilêrê",
                "strFrequentFlyerNumber": "Nûmra pilêrê",
                "strFromAirportCode": "Koda aeropuortê",
                "strFuelType": "Tipa bûyê",
                "strGNIBNumber": "Nûmra GNIB",
                "strGhostPortrait": "Portreta ghost",
                "strGivenNames": "Navê",
                "strGivenNamesRUS": "Navê (Netwaveland)",
                "strGlaresOnDocument": "Ji ronahiya belgeyê dûr bixin",
                "strGrandfatherName": "Navê bibînerê",
                "strHairColor": "Rengê por",
            "strHealthNumber": "Nûmra bîrkçûnê",
            "strHeight": "Alî",
             "strHoldDocumentStraight": "Belgeyê raste bînin",
             "strHoloSimple": "Hevçandinê Holograma",
             "strHoloVerifyDinamic": "Pêşbînîna Holograma Dinamik",
             "strHoloVerifyMultiStatic": "Pêşbînîna Holograma Statîkê Hevkariyê",
             "strHoloVerifyStatic": "Pêşbînîna Holograma Statîkê",
             "strHolograms": "Hologram",
             "strIPI": "IPI (Informasyonê Giranê Navdar)",
             "strIRB900": "Tinta IR B900",
             "strIRVis": "Transparansiya IR",
             "strISOIssuerIDNumber": "Nûmra ya ID ya Îssyerê ISO",
             "strIdentifier": "Identifikator",
             "strIdentityCardNumber": "Nûmra ya kartê identîtî",
             "strIdentityCardNumberCheckDigit": "Çekdîta nûmreyê kartê identîtî",
             "strIdentityCardNumberChecksum": "Çeksumê nûmreyê kartê identîtî",
             "strImagePattern": "Paterna wêneyê",
             "strInTanks": "Di tankeyan de",
             "strInventoryNumber": "Nûmra ya malper",
             "strInvitationNumber": "Nûmra ya daxwaz",
             "strInvitationNumberCheckDigit": "Çekdîta nûmreyê daxwazê",
             "strInvitationNumberChecksum": "Çeksumê nûmreyê daxwazê",
             "strInvitedBy": "Di navê da...",
             "strIssueTimestamp": "Roja weşandina",
             "strIssuingStateCode": "Kodê dewleta weşandina",
             "strIssuingStateName": "Dewleta weşandina",
             "strJurisdictionEndorsementCode": "Kodê destûra dewleta",
             "strJurisdictionRestrictionCode": "Kodê kewnayê dewleta",
             "strJurisdictionVehicleClass": "Klasê ambarê dewleta",
             "strKeepDeviceStill": "Amûrê hîn bikin",
             "strLicenseNumber": "Nûmra ya licansa",
             "strLimitedDurationDocumentIndicator": "Îndîkatora belgeyê bi muddêta sînor",
             "strLine1CheckDigit": "Çekdîta lînê 1",
             "strLine1Checksum": "Çeksumê lînê 1",
             "strLine1OptionalData": "Datayê opsîonal li lînê 1",
             "strLine2CheckDigit": "Çekdîta lînê 2",
             "strLine2Checksum": "Çeksumê lînê 2",
             "strLine2OptionalData": "Datayê opsîonal li lînê 2",
             "strLine3CheckDigit": "Çekdîta lînê 3",
             "strLine3Checksum": "Çeksumê lînê 3",
             "strLine3OptionalData": "Datayê opsîonal li lînê 3",
             "strLookingDocument": "Belgeyekê di girêka xwe de...",
             "strMCNoviceDate": "Roja pêşketina statûya Motorcycle Novice",
             "strMRZ": "MRZ",
             "strMRZLinesICAORFID": "Lînên MRZ ji bo RFID ya ICAO",
             "strMRZString1": "Lîna MRZ 1",
             "strMRZString2": "Lîna MRZ 2",
             "strMRZString3": "Lîna MRZ 3",
             "strMRZStrings": "Lînên MRZ",
             "strMRZStringsWithCorrectCheckSums": "Lînên MRZ bi çeksumên corê",
             "strMRZType": "Tîpa MRZ",
             "strMailingAddressCity": "Adresê posteyê - şaredariye",
             "strMailingAddressJurisdictionCode": "Adresê posteyê - kodê dewleta",
             "strMailingAddressPostalCode": "Adresê posteyê - koda poştê",
             "strMailingAddressStreet": "Adresê posteyê - çarxane",
             "strMake": "Tir",
             "strMaritalStatus": "Statûya zewacê",
             "strMaxMassofTrailerBraked": "Masseya maxîma ambarê (bi qafzandina)",
             "strMaxMassofTrailerUnbraked": "Masseya maxîma ambarê (be qafzandina)",
             "strMaxSpeed": "Lewreya maxîma",
             "strMedicalIndicatorCodes": "Noteyên medikal/kodên",
             "strMiddleName": "Navê navîn",
             "strMiddleNameTruncation": "Qezenoka navê navîn",
             "strMifareData": "Datayê MIFARE",
             "strMifareValidity": "Dirêjîya MIFARE",
             "strMilitaryBookNumber": "Nûmra ya kitêba leşkerî",
             "strModel": "Model",
             "strMonth": "Mehe",
             "strMortgageBy": "Di navê da...",
             "strMotherCountryOfBirth": "Welatiya dayikê li deriya jidayetiya",
             "strMotherDateOfBirth": "Roja jidayetiya dayikê",
             "strMotherGivenName": "Navê dayikê",
             "strMotherPersonalNumber": "Nûmra ya personelê dayikê",
             "strMotherPlaceOfBirth": "Plakê jidayetiya dayikê",
             "strMotherSurname": "Navê dayikê",
             "strMothersName": "Navê dayikê",
             "strNamePrefix": "Prêktîfê navê",
             "strNameSuffix": "Sufîxê navê",
             "strNationality": "Netewe",
             "strNationalityCode": "Koda neteweyê",
             "strNonResidentIndicator": "Îndîkatora neteweyê ne-malper",
             "strNone": "Ne yekê",
             "strNotDefined": "Ne defîn kirî",
             "strNumberOfCardIssuance": "Nûmra ya kartên weşandinê",
             "strNumberOfCardIssuanceCheckDigit": "Çekdîta nûmreyê kartên weşandinê",
             "strNumberOfCardIssuanceChecksum": "Çeksumê nûmreyê kartên weşandinê",
             "strNumberOfCylinders": "Nûmra ya silindran",
             "strNumberofAxels": "Nûmra ya axlan",
             "strNumberofDuplicates": "Nûmra ya duplikatên",
             "strNumberofEntries": "Nûmra ya girêkan",
             "strNumberofSeats": "Nûmra ya sedan",
             "strNumberofStandingPlaces": "Nûmra ya cehên stendinê",
             "strOCRNumber": "Nûmra ya OCR",
             "strOK": "OK",
             "strObservations": "Parastiyan",
             "strOldDateOfIssue": "Roja weşandina piştrast",
             "strOldDocumentNumber": "Nûmra ya belgeyê piştrast",
             "strOldPlaceOfIssue": "Plaka weşandina piştrast",
             "strOptionalData": "Datayê opsîonal",
             "strOptionalDataCheckDigit": "Çekdîta datayê opsîonal",
             "strOptionalDataChecksum": "Çeksumê datayê opsîonal",
            "strOptionalDetails": "Detayên opsîonal",
             "strOrganization": "Korporasyon",
             "strOther": "Yekê din",
             "strOtherName": "Navê din",
             "strOtherPersonName": "Navê kesê din",
             "strOtherValidID": "IDên valîd ên din",
             "strOwner": "Malik",
             "strPDF417Codec": "Codec PDF417",
             "strPNRCode": "Koda PNR",
             "strParrentsGivenNames": "Navên dadên",
             "strPassportNumber": "Nûmra ya pasaporta",
             "strPassportNumberCheckDigit": "Çekdîta nûmreyê pasaporta",
             "strPassportNumberChecksum": "Çeksumê nûmreyê pasaporta",
             "strPatronHeaderVersion": "Versyonê patronê",
             "strPatternDifferentLinesThickness": "Goraniya kalîtya lînên paternê",
             "strPatternIRInvisible": "Paterna nêzîkê IR",
             "strPatternNotInterrupted": "Paşnavê nîne",
             "strPatternNotShifted": "Elemenên paternê nîne bi têgihê",
             "strPatternSameColors": "Rengên paşnavê",
             "strPayGrade": "Grada mafê",
             "strPayloadCapacity": "Kapasîta payload",
             "strPermissibleAxleLoad": "Masseya destûrê axla",
             "strPermitDLClass": "Klasê permitê",
             "strPermitDateofExpiry": "Roja expîryê permitê",
             "strPermitDateofIssue": "Roja weşandina permitê",
             "strPermitEndorsed": "Kodê destûra permitê",
             "strPermitIdentifier": "Identifikatorê permitê",
             "strPermitRestrictionCode": "Kodê kewnayê permitê",
             "strPersonToNotifyAddress": "Adresa kesê ku bi navê...",
             "strPersonToNotifyDateofRecord": "Roja girêka kesê ku bi navê...",
             "strPersonToNotifyName": "Navê kesê ku bi navê...",
             "strPersonToNotifyPhone": "Telefonê kesê ku bi navê...",
             "strPersonalNumber": "Nûmra ya personal",
             "strPersonalNumberCheckDigit": "Çekdîta nûmreyê personal",
             "strPersonalNumberChecksum": "Çeksumê nûmreyê personal",
             "strPersonalSummary": "Sumaryê personal",
             "strPersonalizationSN": "Nûmra ya personalizasyonê",
             "strPhone": "Telefon",
             "strPhotoArea": "Reqafta wêneyê",
             "strPhotoColor": "Renga wêneyê",
             "strPhotoCorners": "Koynên wêneyê",
             "strPhotoElement": "Elemenên wêneyê",
             "strPhotoEmbedType": "Tîpa încirkirina wêneyê",
             "strPhotoProcessing": "Pêvajoyê wêneyê...",
             "strPhotoShape": "Forma wêneyê",
             "strPhotoSizeCheck": "Pêvajoyê reqafta wêneyê",
             "strPlaceDocumentInFrame": "Belgeyê di çarçoveyê de bicîh bikin",
             "strPlaceOfBirthRUS": "Plaka jidayetiya (National)",
             "strPlaceOfBirthStateCode": "Koda plakê jidayetiya",
             "strPlaceOfExamination": "Plaka examînasyona",
             "strPlaceOfIssue": "Plaka weşandina",
             "strPlacePhoneOnDoc": "Plaka telefonê di belgeyê de...",
             "strPlaceofBirth": "Plaka jidayetiya",
             "strPlaceofBirthArea": "Plaka jidayetiya",
             "strPlaceofRegistration": "Plaka rejîstyrasyonê",
             "strPoliceDistrict": "Qezayê polîsê",
             "strPortrait": "Portre",
             "strPortraitComparison": "Goraniya portreyê",
             "strPortraitOfChild": "Portreya zarokê",
             "strPortraitVSCamera": "Portre vs imajê kameryê",
             "strPortraitVSGhost": "Portre vs fîlmê ghost",
             "strPortraitVSRFID": "Portre vs chipê RFID",
             "strPowerWeightRatio": "Rêveberê giştî",
             "strPrecinct": "Precinct",
             "strPrepareCamera": "Kamara ji bo...",
             "strPresentNextPage": "Ji kerema xwe rûpela din peyda bikin",
             "strPreviousType": "Tîpa/numra ya belgeyê berê",
             "strProcessingDocument": "Pêvajoya belgeyê...",
             "strProfession": "Profesyon",
             "strProfessionalIdNumber": "Nûmra ya ID ya profesyonel",
             "strProofOfCitizenship": "Doxlê neteweyê",
             "strPseudoCode": "Kodê pseudonîmê",
             "strPurposeOfEntry": "Mebîna",
             "strRFIDVSCamera": "Chipê RFID vs imajê kameryê",
             "strRaceEthnicity": "Ras/etnîk",
             "strRank": "Destûr",
             "strReadingRFID": "Pêvajoyê RDF",
             "strReadingRFIDDGiOS": "Pêvajoyê RDF %@",
             "strRecognizedDocumentType": "Tîpa belgeyê",
             "strReferenceNumber": "Numra ya giştî",
             "strReferenceNumberCheckDigit": "Çekdîta numra ya giştî",
             "strReferenceNumberChecksum": "Çeksumê numra ya giştî",
             "strRegCertBodyNumber": "Nûmra ya body",
             "strRegCertBodyType": "Tîpa body",
             "strRegCertCarColor": "Renga ambarê",
             "strRegCertCarMark": "Tirê ambarê",
             "strRegCertCarModel": "Modelê ambarê",
             "strRegCertCarType": "Tîpa ambarê",
             "strRegCertMaxWeight": "Masseya maxîma",
             "strRegCertRegNumber": "Nûmra ya rejîstyrasyonê",
             "strRegCertRegNumberCheckDigit": "Çekdîta nûmreyê rejîstyrasyonê",
             "strRegCertRegNumberChecksum": "Çeksumê nûmreyê rejîstyrasyonê",
             "strRegCertVIN": "Nûmra ya identifikasyonê",
             "strRegCertVINCheckDigit": "Çekdîta nûmreyê VIN",
             "strRegCertVINChecksum": "Çeksumê nûmreyê VIN",
             "strRegCertVehicleITSCode": "Koda ITSê ambarê",
             "strRegCertWeight": "Masseya",
             "strRelationship": "Rabûtiya",
             "strReligion": "Dîn",
             "strRemainderTerm": "Mevîna",
             "strResidentFrom": "Rezidan ji",
             "strResidentUntil": "Rezidan heta",
             "strRetirementNumber": "Nûmra ya pensiyê",
             "strRevisionDate": "Roja revîzyonê",
             "strRoomNumber": "Nûmra ya oqafê",
             "strSBHIntegrityOptions": "Opçionên SBHê",
             "strSBHSecurityOptions": "Opçionên SBHê",
             "strSeatNumber": "Nûmra ya sedana",
             "strSecondSurname": "Navê duyemîn",
             "strSection": "Seksiyon",
             "strSecurityText": "Teksta giştî",
             "strSelecteeIndicator": "Indîkatôra selectee",
             "strSequenceNumber": "Nûmra ya serî",
             "strSerialNumber": "Nûmra ya seri",
             "strSettings": "Setings",
             "strSex": "Jin",
             "strSignature": "Ozgar",
             "strSkinColor": "Renga dermanê",
             "strSocialSecurityNumber": "Nûmra ya sosyal",
             "strSpCode": "Koda spesîyal",
             "strSpecialNotes": "Noteyên spesîyal",
             "strSponsor": "Sponsor",
             "strSponsorSSN": "SSNê sponsorê",
             "strSponsorService": "Serwerê sponsorê",
             "strSponsorStatus": "Statûsa sponsorê",
             "strStamp": "Merk",
             "strStampNumber": "Nûmra ya merkê",
             "strStatusDateofExpiry": "Roja expîryê statûsê",
             "strSurname": "Navê",
             "strSurnameAndGivenNames": "Navê û navên dadê",
             "strSurnameAndGivenNamesCheckDigit": "Çekdîta navê û navên dadê",
             "strSurnameAndGivenNamesChecksum": "Çeksumê navê û navên dadê",
             "strSurnameAndGivenNamesRUS": "Navê û navên dadê (National)",
             "strSurnameAtBirth": "Navê li deriya jidayetiya",
             "strSurnameOfHusbandAfterRegistration": "Navê kurê li rejîstyrasyonê",
             "strSurnameOfWifeAfterRegistration": "Navê jinê li rejîstyrasyonê",
             "strSurnameofSpose": "Navê zêrê",
             "strTax": "Tax",
             "strTaxNumber": "Nûmra ya taxê",
             "strTelexCode": "Koda telexê",
             "strTerritorialValidity": "Valîtîya teritoryal",
             "strTicketNumber": "Nûmra ya bile",
             "strTitle": "Pozisyon",
             "strToAirportCode": "Koda aeroparkê",
             "strTorchUnavailable": "Torchê nîne",
             "strTrackingNumber": "Nûmra ya trackingê",
             "strTrailerHitch": "Hitchê ambarê",
             "strTransactionNumber": "Nûmra ya transaksiyonê",
             "strTransmissionType": "Tîpa transmissiya",
             "strTypeApprovalNumber": "Tîpa nûmra ya",
             "strURL": "URL",
             "strUSCIS": "USCIS",
             "strUV": "UV",
             "strUVFibers": "Fibersên UV",
             "strUvluminescence": "Uv",
             "strUnableCaptureMedia": "Kamara konfigura",
            "strUniqueCustomerIdentifier": "Identifikatorê xwedîkarê yekîn",
             "strVRCDataObjectEntry": "Dataya ambarê ji bo grupa DG1",
             "strValidityPeriod": "Mevîna valîtî",
             "strVehicleCategory": "Kategorîya ambarê",
             "strVeteran": "Veteran",
             "strVisaClass": "Klasê vizê",
             "strVisaID": "IDê vizê",
             "strVisaIDCheckDigit": "Çekdîta IDê vizê",
             "strVisaIDChecksum": "Çeksumê IDê vizê",
             "strVisaIDRUS": "IDê vizê (National)",
             "strVisaNumber": "Nûmra ya vizê",
             "strVisaNumberCheckDigit": "Çekdîta nûmreyê vizê",
             "strVisaNumberChecksum": "Çeksumê nûmreyê vizê",
             "strVisaSubClass": "Klasê zêrê vizê",
             "strVisaType": "Tîpa vizê",
             "strVisaValidFrom": "Viza ji bo...",
             "strVisaValidUntil": "Viza heta...",
             "strVisaValidUntilCheckDigit": "Çekdîta roja expîryê vizê",
             "strVisaValidUntilChecksum": "Çeksumê roja expîryê vizê",
             "strVisibleLight": "Rojê sînor",
             "strVoter": "Heval",
            "strVoterKey": "Nîşana Maf",
               "strVoucherNumber": "Nûmra ya Vouchera",
               "strWeight": "Giraniya",
               "strWeightPound": "Giraniya (pound)",
               "strYear": "Sal",
               "strYearsSinceIssue": "Salên li ser çêbûna",
               "streIDPlaceOfBirthCity": "Plakên Navê: Şared",
               "streIDPlaceOfBirthCountry": "Plakên Navê: Welat",
               "streIDPlaceOfBirthState": "Plakên Navê: Parêzgeh",
               "streIDPlaceOfBirthStreet": "Plakên Navê: Kêşan",
               "streIDPlaceOfBirthZipcode": "Plakên Navê: Kodê Postî",
               "streIDResidencePermit1": "Hawarê Dijwarî 1",
               "streIDResidencePermit2": "Hawarê Dijwarî 2",
               "strfppLeftIndexFinger": "Dêra Pêşeng a Sêwa",
               "strfppLeftLittleFinger": "Dêra Zêrîn a Sêwa",
               "strfppLeftMiddleFinger": "Dêra Navîn a Sêwa",
               "strfppLeftRingFinger": "Dêra Ring a Sêwa",
               "strfppLeftThumb": "Dêra Palê",
               "strfppRightIndexFinger": "Dêra Pêşeng a Rast",
               "strfppRightLittleFinger": "Dêra Zêrîn a Rast",
               "strfppRightMiddleFinger": "Dêra Navîn a Rast",
               "strfppRightRingFinger": "Dêra Ring a Rast",
               "strfppRightThumb": "Dêra Palê"
        ]
    }
}
