//
//  File.swift
//
//
//  Created by MOBILE on 20/05/24.
//

import Foundation

class SpanishDataValues {
    func getDictionary() -> [String: String] {
        return [
      
            "RFID_Error_AlreadyDone" : "RFID: La operación solicitada ya está realizada",
            "RFID_Error_Busy" : "RFID: RFID está ocupado",
            "RFID_Error_Failed" : "RFID: Fallido",
            "RFID_Error_FileIOError" : "Archivo RFID: Error de E/S",
            "RFID_Error_InvalidDirectory" : "RFID: Directorio inválido",
            "RFID_Error_InvalidParameter" : "RFID: Parámetro inválido en la llamada ExecuteCommand()",
            "RFID_Error_NoChipDetected" : "RFID: No se detectó ningún chip",
            "RFID_Error_NotAvailable" : "RFID: No disponible",
            "RFID_Error_NotEnoughMemory" : "RFID: Sin suficiente memoria",
            "RFID_Error_NotInitialized" : "RFID: Dispositivo no inicializado",
            "RFID_Error_NotPerformed" : "RFID: No realizado",
            "RFID_Error_OldFirmware" : "RFID: El firmware necesita ser actualizado a una versión más reciente",
            "RFID_Error_PCSC_CantConnectCard" : "PCSC: No se puede conectar la tarjeta",
            "RFID_Error_PCSC_CardIsBusy" : "PCSC: La tarjeta está ocupada",
            "RFID_Error_PCSC_CardIsNotConnected" : "PCSC: La tarjeta no está conectada",
            "RFID_Error_PCSC_ExtLe_Failed" : "PCSC: ExtLe fallido",
            "RFID_Error_PCSC_Failed" : "PCSC: Fallido",
            "RFID_Error_PCSC_FailedSCard" : "PCSC: Tarjeta inteligente fallida",
            "RFID_Error_PCSC_OperationCancelled" : "PCSC: Operación cancelada",
            "RFID_Error_PCSC_ReaderNotAvailable" : "PCSC: Lector no disponible",
            "RFID_Error_Session_AccessControl_AA_Failed" : "RFID: AA fallido",
            "RFID_Error_Session_AccessControl_CA_Failed" : "RFID: CA fallido",
            "RFID_Error_Session_AccessControl_IncorrectOptionCA" : "RFID: Opción CA incorrecta",
            "RFID_Error_Session_AccessControl_RI_Failed" : "RFID: RI fallido",
            "RFID_Error_Session_AccessControl_RequiresCA" : "RFID: Requiere CA",
            "RFID_Error_Session_AccessControl_RequiresCAKeys" : "RFID: Requiere claves CA",
            "RFID_Error_Session_AccessControl_RequiresPACE" : "RFID: Requiere PACE",
            "RFID_Error_Session_AccessControl_RequiresSM" : "RFID: Requiere SM",
            "RFID_Error_Session_AccessControl_RequiresTA" : "RFID: Requiere TA",
            "RFID_Error_Session_AccessControl_TA_Failed" : "RFID: TA fallido",
            "RFID_Error_Session_AccessControl_UnknownType" : "RFID: Tipo de control de acceso desconocido",
            "RFID_Error_Session_AccessKey_IncorrectData" : "RFID: Clave de acceso Datos incorrectos",
            "RFID_Error_Session_AccessKey_IncorrectSMType" : "RFID: Clave de acceso Tipo de SM incorrecto",
            "RFID_Error_Session_AccessKey_NotSet" : "RFID: Clave de acceso no establecida",
            "RFID_Error_Session_AccessKey_Restricted" : "RFID: Clave de acceso restringida",
            "RFID_Error_Session_AccessKey_UnknownType" : "RFID: Tipo de clave de acceso desconocido",
            "RFID_Error_Session_AccessKey_UnsupportedSMType" : "RFID: Tipo de SM no soportado por la clave de acceso",
            "RFID_Error_Session_File_AccessDenied" : "Archivo RFID: Acceso denegado",
            "RFID_Error_Session_File_CantReadData" : "Archivo RFID: No se puede leer los datos",
            "RFID_Error_Session_File_CantUseData" : "Archivo RFID: No se pueden usar los datos",
            "RFID_Error_Session_File_Contents_UnexpectedData" : "Archivo RFID: Contenidos con datos inesperados",
            "RFID_Error_Session_File_IncorrectData" : "Archivo RFID: Datos incorrectos",
            "RFID_Error_Session_File_NotEnoughData" : "Archivo RFID: Datos insuficientes",
            "RFID_Error_Session_File_UnexpectedData" : "Archivo RFID: Datos inesperados",
            "RFID_Error_Session_File_WrongTag" : "Archivo RFID: Etiqueta incorrecta",
            "RFID_Error_Session_IncorrectData" : "RFID: Datos incorrectos",
            "RFID_Error_Session_InvalidAuxData_CommunityID" : "RFID: ID de comunidad de datos auxiliares inválido",
            "RFID_Error_Session_InvalidAuxData_DateOfBirth" : "RFID: Fecha de nacimiento de datos auxiliares inválida",
            "RFID_Error_Session_InvalidAuxData_DateOfExpiry" : "RFID: Fecha de expiración de datos auxiliares inválida",
            "RFID_Error_Session_IsClosed" : "RFID: La sesión está cerrada",
            "RFID_Error_Session_PA_HashCheckFailed" : "RFID: Fallo en la comprobación del hash",
            "RFID_Error_Session_PA_SignatureCheckFailed" : "RFID: Fallo en la comprobación de la firma SO",
            "RFID_Error_Session_ProcedureType_NotSet" : "RFID: Tipo de procedimiento no establecido",
            "RFID_Error_Session_ProcedureType_Unknown" : "RFID: Tipo de procedimiento desconocido",
            "RFID_Error_Session_ProcedureType_Unsupported" : "RFID: Tipo de procedimiento no soportado",
            "RFID_Error_Session_PwdManagement_NotAuthorized" : "RFID: Gestión de contraseña no autorizada",
            "RFID_Error_Session_TerminalType_BadCertificate" : "RFID: Tipo de terminal con certificado inválido",
            "RFID_Error_Session_TerminalType_NotSet" : "RFID: Tipo de terminal no establecido",
            "RFID_Error_Session_TerminalType_Unknown" : "RFID: Tipo de terminal desconocido",
            "RFID_Error_Session_Terminal_UnsupportedOperation" : "RFID: Operación no soportada en el terminal",
            "RFID_Error_Session_eSign_PIN_NotSet" : "RFID: PIN de firma electrónica no establecido",
            "RFID_Error_Session_eSign_PIN_NotVerified" : "RFID: PIN de firma electrónica no verificado",
            "RFID_Error_Session_eSign_RequiresAppSelection" : "RFID: La firma electrónica requiere selección de aplicación",
            "RFID_Error_UnknownCommand" : "RFID: Comando desconocido",
            "RFID_LAYER6_APP_SELECTION_FAILURE" : "LAYER6: Falla en la selección de aplicación ISO7816_A_03 (Fallo en la selección de aplicación)",
            "RFID_LAYER6_EXT_AUTH_FAILURE" : "LAYER6: Fallo en la autenticación externa APDU_INS_EXTERNAL_AUTHENTICATE (Fallo en la autenticación externa)",
            "RFID_LAYER6_FILE_EOF1" : "LAYER6: Lectura más allá de EOF / EOF inesperado",
            "RFID_LAYER6_FILE_EOF2" : "LAYER6: Lectura más allá de EOF / EOF inesperado",
            "RFID_LAYER6_FILE_NOT_FOUND" : "LAYER6: Fallo en la selección de archivo / archivo no encontrado",
            "RFID_LAYER6_GENERAL_AUTH_FAILURE" : "LAYER6: Fallo general de autenticidad",
            "RFID_LAYER6_GET_CHALLENGE_FAILURE" : "LAYER6: Fallo en GET CHALLENGE",
            "RFID_LAYER6_INCORRECT_PARAMS" : "LAYER6: Parámetros incorrectos",
            "RFID_LAYER6_INT_AUTH_FAILURE" : "LAYER6: Fallo en APDU_INS_INTERNAL_AUTHENTICATE (Fallo en la autenticación interna)",
            "RFID_LAYER6_MSE_SET_AT_FAILURE" : "LAYER6: Fallo en MSE:Set AT",
            "RFID_LAYER6_MSE_SET_DST_FAILURE" : "LAYER6: Fallo en MSE:Set DST",
            "RFID_LAYER6_MSE_SET_KAT_FAILURE" : "LAYER6: Fallo en MSE:Set KAT",
            "RFID_LAYER6_MUTUAL_AUTH_ENC_FAIL" : "LAYER6: Falla en el cifrado de autenticación mutua ISO7816_B_02 (Fallo en el cifrado de autenticación mutua)",
            "RFID_LAYER6_MUTUAL_AUTH_FAILURE" : "LAYER6: Fallo en la autenticación mutua ISO7816_B_03 (Fallo en la autenticación mutua)",
            "RFID_LAYER6_MUTUAL_AUTH_MAC_FAIL" : "LAYER6: Fallo en el MAC de autenticación mutua ISO7816_B_01 (Fallo en el MAC de autenticación mutua)",
            "RFID_LAYER6_NON_TLV_RESPONSE_DATA" : "LAYER6: Datos de respuesta no TLV",
            "RFID_LAYER6_NO_REFERENCE_DATA" : "LAYER6: Sin datos de referencia",
            "RFID_LAYER6_PSO_CERTIFICATE_FAILURE" : "LAYER6: Fallo en la certificación PSO",
            "RFID_LAYER6_PWD_BLOCKED" : "LAYER6: Contraseña bloqueada",
            "RFID_LAYER6_PWD_BLOCKED_2" : "LAYER6: Contraseña bloqueada 2",
            "RFID_LAYER6_PWD_DEACTIVATED" : "LAYER6: Contraseña desactivada",
            "RFID_LAYER6_PWD_DEACTIVATED_2" : "LAYER6: Contraseña desactivada 2",
            "RFID_LAYER6_PWD_FAILED" : "LAYER6: Contraseña fallida",
            "RFID_LAYER6_PWD_SUSPENDED" : "LAYER6: Contraseña suspendida",
            "RFID_LAYER6_PWD_SUSPENDED_2" : "LAYER6: Contraseña suspendida 2",
            "RFID_LAYER6_SECURITY_MANAGER" : "LAYER6: La mensajería segura no fue activada",
            "RFID_LAYER6_SM_DO87_INCORRECT" : "LAYER6: Fallo en SM - criptograma incorrecto",
            "RFID_LAYER6_SM_DO87_MISSING" : "LAYER6: Fallo en SM - criptograma faltante",
            "RFID_LAYER6_SM_DO8E_MISSING" : "LAYER6: Fallo en SM - MAC faltante",
            "RFID_LAYER6_SM_DO99_MISSING" : "LAYER6: Fallo en SM - bytes de estado asegurados faltantes",
            "RFID_LAYER6_SM_MAC_INCORRECT" : "LAYER6: Fallo en SM - MAC incorrecto",
            "RFID_LAYER6_WRONG_RND_ICC_LENGTH" : "LAYER6: Longitud de datos incorrecta (APDU_INS_GET_CHALLENGE)",
            "RSDT_RFID_READING_FINISHED" : "La lectura de datos RFID ha finalizado",
            "TCT_Unknown" : "Desconocido",
            "chd_BackgroundComparisonError" : "La luminosidad de las dos páginas es diferente",
            "chd_BadAreaInAxial" : "Fallo en la protección retroreflectante",
            "chd_BarcodeDataFormatError" : "Error de formato de código de barras",
            "chd_BarcodeReadedWithErrors" : "El código de barras se ha leído con errores",
            "chd_BarcodeSizeParamsError" : "Error en los parámetros del código de barras",
            "chd_DocumentIsCancelling" : "El documento está cancelado",
            "chd_ElementShouldBeColored" : "El elemento debe ser a color",
            "chd_ElementShouldBeGrayscale" : "El elemento debe ser en escala de grises",
            "chd_ExceptionInModule" : "Excepción interceptada",
            "chd_FalseIPIParameters" : "Parámetros IPI incorrectos",
            "chd_FalseLuminiscenceError" : "Presencia de objetos luminescentes en exceso",
            "chd_FalseLuminiscenceInBlank" : "Falsa luminiscencia en UV",
            "chd_FalseLuminiscenceInMRZ" : "Luminiscencia excesiva en MRZ",
            "chd_FibersNotFound" : "No se encuentran las fibras",
            "chd_FieldPosCorrector_Highlight_IR" : "Luz excesiva en IR",
            "chd_FieldsComparisonLogicError" : "Error lógico al comparar campos",
            "chd_FixedPatternError" : "No coincidencia del objeto especificado",
            "chd_HologramElementAbsent" : "Holograma ausente",
            "chd_HologramElementPresent" : "Holograma encontrado",
            "chd_Hologram_Side_Top_Images_Absent" : "No hay imágenes laterales o superiores",
            "chd_IncorrectBackgroundLight" : "Brillo de fondo incorrecto",
            "chd_IncorrectTextColor" : "Color de texto incorrecto",
            "chd_InternalError" : "Error interno de procesamiento de datos",
            "chd_InvalidChecksum" : "Checksum inválido",
            "chd_InvalidFieldFormat" : "El formato del campo no coincide con la descripción del documento",
            "chd_InvalidInputData" : "Datos de entrada no válidos",
            "chd_InvisibleElementPresent" : "El objeto debe ser invisible",
            "chd_LogicError" : "Error lógico de datos",
            "chd_LowContrastInIRLight" : "Contraste incorrecto del objeto en luz IR",
            "chd_MobileImages_LowLightConditions" : "Condiciones de iluminación inadecuadas para capturar imágenes",
            "chd_MobileImages_WhileUVNoDifference" : "Baja diferencia entre imágenes en diferentes esquemas de iluminación",
            "chd_NecessaryImageNotFound" : "Falta la imagen requerida para esta verificación",
            "chd_NotAllBarcodesRead" : "Este documento debería contener más códigos de barras",
            "chd_OVI_BadColor_Front" : "Discrepancia de color del objeto OVI bajo luz blanca",
            "chd_OVI_BadColor_Percent" : "Bajo porcentaje de coincidencia entre los elementos OVI",
            "chd_OVI_BadColor_Side" : "Discrepancia de color del objeto OVI bajo luz axial",
            "chd_OVI_ColorInvariable" : "Color OVI invariable",
            "chd_OVI_IR_Invisible" : "Discrepancia de contraste del objeto OVI",
            "chd_OVI_InsufficientArea" : "Área insuficiente del objeto OVI",
            "chd_OVI_Wide_Color_Spread" : "Discrepancia en el rango de colores del objeto OVI",
            "chd_Pass" : "Sin errores",
            "chd_PhotoFalseLuminiscence" : "Falsa luminiscencia en el área de la foto",
            "chd_PhotoPattern_DifferentColors" : "Los colores del patrón en la foto y en el documento en blanco son diferentes",
            "chd_PhotoPattern_DifferentLinesThickness" : "Diferente grosor de las líneas del patrón",
            "chd_PhotoPattern_IR_Visible" : "Patrón de seguridad visible en IR",
            "chd_PhotoPattern_Interrupted" : "El patrón entre la foto y el documento en blanco tiene una interrupción",
            "chd_PhotoPattern_InvalidColor" : "Color no válido del patrón de seguridad",
            "chd_PhotoPattern_Not_Intersect" : "El borde de la foto no se intersecta con el patrón",
            "chd_PhotoPattern_PatternNotFound" : "El patrón no se encontró en el área de la foto",
            "chd_PhotoPattern_Shifted" : "El patrón en la foto está desplazado en relación con el patrón en blanco",
            "chd_PhotoPattern_Shifted_Vert" : "Las líneas del patrón están desplazadas verticalmente entre sí",
            "chd_PhotoSidesNotFound" : "No se encontró el borde de la foto requerido",
            "chd_PhotoSize_Is_Wrong" : "El tamaño de la foto es incorrecto",
            "chd_Photo_Corners_Is_Wrong" : "Las esquinas de la foto no cumplen con los requisitos",
            "chd_Photo_IsNot_Rectangle" : "La forma de la foto no es rectangular",
            "chd_PortraitComparison_NoLivePhoto" : "No hay imagen de cámara",
            "chd_PortraitComparison_NoPortraitDetected" : "No se encontró rostro en la imagen",
            "chd_PortraitComparison_NoServiceLicense" : "No hay licencia para el servicio",
            "chd_PortraitComparison_NoServiceReply" : "El servicio no responde",
            "chd_PortraitComparison_NotEnoughImages" : "No hay suficientes imágenes",
            "chd_PortraitComparison_PortraitsDiffer" : "Los retratos no coinciden",
            "chd_PortraitComparison_ServiceError" : "Error del servicio",
            "chd_SourcesComparisonError" : "No coincidencia de datos de diferentes fuentes",
            "chd_SpecksInUV" : "Sobreexposición o reflejos en la imagen bajo luz UV",
            "chd_SyntaxError" : "Error de sintaxis en los datos",
            "chd_TextColorShouldBeBlue" : "El color del texto debería ser azul",
            "chd_TextColorShouldBeGreen" : "El color del texto debería ser verde",
            "chd_TextColorShouldBeRed" : "El color del texto debería ser rojo",
            "chd_TextShouldBeBlack" : "El color del texto debería ser negro",
            "chd_TooLowResolution" : "Resolución demasiado baja para detectar fibras",
            "chd_TooManyObjects" : "Demasiados objetos",
            "chd_TooMuchShift" : "El valor de desplazamiento es mayor que el valor permitido",
            "chd_TrueLuminiscenceError" : "No coincidencia de objetos luminiscentes",
            "chd_UVDullPaperError" : "Error en la verificación de papel UV mate",
            "chd_UVDullPaper_Blank" : "Verificación de papel UV mate en el área del documento en blanco",
            "chd_UVDullPaper_MRZ" : "Verificación de papel UV mate en el área MRZ",
            "chd_UVDullPaper_Photo" : "Verificación de papel UV mate en el área de la foto",
            "chd_UncertainVerification" : "No se puede tomar una decisión confiable",
            "chd_Unknown" : "Denegación desconocida",
            "chd_VisibleElementAbsent" : "No hay objeto visible bajo IR",
            "strAGY" : "AGY",
            "strAKADateofBirth" : "Fecha de nacimiento AKA",
            "strAKAGivenNames" : "Nombres dados AKA",
            "strAKANamePrefix" : "Prefijo de nombre AKA",
            "strAKANameSuffix" : "Sufijo de nombre AKA",
            "strAKASocialSecurityNumber" : "Número de seguro social AKA",
            "strAKASurname" : "Apellido AKA",
            "strAKASurnameAndGivenNames" : "Nombre completo AKA",
            "strALTCode" : "Código ALT",
            "strAcademicTitle" : "Título académico",
            "strAccessibilityCameraButton" : "Capturar una imagen y comenzar el procesamiento",
            "strAccessibilityCloseButton" : "Cerrar",
            "strAccessibilityTorchButton" : "Linterna",
            "strAccompaniedby" : "Acompañado por",
            "strAddress" : "Dirección",
            "strAddressArea" : "Área",
            "strAddressBuilding" : "Unidad",
            "strAddressCity" : "Ciudad",
            "strAddressCountry" : "País",
            "strAddressFlat" : "Apartamento",
            "strAddressHouse" : "Edificio",
            "strAddressJurisdictionCode" : "Código de jurisdicción",
            "strAddressLocation" : "Ubicación",
            "strAddressMunicipality" : "Municipio",
            "strAddressPostalCode" : "Código postal",
            "strAddressState" : "Estado",
            "strAddressStreet" : "Calle",
            "strAdministrativeNumber" : "Número administrativo",
            "strAge" : "Edad",
            "strAgeAtIssue" : "Edad al emitir",
            "strAirlineDesignatorofboardingpassissuer" : "Designador de aerolínea del emisor del pase de abordar",
            "strAirlineName" : "Nombre de la aerolínea",
            "strAirlineNameFrequentFlyer" : "Programa de lealtad de la aerolínea para viajeros frecuentes",
            "strAirlineNumericCode" : "Código numérico de la aerolínea",
            "strAirportFrom" : "Aeropuerto de salida",
            "strAirportTo" : "Aeropuerto de llegada",
            "strAllergies" : "Alergias",
            "strApplicationDoNotHavePermission" : "La aplicación no tiene permiso para usar la cámara, por favor cambie la configuración de privacidad",
            "strApplicationNumber" : "Número de aplicación",
            "strArtisticName" : "Seudónimo",
            "strAuditInformation" : "Número para validación",
            "strAuthentification" : "Verificación de autenticidad",
            "strAuthority" : "Autoridad emisora",
            "strAuthorityCode" : "Código de autoridad emisora",
            "strAuthorityRUS" : "Autoridad emisora (Nacional)",
            "strAuthorizationNumber" : "Número de autorización",
            "strAxialProtection" : "Protección retroreflectante",
            "strBDBType" : "Tipo de BDB",
            "strBankCardNumber" : "Número de tarjeta bancaria",
            "strBankCardValidThru" : "Validez de la tarjeta bancaria",
            "strBanknoteNumber" : "Número de billete de banco",
            "strBarcode" : "Código de barras",
            "strBarcodeFormatCheck" : "Verificación de formato de código de barras",
            "strBenefitsNumber" : "Número de beneficios",
            "strBinaryCode" : "Código binario",
            "strBiometricFormatOwner" : "Propietario del formato biométrico",
            "strBiometricFormatType" : "Tipo de formato biométrico",
            "strBiometricProductID" : "ID del producto biométrico",
            "strBiometricSubtype" : "Subtipo biométrico",
            "strBiometricType" : "Tipo biométrico",
            "strBlankElement" : "Elemento en blanco",
            "strBloodGroup" : "Grupo sanguíneo",
            "strBookletNumber" : "Número de folleto",
            "strCCWUntil" : "Girar a la izquierda hasta",
            "strCDLClass" : "Clase de CDL",
            "strCSCCode" : "Código CSC",
            "strCVV" : "CVV/CVC",
            "strCaliber" : "Calibre",
            "strCameraUnavailable" : "Cámara no disponible",
            "strCardAccessNumber" : "Número de acceso a la tarjeta",
            "strCategory" : "Categoría",
            "strCenturyDateOfBirth" : "Siglo de nacimiento",
            "strChassisNumber" : "Número de chasis",
            "strCheckInSequenceNumber" : "Número de secuencia de check-in",
            "strChildren" : "Niños",
            "strCitizenshipOfFirstPerson" : "Ciudadanía del primer individuo",
            "strCitizenshipOfSecondPerson" : "Ciudadanía del segundo individuo",
            "strCivilStatus" : "Estado civil",
            "strColorDynamic" : "Dinámica de color",
            "strCommercialVehicleCodes" : "Código de vehículo comercial",
            "strCompanyName" : "Nombre de la empresa",
            "strCompartmentCode" : "Código de compartimento",
            "strComplexion" : "Complexión",
            "strComplianceType" : "Tipo de cumplimiento",
            "strConditions" : "Condiciones",
            "strConfiguration" : "Configuración",
            "strControlNo" : "Número de control",
            "strCopy" : "Copia",
            "strCourtCode" : "Código de tribunal",
            "strCty" : "Condado",
            "strCurrentDate" : "Fecha actual",
            "strCustodyInfo" : "Información de custodia",
            "strDFTAppDirectory" : "Directorio de la aplicación",
            "strDFTCertificate" : "Certificado",
            "strDG1" : "Zona de Lectura Mecánica (DG1)",
            "strDG10" : "no definido (DG10)",
            "strDG11" : "Detalle(s) personal(es) adicional(es) (DG11)",
            "strDG12" : "Detalles del documento adicional (DG12)",
            "strDG13" : "Detalle(s) opcional(es) (DG13)",
            "strDG14" : "Información de EAC (DG14)",
            "strDG15" : "Información de Autenticación Activa (DG15)",
            "strDG16" : "Persona(s) a notificar (DG16)",
            "strDG17" : "DG17",
            "strDG18" : "DG18",
            "strDG19" : "DG19",
            "strDG2" : "Biometría - Datos faciales (DG2)",
            "strDG20" : "DG20",
            "strDG3" : "Biometría - Huella(s) dactilar(es) (DG3)",
            "strDG4" : "Biometría - Datos del iris (DG4)",
            "strDG5" : "Retrato(s) (DG5)",
            "strDG6" : "no definido (DG6)",
            "strDG7" : "Imagen de firma/marca habitual (DG7)",
            "strDG8" : "no definido (DG8)",
            "strDG9" : "no definido (DG9)",
            "strDLCDLRestrictionCode" : "Código de restricción de la CDL",
            "strDLClass" : "Categoría de la DL",
            "strDLClassCodeA1From" : "Categoría de DL A1 válida desde",
            "strDLClassCodeA1Notes" : "Códigos de categoría de DL A1",
            "strDLClassCodeA1To" : "Categoría de DL A1 válida hasta",
            "strDLClassCodeA2From" : "Categoría de DL A2 válida desde",
            "strDLClassCodeA2Notes" : "Códigos de categoría de DL A2",
            "strDLClassCodeA2To" : "Categoría de DL A2 válida hasta",
            "strDLClassCodeA3From" : "Categoría de DL A3 válida desde",
            "strDLClassCodeA3Notes" : "Códigos de categoría de DL A3",
            "strDLClassCodeA3To" : "Categoría de DL A3 válida hasta",
            "strDLClassCodeAFrom" : "Categoría de DL A válida desde",
            "strDLClassCodeAMFrom" : "Categoría de DL AM válida desde",
            "strDLClassCodeAMNotes" : "Códigos de categoría de DL AM",
            "strDLClassCodeAMTo" : "Categoría de DL AM válida hasta",
            "strDLClassCodeANotes" : "Códigos de categoría de DL A",
            "strDLClassCodeATo" : "Categoría de DL A válida hasta",
            "strDLClassCodeB1From" : "Categoría de DL B1 válida desde",
            "strDLClassCodeB1Notes" : "Códigos de categoría de DL B1",
            "strDLClassCodeB1To" : "Categoría de DL B1 válida hasta",
            "strDLClassCodeB2EFrom" : "Categoría de DL B2E válida desde",
            "strDLClassCodeB2ENotes" : "Códigos de categoría de DL B2E",
            "strDLClassCodeB2ETo" : "Categoría de DL B2E válida hasta",
            "strDLClassCodeB2From" : "Categoría de DL B2 válida desde",
            "strDLClassCodeB2Notes" : "Códigos de categoría de DL B2",
            "strDLClassCodeB2To" : "Categoría de DL B2 válida hasta",
            "strDLClassCodeBEFrom" : "Categoría de DL BE válida desde",
            "strDLClassCodeBENotes" : "Códigos de categoría de DL BE",
            "strDLClassCodeBETo" : "Categoría de DL BE válida hasta",
            "strDLClassCodeBFrom" : "Categoría de DL B válida desde",
            "strDLClassCodeBNotes" : "Códigos de categoría de DL B",
            "strDLClassCodeBTPFrom" : "Categoría de DL BTP válida desde",
            "strDLClassCodeBTPNotes" : "Códigos de categoría de DL BTP",
            "strDLClassCodeBTPTo" : "Categoría de DL BTP válida hasta",
            "strDLClassCodeBTo" : "Categoría de DL B válida hasta",
            "strDLClassCodeC1EFrom" : "Categoría de DL C1E válida desde",
            "strDLClassCodeC1ENotes" : "Códigos de categoría de DL C1E",
            "strDLClassCodeC1ETo" : "Categoría de DL C1E válida hasta",
            "strDLClassCodeC1From" : "Categoría de DL C1 válida desde",
            "strDLClassCodeC1Notes" : "Códigos de categoría de DL C1",
            "strDLClassCodeC1To" : "Categoría de DL C1 válida hasta",
            "strDLClassCodeC2From" : "Categoría de DL C2 válida desde",
            "strDLClassCodeC2Notes" : "Códigos de categoría de DL C2",
            "strDLClassCodeC2To" : "Categoría de DL C2 válida hasta",
            "strDLClassCodeC3From" : "Categoría de DL C3 válida desde",
            "strDLClassCodeC3Notes" : "Códigos de categoría de DL C3",
            "strDLClassCodeC3To" : "Categoría de DL C3 válida hasta",
            "strDLClassCodeCAFrom" : "Categoría de DL CA válida desde",
            "strDLClassCodeCANotes" : "Códigos de categoría de DL CA",
            "strDLClassCodeCATo" : "Categoría de DL CA válida hasta",
            "strDLClassCodeCEFrom" : "Categoría de DL CE válida desde",
            "strDLClassCodeCENotes" : "Códigos de categoría de DL CE",
            "strDLClassCodeCETo" : "Categoría de DL CE válida hasta",
            "strDLClassCodeCFrom" : "Categoría de DL C válida desde",
            "strDLClassCodeCNotes" : "Códigos de categoría de DL C",
            "strDLClassCodeCTo" : "Categoría de DL C válida hasta",
            "strDLClassCodeD1EFrom" : "Categoría de DL D1E válida desde",
            "strDLClassCodeD1ENotes" : "Códigos de categoría de DL D1E",
            "strDLClassCodeD1ETo" : "Categoría de DL D1E válida hasta",
            "strDLClassCodeD1From" : "Categoría de DL D1 válida desde",
            "strDLClassCodeD1Notes" : "Códigos de categoría de DL D1",
            "strDLClassCodeD1To" : "Categoría de DL D1 válida hasta",
            "strDLClassCodeD2From" : "Categoría de DL D2 válida desde",
            "strDLClassCodeD2Notes" : "Códigos de categoría de DL D2",
            "strDLClassCodeD2To" : "Categoría de DL D2 válida hasta",
            "strDLClassCodeDEFrom" : "Categoría de DL DE válida desde",
            "strDLClassCodeDENotes" : "Códigos de categoría de DL DE",
            "strDLClassCodeDETo" : "Categoría de DL DE válida hasta",
            "strDLClassCodeDFrom" : "Categoría de DL D válida desde",
            "strDLClassCodeDNotes" : "Códigos de categoría de DL D",
            "strDLClassCodeDTo" : "Categoría de DL D válida hasta",
            "strDLClassCodeEFrom" : "Categoría de DL E válida desde",
            "strDLClassCodeENotes" : "Códigos de categoría de DL E",
            "strDLClassCodeETo" : "Categoría de DL E válida hasta",
            "strDLClassCodeFA1From" : "Categoría de DL FA1 válida desde",
            "strDLClassCodeFA1Notes" : "Códigos de categoría de DL FA1",
            "strDLClassCodeFA1To" : "Categoría de DL FA1 válida hasta",
            "strDLClassCodeFAFrom" : "Categoría de DL FA válida desde",
            "strDLClassCodeFANotes" : "Códigos de categoría de DL FA",
            "strDLClassCodeFATo" : "Categoría de DL FA válida hasta",
            "strDLClassCodeFBFrom" : "Categoría de DL FB válida desde",
            "strDLClassCodeFBNotes" : "Códigos de categoría de DL FB",
            "strDLClassCodeFBTo" : "Categoría de DL FB válida hasta",
            "strDLClassCodeFFrom" : "Categoría de DL F válida desde",
            "strDLClassCodeFNotes" : "Códigos de categoría de DL F",
            "strDLClassCodeFTo" : "Categoría de DL F válida hasta",
            "strDLClassCodeG1From" : "Categoría de DL G1 válida desde",
            "strDLClassCodeG1Notes" : "Códigos de categoría de DL G1",
            "strDLClassCodeG1To" : "Categoría de DL G1 válida hasta",
            "strDLClassCodeGFrom" : "Categoría de DL G válida desde",
            "strDLClassCodeGNotes" : "Códigos de categoría de DL G",
            "strDLClassCodeGTo" : "Categoría de DL G válida hasta",
            "strDLClassCodeHCFrom" : "Categoría de DL HC válida desde",
            "strDLClassCodeHCNotes" : "Códigos de categoría de DL HC",
            "strDLClassCodeHCTo" : "Categoría de DL HC válida hasta",
            "strDLClassCodeHFrom" : "Categoría de DL H válida desde",
            "strDLClassCodeHNotes" : "Códigos de categoría de DL H",
            "strDLClassCodeHRFrom" : "Categoría de DL HR válida desde",
            "strDLClassCodeHRNotes" : "Códigos de categoría de DL HR",
            "strDLClassCodeHRTo" : "Categoría de DL HR válida hasta",
            "strDLClassCodeHTo" : "Categoría de DL H válida hasta",
            "strDLClassCodeIFrom" : "Categoría de DL I válida desde",
            "strDLClassCodeINotes" : "Códigos de categoría de DL I",
            "strDLClassCodeITo" : "Categoría de DL I válida hasta",
            "strDLClassCodeJFrom" : "Categoría de DL J válida desde",
            "strDLClassCodeJNotes" : "Códigos de categoría de DL J",
            "strDLClassCodeJTo" : "Categoría de DL J válida hasta",
            "strDLClassCodeKFrom" : "Categoría de DL K válida desde",
            "strDLClassCodeKNotes" : "Códigos de categoría de DL K",
            "strDLClassCodeKTo" : "Categoría de DL K válida hasta",
            "strDLClassCodeLCFrom" : "Categoría de DL LC válida desde",
            "strDLClassCodeLCNotes" : "Códigos de categoría de DL LC",
            "strDLClassCodeLCTo" : "Categoría de DL LC válida hasta",
            "strDLClassCodeLFrom" : "Categoría de DL L válida desde",
            "strDLClassCodeLKFrom" : "Categoría de DL LK válida desde",
            "strDLClassCodeLKNotes" : "Códigos de categoría de DL LK",
            "strDLClassCodeLKTo" : "Categoría de DL LK válida hasta",
            "strDLClassCodeLNotes" : "Códigos de categoría de DL L",
            "strDLClassCodeLRFrom" : "Categoría de DL LR válida desde",
            "strDLClassCodeLRNotes" : "Códigos de categoría de DL LR",
            "strDLClassCodeLRTo" : "Categoría de DL LR válida hasta",
            "strDLClassCodeLTo" : "Categoría de DL L válida hasta",
            "strDLClassCodeMCFrom" : "Categoría de DL MC válida desde",
            "strDLClassCodeMCNotes" : "Códigos de categoría de DL MC",
            "strDLClassCodeMCTo" : "Categoría de DL MC válida hasta",
            "strDLClassCodeMFrom" : "Categoría de DL M válida desde",
            "strDLClassCodeMNotes" : "Códigos de categoría de DL M",
            "strDLClassCodeMRFrom" : "Categoría de DL MR válida desde",
            "strDLClassCodeMRNotes" : "Códigos de categoría de DL MR",
            "strDLClassCodeMRTo" : "Categoría de DL MR válida hasta",
            "strDLClassCodeMTo" : "Categoría de DL M válida hasta",
            "strDLClassCodeNFrom" : "Categoría de DL N válida desde",
            "strDLClassCodeNNotes" : "Códigos de categoría de DL N",
            "strDLClassCodeNTo" : "Categoría de DL N válida hasta",
            "strDLClassCodeREFrom" : "Categoría de DL RE válida desde",
            "strDLClassCodeRENotes" : "Códigos de categoría de DL RE",
            "strDLClassCodeRETo" : "Categoría de DL RE válida hasta",
            "strDLClassCodeRFrom" : "Categoría de DL R válida desde",
            "strDLClassCodeRNotes" : "Códigos de categoría de DL R",
            "strDLClassCodeRTo" : "Categoría de DL R válida hasta",
            "strDLClassCodeSFrom" : "Categoría de DL S válida desde",
            "strDLClassCodeSNotes" : "Códigos de categoría de DL S",
            "strDLClassCodeSTo" : "Categoría de DL S válida hasta",
            "strDLClassCodeTBFrom" : "Categoría de DL TB válida desde",
            "strDLClassCodeTBNotes" : "Códigos de categoría de DL TB",
            "strDLClassCodeTBTo" : "Categoría de DL TB válida hasta",
            "strDLClassCodeTFrom" : "Categoría de DL T válida desde",
            "strDLClassCodeTMFrom" : "Categoría de DL TM válida desde",
            "strDLClassCodeTMNotes" : "Códigos de categoría de DL TM",
            "strDLClassCodeTMTo" : "Categoría de DL TM válida hasta",
            "strDLClassCodeTNotes" : "Códigos de categoría de DL T",
            "strDLClassCodeTRFrom" : "Categoría de DL TR válida desde",
            "strDLClassCodeTRNotes" : "Códigos de categoría de DL TR",
            "strDLClassCodeTRTo" : "Categoría de DL TR válida hasta",
            "strDLClassCodeTTo" : "Categoría de DL T válida hasta",
            "strDLClassCodeTVFrom" : "Categoría de DL TV válida desde",
            "strDLClassCodeTVNotes" : "Códigos de categoría de DL TV",
            "strDLClassCodeTVTo" : "Categoría de DL TV válida hasta",
            "strDLClassCodeVFrom" : "Categoría de DL V válida desde",
            "strDLClassCodeVNotes" : "Códigos de categoría de DL V",
            "strDLClassCodeVTo" : "Categoría de DL V válida hasta",
            "strDLClassCodeWFrom" : "Categoría de DL W válida desde",
            "strDLClassCodeWNotes" : "Códigos de categoría de DL W",
            "strDLClassCodeWTo" : "Categoría de DL W válida hasta",
            "strDLDuplicateDate" : "Fecha de emisión de duplicado",
            "strDLEndorsed" : "Código de endoso de DL",
            "strDLIssType" : "Tipo de tarjeta",
            "strDLRecordCreated" : "Registro creado",
            "strDLRestrictionCode" : "Código de restricción de DL",
            "strDLUnder18Date" : "Fecha del 18º cumpleaños",
            "strDLUnder19Date" : "Fecha del 19º cumpleaños",
            "strDLUnder21Date" : "Fecha del 21º cumpleaños",
            "strDNINumber" : "Número de DNI",
            "strDSCertificateIssuer" : "Emisor del certificado DS",
            "strDSCertificateSubject" : "Sujeto del certificado DS",
            "strDSCertificateValidFrom" : "Válido desde el certificado DS",
            "strDSCertificateValidTo" : "Válido hasta el certificado DS",
            "strDUFNumber" : "Número de DUF",
            "strDataDiscriminator" : "Discriminador de datos",
            "strDateFirstRenewal" : "Fecha de la primera renovación",
            "strDateOfBirthOfHusband" : "Fecha de nacimiento del esposo",
            "strDateOfBirthOfWife" : "Fecha de nacimiento de la esposa",
            "strDateOfInsuranceExpiry" : "Fecha de vencimiento del seguro",
            "strDateSecondRenewal" : "Fecha de la segunda renovación",
            "strDateofBirth" : "Fecha de nacimiento",
            "strDateofBirthCheckDigit" : "Dígito de verificación de la fecha de nacimiento",
            "strDateofBirthChecksum" : "Suma de verificación de la fecha de nacimiento",
            "strDateofCreation" : "Fecha de creación",
            "strDateofExpiry" : "Fecha de vencimiento",
            "strDateofExpiryCheckDigit" : "Dígito de verificación de la fecha de vencimiento",
            "strDateofExpiryChecksum" : "Suma de verificación de la fecha de vencimiento",
            "strDateofFlight" : "Fecha del vuelo",
            "strDateofIssue" : "Fecha de emisión",
            "strDateofIssueBoardingPass" : "Fecha de emisión del pase de abordar",
            "strDateofIssueCheckDigit" : "Dígito de verificación de la fecha de emisión",
            "strDateofIssueChecksum" : "Suma de verificación de la fecha de emisión",
            "strDateofPersonalization" : "Fecha de personalización",
            "strDateofRegistration" : "Fecha de registro",
            "strDay" : "Día",
            "strDepartment" : "Departamento",
            "strDeptNumber" : "Número de departamento",
            "strDestination" : "Destino",
            "strDiscretionaryData" : "Datos discrecionales",
            "strDoDNumber" : "Número del Departamento de Defensa",
            "strDocumentClassCode" : "Código de clase de documento",
            "strDocumentClassName" : "Clase de documento",
            "strDocumentDiscriminator" : "Discriminador de documento",
            "strDocumentNumber" : "Número de documento",
            "strDocumentNumberCheckDigit" : "Dígito de verificación del número de documento",
            "strDocumentNumberChecksum" : "Suma de verificación del número de documento",
            "strDocumentSeries" : "Serie de documento",
            "strDocumentTooSmall" : "Documento demasiado pequeño",
            "strDonor" : "Donante",
            "strDossierNumber" : "Número de expediente",
            "strDurationofStay" : "Duración de la estadía",
            "strECEnvironmentalType" : "Tipo ambiental del vehículo",
            "strEDLDG1" : "Elementos de datos de texto (DG1)",
            "strEDLDG10" : "No definido (DG10)",
            "strEDLDG11" : "Datos domésticos opcionales (DG11)",
            "strEDLDG12" : "Alerta de no coincidencia (DG12)",
            "strEDLDG13" : "Información de autenticación activa (DG13)",
            "strEDLDG14" : "Información EAC (DG14)",
            "strEDLDG2" : "Información del titular de la licencia (DG2)",
            "strEDLDG3" : "Detalles de la autoridad emisora (DG3)",
            "strEDLDG4" : "Imagen del retrato (DG4)",
            "strEDLDG5" : "Imagen de firma / marca habitual (DG5)",
            "strEDLDG6" : "Biometría - Datos faciales (DG6)",
            "strEDLDG7" : "Biometría - Huella(s) dactilar(es) (DG7)",
            "strEDLDG8" : "Biometría - Datos del iris (DG8)",
            "strEDLDG9" : "Biometría - Otros (DG9)",
            "strEFCOM" : "EF.COM",
            "strEFCVCA" : "EF.CVCA",
            "strEFCardAccess" : "EF.CardAccess",
            "strEFCardSecurity" : "EF.CardSecurity",
            "strEFChipSecurity" : "EF.ChipSecurity",
            "strEFSOD" : "EF.SOD",
            "strEQVCode" : "Código EQV",
            "strElectronicTicketIndicator" : "Indicador de boleto electrónico",
            "strElement" : "Elemento",
            "strEndorsementExpirationDate" : "Fecha de vencimiento del endoso",
            "strEngineModel" : "Modelo de motor",
            "strEngineNumber" : "Número de motor",
            "strEnginePower" : "Potencia del motor",
            "strEngineVolume" : "Volumen del motor",
            "strError" : "Error",
            "strExamDate" : "Fecha del examen",
            "strExeptInTanks" : "Excepto en tanques",
            "strEye" : "Iris",
            "strEyesColor" : "Color de ojos",
            "strFaculty" : "Facultad",
            "strFalseLuminescence" : "Luminiscencia excesiva",
            "strFamilyName" : "Apellido/nombre de nacimiento",
            "strFamilyNameTruncation" : "Truncamiento del apellido/nombre de nacimiento",
            "strFastTrack" : "Servicio de vía rápida",
            "strFatherCountryOfBirth" : "País de nacimiento del padre",
            "strFatherDateOfBirth" : "Fecha de nacimiento del padre",
            "strFatherGivenName" : "Nombre del padre",
            "strFatherPersonalNumber" : "Número personal del padre",
            "strFatherPlaceOfBirth" : "Lugar de nacimiento del padre",
            "strFatherSurname" : "Apellido del padre",
            "strFathersName" : "Nombre del padre",
            "strFathersNameRUS" : "Nombre del padre (Nacional)",
            "strFederalElections" : "Elecciones federales",
            "strFee" : "Tarifa",
            "strFieldFromMRZ" : "Campo del MRZ",
            "strFieldTypeDocumentImage" : "Imagen del documento",
            "strFillElement" : "Elemento de relleno",
            "strFinalCheckDigit" : "Dígito de verificación final",
            "strFinalChecksum" : "Suma de verificación final",
            "strFingerprint" : "Huella dactilar",
            "strFirstIssueDate" : "Fecha de primera emisión",
            "strFirstNameTruncation" : "Truncamiento del primer nombre",
            "strFlightNumber" : "Número de vuelo",
            "strFolioNumber" : "Número de folio",
            "strFormOfEducation" : "Forma de educación",
            "strFreeBaggageAllowance" : "Franquicia de equipaje",
            "strFrequentFlyerAirlineDesignator" : "Designador de aerolínea de viajero frecuente",
            "strFrequentFlyerNumber" : "Número de viajero frecuente",
            "strFromAirportCode" : "Código del aeropuerto de partida",
            "strFuelType" : "Tipo de combustible",
            "strGNIBNumber" : "Número de GNIB",
            "strGhostPortrait" : "Retrato fantasma",
            "strGivenNames" : "Nombre(s) de pila",
            "strGivenNamesRUS" : "Nombre(s) de pila (Nacional)",
            "strGlaresOnDocument" : "Evite los reflejos en el documento",
            "strGrandfatherName" : "Nombre del abuelo",
            "strHairColor" : "Color de cabello",
            "strHealthNumber" : "Número de seguro médico",
            "strHeight" : "Altura",
            "strHoldDocumentStraight" : "Sostenga el documento recto",
            "strHoloSimple" : "Disponibilidad de holograma",
            "strHoloVerifyDinamic" : "Verificar holograma dinámico",
            "strHoloVerifyMultiStatic" : "Verificar holograma estático múltiple",
            "strHoloVerifyStatic" : "Verificar holograma estático",
            "strHolograms" : "Hologramas",
            "strIPI" : "IPI (información personal invisible)",
            "strIRB900" : "Tinta IR B900",
            "strIRVis" : "Transparencia IR",
            "strISOIssuerIDNumber" : "Número de identificación del emisor ISO",
            "strIdentifier" : "Identificador",
            "strIdentityCardNumber" : "Número de documento de identidad",
            "strIdentityCardNumberCheckDigit" : "Dígito de verificación del número de documento de identidad",
            "strIdentityCardNumberChecksum" : "Suma de verificación del número de documento de identidad",
            "strImagePattern" : "Patrones de imagen",
            "strInTanks" : "En tanques",
            "strInventoryNumber" : "Número de inventario",
            "strInvitationNumber" : "Número de invitación",
            "strInvitationNumberCheckDigit" : "Dígito de verificación del número de invitación",
            "strInvitationNumberChecksum" : "Suma de verificación del número de invitación",
            "strInvitedBy" : "Invitado por",
            "strIssueTimestamp" : "Hora de emisión",
            "strIssuingStateCode" : "Código de estado emisor",
            "strIssuingStateName" : "Estado emisor",
            "strJurisdictionEndorsementCode" : "Código de aprobación de jurisdicción",
            "strJurisdictionRestrictionCode" : "Código de restricción de jurisdicción",
            "strJurisdictionVehicleClass" : "Clase de vehículo de jurisdicción",
            "strKeepDeviceStill" : "Mantenga el dispositivo quieto",
            "strLicenseNumber" : "Número de licencia",
            "strLimitedDurationDocumentIndicator" : "Indicador de documento de duración limitada",
            "strLine1CheckDigit" : "Dígito de verificación de la línea 1",
            "strLine1Checksum" : "Suma de verificación de la línea 1",
            "strLine1OptionalData" : "Datos opcionales de la línea 1",
            "strLine2CheckDigit" : "Dígito de verificación de la línea 2",
            "strLine2Checksum" : "Suma de verificación de la línea 2",
            "strLine2OptionalData" : "Datos opcionales de la línea 2",
            "strLine3CheckDigit" : "Dígito de verificación de la línea 3",
            "strLine3Checksum" : "Suma de verificación de la línea 3",
            "strLine3OptionalData" : "Datos opcionales de la línea 3",
            "strLookingDocument" : "Buscando documento...",
            "strMCNoviceDate" : "Fecha de vencimiento del estado de Novato en Motocicleta",
            "strMRZ" : "MRZ",
            "strMRZLinesICAORFID" : "Líneas MRZ de ICAO RFID",
            "strMRZString1" : "Línea MRZ 1",
            "strMRZString2" : "Línea MRZ 2",
            "strMRZString3" : "Línea MRZ 3",
            "strMRZStrings" : "Líneas MRZ",
            "strMRZStringsWithCorrectCheckSums" : "Líneas MRZ con sumas de verificación correctas",
            "strMRZType" : "Tipo de MRZ",
            "strMailingAddressCity" : "Dirección de envío - ciudad",
            "strMailingAddressJurisdictionCode" : "Código de jurisdicción de la dirección de envío",
            "strMailingAddressPostalCode" : "Dirección de envío - código postal",
            "strMailingAddressStreet" : "Dirección de envío - calle",
            "strMake" : "Marca",
            "strMaritalStatus" : "Estado civil",
            "strMaxMassofTrailerBraked" : "Masa máxima del remolque (frenado)",
            "strMaxMassofTrailerUnbraked" : "Masa máxima del remolque (sin frenar)",
            "strMaxSpeed" : "Velocidad máxima",
            "strMedicalIndicatorCodes" : "Notas/códigos médicos",
            "strMiddleName" : "Segundo nombre",
            "strMiddleNameTruncation" : "Truncamiento del segundo nombre",
            "strMifareData" : "Datos MIFARE",
            "strMifareValidity" : "Validez MIFARE",
            "strMilitaryBookNumber" : "Número de libro militar",
            "strModel" : "Modelo",
            "strMonth" : "Mes",
            "strMortgageBy" : "Hipotecado por",
            "strMotherCountryOfBirth" : "País de nacimiento de la madre",
            "strMotherDateOfBirth" : "Fecha de nacimiento de la madre",
            "strMotherGivenName" : "Nombre de pila de la madre",
            "strMotherPersonalNumber" : "Número personal de la madre",
            "strMotherPlaceOfBirth" : "Lugar de nacimiento de la madre",
            "strMotherSurname" : "Apellido de la madre",
            "strMothersName" : "Nombre de la madre",
            "strNamePrefix" : "Prefijo del nombre",
            "strNameSuffix" : "Sufijo del nombre",
            "strNationality" : "Nacionalidad",
            "strNationalityCode" : "Código de nacionalidad",
            "strNonResidentIndicator" : "Indicador de no residente",
            "strNone" : "Ninguno",
            "strNotDefined" : "No definido",
            "strNumberOfCardIssuance" : "Número de emisión de tarjeta",
            "strNumberOfCardIssuanceCheckDigit" : "Dígito de verificación para el número de emisiones de tarjeta",
            "strNumberOfCardIssuanceChecksum" : "Suma de verificación para el número de emisiones de tarjeta",
            "strNumberOfCylinders" : "Número de cilindros",
            "strNumberofAxels" : "Número de ejes",
            "strNumberofDuplicates" : "Número de duplicados",
            "strNumberofEntries" : "Número de entradas",
            "strNumberofSeats" : "Número de asientos",
            "strNumberofStandingPlaces" : "Número de lugares de pie",
            "strOCRNumber" : "Número OCR",
            "strOK" : "OK",
            "strObservations" : "Observaciones",
            "strOldDateOfIssue" : "Antigua fecha de emisión",
            "strOldDocumentNumber" : "Antiguo número de documento",
            "strOldPlaceOfIssue" : "Antiguo lugar de emisión",
            "strOptionalData" : "Datos opcionales",
            "strOptionalDataCheckDigit" : "Dígito de verificación para los datos opcionales",
            "strOptionalDataChecksum" : "Suma de verificación para los datos opcionales",
            "strOptionalDetails" : "Detalles opcionales",
            "strOrganization" : "Organización",
            "strOther" : "Otro",
            "strOtherName" : "Otro nombre",
            "strOtherPersonName" : "Nombre de otra persona",
            "strOtherValidID" : "Otros IDs válidos",
            "strOwner" : "Propietario",
            "strPDF417Codec" : "Códec PDF417",
            "strPNRCode" : "Código PNR",
            "strParrentsGivenNames" : "Nombres de los padres",
            "strPassportNumber" : "Número de pasaporte",
            "strPassportNumberCheckDigit" : "Dígito de verificación para el número de pasaporte",
            "strPassportNumberChecksum" : "Suma de verificación para el número de pasaporte",
            "strPatronHeaderVersion" : "Versión de encabezado del patrón",
            "strPatternDifferentLinesThickness" : "Comparación del grosor de las líneas del patrón",
            "strPatternIRInvisible" : "Patrón invisible en IR",
            "strPatternNotInterrupted" : "Sin interrupciones",
            "strPatternNotShifted" : "Los elementos del patrón no están desplazados",
            "strPatternSameColors" : "Mismos colores del patrón",
            "strPayGrade" : "Grado de pago",
            "strPayloadCapacity" : "Capacidad de carga",
            "strPermissibleAxleLoad" : "Carga máxima por eje",
            "strPermitDLClass" : "Clase de permiso",
            "strPermitDateofExpiry" : "Fecha de vencimiento del permiso",
            "strPermitDateofIssue" : "Fecha de emisión del permiso",
            "strPermitEndorsed" : "Código de endoso del permiso",
            "strPermitIdentifier" : "Identificador del permiso",
            "strPermitRestrictionCode" : "Código de restricción del permiso",
            "strPersonToNotifyAddress" : "Persona a notificar: Dirección",
            "strPersonToNotifyDateofRecord" : "Persona a notificar: Fecha de registro",
            "strPersonToNotifyName" : "Persona a notificar: Nombre",
            "strPersonToNotifyPhone" : "Persona a notificar: Teléfono",
            "strPersonalNumber" : "Número personal",
            "strPersonalNumberCheckDigit" : "Dígito de verificación del número personal",
            "strPersonalNumberChecksum" : "Suma de verificación del número personal",
            "strPersonalSummary" : "Resumen de datos personales",
            "strPersonalizationSN" : "Número de serie de personalización",
            "strPhone" : "Teléfono",
            "strPhotoArea" : "Área de la foto",
            "strPhotoColor" : "Color de la foto",
            "strPhotoCorners" : "Esquinas de la foto",
            "strPhotoElement" : "Elemento de la foto",
            "strPhotoEmbedType" : "Tipo de incrustación de la foto",
            "strPhotoProcessing" : "Procesamiento de la foto...",
            "strPhotoShape" : "Forma de la foto",
            "strPhotoSizeCheck" : "Verificación de tamaño",
            "strPlaceDocumentInFrame" : "Colocar el documento en el marco",
            "strPlaceOfBirthRUS" : "Lugar de nacimiento (Nacional)",
            "strPlaceOfBirthStateCode" : "Código estatal del lugar de nacimiento",
            "strPlaceOfExamination" : "Lugar de examen",
            "strPlaceOfIssue" : "Lugar de emisión",
            "strPlacePhoneOnDoc" : "Coloque el teléfono en el documento por favor",
            "strPlaceofBirth" : "Lugar de nacimiento",
            "strPlaceofBirthArea" : "Área del lugar de nacimiento",
            "strPlaceofRegistration" : "Lugar de registro",
            "strPoliceDistrict" : "Distrito policial",
            "strPortrait" : "Retrato",
            "strPortraitComparison" : "Comparación de los retratos",
            "strPortraitOfChild" : "Retrato del niño",
            "strPortraitVSCamera" : "Retrato vs Imagen de la cámara",
            "strPortraitVSGhost" : "Retrato vs Foto fantasma",
            "strPortraitVSRFID" : "Retrato vs Retrato del chip RFID",
            "strPowerWeightRatio" : "Relación potencia-peso",
            "strPrecinct" : "Recinto",
            "strPrepareCamera" : "Preparando la cámara...",
            "strPresentNextPage" : "Por favor, presente la siguiente página",
            "strPreviousType" : "Tipo/número del documento anterior",
            "strProcessingDocument" : "Procesando documentos...",
            "strProfession" : "Profesión",
            "strProfessionalIdNumber" : "Número de identificación profesional",
            "strProofOfCitizenship" : "Prueba de ciudadanía",
            "strPseudoCode" : "Pseudocódigo",
            "strPurposeOfEntry" : "Propósito de entrada",
            "strRFIDVSCamera" : "Retrato del chip RFID vs Imagen de la cámara",
            "strRaceEthnicity" : "Raza/Etnicidad",
            "strRank" : "Rango",
            "strReadingRFID" : "Leyendo datos del chip RFID",
            "strReadingRFIDDGiOS" : "Leyendo datos %@ del chip RFID",
            "strRecognizedDocumentType" : "Tipo de documento reconocido",
            "strReferenceNumber" : "Número único",
            "strReferenceNumberCheckDigit" : "Dígito de verificación del número único",
            "strReferenceNumberChecksum" : "Suma de verificación del número único",
            "strRegCertBodyNumber" : "Número de carrocería",
            "strRegCertBodyType" : "Tipo de carrocería",
            "strRegCertCarColor" : "Color del vehículo",
            "strRegCertCarMark" : "Marca del vehículo",
            "strRegCertCarModel" : "Modelo del vehículo",
            "strRegCertCarType" : "Tipo de vehículo",
            "strRegCertMaxWeight" : "Peso máximo permitido",
            "strRegCertRegNumber" : "Número de registro",
            "strRegCertRegNumberCheckDigit" : "Dígito de verificación del número de registro",
            "strRegCertRegNumberChecksum" : "Suma de verificación del número de registro",
            "strRegCertVIN" : "Número de identificación del vehículo (VIN)",
            "strRegCertVINCheckDigit" : "Dígito de verificación del VIN",
            "strRegCertVINChecksum" : "Suma de verificación del VIN",
            "strRegCertVehicleITSCode" : "Código ITS del vehículo",
            "strRegCertWeight" : "Masa sin carga",
            "strRelationship" : "Relación",
            "strReligion" : "Religión",
            "strRemainderTerm" : "Meses para expirar",
            "strResidentFrom" : "Residente desde",
            "strResidentUntil" : "Residente hasta",
            "strRetirementNumber" : "Número de jubilación",
            "strRevisionDate" : "Fecha de revisión",
            "strRoomNumber" : "Número de habitación",
            "strSBHIntegrityOptions" : "Opciones de integridad SBH",
            "strSBHSecurityOptions" : "Opciones de seguridad SBH",
            "strSeatNumber" : "Número de asiento",
            "strSecondSurname" : "Segundo apellido",
            "strSection" : "Sección",
            "strSecurityText" : "Texto de seguridad",
            "strSelecteeIndicator" : "Indicador de seleccionado",
            "strSequenceNumber" : "Número de secuencia",
            "strSerialNumber" : "Número de serie",
            "strSettings" : "Ajustes",
            "strSex" : "Sexo",
            "strSignature" : "Firma",
            "strSkinColor" : "Color de piel",
            "strSocialSecurityNumber" : "Número de seguro social",
            "strSpCode" : "Código especial",
            "strSpecialNotes" : "Notas especiales",
            "strSponsor" : "Patrocinador",
            "strSponsorSSN" : "SSN del patrocinador",
            "strSponsorService" : "Servicio del patrocinador",
            "strSponsorStatus" : "Estado del patrocinador",
            "strStamp" : "Sello",
            "strStampNumber" : "Número de sello",
            "strStatusDateofExpiry" : "Fecha de vencimiento del estado",
            "strSurname" : "Apellido",
            "strSurnameAndGivenNames" : "Apellido y nombres",
            "strSurnameAndGivenNamesCheckDigit" : "Dígito de verificación de apellido y nombres",
            "strSurnameAndGivenNamesChecksum" : "Suma de verificación de apellido y nombres",
            "strSurnameAndGivenNamesRUS" : "Apellido y nombres (Nacional)",
            "strSurnameAtBirth" : "Apellido al nacer",
            "strSurnameOfHusbandAfterRegistration" : "Apellido del esposo después del registro",
            "strSurnameOfWifeAfterRegistration" : "Apellido de la esposa después del registro",
            "strSurnameofSpose" : "Apellido del cónyuge",
            "strTax" : "Impuesto",
            "strTaxNumber" : "Número de impuesto",
            "strTelexCode" : "Código telex",
            "strTerritorialValidity" : "Validez territorial",
            "strTicketNumber" : "Número de boleto",
            "strTitle" : "Cargo",
            "strToAirportCode" : "Código del aeropuerto de llegada",
            "strTorchUnavailable" : "Linterna no disponible",
            "strTrackingNumber" : "Número de seguimiento",
            "strTrailerHitch" : "Enganche de remolque",
            "strTransactionNumber" : "Número de transacción",
            "strTransmissionType" : "Tipo de transmisión",
            "strTypeApprovalNumber" : "Número de aprobación del tipo",
            "strURL" : "URL",
            "strUSCIS" : "USCIS",
            "strUV" : "UV",
            "strUVFibers" : "Fibras de seguridad UV",
            "strUVLuminescence" : "Comprobación de papel UV apagado",
            "strUnableCaptureMedia" : "Error en la configuración de la cámara",
            "strUniqueCustomerIdentifier" : "Identificador único del cliente",
            "strVRCDataObjectEntry" : "Datos del vehículo del grupo de datos DG1",
            "strValidityPeriod" : "Período de validez",
            "strVehicleCategory" : "Categoría del vehículo",
            "strVeteran" : "Veterano",
            "strVisaClass" : "Clase de visa",
            "strVisaID" : "ID de visa",
            "strVisaIDCheckDigit" : "Dígito de verificación del ID de visa",
            "strVisaIDChecksum" : "Suma de verificación del ID de visa",
            "strVisaIDRUS" : "ID de visa (Nacional)",
            "strVisaNumber" : "Número de visa",
            "strVisaNumberCheckDigit" : "Dígito de verificación del número de visa",
            "strVisaNumberChecksum" : "Suma de verificación del número de visa",
            "strVisaSubClass" : "Subclase de visa",
            "strVisaType" : "Tipo de visa",
            "strVisaValidFrom" : "Visa válida desde",
            "strVisaValidUntil" : "Visa válida hasta",
            "strVisaValidUntilCheckDigit" : "Dígito de verificación de la fecha de vencimiento de la visa",
            "strVisaValidUntilChecksum" : "Suma de verificación de la fecha de vencimiento de la visa",
            "strVisibleLight" : "Luz visible",
            "strVoter" : "Votante",
            "strVoterKey" : "Clave del votante",
            "strVoucherNumber" : "Número de cupón",
            "strWeight" : "Peso",
            "strWeightPound" : "Peso (libra)",
            "strYear" : "Año",
            "strYearsSinceIssue" : "Años desde la emisión",
            "streIDPlaceOfBirthCity" : "Lugar de nacimiento: Ciudad",
            "streIDPlaceOfBirthCountry" : "Lugar de nacimiento: País",
            "streIDPlaceOfBirthState" : "Lugar de nacimiento: Estado",
            "streIDPlaceOfBirthStreet" : "Lugar de nacimiento: Calle",
            "streIDPlaceOfBirthZipcode" : "Lugar de nacimiento: Código postal",
            "streIDResidencePermit1" : "Permiso de residencia 1",
            "streIDResidencePermit2" : "Permiso de residencia 2",
            "strfppLeftIndexFinger" : "Dedo índice izquierdo",
            "strfppLeftLittleFinger" : "Dedo meñique izquierdo",
            "strfppLeftMiddleFinger" : "Dedo medio izquierdo",
            "strfppLeftRingFinger" : "Dedo anular izquierdo",
            "strfppLeftThumb" : "Pulgar izquierdo",
            "strfppRightIndexFinger" : "Dedo índice derecho",
            "strfppRightLittleFinger" : "Dedo meñique derecho",
            "strfppRightMiddleFinger" : "Dedo medio derecho",
            "strfppRightRingFinger" : "Dedo anular derecho",
            "strfppRightThumb" : "Pulgar derecho",
        ]
    }
}
