//
//  File.swift
//
//
//  Created by MOBILE on 20/05/24.
//

import Foundation

class TurkishDataValues {
    func getDictionary() -> [String: String] {
        return [

            "RFID_Error_AlreadyDone" : "RFID: İstenen işlem zaten yapılmış",
            "RFID_Error_Busy" : "RFID: RFID meşgul",
            "RFID_Error_Failed" : "RFID: Başarısız",
            "RFID_Error_FileIOError" : "RFID Dosya: IO Hatası",
            "RFID_Error_InvalidDirectory" : "RFID: Geçersiz dizin",
            "RFID_Error_InvalidParameter" : "RFID: ExecuteCommand() çağrısında geçersiz parametre bulundu",
            "RFID_Error_NoChipDetected" : "RFID: Çip algılanmadı",
            "RFID_Error_NotAvailable" : "RFID: Kullanılamıyor",
            "RFID_Error_NotEnoughMemory" : "RFID: Bellek yetersiz",
            "RFID_Error_NotInitialized" : "RFID: Cihaz başlatılmamış",
            "RFID_Error_NotPerformed" : "RFID: Gerçekleştirilmedi",
            "RFID_Error_OldFirmware" : "RFID: Firmware güncellenmesi gerekiyor",
            "RFID_Error_PCSC_CantConnectCard" : "PCSC: Kart bağlanamıyor",
            "RFID_Error_PCSC_CardIsBusy" : "PCSC: Kart meşgul",
            "RFID_Error_PCSC_CardIsNotConnected" : "PCSC: Kart bağlı değil",
            "RFID_Error_PCSC_ExtLe_Failed" : "PCSC: ExtLe Başarısız",
            "RFID_Error_PCSC_Failed" : "PCSC: Başarısız",
            "RFID_Error_PCSC_FailedSCard" : "PCSC: Akıllı Kart Başarısız",
            "RFID_Error_PCSC_OperationCancelled" : "PCSC: İşlem iptal edildi",
            "RFID_Error_PCSC_ReaderNotAvailable" : "PCSC: Okuyucu kullanılamıyor",
            "RFID_Error_Session_AccessControl_AA_Failed" : "RFID: AA Başarısız",
            "RFID_Error_Session_AccessControl_CA_Failed" : "RFID: CA Başarısız",
            "RFID_Error_Session_AccessControl_IncorrectOptionCA" : "RFID: Yanlış Seçenek CA",
            "RFID_Error_Session_AccessControl_RI_Failed" : "RFID: RI Başarısız",
            "RFID_Error_Session_AccessControl_RequiresCA" : "RFID: CA Gerekiyor",
            "RFID_Error_Session_AccessControl_RequiresCAKeys" : "RFID: CA Anahtarları Gerekiyor",
            "RFID_Error_Session_AccessControl_RequiresPACE" : "RFID: PACE Gerekiyor",
            "RFID_Error_Session_AccessControl_RequiresSM" : "RFID: SM Gerekiyor",
            "RFID_Error_Session_AccessControl_RequiresTA" : "RFID: TA Gerekiyor",
            "RFID_Error_Session_AccessControl_TA_Failed" : "RFID: TA Başarısız",
            "RFID_Error_Session_AccessControl_UnknownType" : "RFID: Erişim Kontrolü Bilinmeyen Tür",
            "RFID_Error_Session_AccessKey_IncorrectData" : "RFID: Erişim Anahtarı Hatalı Veri",
            "RFID_Error_Session_AccessKey_IncorrectSMType" : "RFID: Erişim Anahtarı Hatalı SM Türü",
            "RFID_Error_Session_AccessKey_NotSet" : "RFID: Erişim Anahtarı Ayarlanmadı",
            "RFID_Error_Session_AccessKey_Restricted" : "RFID: Erişim Anahtarı Kısıtlandı",
            "RFID_Error_Session_AccessKey_UnknownType" : "RFID: Erişim Anahtarı Bilinmeyen Tür",
            "RFID_Error_Session_AccessKey_UnsupportedSMType" : "RFID: Erişim Anahtarı Desteklenmeyen SM Türü",
            "RFID_Error_Session_File_AccessDenied" : "RFID Dosya: Erişim Reddedildi",
            "RFID_Error_Session_File_CantReadData" : "RFID Dosya: Veri Okunamıyor",
            "RFID_Error_Session_File_CantUseData" : "RFID Dosya: Veri Kullanılamıyor",
            "RFID_Error_Session_File_Contents_UnexpectedData" : "RFID Dosya: İçerik Beklenmedik Veri",
            "RFID_Error_Session_File_IncorrectData" : "RFID Dosya: Hatalı Veri",
            "RFID_Error_Session_File_NotEnoughData" : "RFID Dosya: Yetersiz Veri",
            "RFID_Error_Session_File_UnexpectedData" : "RFID Dosya: Beklenmedik Veri",
            "RFID_Error_Session_File_WrongTag" : "RFID Dosya: Hatalı Etiket",
            "RFID_Error_Session_IncorrectData" : "RFID: Hatalı Veri",
            "RFID_Error_Session_InvalidAuxData_CommunityID" : "RFID: Geçersiz Ek Veri Topluluk ID'si",
            "RFID_Error_Session_InvalidAuxData_DateOfBirth" : "RFID: Geçersiz Ek Veri Doğum Tarihi",
            "RFID_Error_Session_InvalidAuxData_DateOfExpiry" : "RFID: Geçersiz Ek Veri Son Kullanma Tarihi",
            "RFID_Error_Session_IsClosed" : "RFID: Oturum Kapalı",
            "RFID_Error_Session_PA_HashCheckFailed" : "RFID: Hash Kontrolü Başarısız",
            "RFID_Error_Session_PA_SignatureCheckFailed" : "RFID: SO İmza Kontrolü Başarısız",
            "RFID_Error_Session_ProcedureType_NotSet" : "RFID: Prosedür Türü Ayarlanmadı",
            "RFID_Error_Session_ProcedureType_Unknown" : "RFID: Prosedür Türü Bilinmiyor",
            "RFID_Error_Session_ProcedureType_Unsupported" : "RFID: Prosedür Türü Desteklenmiyor",
            "RFID_Error_Session_PwdManagement_NotAuthorized" : "RFID: Pwd Yönetimi Yetkili Değil",
            "RFID_Error_Session_TerminalType_BadCertificate" : "RFID: Terminal Türü Geçersiz Sertifika",
            "RFID_Error_Session_TerminalType_NotSet" : "RFID: Terminal Türü Ayarlanmadı",
            "RFID_Error_Session_TerminalType_Unknown" : "RFID: Terminal Türü Bilinmiyor",
            "RFID_Error_Session_Terminal_UnsupportedOperation" : "RFID: Terminal Desteklenmeyen İşlem",
            "RFID_Error_Session_eSign_PIN_NotSet" : "RFID: eSign PIN Ayarlanmadı",
            "RFID_Error_Session_eSign_PIN_NotVerified" : "RFID: eSign PIN Doğrulanmadı",
            "RFID_Error_Session_eSign_RequiresAppSelection" : "RFID: eSign Uygulama Seçimi Gerektirir",
            "RFID_Error_UnknownCommand" : "RFID: Bilinmeyen komut",
            "RFID_LAYER6_APP_SELECTION_FAILURE" : "LAYER6: ISO7816_A_03 \"Uygulama seçimi başarısız\"",
            "RFID_LAYER6_EXT_AUTH_FAILURE" : "LAYER6: APDU_INS_EXTERNAL_AUTHENTICATE (Dış Kimlik Doğrulama) başarısız",
            "RFID_LAYER6_FILE_EOF1" : "LAYER6: Dosya sonu ötesinde okuma / Beklenmeyen dosya sonu",
            "RFID_LAYER6_FILE_EOF2" : "LAYER6: Dosya sonu ötesinde okuma / Beklenmeyen dosya sonu",
            "RFID_LAYER6_FILE_NOT_FOUND" : "LAYER6: Dosya seçimi başarısız / dosya bulunamadı",
            "RFID_LAYER6_GENERAL_AUTH_FAILURE" : "LAYER6: Genel Kimlik Doğrulama Başarısız",
            "RFID_LAYER6_GET_CHALLENGE_FAILURE" : "LAYER6: GET CHALLENGE başarısız",
            "RFID_LAYER6_INCORRECT_PARAMS" : "LAYER6: Hatalı Parametreler",
            "RFID_LAYER6_INT_AUTH_FAILURE" : "LAYER6: APDU_INS_INTERNAL_AUTHENTICATE başarısız",
            "RFID_LAYER6_MSE_SET_AT_FAILURE" : "LAYER6: MSE:Set AT başarısız",
            "RFID_LAYER6_MSE_SET_DST_FAILURE" : "LAYER6: MSE:Set DST başarısız",
            "RFID_LAYER6_MSE_SET_KAT_FAILURE" : "LAYER6: MSE:Set KAT başarısız",
            "RFID_LAYER6_MUTUAL_AUTH_ENC_FAIL": "KATMAN6: ISO7816_B_02 \"Karşılıklı kimlik doğrulama şifreleme hatası\"",
            "RFID_LAYER6_MUTUAL_AUTH_FAILURE": "KATMAN6: ISO7816_B_03 \"Karşılıklı kimlik doğrulama hatası\"",
            "RFID_LAYER6_MUTUAL_AUTH_MAC_FAIL": "KATMAN6: ISO7816_B_01 \"Karşılıklı kimlik doğrulama MAC hatası\"",
            "RFID_LAYER6_NON_TLV_RESPONSE_DATA": "KATMAN6: TLV olmayan yanıt verisi",
            "RFID_LAYER6_NO_REFERENCE_DATA": "KATMAN6: Referans Verisi Yok",
            "RFID_LAYER6_PSO_CERTIFICATE_FAILURE": "KATMAN6: PSO SERTİFİKA hatası",
            "RFID_LAYER6_PWD_BLOCKED": "KATMAN6: Şifre Bloke Edildi",
            "RFID_LAYER6_PWD_BLOCKED_2": "KATMAN6: Şifre Bloke Edildi 2",
            "RFID_LAYER6_PWD_DEACTIVATED": "KATMAN6: Şifre Devre Dışı Bırakıldı",
            "RFID_LAYER6_PWD_DEACTIVATED_2": "KATMAN6: Şifre Devre Dışı Bırakıldı 2",
            "RFID_LAYER6_PWD_FAILED": "KATMAN6: Şifre Hatalı",
            "RFID_LAYER6_PWD_SUSPENDED": "KATMAN6: Şifre Askıya Alındı",
            "RFID_LAYER6_PWD_SUSPENDED_2": "KATMAN6: Şifre Askıya Alındı 2",
            "RFID_LAYER6_SECURITY_MANAGER": "KATMAN6: Güvenli Mesajlaşma etkinleştirilmedi",
            "RFID_LAYER6_SM_DO87_INCORRECT": "KATMAN6: SM hatası – yanlış kriptogram",
            "RFID_LAYER6_SM_DO87_MISSING": "KATMAN6: SM hatası – kriptogram eksik",
            "RFID_LAYER6_SM_DO8E_MISSING": "KATMAN6: SM hatası – MAC eksik",
            "RFID_LAYER6_SM_DO99_MISSING": "KATMAN6: SM hatası – güvenli durum baytları eksik",
            "RFID_LAYER6_SM_MAC_INCORRECT": "KATMAN6: SM hatası – yanlış MAC",
            "RFID_LAYER6_WRONG_RND_ICC_LENGTH": "KATMAN6: Yanlış veri uzunluğu (APDU_INS_GET_CHALLENGE)",
            "RSDT_RFID_READING_FINISHED": "RFID veri okuması tamamlandı",
            "TCT_Unknown": "Bilinmeyen",
            "chd_BackgroundComparisonError": "İki sayfanın parlaklığı farklı",
            "chd_BadAreaInAxial": "Retroreflektif koruma hatası",
            "chd_BarcodeDataFormatError": "Barkod format hatası",
            "chd_BarcodeReadedWithErrors": "Barkod hatalı okundu",
            "chd_BarcodeSizeParamsError": "Barkod parametre hatası",
            "chd_DocumentIsCancelling": "Belge iptal ediliyor",
            "chd_ElementShouldBeColored": "Eleman renkli olmalı",
            "chd_ElementShouldBeGrayscale": "Eleman gri tonlamalı olmalı",
            "chd_ExceptionInModule": "Modülde istisna oluştu",
            "chd_FalseIPIParameters": "Yanlış IPI parametreleri",
            "chd_FalseLuminiscenceError": "Fazla ışıldayan nesnelerin varlığı",
            "chd_FalseLuminiscenceInBlank": "UV'de sahte fosfor",
            "chd_FalseLuminiscenceInMRZ": "MRZ'de aşırı fosfor",
            "chd_FibersNotFound": "Lifler bulunamadı",
            "chd_FieldPosCorrector_Highlight_IR": "IR'de aşırı ışık",
            "chd_FieldsComparisonLogicError": "Alanları karşılaştırırken mantıksal hata",
            "chd_FixedPatternError": "Belirtilen nesne uyuşmazlığı",
            "chd_HologramElementAbsent": "Hologram yok",
            "chd_HologramElementPresent": "Hologram bulundu",
            "chd_Hologram_Side_Top_Images_Absent": "Yan veya üst görüntüler yok",
            "chd_IncorrectBackgroundLight": "Yanlış arka plan parlaklığı",
            "chd_IncorrectTextColor": "Yanlış metin rengi",
            "chd_InternalError": "Dahili veri işleme hatası",
            "chd_InvalidChecksum": "Geçersiz kontrol toplamı",
            "chd_InvalidFieldFormat": "Alanın formatı belgenin tanımıyla uyuşmuyor",
            "chd_InvalidInputData": "Geçersiz giriş verisi",
            "chd_InvisibleElementPresent": "Nesne görünmez olmalı",
            "chd_LogicError": "Mantıksal veri hatası",
            "chd_LowContrastInIRLight": "IR ışığında yanlış nesne kontrastı",
            "chd_MobileImages_LowLightConditions": "Görüntüleri yakalamak için uygun olmayan ışık koşulları",
            "chd_MobileImages_WhileUVNoDifference": "Farklı aydınlatma düzenlerindeki görüntüler arasında düşük fark",
            "chd_NecessaryImageNotFound": "Bu kontrol için gereken görüntü bulunamadı",
            "chd_NotAllBarcodesRead": "Bu belgede daha fazla barkod bulunmalı",
            "chd_OVI_BadColor_Front": "Beyaz ışık altında OVI nesne rengi uyuşmazlığı",
            "chd_OVI_BadColor_Percent": "OVI unsurları arasında düşük uyuşma yüzdesi",
            "chd_OVI_BadColor_Side": "Aksiyal ışık altında OVI nesne rengi uyuşmazlığı",
            "chd_OVI_ColorInvariable": "OVI rengi değişmez",
            "chd_OVI_IR_Invisible": "OVI nesne kontrast uyuşmazlığı",
            "chd_OVI_InsufficientArea": "Yetersiz OVI nesne alanı",
            "chd_OVI_Wide_Color_Spread": "OVI nesne renk aralığı uyuşmazlığı",
            "chd_Pass": "Hata yok",
            "chd_PhotoFalseLuminiscence": "Fotoğraf alanında yanlış fosfor",
            "chd_PhotoPattern_DifferentColors": "Fotoğraftaki desen ve boş alandaki renkler farklı",
            "chd_PhotoPattern_DifferentLinesThickness": "Desen çizgilerinin farklı kalınlığı",
            "chd_PhotoPattern_IR_Visible": "IR'de güvenlik deseni görünür",
            "chd_PhotoPattern_Interrupted": "Fotoğraf ile boş alan arasındaki desende kesik var",
            "chd_PhotoPattern_InvalidColor": "Güvenlik deseninin geçersiz rengi",
            "chd_PhotoPattern_Not_Intersect": "Fotoğraf kenarı desenle kesişmiyor",
            "chd_PhotoPattern_PatternNotFound": "Fotoğraf alanında desen bulunamadı",
            "chd_PhotoPattern_Shifted": "Fotoğraftaki desen, boş alandaki desene göre kaymış",
            "chd_PhotoPattern_Shifted_Vert": "Desen çizgileri dikey olarak kaydırılmış",
            "chd_PhotoSidesNotFound": "Gerekli fotoğraf kenarı bulunamadı",
            "chd_PhotoSize_Is_Wrong": "Fotoğraf boyutu yanlış",
            "chd_Photo_Corners_Is_Wrong": "Fotoğraf köşeleri gereksinimleri karşılamıyor",
            "chd_Photo_IsNot_Rectangle": "Fotoğrafın şekli dikdörtgen değil",
            "chd_PortraitComparison_NoLivePhoto": "Canlı bir fotoğraf yok",
            "chd_PortraitComparison_NoPortraitDetected": "Görüntüde yüz bulunamadı",
            "chd_PortraitComparison_NoServiceLicense": "Hizmet için lisans yok",
            "chd_PortraitComparison_NoServiceReply": "Hizmet cevap vermiyor",
            "chd_PortraitComparison_NotEnoughImages": "Yeterli sayıda görüntü yok",
            "chd_PortraitComparison_PortraitsDiffer": "Portreler uyuşmuyor",
            "chd_PortraitComparison_ServiceError": "Hizmet hatası",
            "chd_SourcesComparisonError": "Farklı kaynaklardan gelen verilerin uyuşmaması",
            "chd_SpecksInUV": "UV ışığında görüntüde fazla pozlama veya parlamalar",
            "chd_SyntaxError": "Veri sözdizimi hatası",
            "chd_TextColorShouldBeBlue": "Metin rengi mavi olmalı",
            "chd_TextColorShouldBeGreen": "Metin rengi yeşil olmalı",
            "chd_TextColorShouldBeRed": "Metin rengi kırmızı olmalı",
            "chd_TextShouldBeBlack": "Metin rengi siyah olmalı",
            "chd_TooLowResolution": "Lifleri tespit etmek için çözünürlük çok düşük",
            "chd_TooManyObjects": "Çok fazla nesne",
            "chd_TooMuchShift": "Kaydırma değeri izin verilen değerden büyük",
            "chd_TrueLuminiscenceError": "Fosforlu nesnelerin uyuşmaması",
            "chd_UVDullPaperError": "UV mat kağıt kontrol hatası",
            "chd_UVDullPaper_Blank": "Boş alanın UV mat kağıt kontrolü",
            "chd_UVDullPaper_MRZ": "MRZ alanında UV mat kağıt kontrolü",
            "chd_UVDullPaper_Photo": "Fotoğraf alanında UV mat kağıt kontrolü",
            "chd_UncertainVerification": "Güvenilir karar verilemiyor",
            "chd_Unknown": "Bilinmeyen ret",
            "chd_VisibleElementAbsent": "IR altında görünür nesne yok",
            "strAGY": "AGY",
            "strAKADateofBirth": "AKA Doğum tarihi",
            "strAKAGivenNames": "AKA Verilen isimler",
            "strAKANamePrefix": "AKA İsim öneki",
            "strAKANameSuffix": "AKA İsim soneki",
            "strAKASocialSecurityNumber": "AKA Sosyal Güvenlik Numarası",
            "strAKASurname": "AKA Soyadı",
            "strAKASurnameAndGivenNames": "AKA Tam adı",
            "strALTCode": "ALT kodu",
            "strAcademicTitle": "Akademik unvan",
            "strAccessibilityCameraButton": "Bir görüntü çekin ve işlemeyi başlatın",
            "strAccessibilityCloseButton": "Kapat",
            "strAccessibilityTorchButton": "Fener",
            "strAccompaniedby": "Eşliğinde",
            "strAddress": "Adres",
            "strAddressArea": "Alan",
            "strAddressBuilding": "Birim",
            "strAddressCity": "Şehir",
            "strAddressCountry": "Ülke",
            "strAddressFlat": "Daire",
            "strAddressHouse": "Bina",
            "strAddressJurisdictionCode": "Yargı kodu",
            "strAddressLocation": "Konum",
            "strAddressMunicipality": "Belediye",
            "strAddressPostalCode": "Posta kodu",
            "strAddressState": "Eyalet",
            "strAddressStreet": "Cadde",
            "strAdministrativeNumber": "Yönetim numarası",
            "strAge": "Yaş",
            "strAgeAtIssue": "Sorun yaşında",
            "strAirlineDesignatorofboardingpassissuer": "Biniş kartı veren havayolu belirleyici",
            "strAirlineName": "Havayolu adı",
            "strAirlineNameFrequentFlyer": "Sık uçanlar için havayolu sadakat programı",
            "strAirlineNumericCode": "Havayolu sayısal kodu",
            "strAirportFrom": "Kalkış havalimanı",
            "strAirportTo": "Varış havalimanı",
            "strAllergies": "Alerjiler",
            "strApplicationDoNotHavePermission": "Uygulamanın kamerayı kullanma izni yok, lütfen gizlilik ayarlarını değiştirin",
            "strApplicationNumber": "Başvuru numarası",
            "strArtisticName": "Takma ad",
            "strAuditInformation": "Doğrulama numarası",
            "strAuthentification": "Doğrulama",
            "strAuthority": "Veren yetkili",
            "strAuthorityCode": "Veren yetkili kodu",
            "strAuthorityRUS": "Veren yetkili (Ulusal)",
            "strAuthorizationNumber": "Yetkilendirme numarası",
            "strAxialProtection": "Eksen koruması",
            "strBDBType": "BDB türü",
            "strBankCardNumber": "Banka kartı numarası",
            "strBankCardValidThru": "Banka kartı geçerlilik süresi",
            "strBanknoteNumber": "Banknot numarası",
            "strBarcode": "Barkod",
            "strBarcodeFormatCheck": "Barkod format kontrolü",
            "strBenefitsNumber": "Fayda numarası",
            "strBinaryCode": "İkili kod",
            "strBiometricFormatOwner": "Biyometrik format sahibi",
            "strBiometricFormatType": "Biyometrik format türü",
            "strBiometricProductID": "Biyometrik ürün kimliği",
            "strBiometricSubtype": "Biyometrik alt tür",
            "strBiometricType": "Biyometrik tür",
            "strBlankElement": "Boş öğe",
            "strBloodGroup": "Kan grubu",
            "strBookletNumber": "Broşür numarası",
            "strCCWUntil": "Saat yönünde son",
            "strCDLClass": "CDL Sınıfı",
            "strCSCCode": "CSC Kodu",
            "strCVV": "CVV/CVC",
            "strCaliber": "Kalibre",
            "strCameraUnavailable": "Kamera kullanılamıyor",
            "strCardAccessNumber": "Kart erişim numarası",
            "strCategory": "Kategori",
            "strCenturyDateOfBirth": "Doğum yılı yüzyılı",
            "strChassisNumber": "Şasi numarası",
            "strCheckInSequenceNumber": "Giriş sıra numarası",
            "strChildren": "Çocuklar",
            "strCitizenshipOfFirstPerson": "İlk kişinin vatandaşlığı",
            "strCitizenshipOfSecondPerson": "İkinci kişinin vatandaşlığı",
            "strCivilStatus": "Medeni durum",
            "strColorDynamic": "Renk dinamikleri",
            "strCommercialVehicleCodes": "Ticari araç kodları",
            "strCompanyName": "Şirket adı",
            "strCompartmentCode": "Bölme kodu",
            "strComplexion": "Ten rengi",
            "strComplianceType": "Uygunluk tipi",
            "strConditions": "Koşullar",
            "strConfiguration": "Yapılandırma",
            "strControlNo": "Kontrol numarası",
            "strCopy": "Kopya",
            "strCourtCode": "Mahkeme kodu",
            "strCty": "İlçe",
            "strCurrentDate": "Geçerli tarih",
            "strCustodyInfo": "Velayet bilgisi",
            "strDFTAppDirectory": "Uygulama dizini",
            "strDFTCertificate": "Sertifika",
            "strDG1": "Makine Okunabilir Bölge (DG1)",
            "strDG10": "Tanımlanmamış (DG10)",
            "strDG11": "Ek kişisel detay(lar) (DG11)",
            "strDG12": "Ek belge detayları (DG12)",
            "strDG13": "İsteğe bağlı detay(lar) (DG13)",
            "strDG14": "EAC bilgisi (DG14)",
            "strDG15": "Etkin Kimlik Doğrulama bilgisi (DG15)",
            "strDG16": "Bildirilecek kişi(ler) (DG16)",
            "strDG17": "DG17",
            "strDG18": "DG18",
            "strDG19": "DG19",
            "strDG2": "Biyometri - Yüz verileri (DG2)",
            "strDG20": "DG20",
            "strDG3": "Biyometri - Parmak izi(leri) (DG3)",
            "strDG4": "Biyometri - Iris Verisi (DG4)",
            "strDG5": "Portre(ler) (DG5)",
            "strDG6": "Tanımlanmamış (DG6)",
            "strDG7": "İmza / alışılmış işaret görüntüsü (DG7)",
            "strDG8": "Tanımlanmamış (DG8)",
            "strDG9": "Tanımlanmamış (DG9)",
            "strDLCDLRestrictionCode": "CDL Kısıtlama Kodu",
            "strDLClass": "Sürücü belgesi kategorisi",
            "strDLClassCodeA1From": "A1 kategorisi geçerli başlangıç tarihi",
            "strDLClassCodeA1Notes": "A1 kategorisi kodları",
            "strDLClassCodeA1To": "A1 kategorisi geçerli bitiş tarihi",
            "strDLClassCodeA2From": "A2 kategorisi geçerli başlangıç tarihi",
            "strDLClassCodeA2Notes": "A2 kategorisi kodları",
            "strDLClassCodeA2To": "A2 kategorisi geçerli bitiş tarihi",
            "strDLClassCodeA3From": "A3 kategorisi geçerli başlangıç tarihi",
            "strDLClassCodeA3Notes": "A3 kategorisi kodları",
            "strDLClassCodeA3To": "A3 kategorisi geçerli bitiş tarihi",
            "strDLClassCodeAFrom": "A kategorisi geçerli başlangıç tarihi",
            "strDLClassCodeAMFrom": "AM kategorisi geçerli başlangıç tarihi",
            "strDLClassCodeAMNotes": "AM kategorisi kodları",
            "strDLClassCodeAMTo": "DL kategorisi AM için geçerli bitiş tarihi",
            "strDLClassCodeANotes": "DL kategorisi A kodları",
            "strDLClassCodeATo": "DL kategorisi A için geçerli bitiş tarihi",
            "strDLClassCodeB1From": "DL kategorisi B1 için geçerli başlangıç tarihi",
            "strDLClassCodeB1Notes": "DL kategorisi B1 kodları",
            "strDLClassCodeB1To": "DL kategorisi B1 için geçerli bitiş tarihi",
            "strDLClassCodeB2EFrom": "DL kategorisi B2E için geçerli başlangıç tarihi",
            "strDLClassCodeB2ENotes": "DL kategorisi B2E kodları",
            "strDLClassCodeB2ETo": "DL kategorisi B2E için geçerli bitiş tarihi",
            "strDLClassCodeB2From": "DL kategorisi B2 için geçerli başlangıç tarihi",
            "strDLClassCodeB2Notes": "DL kategorisi B2 kodları",
            "strDLClassCodeB2To": "DL kategorisi B2 için geçerli bitiş tarihi",
            "strDLClassCodeBEFrom": "DL kategorisi BE için geçerli başlangıç tarihi",
            "strDLClassCodeBENotes": "DL kategorisi BE kodları",
            "strDLClassCodeBETo": "DL kategorisi BE için geçerli bitiş tarihi",
            "strDLClassCodeBFrom": "DL kategorisi B için geçerli başlangıç tarihi",
            "strDLClassCodeBNotes": "DL kategorisi B kodları",
            "strDLClassCodeBTPFrom": "DL kategorisi BTP için geçerli başlangıç tarihi",
            "strDLClassCodeBTPNotes": "DL kategorisi BTP kodları",
            "strDLClassCodeBTPTo": "DL kategorisi BTP için geçerli bitiş tarihi",
            "strDLClassCodeBTo": "DL kategorisi B için geçerli bitiş tarihi",
            "strDLClassCodeC1EFrom": "DL kategorisi C1E için geçerli başlangıç tarihi",
            "strDLClassCodeC1ENotes": "DL kategorisi C1E kodları",
            "strDLClassCodeC1ETo": "DL kategorisi C1E için geçerli bitiş tarihi",
            "strDLClassCodeC1From": "DL kategorisi C1 için geçerli başlangıç tarihi",
            "strDLClassCodeC1Notes": "DL kategorisi C1 kodları",
            "strDLClassCodeC1To": "DL kategorisi C1 için geçerli bitiş tarihi",
            "strDLClassCodeC2From": "DL kategorisi C2 için geçerli başlangıç tarihi",
            "strDLClassCodeC2Notes": "DL kategorisi C2 kodları",
            "strDLClassCodeC2To": "DL kategorisi C2 için geçerli bitiş tarihi",
            "strDLClassCodeC3From": "DL kategorisi C3 için geçerli başlangıç tarihi",
            "strDLClassCodeC3Notes": "DL kategorisi C3 kodları",
            "strDLClassCodeC3To": "DL kategorisi C3 için geçerli bitiş tarihi",
            "strDLClassCodeCAFrom": "DL kategorisi CA için geçerli başlangıç tarihi",
            "strDLClassCodeCANotes": "DL kategorisi CA kodları",
            "strDLClassCodeCATo": "DL kategorisi CA için geçerli bitiş tarihi",
            "strDLClassCodeCEFrom": "DL kategorisi CE için geçerli başlangıç tarihi",
            "strDLClassCodeCENotes": "DL kategorisi CE kodları",
            "strDLClassCodeCETo": "DL kategorisi CE için geçerli bitiş tarihi",
            "strDLClassCodeCFrom": "DL kategorisi C için geçerli başlangıç tarihi",
            "strDLClassCodeCNotes": "DL kategorisi C kodları",
            "strDLClassCodeCTo": "DL kategorisi C için geçerli bitiş tarihi",
            "strDLClassCodeD1EFrom": "DL kategorisi D1E için geçerli başlangıç tarihi",
            "strDLClassCodeD1ENotes": "DL kategorisi D1E kodları",
            "strDLClassCodeD1ETo": "DL kategorisi D1E için geçerli bitiş tarihi",
            "strDLClassCodeD1From": "DL kategorisi D1 için geçerli başlangıç tarihi",
            "strDLClassCodeD1Notes": "DL kategorisi D1 kodları",
            "strDLClassCodeD1To": "DL kategorisi D1 için geçerli bitiş tarihi",
            "strDLClassCodeD2From": "DL kategorisi D2 için geçerli başlangıç tarihi",
            "strDLClassCodeD2Notes": "DL kategorisi D2 kodları",
            "strDLClassCodeD2To": "DL kategorisi D2 için geçerli bitiş tarihi",
            "strDLClassCodeDEFrom": "DL kategorisi DE için geçerli başlangıç tarihi",
            "strDLClassCodeDENotes": "DL kategorisi DE kodları",
            "strDLClassCodeDETo": "DL kategorisi DE için geçerli bitiş tarihi",
            "strDLClassCodeDFrom": "DL kategorisi D için geçerli başlangıç tarihi",
            "strDLClassCodeDNotes": "DL kategorisi D kodları",
            "strDLClassCodeDTo": "DL kategorisi D için geçerli bitiş tarihi",
            "strDLClassCodeEFrom": "DL kategorisi E için geçerli başlangıç tarihi",
            "strDLClassCodeENotes": "DL kategorisi E kodları",
            "strDLClassCodeETo": "DL kategorisi E için geçerli bitiş tarihi",
            "strDLClassCodeFA1From": "DL kategorisi FA1 için geçerli başlangıç tarihi",
            "strDLClassCodeFA1Notes": "DL kategorisi FA1 kodları",
            "strDLClassCodeFA1To": "DL kategorisi FA1 için geçerli bitiş tarihi",
            "strDLClassCodeFAFrom": "DL kategorisi FA için geçerli başlangıç tarihi",
            "strDLClassCodeFANotes": "DL kategorisi FA kodları",
            "strDLClassCodeFATo": "DL kategorisi FA için geçerli bitiş tarihi",
            "strDLClassCodeFBFrom": "DL kategorisi FB için geçerli başlangıç tarihi",
            "strDLClassCodeFBNotes": "DL kategorisi FB kodları",
            "strDLClassCodeFBTo": "DL kategorisi FB için geçerli bitiş tarihi",
            "strDLClassCodeFFrom": "DL kategorisi F için geçerli başlangıç tarihi",
            "strDLClassCodeFNotes": "DL kategorisi F kodları",
            "strDLClassCodeFTo": "DL kategorisi F için geçerli bitiş tarihi",
            "strDLClassCodeG1From": "DL kategorisi G1 için geçerli başlangıç tarihi",
            "strDLClassCodeG1Notes": "DL kategorisi G1 kodları",
            "strDLClassCodeG1To": "DL kategorisi G1 için geçerli bitiş tarihi",
            "strDLClassCodeGFrom": "DL kategorisi G için geçerli başlangıç tarihi",
            "strDLClassCodeGNotes": "DL kategorisi G kodları",
            "strDLClassCodeGTo": "DL kategorisi G için geçerli bitiş tarihi",
            "strDLClassCodeHCFrom": "DL kategorisi HC için geçerli başlangıç tarihi",
            "strDLClassCodeHCNotes": "DL kategorisi HC kodları",
            "strDLClassCodeHCTo": "DL kategorisi HC için geçerli bitiş tarihi",
            "strDLClassCodeHFrom": "DL kategorisi H için geçerli başlangıç tarihi",
            "strDLClassCodeHNotes": "DL kategorisi H kodları",
            "strDLClassCodeHRFrom": "DL kategorisi HR için geçerli başlangıç tarihi",
            "strDLClassCodeHRNotes": "DL kategorisi HR kodları",
            "strDLClassCodeHRTo": "DL kategorisi HR için geçerli bitiş tarihi",
            "strDLClassCodeHTo": "DL kategorisi H için geçerli bitiş tarihi",
            "strDLClassCodeIFrom": "DL kategorisi I için geçerli başlangıç tarihi",
            "strDLClassCodeINotes": "DL kategorisi I kodları",
            "strDLClassCodeITo": "DL kategorisi I için geçerli bitiş tarihi",
            "strDLClassCodeJFrom": "DL kategorisi J için geçerli başlangıç tarihi",
            "strDLClassCodeJNotes": "DL kategorisi J kodları",
            "strDLClassCodeJTo": "DL kategorisi J için geçerli bitiş tarihi",
            "strDLClassCodeKFrom": "DL kategorisi K için geçerli başlangıç tarihi",
            "strDLClassCodeKNotes": "DL kategorisi K kodları",
            "strDLClassCodeKTo": "DL kategorisi K için geçerli bitiş tarihi",
            "strDLClassCodeLCFrom": "DL kategorisi LC için geçerli başlangıç tarihi",
            "strDLClassCodeLCNotes": "DL kategorisi LC kodları",
            "strDLClassCodeLCTo": "DL kategorisi LC için geçerli bitiş tarihi",
            "strDLClassCodeLFrom": "DL kategorisi L için geçerli başlangıç tarihi",
            "strDLClassCodeLKFrom": "DL kategorisi LK için geçerli başlangıç tarihi",
            "strDLClassCodeLKNotes": "DL kategorisi LK kodları",
            "strDLClassCodeLKTo": "DL kategorisi LK için geçerli bitiş tarihi",
            "strDLClassCodeLNotes": "DL kategorisi L kodları",
            "strDLClassCodeLRFrom": "DL kategorisi LR için geçerli başlangıç tarihi",
            "strDLClassCodeLRNotes": "DL kategorisi LR kodları",
            "strDLClassCodeLRTo": "DL kategorisi LR için geçerli bitiş tarihi",
            "strDLClassCodeLTo": "DL kategorisi L için geçerli bitiş tarihi",
            "strDLClassCodeMCFrom": "DL kategorisi MC için geçerli başlangıç tarihi",
            "strDLClassCodeMCNotes": "DL kategorisi MC kodları",
            "strDLClassCodeMCTo": "DL kategorisi MC için geçerli bitiş tarihi",
            "strDLClassCodeMFrom": "DL kategorisi M için geçerli başlangıç tarihi",
            "strDLClassCodeMNotes": "DL kategorisi M kodları",
            "strDLClassCodeMRFrom": "DL kategorisi MR için geçerli başlangıç tarihi",
            "strDLClassCodeMRNotes": "DL kategorisi MR kodları",
            "strDLClassCodeMRTo": "DL kategorisi MR için geçerli bitiş tarihi",
            "strDLClassCodeMTo": "DL kategorisi M için geçerli bitiş tarihi",
            "strDLClassCodeNFrom": "DL kategorisi N için geçerli başlangıç tarihi",
            "strDLClassCodeNNotes": "DL kategorisi N kodları",
            "strDLClassCodeNTo": "DL kategorisi N için geçerli bitiş tarihi",
            "strDLClassCodeREFrom": "DL kategorisi RE için geçerli başlangıç tarihi",
            "strDLClassCodeRENotes": "DL kategorisi RE kodları",
            "strDLClassCodeRETo": "DL kategorisi RE için geçerli bitiş tarihi",
            "strDLClassCodeRFrom": "DL kategorisi R için geçerli başlangıç tarihi",
            "strDLClassCodeRNotes": "DL kategorisi R kodları",
            "strDLClassCodeRTo": "DL kategorisi R için geçerli bitiş tarihi",
            "strDLClassCodeSFrom": "DL kategorisi S için geçerli başlangıç tarihi",
            "strDLClassCodeSNotes": "DL kategorisi S kodları",
            "strDLClassCodeSTo": "DL kategorisi S için geçerli bitiş tarihi",
            "strDLClassCodeTBFrom": "DL kategorisi TB için geçerli başlangıç tarihi",
            "strDLClassCodeTBNotes": "DL kategorisi TB kodları",
            "strDLClassCodeTBTo": "DL kategorisi TB için geçerli bitiş tarihi",
            "strDLClassCodeTFrom": "DL kategorisi T için geçerli başlangıç tarihi",
            "strDLClassCodeTMFrom": "DL kategorisi TM için geçerli başlangıç tarihi",
            "strDLClassCodeTMNotes": "DL kategorisi TM kodları",
            "strDLClassCodeTMTo": "DL kategorisi TM için geçerli bitiş tarihi",
            "strDLClassCodeTNotes": "DL kategorisi T kodları",
            "strDLClassCodeTRFrom": "DL kategorisi TR için geçerli başlangıç tarihi",
            "strDLClassCodeTRNotes": "DL kategorisi TR kodları",
            "strDLClassCodeTRTo": "DL kategorisi TR için geçerli bitiş tarihi",
            "strDLClassCodeTTo": "DL kategorisi T için geçerli bitiş tarihi",
            "strDLClassCodeTVFrom": "DL kategorisi TV için geçerli başlangıç tarihi",
            "strDLClassCodeTVNotes": "DL kategorisi TV kodları",
            "strDLClassCodeTVTo": "DL kategorisi TV için geçerli bitiş tarihi",
            "strDLClassCodeVFrom": "DL kategorisi V için geçerli başlangıç tarihi",
            "strDLClassCodeVNotes": "DL kategorisi V kodları",
            "strDLClassCodeVTo": "DL kategorisi V için geçerli bitiş tarihi",
            "strDLClassCodeWFrom": "DL kategorisi W için geçerli başlangıç tarihi",
            "strDLClassCodeWNotes": "DL kategorisi W kodları",
            "strDLClassCodeWTo": "DL kategorisi W için geçerli bitiş tarihi",
            "strDLDuplicateDate": "Çoğaltma tarihi",
            "strDLEndorsed": "DL onay kodu",
            "strDLIssType": "Kart tipi",
            "strDLRecordCreated": "Kayıt oluşturulma tarihi",
            "strDLRestrictionCode": "DL kısıtlama kodu",
            "strDLUnder18Date": "18. doğum günü tarihi",
            "strDLUnder19Date": "19. doğum günü tarihi",
            "strDLUnder21Date": "21. doğum günü tarihi",
            "strDNINumber": "DNI numarası",
            "strDSCertificateIssuer": "DS sertifika düzenleyicisi",
            "strDSCertificateSubject": "DS sertifika konusu",
            "strDSCertificateValidFrom": "DS sertifikasının geçerlilik başlangıç tarihi",
            "strDSCertificateValidTo": "DS sertifikasının geçerlilik bitiş tarihi",
            "strDUFNumber": "DUF numarası",
            "strDataDiscriminator": "Veri ayırt edici",
            "strDateFirstRenewal": "İlk yenileme tarihi",
            "strDateOfBirthOfHusband": "Eşin doğum tarihi",
            "strDateOfBirthOfWife": "Eşin doğum tarihi",
            "strDateOfInsuranceExpiry": "Sigorta sona erme tarihi",
            "strDateSecondRenewal": "İkinci yenileme tarihi",
            "strDateofBirth": "Doğum tarihi",
            "strDateofBirthCheckDigit": "Doğum tarihi kontrol rakamı",
            "strDateofBirthChecksum": "Doğum tarihi toplamı",
            "strDateofCreation": "Oluşturma tarihi",
            "strDateofExpiry": "Sona erme tarihi",
            "strDateofExpiryCheckDigit": "Sona erme tarihi kontrol rakamı",
            "strDateofExpiryChecksum": "Sona erme tarihi toplamı",
            "strDateofFlight": "Uçuş tarihi",
            "strDateofIssue": "Veriliş tarihi",
            "strDateofIssueBoardingPass": "Biniş kartı veriliş tarihi",
            "strDateofIssueCheckDigit": "Veriliş tarihi kontrol rakamı",
            "strDateofIssueChecksum": "Veriliş tarihi toplamı",
            "strDateofPersonalization": "Kişiselleştirme tarihi",
            "strDateofRegistration": "Kayıt tarihi",
            "strDay": "Gün",
            "strDepartment": "Departman",
            "strDeptNumber": "Departman numarası",
            "strDestination": "Varış noktası",
            "strDiscretionaryData": "Keyfi veri",
            "strDoDNumber": "DoD numarası",
            "strDocumentClassCode": "Belge sınıf kodu",
            "strDocumentClassName": "Belge sınıfı",
            "strDocumentDiscriminator": "Belge ayırt edici",
            "strDocumentNumber": "Belge numarası",
            "strDocumentNumberCheckDigit": "Belge numarası kontrol rakamı",
            "strDocumentNumberChecksum": "Belge numarası toplamı",
            "strDocumentSeries": "Belge serisi",
            "strDocumentTooSmall": "Belge çerçevesine yerleştirin",
            "strDonor": "Bağışçı",
            "strDossierNumber": "Dosya numarası",
            "strDurationofStay": "Konaklama süresi",
            "strECEnvironmentalType": "Araç çevre türü",
            "strEDLDG1": "Metin veri öğeleri (DG1)",
            "strEDLDG10": "Tanımlanmamış (DG10)",
            "strEDLDG11": "Opsiyonel yerel veri (DG11)",
            "strEDLDG12": "Eşleşmeme uyarısı (DG12)",
            "strEDLDG13": "Aktif doğrulama bilgileri (DG13)",
            "strEDLDG14": "EAC bilgisi (DG14)",
            "strEDLDG2": "Lisans sahibi bilgileri (DG2)",
            "strEDLDG3": "Düzenleyici makam detayları (DG3)",
            "strEDLDG4": "Portre görüntüsü (DG4)",
            "strEDLDG5": "İmza / tipik işareti görüntüsü (DG5)",
            "strEDLDG6": "Biyometri - Yüz verileri (DG6)",
            "strEDLDG7": "Biyometri - Parmak izi(leri) (DG7)",
            "strEDLDG8": "Biyometri - Iris Verileri (DG8)",
            "strEDLDG9": "Biyometri - Diğer (DG9)",
            "strEFCOM": "EF.COM",
            "strEFCVCA": "EF.CVCA",
            "strEFCardAccess": "EF.KartErişim",
            "strEFCardSecurity": "EF.KartGüvenlik",
            "strEFChipSecurity": "EF.CipGüvenlik",
            "strEFSOD": "EF.SOD",
            "strEQVCode": "EQV kodu",
            "strElectronicTicketIndicator": "Elektronik bilet göstergesi",
            "strElement": "Öğe",
            "strEndorsementExpirationDate": "Onayın sona erme tarihi",
            "strEngineModel": "Motor modeli",
            "strEngineNumber": "Motor numarası",
            "strEnginePower": "Motor gücü",
            "strEngineVolume": "Motor hacmi",
            "strError": "Hata",
            "strExamDate": "Sınav tarihi",
            "strExeptInTanks": "Tanklarda hariç",
            "strEye": "Göz",
            "strEyesColor": "Göz rengi",
            "strFaculty": "Fakülte",
            "strFalseLuminescence": "Aşırı fosforesans",
            "strFamilyName": "Doğumda soyadı/verilen isim",
            "strFamilyNameTruncation": "Kısaltılmış soyadı/doğumda verilen isim",
            "strFastTrack": "Hızlı geçiş hizmeti",
            "strFatherCountryOfBirth": "Baba doğum ülkesi",
            "strFatherDateOfBirth": "Baba doğum tarihi",
            "strFatherGivenName": "Baba verilen ismi",
            "strFatherPersonalNumber": "Baba kişisel numarası",
            "strFatherPlaceOfBirth": "Baba doğum yeri",
            "strFatherSurname": "Baba soyadı",
            "strFathersName": "Baba adı",
            "strFathersNameRUS": "Baba adı (Milli)",
            "strFederalElections": "Federal seçimler",
            "strFee": "Ücret",
            "strFieldFromMRZ": "MRZ'den alan",
            "strFieldTypeDocumentImage": "Belge görüntüsü",
            "strFillElement": "Dolum öğesi",
            "strFinalCheckDigit": "Nihai kontrol rakamı",
            "strFinalChecksum": "Nihai toplam",
            "strFingerprint": "Parmak izi",
            "strFirstIssueDate": "İlk veriliş tarihi",
            "strFirstNameTruncation": "Adın kısaltılması",
            "strFlightNumber": "Uçuş numarası",
            "strFolioNumber": "Folio numarası",
            "strFormOfEducation": "Eğitim şekli",
            "strFreeBaggageAllowance": "Ücretsiz bagaj hakkı",
            "strFrequentFlyerAirlineDesignator": "Sık uçan yolcu havayolu belirleyici",
            "strFrequentFlyerNumber": "Sık uçan yolcu numarası",
            "strFromAirportCode": "Kalkış havaalanı kodu",
            "strFuelType": "Yakıt tipi",
            "strGNIBNumber": "GNIB numarası",
            "strGhostPortrait": "Hayalet portre",
            "strGivenNames": "Verilen isim",
            "strGivenNamesRUS": "Verilen isim (Milli)",
            "strGlaresOnDocument": "Belgede parlamaları önleyin",
            "strGrandfatherName": "Dede adı",
            "strHairColor": "Saç rengi",
            "strHealthNumber": "Sağlık sigortası numarası",
            "strHeight": "Boy",
            "strHoldDocumentStraight": "Belgeyi düz tutun",
            "strHoloSimple": "Hologram mevcudiyeti",
            "strHoloVerifyDinamic": "Dinamik hologramı doğrulayın",
            "strHoloVerifyMultiStatic": "Çoklu Statik Hologramı Doğrulayın",
            "strHoloVerifyStatic": "Statik Hologramı Doğrulayın",
            "strHolograms": "Hologramlar",
            "strIPI": "IPI (görünmez kişisel bilgi)",
            "strIRB900": "IR B900 mürekkebi",
            "strIRVis": "IR geçirgenliği",
            "strISOIssuerIDNumber": "ISO veren kimlik numarası",
            "strIdentifier": "Tanımlayıcı",
            "strIdentityCardNumber": "Kimlik kartı numarası",
            "strIdentityCardNumberCheckDigit": "Kimlik kartı numarası için kontrol basamağı",
            "strIdentityCardNumberChecksum": "Kimlik kartı numarası için toplam kontrol",
            "strImagePattern": "Görüntü desenleri",
            "strInTanks": "Tanklarda",
            "strInventoryNumber": "Envanter numarası",
            "strInvitationNumber": "Davet numarası",
            "strInvitationNumberCheckDigit": "Davet numarası için kontrol basamağı",
            "strInvitationNumberChecksum": "Davet numarası için toplam kontrol",
            "strInvitedBy": "Davet eden",
            "strIssueTimestamp": "Süre damgası",
            "strIssuingStateCode": "Veren devlet kodu",
            "strIssuingStateName": "Veren devlet",
            "strJurisdictionEndorsementCode": "Yetki onay kodu",
            "strJurisdictionRestrictionCode": "Yetki kısıtlama kodu",
            "strJurisdictionVehicleClass": "Yetki araç sınıfı",
            "strKeepDeviceStill": "Cihazı sabit tutun",
            "strLicenseNumber": "Sürücü belge numarası",
            "strLimitedDurationDocumentIndicator": "Belgenin sınırlı süre göstergesi",
            "strLine1CheckDigit": "Satır 1 için kontrol basamağı",
            "strLine1Checksum": "Satır 1 için toplam kontrol",
            "strLine1OptionalData": "Satır 1'den isteğe bağlı veriler",
            "strLine2CheckDigit": "Satır 2 için kontrol basamağı",
            "strLine2Checksum": "Satır 2 için toplam kontrol",
            "strLine2OptionalData": "Satır 2'den isteğe bağlı veriler",
            "strLine3CheckDigit": "Satır 3 için kontrol basamağı",
            "strLine3Checksum": "Satır 3 için toplam kontrol",
            "strLine3OptionalData": "Satır 3'ten isteğe bağlı veriler",
            "strLookingDocument": "Belge aranıyor...",
            "strMCNoviceDate": "Motosiklet Novis durumunun son kullanma tarihi",
            "strMRZ": "MRZ",
            "strMRZLinesICAORFID": "ICAO RFID'den MRZ satırları",
            "strMRZString1": "MRZ satırı 1",
            "strMRZString2": "MRZ satırı 2",
            "strMRZString3": "MRZ satırı 3",
            "strMRZStrings": "MRZ satırları",
            "strMRZStringsWithCorrectCheckSums": "Doğru kontrol toplamlarına sahip MRZ satırları",
            "strMRZType": "MRZ Türü",
            "strMailingAddressCity": "Posta adresi - şehir",
            "strMailingAddressJurisdictionCode": "Posta adresi - yetki kodu",
            "strMailingAddressPostalCode": "Posta adresi - posta kodu",
            "strMailingAddressStreet": "Posta adresi - sokak",
            "strMake": "Marka",
            "strMaritalStatus": "Medeni durum",
            "strMaxMassofTrailerBraked": "Römorkun maksimum ağırlığı (frenli)",
            "strMaxMassofTrailerUnbraked": "Römorkun maksimum ağırlığı (frensiz)",
            "strMaxSpeed": "Maksimum hız",
            "strMedicalIndicatorCodes": "Tıbbi notlar/kodlar",
            "strMiddleName": "Orta isim",
            "strMiddleNameTruncation": "Orta isim kısaltma",
            "strMifareData": "MIFARE verisi",
            "strMifareValidity": "MIFARE geçerliliği",
            "strMilitaryBookNumber": "Askeri kimlik numarası",
            "strModel": "Model",
            "strMonth": "Ay",
            "strMortgageBy": "Mortgage by",
            "strMotherCountryOfBirth": "Anne ülkesi",
            "strMotherDateOfBirth": "Anne doğum tarihi",
            "strMotherGivenName": "Anne adı",
            "strMotherPersonalNumber": "Anne kişisel numarası",
            "strMotherPlaceOfBirth": "Anne doğum yeri",
            "strMotherSurname": "Anne soyadı",
            "strMothersName": "Anne adı",
            "strNamePrefix": "İsim ön eki",
            "strNameSuffix": "İsim soneki",
            "strNationality": "Uyruk",
            "strNationalityCode": "Uyruk kodu",
            "strNonResidentIndicator": "Sürekli olmayan gösterge",
            "strNone": "Hiçbiri",
            "strNotDefined": "Tanımlanmamış",
            "strNumberOfCardIssuance": "Kart çıkarma sayısı",
            "strNumberOfCardIssuanceCheckDigit": "Kart çıkarma sayısı için kontrol rakamı",
            "strNumberOfCardIssuanceChecksum": "Kart çıkarma sayısı için toplam kontrol",
            "strNumberOfCylinders": "Silindir sayısı",
            "strNumberofAxels": "Aks sayısı",
            "strNumberofDuplicates": "Kopya sayısı",
            "strNumberofEntries": "Giriş sayısı",
            "strNumberofSeats": "Koltuk sayısı",
            "strNumberofStandingPlaces": "Ayakta durma alanı sayısı",
            "strOCRNumber": "OCR numarası",
            "strOK": "Tamam",
            "strObservations": "Gözlemler",
            "strOldDateOfIssue": "Eski çıkış tarihi",
            "strOldDocumentNumber": "Eski belge numarası",
            "strOldPlaceOfIssue": "Eski çıkış yeri",
            "strOptionalData": "İsteğe bağlı veri",
            "strOptionalDataCheckDigit": "İsteğe bağlı veri için kontrol rakamı",
            "strOptionalDataChecksum": "İsteğe bağlı veri için toplam kontrol",
            "strOptionalDetails": "İsteğe bağlı detaylar",
            "strOrganization": "Kuruluş",
            "strOther": "Diğer",
            "strOtherName": "Diğer ad",
            "strOtherPersonName": "Diğer kişi adı",
            "strOtherValidID": "Diğer geçerli kimlikler",
            "strOwner": "Sahip",
            "strPDF417Codec": "PDF417 kodeki",
            "strPNRCode": "PNR kodu",
            "strParrentsGivenNames": "Ebeveynlerin verilen isimleri",
            "strPassportNumber": "Pasaport numarası",
            "strPassportNumberCheckDigit": "Pasaport numarası için kontrol rakamı",
            "strPassportNumberChecksum": "Pasaport numarası için toplam kontrol",
            "strPatronHeaderVersion": "Patron başlık sürümü",
            "strPatternDifferentLinesThickness": "Desen çizgilerinin kalınlığının karşılaştırılması",
            "strPatternIRInvisible": "IR'de görünmez desen",
            "strPatternNotInterrupted": "Kesintisiz desen",
            "strPatternNotShifted": "Desen öğeleri kaydırılmamış",
            "strPatternSameColors": "Desenin aynı renkleri",
            "strPayGrade": "Ücret derecesi",
            "strPayloadCapacity": "Yük kapasitesi",
            "strPermissibleAxleLoad": "İzin verilen aks yükü",
            "strPermitDLClass": "İzin sınıfı",
            "strPermitDateofExpiry": "İzin sona erme tarihi",
            "strPermitDateofIssue": "İzin verme tarihi",
            "strPermitEndorsed": "İzin onay kodu",
            "strPermitIdentifier": "İzin tanımlayıcı",
            "strPermitRestrictionCode": "İzin kısıtlama kodu",
            "strPersonToNotifyAddress": "Bildirilecek kişi: Adres",
            "strPersonToNotifyDateofRecord": "Bildirilecek kişi: Kayıt tarihi",
            "strPersonToNotifyName": "Bildirilecek kişi: Adı",
            "strPersonToNotifyPhone": "Bildirilecek kişi: Telefon",
            "strPersonalNumber": "Kişisel numara",
            "strPersonalNumberCheckDigit": "Kişisel numara için kontrol rakamı",
            "strPersonalNumberChecksum": "Kişisel numara için toplam kontrol",
            "strPersonalSummary": "Kişisel veri özeti",
            "strPersonalizationSN": "Kişiselleştirme seri numarası",
            "strPhone": "Telefon",
            "strPhotoArea": "Fotoğraf alanı",
            "strPhotoColor": "Fotoğraf rengi",
            "strPhotoCorners": "Fotoğraf köşeleri",
            "strPhotoElement": "Fotoğraf öğesi",
            "strPhotoEmbedType": "Fotoğraf gömme türü",
            "strPhotoProcessing": "Fotoğraf işleme...",
            "strPhotoShape": "Fotoğraf şekli",
            "strPhotoSizeCheck": "Boyut kontrolü",
            "strPlaceDocumentInFrame": "Belgeyi çerçeveye yerleştirin",
            "strPlaceOfBirthRUS": "Doğum yeri (Milli)",
            "strPlaceOfBirthStateCode": "Doğum yeri devlet kodu",
            "strPlaceOfExamination": "Muayene yeri",
            "strPlaceOfIssue": "Veriliş yeri",
            "strPlacePhoneOnDoc": "Lütfen telefonu belgenin üzerine yerleştirin",
            "strPlaceofBirth": "Doğum yeri",
            "strPlaceofBirthArea": "Doğum yeri alanı",
            "strPlaceofRegistration": "Kayıt yeri",
            "strPoliceDistrict": "Polis bölgesi",
            "strPortrait": "Portre",
            "strPortraitComparison": "Portrelerin karşılaştırılması",
            "strPortraitOfChild": "Çocuk portresi",
            "strPortraitVSCamera": "Portre vs Kamera görüntüsü",
            "strPortraitVSGhost": "Portre vs Hayalet fotoğrafı",
            "strPortraitVSRFID": "Portre vs RFID çipi portresi",
            "strPowerWeightRatio": "Güç-ağırlık oranı",
            "strPrecinct": "Oy bölgesi",
            "strPrepareCamera": "Kamerayı hazırlama...",
            "strPresentNextPage": "Lütfen bir sonraki sayfayı sağlayın",
            "strPreviousType": "Önceki belge türü/numarası",
            "strProcessingDocument": "Belge işleme...",
            "strProfession": "Meslek",
            "strProfessionalIdNumber": "Mesleki kimlik numarası",
            "strProofOfCitizenship": "Vatandaşlık kanıtı",
            "strPseudoCode": "Sözde kod",
            "strPurposeOfEntry": "Giriş amacı",
            "strRFIDVSCamera": "RFID çipi portresi vs Kamera görüntüsü",
            "strRaceEthnicity": "Irk/etnik köken",
            "strRank": "Sıralama",
            "strReadingRFID": "RFID çip verilerinin okunması",
            "strReadingRFIDDGiOS": "RFID %@ verilerinin okunması",
            "strRecognizedDocumentType": "Belge türü",
            "strReferenceNumber": "Tekil numara",
            "strReferenceNumberCheckDigit": "Tekil numara kontrol rakamı",
            "strReferenceNumberChecksum": "Tekil numara toplam kontrol",
            "strRegCertBodyNumber": "Gövde numarası",
            "strRegCertBodyType": "Gövde tipi",
            "strRegCertCarColor": "Araç rengi",
            "strRegCertCarMark": "Araç markası",
            "strRegCertCarModel": "Araç modeli",
            "strRegCertCarType": "Araç tipi",
            "strRegCertMaxWeight": "Maksimum izin verilen ağırlık",
            "strRegCertRegNumber": "Kayıt numarası",
            "strRegCertRegNumberCheckDigit": "Kayıt numarası kontrol rakamı",
            "strRegCertRegNumberChecksum": "Kayıt numarası toplam kontrol",
            "strRegCertVIN": "Araç tanımlama numarası (VIN)",
            "strRegCertVINCheckDigit": "VIN kontrol rakamı",
            "strRegCertVINChecksum": "VIN toplam kontrol",
            "strRegCertVehicleITSCode": "Araç ITS kodu",
            "strRegCertWeight": "Boş ağırlık",
            "strRelationship": "İlişki",
            "strReligion": "Din",
            "strRemainderTerm": "Sona erme için kalan ay sayısı",
            "strResidentFrom": "Yerli olarak",
            "strResidentUntil": "Yerli olarak",
            "strRetirementNumber": "Emeklilik numarası",
            "strRevisionDate": "Revizyon tarihi",
            "strRoomNumber": "Oda numarası",
            "strSBHIntegrityOptions": "SBH bütünlük seçenekleri",
            "strSBHSecurityOptions": "SBH güvenlik seçenekleri",
            "strSeatNumber": "Koltuk numarası",
            "strSecondSurname": "İkinci soyad",
            "strSection": "Bölüm",
            "strSecurityText": "Güvenlik metni",
            "strSelecteeIndicator": "Seçilen gösterge",
            "strSequenceNumber": "Sıra numarası",
            "strSerialNumber": "Seri numarası",
            "strSettings": "Ayarlar",
            "strSex": "Cinsiyet",
            "strSignature": "İmza",
            "strSkinColor": "Cilt rengi",
            "strSocialSecurityNumber": "Sosyal sigorta numarası",
            "strSpCode": "Özel kod",
            "strSpecialNotes": "Özel notlar",
            "strSponsor": "Sponsor",
            "strSponsorSSN": "Sponsor SSN",
            "strSponsorService": "Sponsor hizmeti",
            "strSponsorStatus": "Sponsor durumu",
            "strStamp": "Mühür",
            "strStampNumber": "Mühür numarası",
            "strStatusDateofExpiry": "Durumun son kullanma tarihi",
            "strSurname": "Soyadı",
            "strSurnameAndGivenNames": "Soyadı ve verilen adlar",
            "strSurnameAndGivenNamesCheckDigit": "Soyadı ve verilen adlar için kontrol basamağı",
            "strSurnameAndGivenNamesChecksum": "Soyadı ve verilen adlar için toplam kontrol",
            "strSurnameAndGivenNamesRUS": "Soyadı ve verilen adlar (Milli)",
            "strSurnameAtBirth": "Doğumda soyadı",
            "strSurnameOfHusbandAfterRegistration": "Kayıttan sonra eşin soyadı",
            "strSurnameOfWifeAfterRegistration": "Kayıttan sonra eşin soyadı",
            "strSurnameofSpose": "Eşin soyadı",
            "strTax": "Vergi",
            "strTaxNumber": "Vergi numarası",
            "strTelexCode": "Telex kodu",
            "strTerritorialValidity": "Bölgesel geçerlilik",
            "strTicketNumber": "Bilet numarası",
            "strTitle": "Unvan",
            "strToAirportCode": "Varış havalimanı kodu",
            "strTorchUnavailable": "Fener mevcut değil",
            "strTrackingNumber": "Takip numarası",
            "strTrailerHitch": "Römork çeki demiri",
            "strTransactionNumber": "İşlem numarası",
            "strTransmissionType": "Şanzıman tipi",
            "strTypeApprovalNumber": "Onay numarası türü",
            "strURL": "URL",
            "strUSCIS": "USCIS",
            "strUV": "UV",
            "strUVFibers": "UV güvenlik lifleri",
            "strUVLuminescence": "UV donuk kağıt kontrolü",
            "strUnableCaptureMedia": "Kamera yapılandırması başarısız",
            "strUniqueCustomerIdentifier": "Benzersiz müşteri tanımlayıcı",
            "strVRCDataObjectEntry": "DG1 veri grubundan araç verileri",
            "strValidityPeriod": "Geçerlilik süresi",
            "strVehicleCategory": "Araç kategorisi",
            "strVeteran": "Gaziler",
            "strVisaClass": "Vize Sınıfı",
            "strVisaID": "Vize Kimliği",
            "strVisaIDCheckDigit": "Vize Kimliği için kontrol basamağı",
            "strVisaIDChecksum": "Vize Kimliği için toplam kontrol",
            "strVisaIDRUS": "Vize Kimliği (Milli)",
            "strVisaNumber": "Vize Numarası",
            "strVisaNumberCheckDigit": "Vize Numarası için kontrol basamağı",
            "strVisaNumberChecksum": "Vize Numarası için toplam kontrol",
            "strVisaSubClass": "Vize Alt Sınıfı",
            "strVisaType": "Vize Türü",
            "strVisaValidFrom": "Vize geçerlilik tarihi",
            "strVisaValidUntil": "Vize bitiş tarihi",
            "strVisaValidUntilCheckDigit": "Vize son kullanma tarihi için kontrol basamağı",
            "strVisaValidUntilChecksum": "Vize son kullanma tarihi için toplam kontrol",
            "strVisibleLight": "Görünür ışık",
            "strVoter": "Oy veren",
            "strVoterKey": "Oy veren anahtarı",
            "strVoucherNumber": "Kupon numarası",
            "strWeight": "Ağırlık",
            "strWeightPound": "Ağırlık (pound)",
            "strYear": "Yıl",
            "strYearsSinceIssue": "Verilme tarihinden bu yana geçen yıllar",
            "streIDPlaceOfBirthCity": "Doğum Yeri: Şehir",
            "streIDPlaceOfBirthCountry": "Doğum Yeri: Ülke",
            "streIDPlaceOfBirthState": "Doğum Yeri: Eyalet",
            "streIDPlaceOfBirthStreet": "Doğum Yeri: Sokak",
            "streIDPlaceOfBirthZipcode": "Doğum Yeri: Posta kodu",
            "streIDResidencePermit1": "İkamet izni 1",
            "streIDResidencePermit2": "İkamet izni 2",
            "strfppLeftIndexFinger": "Sol işaret parmağı",
            "strfppLeftLittleFinger": "Sol serçe parmağı",
            "strfppLeftMiddleFinger": "Sol orta parmağı",
            "strfppLeftRingFinger": "Sol yüzük parmağı",
            "strfppLeftThumb": "Sol baş parmağı",
            "strfppRightIndexFinger": "Sağ işaret parmağı",
            "strfppRightLittleFinger": "Sağ serçe parmağı",
            "strfppRightMiddleFinger": "Sağ orta parmağı",
            "strfppRightRingFinger": "Sağ yüzük parmağı",
            "strfppRightThumb": "Sağ baş parmağı"
            
            
        ]
    }
}
