//
//  File.swift
//
//
//  Created by MOBILE on 20/05/24.
//

import Foundation

class UrduDataValues {
    func getDictionary() -> [String: String] {
        return [
            "RFID_Error_AlreadyDone": "RFID: مطلوبہ آپریشن پہلے ہی ہو چکا ہے",
              "RFID_Error_Busy": "RFID: RFID مصروف ہے",
              "RFID_Error_Failed": "RFID: ناکام",
              "RFID_Error_FileIOError": "RFID فائل: IO ایرر",
              "RFID_Error_InvalidDirectory": "RFID: غلط ڈائریکٹری",
              "RFID_Error_InvalidParameter": "RFID: ExecuteCommand() کال میں غلط پیرامیٹر پایا گیا",
              "RFID_Error_NoChipDetected": "RFID: کوئی چپ نہیں ملی",
              "RFID_Error_NotAvailable": "RFID: دستیاب نہیں",
              "RFID_Error_NotEnoughMemory": "RFID: میموری ختم ہو گئی ہے",
              "RFID_Error_NotInitialized": "RFID: ڈیوائس غیر شروع شدہ ہے",
              "RFID_Error_NotPerformed": "RFID: انجام نہیں دیا گیا",
              "RFID_Error_OldFirmware": "RFID: فریم ویئر کو نئے ورژن کے ساتھ اپ ڈیٹ کرنا ہوگا",
              "RFID_Error_PCSC_CantConnectCard": "PCSC: کارڈ کو کنیکٹ نہیں کیا جا سکتا",
              "RFID_Error_PCSC_CardIsBusy": "PCSC: کارڈ مصروف ہے",
              "RFID_Error_PCSC_CardIsNotConnected": "PCSC: کارڈ کنیکٹ نہیں ہے",
              "RFID_Error_PCSC_ExtLe_Failed": "PCSC: ExtLe ناکام",
              "RFID_Error_PCSC_Failed": "PCSC: ناکام",
              "RFID_Error_PCSC_FailedSCard": "PCSC: سمارٹ کارڈ ناکام",
              "RFID_Error_PCSC_OperationCancelled": "PCSC: آپریشن منسوخ کر دیا گیا",
              "RFID_Error_PCSC_ReaderNotAvailable": "PCSC: ریڈر دستیاب نہیں ہے",
              "RFID_Error_Session_AccessControl_AA_Failed": "RFID: AA ناکام",
              "RFID_Error_Session_AccessControl_CA_Failed": "RFID: CA ناکام",
              "RFID_Error_Session_AccessControl_IncorrectOptionCA": "RFID: غلط آپشن CA",
              "RFID_Error_Session_AccessControl_RI_Failed": "RFID: RI ناکام",
              "RFID_Error_Session_AccessControl_RequiresCA": "RFID: CA کی ضرورت ہے",
              "RFID_Error_Session_AccessControl_RequiresCAKeys": "RFID: CA کیز کی ضرورت ہے",
              "RFID_Error_Session_AccessControl_RequiresPACE": "RFID: PACE کی ضرورت ہے",
              "RFID_Error_Session_AccessControl_RequiresSM": "RFID: SM کی ضرورت ہے",
              "RFID_Error_Session_AccessControl_RequiresTA": "RFID: TA کی ضرورت ہے",
              "RFID_Error_Session_AccessControl_TA_Failed": "RFID: TA ناکام",
              "RFID_Error_Session_AccessControl_UnknownType": "RFID: رسائی کنٹرول نامعلوم قسم",
              "RFID_Error_Session_AccessKey_IncorrectData": "RFID: رسائی کلید غلط ڈیٹا",
              "RFID_Error_Session_AccessKey_IncorrectSMType": "RFID: رسائی کلید غلط SM قسم",
              "RFID_Error_Session_AccessKey_NotSet": "RFID: رسائی کلید سیٹ نہیں",
              "RFID_Error_Session_AccessKey_Restricted": "RFID: رسائی کلید محدود",
              "RFID_Error_Session_AccessKey_UnknownType": "RFID: رسائی کلید نامعلوم قسم",
              "RFID_Error_Session_AccessKey_UnsupportedSMType": "RFID: رسائی کلید غیر معاون SM قسم",
              "RFID_Error_Session_File_AccessDenied": "RFID فائل: رسائی مسترد",
              "RFID_Error_Session_File_CantReadData": "RFID فائل: ڈیٹا نہیں پڑھ سکتا",
              "RFID_Error_Session_File_CantUseData": "RFID فائل: ڈیٹا استعمال نہیں کر سکتا",
              "RFID_Error_Session_File_Contents_UnexpectedData": "RFID فائل: مواد غیر متوقع ڈیٹا",
              "RFID_Error_Session_File_IncorrectData": "RFID فائل: غلط ڈیٹا",
              "RFID_Error_Session_File_NotEnoughData": "RFID فائل: ڈیٹا کافی نہیں",
              "RFID_Error_Session_File_UnexpectedData": "RFID فائل: غیر متوقع ڈیٹا",
              "RFID_Error_Session_File_WrongTag": "RFID فائل: غلط ٹیگ",
              "RFID_Error_Session_IncorrectData": "RFID: غلط ڈیٹا",
              "RFID_Error_Session_InvalidAuxData_CommunityID": "RFID: غلط معاون ڈیٹا کمیونٹی آئی ڈی",
              "RFID_Error_Session_InvalidAuxData_DateOfBirth": "RFID: غلط معاون ڈیٹا تاریخ پیدائش",
              "RFID_Error_Session_InvalidAuxData_DateOfExpiry": "RFID: غلط معاون ڈیٹا تاریخ ختمی",
              "RFID_Error_Session_IsClosed": "RFID: سیشن بند ہے",
              "RFID_Error_Session_PA_HashCheckFailed": "RFID: ہیش چیک ناکام",
              "RFID_Error_Session_PA_SignatureCheckFailed": "RFID: SO دستخط چیک ناکام",
              "RFID_Error_Session_ProcedureType_NotSet": "RFID: پروسیجر قسم سیٹ نہیں",
              "RFID_Error_Session_ProcedureType_Unknown": "RFID: پروسیجر قسم نامعلوم",
              "RFID_Error_Session_ProcedureType_Unsupported": "RFID: پروسیجر قسم غیر معاون",
              "RFID_Error_Session_PwdManagement_NotAuthorized": "RFID: پاسورڈ مینجمنٹ مجاز نہیں",
              "RFID_Error_Session_TerminalType_BadCertificate": "RFID: ٹرمینل قسم خراب سرٹیفکیٹ",
              "RFID_Error_Session_TerminalType_NotSet": "RFID: ٹرمینل قسم سیٹ نہیں",
              "RFID_Error_Session_TerminalType_Unknown": "RFID: ٹرمینل قسم نامعلوم",
              "RFID_Error_Session_Terminal_UnsupportedOperation": "RFID: ٹرمینل غیر معاون آپریشن",
              "RFID_Error_Session_eSign_PIN_NotSet": "RFID: ای سائن پن سیٹ نہیں",
              "RFID_Error_Session_eSign_PIN_NotVerified": "RFID: ای سائن پن تصدیق نہیں ہوئی",
              "RFID_Error_Session_eSign_RequiresAppSelection": "RFID: ای سائن ایپلیکیشن کے انتخاب کی ضرورت ہے",
              "RFID_Error_UnknownCommand": "RFID: نامعلوم کمانڈ",
              "RFID_LAYER6_APP_SELECTION_FAILURE": "LAYER6: ISO7816_A_03 \"ایپلیکیشن کے انتخاب میں ناکامی\"",
              "RFID_LAYER6_EXT_AUTH_FAILURE": "LAYER6: APDU_INS_EXTERNAL_AUTHENTICATE (بیرونی تصدیق) ناکامی",
              "RFID_LAYER6_FILE_EOF1": "LAYER6: EOF سے آگے پڑھنا / غیر متوقع EOF",
              "RFID_LAYER6_FILE_EOF2": "LAYER6: EOF سے آگے پڑھنا / غیر متوقع EOF",
              "RFID_LAYER6_FILE_NOT_FOUND": "LAYER6: فائل کے انتخاب میں ناکامی / فائل نہیں ملی",
              "RFID_LAYER6_GENERAL_AUTH_FAILURE": "LAYER6: عمومی تصدیق میں ناکامی",
              "RFID_LAYER6_GET_CHALLENGE_FAILURE": "LAYER6: چیلنج حاصل کرنے میں ناکامی",
              "RFID_LAYER6_INCORRECT_PARAMS": "LAYER6: غلط پیرامیٹرز",
              "RFID_LAYER6_INT_AUTH_FAILURE": "LAYER6: APDU_INS_INTERNAL_AUTHENTICATE ناکامی",
              "RFID_LAYER6_MSE_SET_AT_FAILURE": "LAYER6: MSE:Set AT ناکامی",
              "RFID_LAYER6_MSE_SET_DST_FAILURE": "LAYER6: MSE:Set DST ناکامی",
              "RFID_LAYER6_MSE_SET_KAT_FAILURE": "LAYER6: MSE:Set KAT ناکامی",
              "RFID_LAYER6_MUTUAL_AUTH_ENC_FAIL": "LAYER6: ISO7816_B_02 \"باہمی تصدیق خفیہ کاری ناکامی\"",
              "RFID_LAYER6_MUTUAL_AUTH_FAILURE": "LAYER6: ISO7816_B_03 \"باہمی تصدیق ناکامی\"",
              "RFID_LAYER6_MUTUAL_AUTH_MAC_FAIL": "LAYER6: ISO7816_B_01 \"باہمی تصدیق MAC ناکامی\"",
              "RFID_LAYER6_NON_TLV_RESPONSE_DATA": "LAYER6: TLV جوابی ڈیٹا نہیں",
              "RFID_LAYER6_NO_REFERENCE_DATA": "LAYER6: کوئی حوالہ ڈیٹا نہیں",
              "RFID_LAYER6_PSO_CERTIFICATE_FAILURE": "LAYER6: PSO سرٹیفکیٹ ناکامی",
              "RFID_LAYER6_PWD_BLOCKED": "LAYER6: پاسورڈ بلاک",
              "RFID_LAYER6_PWD_BLOCKED_2": "LAYER6: پاسورڈ بلاک 2",
              "RFID_LAYER6_PWD_DEACTIVATED": "LAYER6: پاسورڈ غیر فعال",
              "RFID_LAYER6_PWD_DEACTIVATED_2": "LAYER6: پاسورڈ غیر فعال 2",
              "RFID_LAYER6_PWD_FAILED": "LAYER6: پاسورڈ ناکام",
              "RFID_LAYER6_PWD_SUSPENDED": "LAYER6: پاسورڈ معطل",
            "RFID_LAYER6_PWD_SUSPENDED_2" : "LAYER6: پاسورڈ معطل 2",
              "RFID_LAYER6_SECURITY_MANAGER" : "LAYER6: محفوظ میسجنگ کو فعال نہیں کیا گیا",
              "RFID_LAYER6_SM_DO87_INCORRECT" : "LAYER6: SM ناکامی – غلط کرپٹوگرام",
              "RFID_LAYER6_SM_DO87_MISSING" : "LAYER6: SM ناکامی – کرپٹوگرام غائب",
              "RFID_LAYER6_SM_DO8E_MISSING" : "LAYER6: SM ناکامی – MAC غائب",
              "RFID_LAYER6_SM_DO99_MISSING" : "LAYER6: SM ناکامی – محفوظ اسٹیٹس بائٹس غائب",
              "RFID_LAYER6_SM_MAC_INCORRECT" : "LAYER6: SM ناکامی – غلط MAC",
              "RFID_LAYER6_WRONG_RND_ICC_LENGTH" : "LAYER6: غلط ڈیٹا لمبائی (APDU_INS_GET_CHALLENGE)",
              "RSDT_RFID_READING_FINISHED" : "RFID ڈیٹا پڑھنا مکمل ہو گیا ہے",
              "TCT_Unknown" : "نامعلوم",
              "chd_BackgroundComparisonError" : "دونوں صفحات کی روشنی مختلف ہے",
              "chd_BadAreaInAxial" : "ریٹرو ریفلیکٹو تحفظ ناکام",
              "chd_BarcodeDataFormatError" : "بارکوڈ فارمیٹ ایرر",
              "chd_BarcodeReadedWithErrors" : "بارکوڈ کو غلطیوں کے ساتھ پڑھا گیا",
              "chd_BarcodeSizeParamsError" : "بارکوڈ پیرامیٹر ایرر",
              "chd_DocumentIsCancelling" : "دستاویز منسوخ ہو رہی ہے",
              "chd_ElementShouldBeColored" : "عنصر کو رنگین ہونا چاہیے",
              "chd_ElementShouldBeGrayscale" : "عنصر کو سرمئی ہونا چاہیے",
              "chd_ExceptionInModule" : "انٹرسیپٹڈ استثنا",
              "chd_FalseIPIParameters" : "غلط IPI پیرامیٹرز",
              "chd_FalseLuminiscenceError" : "اضافی روشنی والے اشیاء کی موجودگی",
              "chd_FalseLuminiscenceInBlank" : "یو وی میں جعلی روشنی",
              "chd_FalseLuminiscenceInMRZ" : "MRZ میں زیادہ روشنی",
              "chd_FibersNotFound" : "فائبرز نہیں ملے",
              "chd_FieldPosCorrector_Highlight_IR" : "IR میں زیادہ روشنی",
              "chd_FieldsComparisonLogicError" : "فیلڈز کا موازنہ کرتے وقت منطقی خرابی",
              "chd_FixedPatternError" : "مخصوص شے کا عدم اتفاق",
              "chd_HologramElementAbsent" : "ہولوگرام غائب ہے",
              "chd_HologramElementPresent" : "ہولوگرام ملا",
              "chd_Hologram_Side_Top_Images_Absent" : "کوئی سائیڈ یا ٹاپ تصاویر نہیں",
              "chd_IncorrectBackgroundLight" : "غلط پس منظر کی روشنی",
              "chd_IncorrectTextColor" : "غلط متن کا رنگ",
              "chd_InternalError" : "داخلی ڈیٹا پروسیسنگ کی خرابی",
              "chd_InvalidChecksum" : "غلط چیکسم",
              "chd_InvalidFieldFormat" : "فیلڈ کا فارمیٹ دستاویز کی وضاحت کے مطابق نہیں ہے",
              "chd_InvalidInputData" : "غلط ان پٹ ڈیٹا",
              "chd_InvisibleElementPresent" : "شے کو نظر نہیں آنا چاہیے",
              "chd_LogicError" : "منطقی ڈیٹا خرابی",
              "chd_LowContrastInIRLight" : "IR روشنی میں غلط شے کا کانٹراسٹ",
              "chd_MobileImages_LowLightConditions" : "تصاویر لینے کے لیے نامناسب روشنی کے حالات",
              "chd_MobileImages_WhileUVNoDifference" : "مختلف روشنی کی اسکیموں میں تصاویر میں کم فرق",
              "chd_NecessaryImageNotFound" : "اس چیک کے لئے مطلوبہ تصویر غائب ہے",
              "chd_NotAllBarcodesRead" : "اس دستاویز میں مزید بارکوڈز ہونے چاہئیں",
              "chd_OVI_BadColor_Front" : "سفید روشنی میں OVI شے کا رنگ عدم مطابقت",
              "chd_OVI_BadColor_Percent" : "OVI عناصر کے درمیان کم مطابقت کی فیصد",
              "chd_OVI_BadColor_Side" : "محوری روشنی میں OVI شے کا رنگ عدم مطابقت",
              "chd_OVI_ColorInvariable" : "OVI رنگ ناقابل تغیر",
              "chd_OVI_IR_Invisible" : "OVI شے کا کانٹراسٹ عدم مطابقت",
              "chd_OVI_InsufficientArea" : "OVI شے کا ناکافی علاقہ",
              "chd_OVI_Wide_Color_Spread" : "OVI شے کے رنگ کی حدود عدم مطابقت",
              "chd_Pass" : "کوئی غلطی نہیں",
              "chd_PhotoFalseLuminiscence" : "تصویر کے علاقے میں جعلی روشنی",
              "chd_PhotoPattern_DifferentColors" : "تصویر پر پیٹرن کے رنگ اور خالی جگہ کے رنگ مختلف ہیں",
              "chd_PhotoPattern_DifferentLinesThickness" : "پیٹرن لائنوں کی مختلف موٹائی",
              "chd_PhotoPattern_IR_Visible" : "IR میں سیکیورٹی پیٹرن نظر آتا ہے",
              "chd_PhotoPattern_Interrupted" : "تصویر اور خالی جگہ کے درمیان پیٹرن میں وقفہ ہے",
              "chd_PhotoPattern_InvalidColor" : "سیکیورٹی پیٹرن کا رنگ غلط ہے",
              "chd_PhotoPattern_Not_Intersect" : "تصویر کے کنارے پیٹرن کے ساتھ متصل نہیں ہیں",
              "chd_PhotoPattern_PatternNotFound" : "تصویر کے علاقے میں پیٹرن نہیں ملا",
              "chd_PhotoPattern_Shifted" : "تصویر پر پیٹرن خالی جگہ کے پیٹرن کے مقابلے میں منتقل ہے",
              "chd_PhotoPattern_Shifted_Vert" : "پیٹرن لائنیں ایک دوسرے کے مقابلے میں عمودی طور پر منتقل ہیں",
              "chd_PhotoSidesNotFound" : "مطلوبہ تصویر کی سرحد نہیں ملی",
              "chd_PhotoSize_Is_Wrong" : "تصویر کا سائز غلط ہے",
              "chd_Photo_Corners_Is_Wrong" : "تصویر کے کونے ضروریات کے مطابق نہیں ہیں",
              "chd_Photo_IsNot_Rectangle" : "تصویر کی شکل مستطیل نہیں ہے",
              "chd_PortraitComparison_NoLivePhoto" : "کیمرے کی تصویر نہیں ہے",
              "chd_PortraitComparison_NoPortraitDetected" : "تصویر میں کوئی چہرہ نہیں ملا",
              "chd_PortraitComparison_NoServiceLicense" : "سروس کے لئے کوئی لائسنس نہیں ہے",
              "chd_PortraitComparison_NoServiceReply" : "سروس کا جواب نہیں آیا",
              "chd_PortraitComparison_NotEnoughImages" : "تصاویر ناکافی ہیں",
              "chd_PortraitComparison_PortraitsDiffer" : "تصاویر مطابقت نہیں رکھتیں",
              "chd_PortraitComparison_ServiceError" : "سروس کی خرابی",
              "chd_SourcesComparisonError" : "مختلف ذرائع سے ڈیٹا کا عدم اتفاق",
              "chd_SpecksInUV" : "UV روشنی میں تصویر میں زیادہ روشنی یا چمک",
              "chd_SyntaxError" : "ڈیٹا کی نحو کی خرابی",
              "chd_TextColorShouldBeBlue" : "متن کا رنگ نیلا ہونا چاہیے",
              "chd_TextColorShouldBeGreen" : "متن کا رنگ سبز ہونا چاہیے",
              "chd_TextColorShouldBeRed" : "متن کا رنگ سرخ ہونا چاہیے",
              "chd_TextShouldBeBlack" : "متن کا رنگ سیاہ ہونا چاہیے",
              "chd_TooLowResolution" : "فائبرز کا پتہ لگانے کے لئے بہت کم ریزولوشن",
              "chd_TooManyObjects" : "بہت زیادہ اشیاء",
              "chd_TooMuchShift" : "منتقلی کی قیمت مجاز قیمت سے زیادہ ہے",
              "chd_TrueLuminiscenceError" : "روشنی والے اشیاء کا عدم اتفاق",
              "chd_UVDullPaperError" : "UV ڈل پیپر چیک کی خرابی",
              "chd_UVDullPaper_Blank" : "خالی جگہ میں UV ڈل پیپر چیک",
              "chd_UVDullPaper_MRZ" : "MRZ علاقے میں UV ڈل پیپر چیک",
              "chd_UVDullPaper_Photo" : "تصویر کے علاقے میں UV ڈل پیپر چیک",
              "chd_UncertainVerification" : "قابل اعتماد فیصلہ نہیں کیا جا سکتا",
              "chd_Unknown" : "نامعلوم انکار",
              "chd_VisibleElementAbsent" : "IR میں کوئی نظر آنے والی شے نہیں",
              "strAGY" : "AGY",
              "strAKADateofBirth" : "AKA تاریخ پیدائش",
              "strAKAGivenNames" : "AKA دیا ہوا نام",
              "strAKANamePrefix" : "AKA نام کا سابقہ",
              "strAKANameSuffix" : "AKA نام کا لاحقہ",
              "strAKASocialSecurityNumber" : "AKA سوشل انشورنس نمبر",
              "strAKASurname" : "AKA خاندانی نام",
              "strAKASurnameAndGivenNames" : "AKA مکمل نام",
              "strALTCode" : "ALT کوڈ",
              "strAcademicTitle" : "اکیڈمک عنوان",
            "strAccessibilityCameraButton" : "تصویر کھینچیں اور پروسیسنگ شروع کریں",
            "strAccessibilityCloseButton" : "بند کریں",
            "strAccessibilityTorchButton" : "ٹارچ",
            "strAccompaniedby" : "کے ساتھ",
            "strAddress" : "پتہ",
            "strAddressArea" : "علاقہ",
            "strAddressBuilding" : "یونٹ",
            "strAddressCity" : "شہر",
            "strAddressCountry" : "ملک",
            "strAddressFlat" : "فلیٹ",
            "strAddressHouse" : "عمارت",
            "strAddressJurisdictionCode" : "دائرہ اختیار کا کوڈ",
            "strAddressLocation" : "مقام",
            "strAddressMunicipality" : "میونسپلٹی",
            "strAddressPostalCode" : "ڈاک کا کوڈ",
            "strAddressState" : "ریاست",
            "strAddressStreet" : "گلی",
            "strAdministrativeNumber" : "انتظامی نمبر",
            "strAge" : "عمر",
            "strAgeAtIssue" : "اجرا کے وقت عمر",
            "strAirlineDesignatorofboardingpassissuer" : "بورڈنگ پاس جاری کرنے والے کا ایئرلائن ڈیزائنٹر",
            "strAirlineName" : "ایئرلائن کا نام",
            "strAirlineNameFrequentFlyer" : "فریکوئنٹ فلائرز کے لیے ایئرلائن لائلٹی پروگرام",
            "strAirlineNumericCode" : "ایئرلائن کا عددی کوڈ",
            "strAirportFrom" : "روانگی کا ہوائی اڈہ",
            "strAirportTo" : "آمد کا ہوائی اڈہ",
            "strAllergies" : "الرجیز",
            "strApplicationDoNotHavePermission" : "ایپلیکیشن کے پاس کیمرہ استعمال کرنے کی اجازت نہیں ہے، براہ کرم پرائیویسی سیٹنگز تبدیل کریں",
            "strApplicationNumber" : "درخواست نمبر",
            "strArtisticName" : "قلمی نام",
            "strAuditInformation" : "تصدیق کے لیے نمبر",
            "strAuthentification" : "مستندیت کی تصدیق",
            "strAuthority" : "جاری کرنے والی اتھارٹی",
            "strAuthorityCode" : "جاری کرنے والی اتھارٹی کا کوڈ",
            "strAuthorityRUS" : "جاری کرنے والی اتھارٹی (قومی)",
            "strAuthorizationNumber" : "اجازت نمبر",
            "strAxialProtection" : "ریٹرو ریفلیکٹو تحفظ",
            "strBDBType" : "BDB قسم",
            "strBankCardNumber" : "بینک کارڈ نمبر",
            "strBankCardValidThru" : "بینک کارڈ کی مدت",
            "strBanknoteNumber" : "بینک نوٹ نمبر",
            "strBarcode" : "بارکوڈ",
            "strBarcodeFormatCheck" : "بارکوڈ فارمیٹ چیک",
            "strBenefitsNumber" : "فائدہ نمبر",
            "strBinaryCode" : "بائنری کوڈ",
            "strBiometricFormatOwner" : "بائیومیٹرک فارمیٹ کا مالک",
            "strBiometricFormatType" : "بائیومیٹرک فارمیٹ کی قسم",
            "strBiometricProductID" : "بائیومیٹرک پروڈکٹ آئی ڈی",
            "strBiometricSubtype" : "بائیومیٹرک ذیلی قسم",
            "strBiometricType" : "بائیومیٹرک قسم",
            "strBlankElement" : "خالی عنصر",
            "strBloodGroup" : "خون کا گروپ",
            "strBookletNumber" : "بکلیٹ نمبر",
            "strCCWUntil" : "CCW تک",
            "strCDLClass" : "CDL کلاس",
            "strCSCCode" : "CSC کوڈ",
            "strCVV" : "CVV/CVC",
            "strCaliber" : "کیلبر",
            "strCameraUnavailable" : "کیمرہ دستیاب نہیں",
            "strCardAccessNumber" : "کارڈ رسائی نمبر",
            "strCategory" : "زمرہ",
            "strCenturyDateOfBirth" : "صدی کی پیدائش",
            "strChassisNumber" : "چیسس نمبر",
            "strCheckInSequenceNumber" : "چیک ان سلسلہ نمبر",
            "strChildren" : "بچے",
            "strCitizenshipOfFirstPerson" : "پہلے شخص کی شہریت",
            "strCitizenshipOfSecondPerson" : "دوسرے شخص کی شہریت",
            "strCivilStatus" : "شہری حیثیت",
            "strColorDynamic" : "رنگ کی حرکیات",
            "strCommercialVehicleCodes" : "کمرشل گاڑی کا کوڈ",
            "strCompanyName" : "کمپنی کا نام",
            "strCompartmentCode" : "کمپارٹمنٹ کوڈ",
            "strComplexion" : "رنگت",
            "strComplianceType" : "مطابقت کی قسم",
            "strConditions" : "شرائط",
            "strConfiguration" : "تشکیل",
            "strControlNo" : "کنٹرول نمبر",
            "strCopy" : "نقل",
            "strCourtCode" : "عدالتی کوڈ",
            "strCty" : "کاؤنٹی",
            "strCurrentDate" : "موجودہ تاریخ",
            "strCustodyInfo" : "تحویل کی معلومات",
            "strDFTAppDirectory" : "ایپ ڈائریکٹری",
            "strDFTCertificate" : "سرٹیفکیٹ",
            "strDG1" : "مشین پڑھنے والا زون (DG1)",
            "strDG10" : "تعریف نہیں (DG10)",
            "strDG11" : "اضافی ذاتی تفصیل (DG11)",
            "strDG12" : "اضافی دستاویز کی تفصیلات (DG12)",
            "strDG13" : "اختیاری تفصیل (DG13)",
            "strDG14" : "EAC معلومات (DG14)",
            "strDG15" : "فعال تصدیق کی معلومات (DG15)",
            "strDG16" : "اطلاع کے لیے شخص (DG16)",
            "strDG17" : "DG17",
            "strDG18" : "DG18",
            "strDG19" : "DG19",
            "strDG2" : "بائیومیٹری - چہرے کے ڈیٹا (DG2)",
            "strDG20" : "DG20",
            "strDG3" : "بائیومیٹری - فنگر پرنٹ (DG3)",
            "strDG4" : "بائیومیٹری - آئرس ڈیٹا (DG4)",
            "strDG5" : "تصویر (DG5)",
            "strDG6": "متعین نہیں (DG6)",
            "strDG7": "دستخط / عام نشان کی تصویر (DG7)",
            "strDG8": "متعین نہیں (DG8)",
            "strDG9": "متعین نہیں (DG9)",
            "strDLCDLRestrictionCode": "سی ڈی ایل پابندی کوڈ",
            "strDLClass": "ڈی ایل زمرہ",
            "strDLClassCodeA1From": "ڈی ایل زمرہ A1 سے جائز",
            "strDLClassCodeA1Notes": "ڈی ایل زمرہ A1 کوڈ",
            "strDLClassCodeA1To": "ڈی ایل زمرہ A1 تک جائز",
            "strDLClassCodeA2From": "ڈی ایل زمرہ A2 سے جائز",
            "strDLClassCodeA2Notes": "ڈی ایل زمرہ A2 کوڈ",
            "strDLClassCodeA2To": "ڈی ایل زمرہ A2 تک جائز",
            "strDLClassCodeA3From": "ڈی ایل زمرہ A3 سے جائز",
            "strDLClassCodeA3Notes": "ڈی ایل زمرہ A3 کوڈ",
            "strDLClassCodeA3To": "ڈی ایل زمرہ A3 تک جائز",
            "strDLClassCodeAFrom": "ڈی ایل زمرہ A سے جائز",
            "strDLClassCodeAMFrom": "ڈی ایل زمرہ AM سے جائز",
            "strDLClassCodeAMNotes": "ڈی ایل زمرہ AM کوڈ",
            "strDLClassCodeAMTo": "ڈی ایل زمرہ AM تک جائز",
            "strDLClassCodeANotes": "ڈی ایل زمرہ A کوڈ",
            "strDLClassCodeATo": "ڈی ایل زمرہ A تک جائز",
            "strDLClassCodeB1From": "ڈی ایل زمرہ B1 سے جائز",
            "strDLClassCodeB1Notes": "ڈی ایل زمرہ B1 کوڈ",
            "strDLClassCodeB1To": "ڈی ایل زمرہ B1 تک جائز",
            "strDLClassCodeB2EFrom": "ڈی ایل زمرہ B2E سے جائز",
            "strDLClassCodeB2ENotes": "ڈی ایل زمرہ B2E کوڈ",
            "strDLClassCodeB2ETo": "ڈی ایل زمرہ B2E تک جائز",
            "strDLClassCodeB2From": "ڈی ایل زمرہ B2 سے جائز",
            "strDLClassCodeB2Notes": "ڈی ایل زمرہ B2 کوڈ",
            "strDLClassCodeB2To": "ڈی ایل زمرہ B2 تک جائز",
            "strDLClassCodeBEFrom": "ڈی ایل زمرہ BE سے جائز",
            "strDLClassCodeBENotes": "ڈی ایل زمرہ BE کوڈ",
            "strDLClassCodeBETo": "ڈی ایل زمرہ BE تک جائز",
            "strDLClassCodeBFrom": "ڈی ایل زمرہ B سے جائز",
            "strDLClassCodeBNotes": "ڈی ایل زمرہ B کوڈ",
            "strDLClassCodeBTPFrom": "ڈی ایل زمرہ BTP سے جائز",
            "strDLClassCodeBTPNotes": "ڈی ایل زمرہ BTP کوڈ",
            "strDLClassCodeBTPTo": "ڈی ایل زمرہ BTP تک جائز",
            "strDLClassCodeBTo": "ڈی ایل زمرہ B تک جائز",
            "strDLClassCodeC1EFrom": "ڈی ایل زمرہ C1E سے جائز",
            "strDLClassCodeC1ENotes": "ڈی ایل زمرہ C1E کوڈ",
            "strDLClassCodeC1ETo": "ڈی ایل زمرہ C1E تک جائز",
            "strDLClassCodeC1From": "ڈی ایل زمرہ C1 سے جائز",
            "strDLClassCodeC1Notes": "ڈی ایل زمرہ C1 کوڈ",
            "strDLClassCodeC1To": "ڈی ایل زمرہ C1 تک جائز",
            "strDLClassCodeC2From": "ڈی ایل زمرہ C2 سے جائز",
            "strDLClassCodeC2Notes": "ڈی ایل زمرہ C2 کوڈ",
            "strDLClassCodeC2To": "ڈی ایل زمرہ C2 تک جائز",
            "strDLClassCodeC3From": "ڈی ایل زمرہ C3 سے جائز",
            "strDLClassCodeC3Notes": "ڈی ایل زمرہ C3 کوڈ",
            "strDLClassCodeC3To": "ڈی ایل زمرہ C3 تک جائز",
            "strDLClassCodeCAFrom": "ڈی ایل زمرہ CA سے جائز",
            "strDLClassCodeCANotes": "ڈی ایل زمرہ CA کوڈ",
            "strDLClassCodeCATo": "ڈی ایل زمرہ CA تک جائز",
            "strDLClassCodeCEFrom": "ڈی ایل زمرہ CE سے جائز",
            "strDLClassCodeCENotes": "ڈی ایل زمرہ CE کوڈ",
            "strDLClassCodeCETo": "ڈی ایل زمرہ CE تک جائز",
            "strDLClassCodeCFrom": "ڈی ایل زمرہ C سے جائز",
            "strDLClassCodeCNotes": "ڈی ایل زمرہ C کوڈ",
            "strDLClassCodeCTo": "ڈی ایل زمرہ C تک جائز",
            "strDLClassCodeD1EFrom": "ڈی ایل زمرہ D1E سے جائز",
            "strDLClassCodeD1ENotes": "ڈی ایل زمرہ D1E کوڈ",
            "strDLClassCodeD1ETo": "ڈی ایل زمرہ D1E تک جائز",
            "strDLClassCodeD1From": "ڈی ایل زمرہ D1 سے جائز",
            "strDLClassCodeD1Notes": "ڈی ایل زمرہ D1 کوڈ",
            "strDLClassCodeD1To": "ڈی ایل زمرہ D1 تک جائز",
            "strDLClassCodeD2From": "ڈی ایل زمرہ D2 سے جائز",
            "strDLClassCodeD2Notes": "ڈی ایل زمرہ D2 کوڈ",
            "strDLClassCodeD2To": "ڈی ایل زمرہ D2 تک جائز",
            "strDLClassCodeDEFrom": "ڈی ایل زمرہ DE سے جائز",
            "strDLClassCodeDENotes": "ڈی ایل زمرہ DE کوڈ",
            "strDLClassCodeDETo": "ڈی ایل زمرہ DE تک جائز",
            "strDLClassCodeDFrom": "ڈی ایل زمرہ D سے جائز",
            "strDLClassCodeDNotes": "ڈی ایل زمرہ D کوڈ",
            "strDLClassCodeDTo": "ڈی ایل زمرہ D تک جائز",
            "strDLClassCodeEFrom": "ڈی ایل زمرہ E سے جائز",
            "strDLClassCodeENotes": "ڈی ایل زمرہ E کوڈ",
            "strDLClassCodeETo": "ڈی ایل زمرہ E تک جائز",
            "strDLClassCodeFA1From": "ڈی ایل زمرہ FA1 سے جائز",
            "strDLClassCodeFA1Notes": "ڈی ایل زمرہ FA1 کوڈ",
            "strDLClassCodeFA1To": "ڈی ایل زمرہ FA1 تک جائز",
            "strDLClassCodeFAFrom": "ڈی ایل زمرہ FA سے جائز",
            "strDLClassCodeFANotes": "ڈی ایل زمرہ FA کوڈ",
            "strDLClassCodeFATo": "ڈی ایل زمرہ FA تک جائز",
            "strDLClassCodeFBFrom": "ڈی ایل زمرہ FB سے جائز",
            "strDLClassCodeFBNotes": "ڈی ایل زمرہ FB کوڈ",
            "strDLClassCodeFBTo": "ڈی ایل زمرہ FB تک جائز",
            "strDLClassCodeFFrom": "ڈی ایل زمرہ F سے جائز",
            "strDLClassCodeFNotes": "ڈی ایل زمرہ F کوڈ",
            "strDLClassCodeFTo": "ڈی ایل زمرہ F تک جائز",
            "strDLClassCodeG1From": "ڈی ایل زمرہ G1 سے جائز",
            "strDLClassCodeG1Notes": "ڈی ایل زمرہ G1 کوڈ",
            "strDLClassCodeG1To": "ڈی ایل زمرہ G1 تک جائز",
            "strDLClassCodeGFrom": "ڈی ایل زمرہ G سے جائز",
            "strDLClassCodeGNotes": "ڈی ایل زمرہ G کوڈ",
            "strDLClassCodeGTo": "ڈی ایل زمرہ G تک جائز",
            "strDLClassCodeHCFrom": "ڈی ایل زمرہ HC سے جائز",
            "strDLClassCodeHCNotes": "ڈی ایل زمرہ HC کوڈ",
            "strDLClassCodeHCTo": "ڈی ایل زمرہ HC تک جائز",
            "strDLClassCodeHFrom": "ڈی ایل زمرہ H سے جائز",
            "strDLClassCodeHNotes": "ڈی ایل زمرہ H کوڈ",
            "strDLClassCodeHRFrom": "ڈی ایل زمرہ HR سے جائز",
            "strDLClassCodeHRNotes": "ڈی ایل قسم HR کوڈز",
               "strDLClassCodeHRTo": "ڈی ایل قسم HR معتبر تک",
               "strDLClassCodeHTo": "ڈی ایل قسم H معتبر تک",
               "strDLClassCodeIFrom": "ڈی ایل قسم I معتبر سے",
               "strDLClassCodeINotes": "ڈی ایل قسم I کوڈز",
               "strDLClassCodeITo": "ڈی ایل قسم I معتبر تک",
               "strDLClassCodeJFrom": "ڈی ایل قسم J معتبر سے",
               "strDLClassCodeJNotes": "ڈی ایل قسم J کوڈز",
               "strDLClassCodeJTo": "ڈی ایل قسم J معتبر تک",
               "strDLClassCodeKFrom": "ڈی ایل قسم K معتبر سے",
               "strDLClassCodeKNotes": "ڈی ایل قسم K کوڈز",
               "strDLClassCodeKTo": "ڈی ایل قسم K معتبر تک",
               "strDLClassCodeLCFrom": "ڈی ایل قسم LC معتبر سے",
               "strDLClassCodeLCNotes": "ڈی ایل قسم LC کوڈز",
               "strDLClassCodeLCTo": "ڈی ایل قسم LC معتبر تک",
               "strDLClassCodeLFrom": "ڈی ایل قسم L معتبر سے",
               "strDLClassCodeLKFrom": "ڈی ایل قسم LK معتبر سے",
               "strDLClassCodeLKNotes": "ڈی ایل قسم LK کوڈز",
               "strDLClassCodeLKTo": "ڈی ایل قسم LK معتبر تک",
               "strDLClassCodeLNotes": "ڈی ایل قسم L کوڈز",
               "strDLClassCodeLRFrom": "ڈی ایل قسم LR معتبر سے",
               "strDLClassCodeLRNotes": "ڈی ایل قسم LR کوڈز",
               "strDLClassCodeLRTo": "ڈی ایل قسم LR معتبر تک",
               "strDLClassCodeLTo": "ڈی ایل قسم L معتبر تک",
               "strDLClassCodeMCFrom": "ڈی ایل قسم MC معتبر سے",
               "strDLClassCodeMCNotes": "ڈی ایل قسم MC کوڈز",
               "strDLClassCodeMCTo": "ڈی ایل قسم MC معتبر تک",
               "strDLClassCodeMFrom": "ڈی ایل قسم M معتبر سے",
               "strDLClassCodeMNotes": "ڈی ایل قسم M کوڈز",
               "strDLClassCodeMRFrom": "ڈی ایل قسم MR معتبر سے",
               "strDLClassCodeMRNotes": "ڈی ایل قسم MR کوڈز",
               "strDLClassCodeMRTo": "ڈی ایل قسم MR معتبر تک",
               "strDLClassCodeMTo": "ڈی ایل قسم M معتبر تک",
               "strDLClassCodeNFrom": "ڈی ایل قسم N معتبر سے",
               "strDLClassCodeNNotes": "ڈی ایل قسم N کوڈز",
               "strDLClassCodeNTo": "ڈی ایل قسم N معتبر تک",
               "strDLClassCodeREFrom": "ڈی ایل قسم RE معتبر سے",
               "strDLClassCodeRENotes": "ڈی ایل قسم RE کوڈز",
               "strDLClassCodeRETo": "ڈی ایل قسم RE معتبر تک",
               "strDLClassCodeRFrom": "ڈی ایل قسم R معتبر سے",
               "strDLClassCodeRNotes": "ڈی ایل قسم R کوڈز",
               "strDLClassCodeRTo": "ڈی ایل قسم R معتبر تک",
               "strDLClassCodeSFrom": "ڈی ایل قسم S معتبر سے",
               "strDLClassCodeSNotes": "ڈی ایل قسم S کوڈز",
               "strDLClassCodeSTo": "ڈی ایل قسم S معتبر تک",
               "strDLClassCodeTBFrom": "ڈی ایل قسم TB معتبر سے",
               "strDLClassCodeTBNotes": "ڈی ایل قسم TB کوڈز",
               "strDLClassCodeTBTo": "ڈی ایل قسم TB معتبر تک",
               "strDLClassCodeTFrom": "ڈی ایل قسم T معتبر سے",
               "strDLClassCodeTMFrom": "ڈی ایل قسم TM معتبر سے",
               "strDLClassCodeTMNotes": "ڈی ایل قسم TM کوڈز",
               "strDLClassCodeTMTo": "ڈی ایل قسم TM معتبر تک",
               "strDLClassCodeTNotes": "ڈی ایل قسم T کوڈز",
               "strDLClassCodeTRFrom": "ڈی ایل قسم TR معتبر سے",
               "strDLClassCodeTRNotes": "ڈی ایل قسم TR کوڈز",
               "strDLClassCodeTRTo": "ڈی ایل قسم TR معتبر تک",
            "strDLClassCodeTTo": "ڈی ایل قسم T معتبر تک",
              "strDLClassCodeTVFrom": "ڈی ایل قسم TV معتبر سے",
              "strDLClassCodeTVNotes": "ڈی ایل قسم TV کوڈز",
              "strDLClassCodeTVTo": "ڈی ایل قسم TV معتبر تک",
              "strDLClassCodeVFrom": "ڈی ایل قسم V معتبر سے",
              "strDLClassCodeVNotes": "ڈی ایل قسم V کوڈز",
              "strDLClassCodeVTo": "ڈی ایل قسم V معتبر تک",
              "strDLClassCodeWFrom": "ڈی ایل قسم W معتبر سے",
              "strDLClassCodeWNotes": "ڈی ایل قسم W کوڈز",
              "strDLClassCodeWTo": "ڈی ایل قسم W معتبر تک",
              "strDLDuplicateDate": "دوہری جاری کرنے کی تاریخ",
              "strDLEndorsed": "ڈی ایل انڈورسمنٹ کوڈ",
              "strDLIssType": "کارڈ قسم",
              "strDLRecordCreated": "ریکارڈ بنایا گیا",
              "strDLRestrictionCode": "ڈی ایل روکنے کا کوڈ",
              "strDLUnder18Date": "18ویں سالگرہ کی تاریخ",
              "strDLUnder19Date": "19ویں سالگرہ کی تاریخ",
              "strDLUnder21Date": "21ویں سالگرہ کی تاریخ",
              "strDNINumber": "ڈی این آئی نمبر",
              "strDSCertificateIssuer": "ڈی ایس سرٹیفکیٹ جاری کرنے والا",
              "strDSCertificateSubject": "ڈی ایس سرٹیفکیٹ موضوع",
              "strDSCertificateValidFrom": "ڈی ایس سرٹیفکیٹ معتبر ابتدا تاریخ",
              "strDSCertificateValidTo": "ڈی ایس سرٹیفکیٹ معتبر ختم ہونے کی تاریخ",
              "strDUFNumber": "ڈی یو ایف نمبر",
              "strDataDiscriminator": "ڈیٹا کا تفریق کرنے والا",
              "strDateFirstRenewal": "پہلی تجدید کی تاریخ",
              "strDateOfBirthOfHusband": "شوہر کی پیدائش کی تاریخ",
              "strDateOfBirthOfWife": "بیوی کی پیدائش کی تاریخ",
              "strDateOfInsuranceExpiry": "انشورنس ختم ہونے کی تاریخ",
              "strDateSecondRenewal": "دوسری تجدید کی تاریخ",
              "strDateofBirth": "پیدائش کی تاریخ",
              "strDateofBirthCheckDigit": "پیدائش کی تاریخ کا چیک ڈیجٹ",
              "strDateofBirthChecksum": "پیدائش کی تاریخ کا چیکسم",
              "strDateofCreation": "تخلیق کی تاریخ",
              "strDateofExpiry": "ختم ہونے کی تاریخ",
              "strDateofExpiryCheckDigit": "ختم ہونے کی تاریخ کا چیک ڈیجٹ",
              "strDateofExpiryChecksum": "ختم ہونے کی تاریخ کا چیکسم",
              "strDateofFlight": "پرواز کی تاریخ",
              "strDateofIssue": "جاری کرنے کی تاریخ",
              "strDateofIssueBoardingPass": "برڈنگ پاس جاری کرنے کی تاریخ",
              "strDateofIssueCheckDigit": "جاری کرنے کی تاریخ کا چیک ڈیجٹ",
              "strDateofIssueChecksum": "جاری کرنے کی تاریخ کا چیکسم",
            "strDateofPersonalization": "شخصی سازی کی تاریخ",
               "strDateofRegistration": "ثبت نام کی تاریخ",
               "strDay": "روز",
               "strDepartment": "قسمت",
               "strDeptNumber": "قسمتی عدد",
               "strDestination": "مقصد",
               "strDiscretionaryData": "اختیاری معلومات",
               "strDoDNumber": "DoD عدد",
               "strDocumentClassCode": "مستندات کا کلاس کوڈ",
               "strDocumentClassName": "مستندات کا نام",
               "strDocumentDiscriminator": "مستندات کا تفریق کنندہ",
               "strDocumentNumber": "مستندات کی تعداد",
               "strDocumentNumberCheckDigit": "مستندات کی تعداد کی چیک ڈجیٹ",
               "strDocumentNumberChecksum": "مستندات کی تعداد کی چیک سمرس",
               "strDocumentSeries": "مستندات کی سیریز",
               "strDocumentTooSmall": "دستاویز کو فریم میں فٹ کریں۔",
               "strDonor": "بخشدار",
               "strDossierNumber": "فائل کی تعداد",
               "strDurationofStay": "رہائش کی مدت",
               "strECEnvironmentalType": "گاڑی کا محیطی قسم",
               "strEDLDG1": "ٹیکسٹ ڈیٹا عناصر (DG1)",
               "strEDLDG10": "وضاحت نہیں کی گئی (DG10)",
               "strEDLDG11": "اختیاری داخلی معلومات (DG11)",
               "strEDLDG12": "نصف متابق اعلان (DG12)",
               "strEDLDG13": "فعال تصدیق معلومات (DG13)",
               "strEDLDG14": "EAC معلومات (DG14)",
               "strEDLDG2": "لیسانس دار کی معلومات (DG2)",
               "strEDLDG3": "جاری کرنے والی ادارہ کی تفصیلات (DG3)",
               "strEDLDG4": "پورٹریٹ تصویر (DG4)",
               "strEDLDG5": "امضا / عادی نشان کی تصویر (DG5)",
            "strEDLDG6": "بائیومیٹری - چہرے کا ڈیٹا (DG6)",
                "strEDLDG7": "بائیومیٹری - فنگر پرنٹ(s) (DG7)",
                "strEDLDG8": "بائیومیٹری - آئرس ڈیٹا (DG8)",
                "strEDLDG9": "بائیومیٹری - دیگر (DG9)",
                "strEFCOM": "EF.COM",
                "strEFCVCA": "EF.CVCA",
                "strEFCardAccess": "EF.CardAccess",
                "strEFCardSecurity": "EF.CardSecurity",
                "strEFChipSecurity": "EF.ChipSecurity",
                "strEFSOD": "EF.SOD",
                "strEQVCode": "EQV کوڈ",
                "strElectronicTicketIndicator": "الیکٹرانک ٹکٹ اشارے",
                "strElement": "عنصر",
                "strEndorsementExpirationDate": "تصدیق کی میعاد ختم ہونے کی تاریخ",
                "strEngineModel": "انجن ماڈل",
                "strEngineNumber": "انجن نمبر",
                "strEnginePower": "انجن کی طاقت",
                "strEngineVolume": "انجن کا حجم",
                "strError": "غلطی",
                "strExamDate": "امتحان کی تاریخ",
                "strExeptInTanks": "ٹینکوں میں نہیں",
                "strEye": "آئرس",
                "strEyesColor": "آنکھوں کا رنگ",
                "strFaculty": "فیکلٹی",
                "strFalseLuminescence": "اضافی روشنی",
                "strFamilyName": "خاندانی نام/پیدائش کے وقت دیا گیا نام",
                "strFamilyNameTruncation": "خاندانی نام/پیدائش کے وقت دیا گیا نام منقطع",
                "strFastTrack": "فاسٹ ٹریک سروس",
                "strFatherCountryOfBirth": "والد کی پیدائش کا ملک",
                "strFatherDateOfBirth": "والد کی تاریخ پیدائش",
                "strFatherGivenName": "والد کا دیا ہوا نام",
                "strFatherPersonalNumber": "والد کا ذاتی نمبر",
                "strFatherPlaceOfBirth": "والد کی پیدائش کا مقام",
                "strFatherSurname": "والد کا خاندانی نام",
                "strFathersName": "والد کا نام",
                "strFathersNameRUS": "والد کا نام (قومی)",
                "strFederalElections": "وفاقی انتخابات",
                "strFee": "فیس",
                "strFieldFromMRZ": "MRZ سے فیلڈ",
                "strFieldTypeDocumentImage": "دستاویز کی تصویر",
                "strFillElement": "پُر کرنے والا عنصر",
                "strFinalCheckDigit": "آخری چیک ڈیجٹ",
                "strFinalChecksum": "آخری چیکسم",
                "strFingerprint": "فنگر پرنٹ",
                "strFirstIssueDate": "پہلی اجراء کی تاریخ",
                "strFirstNameTruncation": "پہلا نام منقطع",
                "strFlightNumber": "پرواز کا نمبر",
                "strFolioNumber": "فولیو نمبر",
                "strFormOfEducation": "تعلیم کی شکل",
                "strFreeBaggageAllowance": "مفت سامان الاؤنس",
                "strFrequentFlyerAirlineDesignator": "فری کوئینٹ فلائر ایئر لائن ڈیزائنر",
                "strFrequentFlyerNumber": "فری کوئینٹ فلائر نمبر",
                "strFromAirportCode": "روانگی کے ہوائی اڈے کا کوڈ",
                "strFuelType": "ایندھن کی قسم",
                "strGNIBNumber": "GNIB نمبر",
                "strGhostPortrait": "شبیہ تصویر",
                "strGivenNames": "دیا ہوا نام",
                "strGivenNamesRUS": "دیا ہوا نام (قومی)",
                "strGlaresOnDocument": "دستاویز پر چمک سے بچیں",
                "strGrandfatherName": "دادا کا نام",
                "strHairColor": "بالوں کا رنگ",
                "strHealthNumber": "صحت بیمہ نمبر",
                "strHeight": "قد",
                "strHoldDocumentStraight": "دستاویز کو سیدھا رکھیں",
                "strHoloSimple": "ہولوگرام کی دستیابی",
                "strHoloVerifyDinamic": "متحرک ہولوگرام کی تصدیق کریں",
                "strHoloVerifyMultiStatic": "متعدد جامد ہولوگرام کی تصدیق کریں",
                "strHoloVerifyStatic": "جامد ہولوگرام کی تصدیق کریں",
                "strHolograms": "ہولوگرام",
                "strIPI": "IPI (غیر مرئی ذاتی معلومات)",
                "strIRB900": "IR B900 سیاہی",
                "strIRVis": "IR شفافیت",
                "strISOIssuerIDNumber": "آئی ایس او جاری کرنے والا آئی ڈی نمبر",
                "strIdentifier": "شناخت کنندہ",
                "strIdentityCardNumber": "شناختی کارڈ نمبر",
                "strIdentityCardNumberCheckDigit": "شناختی کارڈ نمبر کے لئے چیک ڈیجٹ",
                "strIdentityCardNumberChecksum": "شناختی کارڈ نمبر کے لئے چیکسم",
                "strImagePattern": "تصویری نمونے",
                "strInTanks": "ٹینکوں میں",
                "strInventoryNumber": "انوینٹری نمبر",
                "strInvitationNumber": "دعوت نمبر",
                "strInvitationNumberCheckDigit": "دعوت نمبر کے لئے چیک ڈیجٹ",
                "strInvitationNumberChecksum": "دعوت نمبر کے لئے چیکسم",
                "strInvitedBy": "مدعو کرنے والا",
                "strIssueTimestamp": "اجراء کا وقت",
                "strIssuingStateCode": "اجراء کرنے والے ریاست کا کوڈ",
                "strIssuingStateName": "اجراء کرنے والی ریاست",
                "strJurisdictionEndorsementCode": "دائرہ اختیار کی توثیق کوڈ",
                "strJurisdictionRestrictionCode": "دائرہ اختیار کی پابندی کوڈ",
                "strJurisdictionVehicleClass": "دائرہ اختیار کی گاڑی کلاس",
                "strKeepDeviceStill": "ڈیوائس کو ساکن رکھیں",
                "strLicenseNumber": "لائسنس نمبر",
                "strLimitedDurationDocumentIndicator": "دستاویز کی محدود مدت کا اشارہ",
                "strLine1CheckDigit": "لائن 1 کے لئے چیک ڈیجٹ",
                "strLine1Checksum": "لائن 1 کے لئے چیکسم",
                "strLine1OptionalData": "لائن 1 سے اختیاری ڈیٹا",
                "strLine2CheckDigit": "لائن 2 کے لئے چیک ڈیجٹ",
                "strLine2Checksum": "لائن 2 کے لئے چیکسم",
                "strLine2OptionalData": "لائن 2 سے اختیاری ڈیٹا",
                "strLine3CheckDigit": "لائن 3 کے لئے چیک ڈیجٹ",
                "strLine3Checksum": "لائن 3 کے لئے چیکسم",
                "strLine3OptionalData": "لائن 3 سے اختیاری ڈیٹا",
                "strLookingDocument": "ایک دستاویز تلاش کر رہا ہے...",
                "strMCNoviceDate": "موٹر سائیکل نووائس کی میعاد ختم ہونے کی تاریخ",
                "strMRZ": "MRZ",
                "strMRZLinesICAORFID": "MRZ لائنیں ICAO RFID سے",
                "strMRZString1": "MRZ لائن 1",
                "strMRZString2": "MRZ لائن 2",
                "strMRZString3": "MRZ لائن 3",
                "strMRZStrings": "MRZ لائنیں",
                "strMRZStringsWithCorrectCheckSums": "صحیح چیکسم کے ساتھ MRZ لائنیں",
                "strMRZType": "MRZ قسم",
                "strMailingAddressCity": "میلنگ ایڈریس - شہر",
                "strMailingAddressJurisdictionCode": "میلنگ ایڈریس - دائرہ اختیار کا کوڈ",
                "strMailingAddressPostalCode": "میلنگ ایڈریس - پوسٹل کوڈ",
                "strMailingAddressStreet": "میلنگ ایڈریس - گلی",
                "strMake": "بنانا",
                "strMaritalStatus": "ازدواجی حیثیت",
                "strMaxMassofTrailerBraked": "ٹرالر کی زیادہ سے زیادہ ماس (بریکڈ)",
                "strMaxMassofTrailerUnbraked": "ٹرالر کی زیادہ سے زیادہ ماس (غیر بریکڈ)",
                "strMaxSpeed": "زیادہ سے زیادہ رفتار",
                "strMedicalIndicatorCodes": "طبی نوٹ/کوڈ",
                "strMiddleName": "درمیانی نام",
                "strMiddleNameTruncation": "درمیانی نام منقطع",
                "strMifareData": "MIFARE ڈیٹا",
                "strMifareValidity": "MIFARE کی میعاد",
                "strMilitaryBookNumber": "ملٹری آئی ڈی نمبر",
                "strModel": "ماڈل",
                "strMonth": "مہینہ",
                "strMortgageBy": "رہن کے ذریعہ",
                "strMotherCountryOfBirth": "والدہ کی پیدائش کا ملک",
                "strMotherDateOfBirth": "والدہ کی تاریخ پیدائش",
                "strMotherGivenName": "والدہ کا دیا ہوا نام",
                "strMotherPersonalNumber": "والدہ کا ذاتی نمبر",
                "strMotherPlaceOfBirth": "والدہ کی پیدائش کا مقام",
                "strMotherSurname": "والدہ کا خاندانی نام",
                "strMothersName": "والدہ کا نام",
                "strNamePrefix": "نام کا سابقہ",
                "strNameSuffix": "نام کا لاحقہ",
                "strNationality": "قومیت",
                "strNationalityCode": "قومیت کا کوڈ",
                "strNonResidentIndicator": "غیر رہائشی اشارہ",
                "strNone": "کوئی نہیں",
                "strNotDefined": "غیر متعین",
                "strNumberOfCardIssuance": "کارڈ کے اجراء کی تعداد",
                "strNumberOfCardIssuanceCheckDigit": "کارڈ کے اجراء کی تعداد کے لئے چیک ڈیجٹ",
                "strNumberOfCardIssuanceChecksum": "کارڈ کے اجراء کی تعداد کے لئے چیکسم",
                "strNumberOfCylinders": "سلنڈرز کی تعداد",
                "strNumberofAxels": "ایکسل کی تعداد",
                "strNumberofDuplicates": "نقل کی تعداد",
                "strNumberofEntries": "داخلے کی تعداد",
                "strNumberofSeats": "نشستوں کی تعداد",
                "strNumberofStandingPlaces": "کھڑے ہونے کی جگہوں کی تعداد",
                "strOCRNumber": "OCR نمبر",
                "strOK": "ٹھیک ہے",
                "strObservations": "مشاہدات",
                "strOldDateOfIssue": "پرانا اجراء کی تاریخ",
                "strOldDocumentNumber": "پرانا دستاویز نمبر",
                "strOldPlaceOfIssue": "پرانا اجراء کا مقام",
                "strOptionalData": "اختیاری ڈیٹا",
                "strOptionalDataCheckDigit": "اختیاری ڈیٹا کے لئے چیک ڈیجٹ",
                "strOptionalDataChecksum": "اختیاری ڈیٹا کے لئے چیکسم",
                "strOptionalDetails": "اختیاری تفصیلات",
                "strOrganization": "تنظیم",
                "strOther": "دیگر",
                "strOtherName": "دوسرا نام",
                "strOtherPersonName": "دوسری شخص، نام",
                "strOtherValidID": "دیگر درست IDs",
                "strOwner": "مالک",
                "strPDF417Codec": "PDF417 کوڈک",
            "strPNRCode": "PNR کوڈ",
                "strParrentsGivenNames": "والدین کے دیے گئے نام",
                "strPassportNumber": "پاسپورٹ نمبر",
                "strPassportNumberCheckDigit": "پاسپورٹ نمبر کے لئے چیک ڈیجٹ",
                "strPassportNumberChecksum": "پاسپورٹ نمبر کے لئے چیکسم",
                "strPatronHeaderVersion": "پیٹرون ہیڈر ورژن",
                "strPatternDifferentLinesThickness": "نقش کی لکیروں کی موٹائی کا موازنہ",
                "strPatternIRInvisible": "آئی آر میں نظر نہ آنے والا نقش",
                "strPatternNotInterrupted": "کوئی وقفہ نہیں",
                "strPatternNotShifted": "نقش کے عناصر منتقل نہیں ہوئے",
                "strPatternSameColors": "نقش کے ایک ہی رنگ",
                "strPayGrade": "تنخواہ کا گریڈ",
                "strPayloadCapacity": "پے لوڈ کی گنجائش",
                "strPermissibleAxleLoad": "اجازت یافتہ ایکسل لوڈ",
                "strPermitDLClass": "پرمیٹ کلاس",
                "strPermitDateofExpiry": "پرمیٹ کی میعاد ختم ہونے کی تاریخ",
                "strPermitDateofIssue": "پرمیٹ کے اجراء کی تاریخ",
                "strPermitEndorsed": "پرمیٹ کی توثیق کا کوڈ",
                "strPermitIdentifier": "پرمیٹ شناخت کنندہ",
                "strPermitRestrictionCode": "پرمیٹ پابندی کا کوڈ",
                "strPersonToNotifyAddress": "مطلع کرنے والے شخص کا پتہ",
                "strPersonToNotifyDateofRecord": "مطلع کرنے والے شخص کا ریکارڈ کی تاریخ",
                "strPersonToNotifyName": "مطلع کرنے والے شخص کا نام",
                "strPersonToNotifyPhone": "مطلع کرنے والے شخص کا فون",
                "strPersonalNumber": "ذاتی نمبر",
                "strPersonalNumberCheckDigit": "ذاتی نمبر کے لئے چیک ڈیجٹ",
                "strPersonalNumberChecksum": "ذاتی نمبر کے لئے چیکسم",
                "strPersonalSummary": "ذاتی معلومات کا خلاصہ",
                "strPersonalizationSN": "شخصی بنانے کا سیریل نمبر",
                "strPhone": "فون",
                "strPhotoArea": "تصویر کا علاقہ",
                "strPhotoColor": "تصویر کا رنگ",
                "strPhotoCorners": "تصویر کے کونے",
                "strPhotoElement": "تصویر کا عنصر",
                "strPhotoEmbedType": "تصویر سرایت کی قسم",
                "strPhotoProcessing": "تصویر کی کارروائی...",
                "strPhotoShape": "تصویر کی شکل",
                "strPhotoSizeCheck": "سائز کی جانچ",
                "strPlaceDocumentInFrame": "دستاویز کو فریم میں فٹ کریں۔",
                "strPlaceOfBirthRUS": "پیدائش کا مقام (قومی)",
                "strPlaceOfBirthStateCode": "پیدائش کی ریاست کا کوڈ",
                "strPlaceOfExamination": "امتحان کا مقام",
                "strPlaceOfIssue": "اجراء کا مقام",
                "strPlacePhoneOnDoc": "برائے مہربانی فون کو دستاویز پر رکھیں",
                "strPlaceofBirth": "پیدائش کا مقام",
                "strPlaceofBirthArea": "پیدائش کا علاقہ",
                "strPlaceofRegistration": "رجسٹریشن کا مقام",
                "strPoliceDistrict": "پولیس ڈسٹرکٹ",
                "strPortrait": "پورٹریٹ",
                "strPortraitComparison": "پورٹریٹس کا موازنہ",
                "strPortraitOfChild": "بچے کا پورٹریٹ",
                "strPortraitVSCamera": "پورٹریٹ بمقابلہ کیمرہ تصویر",
                "strPortraitVSGhost": "پورٹریٹ بمقابلہ گوسٹ تصویر",
                "strPortraitVSRFID": "پورٹریٹ بمقابلہ RFID چپ پورٹریٹ",
                "strPowerWeightRatio": "طاقت سے وزن کا تناسب",
                "strPrecinct": "پریسنکٹ",
                "strPrepareCamera": "کیمرہ تیار ہو رہا ہے...",
                "strPresentNextPage": "براہ کرم اگلا صفحہ فراہم کریں۔",
                "strPreviousType": "پچھلی دستاویز کی قسم/نمبر",
                "strProcessingDocument": "دستاویز کی کارروائی...",
                "strProfession": "پیشہ",
                "strProfessionalIdNumber": "پروفیشنل آئی ڈی نمبر",
                "strProofOfCitizenship": "شہریت کا ثبوت",
                "strPseudoCode": "پسیوڈو کوڈ",
                "strPurposeOfEntry": "داخلے کا مقصد",
                "strRFIDVSCamera": "RFID چپ پورٹریٹ بمقابلہ کیمرہ تصویر",
                "strRaceEthnicity": "نسل/قومیت",
                "strRank": "رینک",
                "strReadingRFID": "RFID چپ ڈیٹا پڑھنا",
                "strReadingRFIDDGiOS": "RFID %@ ڈیٹا پڑھنا",
                "strRecognizedDocumentType": "دستاویز کی قسم",
                "strReferenceNumber": "یونیک نمبر",
                "strReferenceNumberCheckDigit": "یونیک نمبر کے لئے چیک ڈیجٹ",
                "strReferenceNumberChecksum": "یونیک نمبر کے لئے چیکسم",
                "strRegCertBodyNumber": "باڈی نمبر",
                "strRegCertBodyType": "باڈی کی قسم",
                "strRegCertCarColor": "گاڑی کا رنگ",
                "strRegCertCarMark": "گاڑی کا برانڈ",
                "strRegCertCarModel": "گاڑی کا ماڈل",
                "strRegCertCarType": "گاڑی کی قسم",
                "strRegCertMaxWeight": "زیادہ سے زیادہ اجازت یافتہ وزن",
                "strRegCertRegNumber": "رجسٹریشن نمبر",
                "strRegCertRegNumberCheckDigit": "رجسٹریشن نمبر کے لئے چیک ڈیجٹ",
                "strRegCertRegNumberChecksum": "رجسٹریشن نمبر کے لئے چیکسم",
                "strRegCertVIN": "گاڑی کی شناختی نمبر (VIN)",
                "strRegCertVINCheckDigit": "VIN کے لئے چیک ڈیجٹ",
                "strRegCertVINChecksum": "VIN کے لئے چیکسم",
                "strRegCertVehicleITSCode": "گاڑی کا ITS کوڈ",
                "strRegCertWeight": "غیر لوڈ شدہ ماس",
                "strRelationship": "رشتہ",
                "strReligion": "مذہب",
                "strRemainderTerm": "خاتمے تک مہینے",
                "strResidentFrom": "رہائشی سے",
                "strResidentUntil": "رہائشی تک",
                "strRetirementNumber": "ریٹائرمنٹ نمبر",
                "strRevisionDate": "ترمیم کی تاریخ",
                "strRoomNumber": "کمرے کا نمبر",
                "strSBHIntegrityOptions": "SBH سالمیت کے اختیارات",
                "strSBHSecurityOptions": "SBH سیکورٹی کے اختیارات",
                "strSeatNumber": "سیٹ نمبر",
                "strSecondSurname": "دوسرا خاندانی نام",
                "strSection": "سیکشن",
                "strSecurityText": "سیکورٹی ٹیکسٹ",
                "strSelecteeIndicator": "منتخب کنندہ کا اشارہ",
                "strSequenceNumber": "سیریز نمبر",
                "strSerialNumber": "سیریل نمبر",
                "strSettings": "ترتیبات",
                "strSex": "جنس",
                "strSignature": "دستخط",
                "strSkinColor": "جلد کا رنگ",
                "strSocialSecurityNumber": "سوشل انشورنس نمبر",
                "strSpCode": "خصوصی کوڈ",
                "strSpecialNotes": "خصوصی نوٹس",
                "strSponsor": "سرپرست",
                "strSponsorSSN": "سرپرست SSN",
                "strSponsorService": "سرپرست سروس",
                "strSponsorStatus": "سرپرست کی حیثیت",
                "strStamp": "مہر",
                "strStampNumber": "مہر نمبر",
                "strStatusDateofExpiry": "حیثیت کی میعاد ختم ہونے کی تاریخ",
                "strSurname": "خاندانی نام",
                "strSurnameAndGivenNames": "خاندانی نام اور دیے گئے نام",
                "strSurnameAndGivenNamesCheckDigit": "خاندانی نام اور دیے گئے نام کے لئے چیک ڈیجٹ",
                "strSurnameAndGivenNamesChecksum": "خاندانی نام اور دیے گئے نام کے لئے چیکسم",
                "strSurnameAndGivenNamesRUS": "خاندانی نام اور دیے گئے نام (قومی)",
                "strSurnameAtBirth": "پیدائش کے وقت خاندانی نام",
                "strSurnameOfHusbandAfterRegistration": "رجسٹریشن کے بعد شوہر کا خاندانی نام",
                "strSurnameOfWifeAfterRegistration": "رجسٹریشن کے بعد بیوی کا خاندانی نام",
                "strSurnameofSpose": "شریک حیات کا خاندانی نام",
                "strTax": "ٹیکس",
                "strTaxNumber": "ٹیکس نمبر",
                "strTelexCode": "ٹیلیگراف کوڈ",
                "strTerritorialValidity": "علاقائی درستگی",
                "strTicketNumber": "ٹکٹ نمبر",
                "strTitle": "پوزیشن",
                "strToAirportCode": "ایئرپورٹ آف آریول کا کوڈ",
                "strTorchUnavailable": "ٹارچ دستیاب نہیں",
                "strTrackingNumber": "ٹریکنگ نمبر",
                "strTrailerHitch": "ٹرالر ہچ",
                "strTransactionNumber": "ٹرانزیکشن نمبر",
                "strTransmissionType": "ٹرانسمیشن کی قسم",
                "strTypeApprovalNumber": "منظوری کی قسم نمبر",
                "strURL": "یو آر ایل",
                "strUSCIS": "یو ایس سی آئی ایس",
                "strUV": "یو وی",
                "strUVFibers": "یو وی سیکورٹی فائبر",
                "strUVLuminescence": "یو وی مدھم کاغذ کی جانچ",
                "strUnableCaptureMedia": "کیمرہ کنفیگریشن ناکام",
                "strUniqueCustomerIdentifier": "یونیک کسٹمر شناخت کنندہ",
                "strVRCDataObjectEntry": "ڈی جی 1 ڈیٹا گروپ سے گاڑی کا ڈیٹا",
                "strValidityPeriod": "درستگی کی مدت",
                "strVehicleCategory": "گاڑی کی قسم",
                "strVeteran": "ویٹرن",
                "strVisaClass": "ویزا کلاس",
                "strVisaID": "ویزا آئی ڈی",
                "strVisaIDCheckDigit": "ویزا آئی ڈی کے لئے چیک ڈیجٹ",
                "strVisaIDChecksum": "ویزا آئی ڈی کے لئے چیکسم",
                "strVisaIDRUS": "ویزا آئی ڈی (قومی)",
                "strVisaNumber": "ویزا نمبر",
                "strVisaNumberCheckDigit": "ویزا نمبر کے لئے چیک ڈیجٹ",
                "strVisaNumberChecksum": "ویزا نمبر کے لئے چیکسم",
                "strVisaSubClass": "ویزا سب کلاس",
                "strVisaType": "ویزا کی قسم",
                "strVisaValidFrom": "ویزا کی میعاد شروع",
                "strVisaValidUntil": "ویزا کی میعاد ختم",
                "strVisaValidUntilCheckDigit": "ویزا کی میعاد ختم ہونے کی تاریخ کے لئے چیک ڈیجٹ",
                "strVisaValidUntilChecksum": "ویزا کی میعاد ختم ہونے کی تاریخ کے لئے چیکسم",
                "strVisibleLight": "نظر آنے والی روشنی",
                "strVoter": "ووٹر",
                "strVoterKey": "ووٹر کی",
                "strVoucherNumber": "واؤچر نمبر",
                "strWeight": "وزن",
                "strWeightPound": "وزن (پاؤنڈ)",
                "strYear": "سال",
                "strYearsSinceIssue": "اجراء کے بعد سے سال",
                "streIDPlaceOfBirthCity": "پیدائش کا مقام: شہر",
                "streIDPlaceOfBirthCountry": "پیدائش کا مقام: ملک",
                "streIDPlaceOfBirthState": "پیدائش کا مقام: ریاست",
                "streIDPlaceOfBirthStreet": "پیدائش کا مقام: گلی",
                "streIDPlaceOfBirthZipcode": "پیدائش کا مقام: پوسٹل کوڈ",
                "streIDResidencePermit1": "رہائشی اجازت نامہ 1",
                "streIDResidencePermit2": "رہائشی اجازت نامہ 2",
                "strfppLeftIndexFinger": "بایاں انڈیکس فنگر",
                "strfppLeftLittleFinger": "بایاں چھوٹا فنگر",
                "strfppLeftMiddleFinger": "بایاں درمیانی فنگر",
                "strfppLeftRingFinger": "بایاں رنگ فنگر",
                "strfppLeftThumb": "بایاں انگوٹھا",
                "strfppRightIndexFinger": "دایاں انڈیکس فنگر",
                "strfppRightLittleFinger": "دایاں چھوٹا فنگر",
                "strfppRightMiddleFinger": "دایاں درمیانی فنگر",
                "strfppRightRingFinger": "دایاں رنگ فنگر",
                "strfppRightThumb": "دایاں انگوٹھا"
        ]
    }
}
